### ISSUE TITLE
cant see the sidecard thingy 

### ISSUE THREAD

**Issue by aamyush** [surfbryce/beautiful-lyrics#10]
no sidecard how do i get the sidecard in the gifs?

**Comment by feliflop** [comment]
I think that sidebar its from nord theme

**Comment by Blankk02** [comment]
To do that you go to your PFP, click on Experimental Features, and then search for "side" you should have the option to enable it.

**Comment by surfbryce** [comment]
What @Blankk02 said; but since this is a common question now - I've added it to the FAQ section on the GitHub page. See it there if you have anymore questions.
