### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by NikhilYTOP** [surfbryce/beautiful-lyrics#1000]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Alignment Issue, Also stuck on loading lyrics for every song(even for popular ones)
![image](https://github.com/user-attachments/assets/ce08276f-1b54-4a4c-ac07-709b5afde9ed)
even if i remove everything else issue still presists

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

![image](https://github.com/user-attachments/assets/8b439dba-3687-4139-a088-d364be4b662b)

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/e487f972-517e-4a5e-a99f-12a7c97912ee)

![image](https://github.com/user-attachments/assets/79e6203a-4203-47dd-aa05-4c1c750e6ad0)

![image](https://github.com/user-attachments/assets/4e146422-2769-4034-a503-070580f67017)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Hey, here's the fix for it 

https://github.com/surfbryce/beautiful-lyrics/issues/965
