### ISSUE TITLE
Lyrics is not showing

### ISSUE THREAD

**Issue by SwayamSat** [surfbryce/beautiful-lyrics#1002]
![Screenshot 2024-11-16 144238](https://github.com/user-attachments/assets/1af30d10-5031-44d6-8667-8e5d8a606fc3)
![Screenshot 2024-11-16 144736](https://github.com/user-attachments/assets/c228c93a-f343-460c-a63f-e12461c1a73b)
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Lyrics is not showing it just keeps loading forever

### What Country are you from?

INDIA

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

i am in latest build in both the spotify and spicify 

### Spotify HTML/CSS and Console Screenshots

how can i attach?

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by zydiaa** [comment]
Same for me, nothing is loading.
![image](https://github.com/user-attachments/assets/b64ae65a-f8e3-409d-b19e-794b0ecab284)

**Comment by reda12323** [comment]
Me to same problem after the last update of spotify the lyrics don't show in a lot of song that the lyrics was appear before

**Comment by Mysticc28** [comment]
Hey OP, unfortunately there's no fix available for the missing lyrics rn, but there is a fix for your misoriented - elements is fullscreen. Here's the fix

https://github.com/surfbryce/beautiful-lyrics/issues/965

**Comment by LILITHDELLUNA** [comment]
SAME

**Comment by tealytee** [comment]
same

**Comment by SwayamSat** [comment]
> Hey OP, unfortunately there's no fix available for the missing lyrics rn as there's an API failing, but there is a fix for your misoriented elements in fullscreen mode. Here's the fix
> 
> #965

i have done this still not fixed the fullscreen has fixed

**Comment by Mysticc28** [comment]
> > Hey OP, unfortunately there's no fix available for the missing lyrics rn as there's an API failing, but there is a fix for your misoriented elements in fullscreen mode. Here's the fix
> > 
> > #965
> 
> i have done this still not fixed the fullscreen has fixed

Yes, this fix was only for the fullscreen issue not lyrics, the developer will have to come up with a fix for it

**Comment by crawqxx** [comment]
same, lyrics got deleted from most songs that had before, thats very sad :(

**Comment by 108hills** [comment]
same, any temporary fix for this?

**Comment by yxsefo** [comment]
same for me just downloaded it

**Comment by Quelxy** [comment]
same for me, only a few songs have lyrics

**Comment by Felykxzy** [comment]
It’s the same for me, at first I thought that I had a problem and then I read here that it was an error in the api

**Comment by lichi7887** [comment]
I also encountered the same problem. I thought it was my network problem, because I came to Github in Chinese Mainland and found that many people had the same problem as me

**Comment by caek353** [comment]
Same for me! Thought I had a problem on my side.

**Comment by Fadhilul** [comment]
Me too

**Comment by caraar12345** [comment]
@surfbryce (the dev and owner of the API) has posted an update in issue #984: https://github.com/surfbryce/beautiful-lyrics/issues/984#issuecomment-2480025661
