### ISSUE TITLE
Is not working on MacOS Sotify!

### ISSUE THREAD

**Issue by yvexeldev** [surfbryce/beautiful-lyrics#1013]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Spicetify extension Beautiful lyrics is not working on my macos spotify! 
<img width="1624" alt="Screenshot 2024-11-29 at 11 19 50" src="https://github.com/user-attachments/assets/c54f7198-c258-448b-a5a1-dd8f726161e7">
<img width="1624" alt="Screenshot 2024-11-29 at 11 19 47" src="https://github.com/user-attachments/assets/76822a6a-513d-4d7d-81e0-dd40ebbe2ece">

### What Country are you from?

Uzbekistan

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

<img width="1614" alt="Screenshot 2024-11-29 at 11 22 37" src="https://github.com/user-attachments/assets/f6c9b08e-4d53-4710-a443-2d069205671e">

### Spotify HTML/CSS and Console Screenshots

<img width="1614" alt="Screenshot 2024-11-29 at 11 22 52" src="https://github.com/user-attachments/assets/8022e1d3-524a-4510-83c5-49729d69d52b">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@yvexeldev Unfortunately, I think the Cloudflare endpoints are blocked in your Country. I would highly recommend using a VPN.

**Comment by yvexeldev** [comment]
> @yvexeldev Unfortunately, I think the Cloudflare endpoints are blocked in your Country. I would highly recommend using a VPN.

THANKS A LOT! IT WORKS NOW!
