### ISSUE TITLE
beautiful lyrics button doesn't appear 

### ISSUE THREAD

**Issue by 11haku** [surfbryce/beautiful-lyrics#1024]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Hey!

i really like this plugin and i used it for a while but today it doesn't work... i tried reinstalling spicetify and spotify (many times and different versions) but still nothing works 
pls help

### What Country are you from?

Russia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

my spotify now is 1.2.52.442.g01893f92
spicetify v2.38.5

### Spotify HTML/CSS and Console Screenshots

.

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@11haku Your country is most likely blocking Cloudflare CDNs, you need to use a VPN.
