### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by GhostKillerhack** [surfbryce/beautiful-lyrics#1025]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

  beatiful lyrics just does not work

### What Country are you from?

Russia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

cant get it because beautiful lyrics doesnt work

### Spotify HTML/CSS and Console Screenshots

cant get it because beautiful lyrics doesnt work

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@GhostKillerhack In Russia Cloudflare CDNs are blocked, use a VPN.
