### ISSUE TITLE
Make words consistent across songs

### ISSUE THREAD

**Issue by bobjoerules** [surfbryce/beautiful-lyrics#1029]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I was listening to some rap songs and found that the n word was sometimes bleeped out with **** but other times was written out.

### What is your Suggestion?

I believe this is due to apple music bleeping out the word while musixmatch does not. My suggestion is to have it either bleeped out locally for every song or have it unbleeped. Basically make it consistent.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@bobjoerules It can't be unbleeped since it's impossible to know what the original word was, either way I refuse to modify the lyrics provided.

**Comment by bobjoerules** [comment]
I mean make them all bleeped so the n word never is shown instead of only sometimes

**Comment by bobjoerules** [comment]
But okay
