### ISSUE TITLE
how to use and how to download( I'm a github beginner) 

### ISSUE THREAD

**Issue by KhzRyuu** [surfbryce/beautiful-lyrics#1030]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

i dont really know how to use it

### What is your Suggestion?

just give us a guide

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by LaymGlitched** [comment]
You need Spicetify (https://spicetify.app) for Spotify, make sure when you install Speicetify, you get Marketplace, and then in Spotify, you can download Beautiful Lyrics.
