### ISSUE TITLE
Beautiful lyrics doesn't work

### ISSUE THREAD

**Issue by wxxd52** [surfbryce/beautiful-lyrics#1031]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Снимок экрана 2024-12-12 133249](https://github.com/user-attachments/assets/30f660af-2f36-4241-a8e2-85b87bcea1f7)

### What Country are you from?

Russia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

«Shift + B + L + I», "Shift + B + L + H" and "Shift + B + L + C" don't work. 
Red notification does not appear

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/3d0e3460-faf8-49fc-a6b0-572cd1599bed)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@wxxd52 You are in Russia. They block Cloudflare host names so you need to use a VPN. Sorry!
