### ISSUE TITLE
question about API authorization

### ISSUE THREAD

**Issue by RoootTheFox** [surfbryce/beautiful-lyrics#1034]
hai, first of all, thanks for making this extension - i do have a question however:

I noticed that the extension sends your Spotify session token to its API, and manually sending requests to the API confirms that it does *want* you to specify a Spotify token, returning `Invalid Authorization` if none is specified.
However, giving it expired tokens or random strings works just fine too, which makes me question why the API wants your Spotify session token in the first place.

![image](https://github.com/user-attachments/assets/67e828b0-b88d-4ffc-80ec-4ff6a0d0b550)

This is an additional concern with the backend being closed-source, as there's no way to verify what it actually does with said token, which means users would have to blindly trust you with their Spotify account.

I obviously don't think you're doing anything malicious, but having a bit of transparency on *why* the API wants your Spotify token and what it does with it would be nice (and if it doesn't need it, having the extension not send it at all)

thank you ^^

**Comment by surfbryce** [comment]
@RoootTheFox There's plenty of transparency everywhere; you just need to look for it. I would recommend reading the Wiki where I go into depth on what it is used for and how it improves the overall experience. There is backend caching going on so the token isn't always used, so the songs you are using are most likely already cached.
