### ISSUE TITLE
Spotify can't play this song label on every skip

### ISSUE THREAD

**Issue by Kjay7** [surfbryce/beautiful-lyrics#104]
![Picture2](https://github.com/surfbryce/beautiful-lyrics/assets/118202584/89d5a280-bfad-4173-9d7f-429ed525aeaf)

When I click next/previous, this label shown in the picture shows up. It only happens with this extension and I really like it.

**Comment by edajasopar** [comment]
this keeps happening to me as well

**Comment by surfbryce** [comment]
@Kjay7 I'm assuming this is because of what I do internally to keep the song timestamps in sync for the lyrics. This doesn't affect anything functionally but I can imagine the popup is annoying so I'll look into hiding it when it pops up.

**Comment by voidlesity** [comment]
Hey any updates on this I really love your extension but I'm also kinda bothered by the constant popup

**Comment by surfbryce** [comment]
@voidlesity Sorry but I do not have an update. It's difficult to find out why it's doing this because it doesn't happen for me. So it'll probably be a while.

**Comment by surfbryce** [comment]
Should be fixed! Re-create the issue
