### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by Qusab83** [surfbryce/beautiful-lyrics#1050]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

There is no normal visualization of the lyrics for all songs. For example, as in the screenshot, it's like clicking on a transparent button. Which is in the second screenshot.

### What Country are you from?

Russia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

![image](https://github.com/user-attachments/assets/4b5430fb-aa96-4793-a002-15186f95d9ec)
![image](https://github.com/user-attachments/assets/273ea953-7ca9-4d3f-abec-7e2c3e4c066b)

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/6c58b7ff-6a98-4013-8a65-73686dca97ce)
![image](https://github.com/user-attachments/assets/fef21a12-e92a-438d-b1be-3b6ad0a6bb47)

### Information Checklist

- [X] Spotify/Spicetify Information
- [ ] Spotify HTML File
- [ ] Spotify CSS File
- [x] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Qusab83 Russia blocks Cloudflare CDNs, use a VPN
