### ISSUE TITLE
(ASK) Song lyrics

### ISSUE THREAD

**Issue by FlimixST** [surfbryce/beautiful-lyrics#106]
Hello, I wanted to ask, how does it work to show text by words and not by sentences? And why in that case very few tracks have it?

With text that shows word by word:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/57029290/69a1d8df-905c-4081-b5c9-38133ca50e3a)

With plain text:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/57029290/20cc0197-c8d3-4a86-9f75-4845680e9b73)

**Comment by surfbryce** [comment]
@FlimixST Artists/label companies will write and send lyrics to other companies that then provide those lyrics to people like Apple Music, Spotify, Tidal, Pandora, etc.

I get lyrics from those companies directly.

So whether a song is syllable/line/static synced is all dependent on how much work the artist/label decided to put into syncing/writing the lyrics.

The extension just gets lyrics not generates them; eventually, there will be a lyrics editor so anyone can sync a song so it’s syllable/line synced.
