### ISSUE TITLE
Cannot scroll in built-in lyrics page (when Beautiful Lyrics is installed)

### ISSUE THREAD

**Issue by meteorsquare** [surfbryce/beautiful-lyrics#107]
When the extension is installed, I cannot scroll in the normal Spotify lyrics page. I know that sounds weird but it's nice having both options for lyrics.

https://github.com/surfbryce/beautiful-lyrics/assets/58662679/0aac4b17-4dc3-41da-9aeb-5b15ae132fa0

Spotify for Windows (64 bit)
1.2.15.828.g79f41970
Spicetify v2.21.0
xpui_2023-07-05_1688572738483_79f4197
cef_113.3.1+g525fa10+chromium-113.0.5672.128

**Comment by surfbryce** [comment]
@meteorsquare Very late, but this should be fixed now
