### ISSUE TITLE
Compatibility with Full Screen extension

### ISSUE THREAD

**Issue by Gam3-Dev** [surfbryce/beautiful-lyrics#110]
It would be better to use the full screen extension with the style of lyrics from this extension

**Comment by surfbryce** [comment]
@Gam3-Dev I did develop the systems used in my extension with external usage in mind. I just have not exposed the methods to do yet. The main thing is that the extension is not finished to the degree where I would be ok with exposing these methods yet.

There are a couple of things I want to look into and implement first. After that I will consider exposing the internals (it's very likely that I will).

I also would like to mention that Beautiful Lyrics does have its own proper fullscreen mode. It replaces the original Spotify fullscreen button functionality. If you have any suggestions/features that are missing from this for your own taste I would love to hear them (via Issues on this GitHub of course)
