### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by zakaryan2004** [surfbryce/beautiful-lyrics#111]
https://github.com/surfbryce/beautiful-lyrics/blob/56282b43b85f0dc700b97c5f04176fe4c0d39f5b/src/Services/Player/Song.ts#L150

This is an unconventional issue. I was reading the source code, and I noticed this typo. I, unfortunately, didn't take the time to check if this affects anything or otherwise put any effort into this issue report, but I did search the code and found that this is the only instance of this typo. I don't know if it affects anything, but I guess it's better to be safe than sorry.

**Comment by surfbryce** [comment]
@zakaryan2004 Its a typing so it isn’t a functional bug but I’ll definitely fix that thanks!
