### ISSUE TITLE
Edge and glow from text in full screen mode

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#113]
Hi, I would like to say that in the song where the text goes in blocks using full screen mode on the left side you can see that the lighting of the text reaches the edges.
You can see it in the screenshot below:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/01299a0d-0774-4226-9274-b428f5b188b3)

**Comment by surfbryce** [comment]
Duplicate of #100
