### ISSUE TITLE
Some songs have delay or it's faster than the lyrics

### ISSUE THREAD

**Issue by ItzAsyran** [surfbryce/beautiful-lyrics#115]
The example one is _What Lovers Do by Maroon 5_ which the song is faster than the lyrics

**Comment by zerol1ght** [comment]
The fault is who synchronized the lyrics to the song. (I checked the song on MusixMatch, it is not synched correctly)

**Comment by surfbryce** [comment]
@zerol1ght is correct (and thank you for responding).

Some songs just have poorly synced or very closely-synced lyrics where they will be slightly out of sync or faster in certain segments but then realign themselves. It's just the nature of how artists/labels sync their songs to the lyrics.
