### ISSUE TITLE
Update 3.1.12 causes alignment issues with the comfy theme in cinema mode

### ISSUE THREAD

**Issue by jrvgr** [surfbryce/beautiful-lyrics#119]
<img width="1912" alt="CleanShot 2023-08-20 at 12 53 01@2x" src="https://github.com/surfbryce/beautiful-lyrics/assets/30769091/565df9a3-a278-4e57-97b8-f8d611c76580">
<img width="1912" alt="CleanShot 2023-08-20 at 12 53 41@2x" src="https://github.com/surfbryce/beautiful-lyrics/assets/30769091/82b367fa-cc67-4c23-82e0-2103c5045a7b">

**Comment by surfbryce** [comment]
I don't have this issue with comfy - I'm pushing out a new update so please let me know if it still occurs!

**Comment by jrvgr** [comment]
disabling this style on the element i also highlighted seems to fix the issue entirely
![CleanShot 2023-08-31 at 13 20 19@2x](https://github.com/surfbryce/beautiful-lyrics/assets/30769091/a0bfd6d0-bc47-4c4c-90f5-b5dc85e96f3e)

**Comment by jrvgr** [comment]
For people having the same problem as me, i created a custom css snippet you can use to fix this problem: ```body:has(.Root__main-view-overlay .BeautifulLyricsPage) .Root__top-container {
grid-template-areas:
"top-bar top-bar top-bar"
"left-sidebar main-view right-sidebar"
"now-playing-bar now-playing-bar now-playing-bar" !important;```

**Comment by Joeeeeb5** [comment]
> body:has(.Root__main-view-overlay .BeautifulLyricsPage) .Root__top-container { grid-template-areas: "top-bar top-bar top-bar" "left-sidebar main-view right-sidebar" "now-playing-bar now-playing-bar now-playing-bar" !important;

Doesn't work for me

**Comment by jrvgr** [comment]
Hi @surfbryce, any updates on this?

**Comment by surfbryce** [comment]
Yep @jrvgr (@Joeeeeb5 ) this should now be fixed! Let me know if there are issues!
