### ISSUE TITLE
Animation on SideCard is buggy

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#12]
After the latest Spotify update, I can only see the animation on top of the sidecard, but below it is the same as the original Spotify
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/509b78cb-1369-4aae-b74f-844afddcd204)

**Comment by surfbryce** [comment]
This was fixed in 2.3.2 - make sure your extension is updated.
