### ISSUE TITLE
Automatically turn the lyrics in parentheses into adlibs

### ISSUE THREAD

**Issue by ImZen0x** [surfbryce/beautiful-lyrics#120]
example: turn this 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/117906726/41a51028-215f-47cb-8f1f-3016af00176e)

to this:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/117906726/a726d6eb-19aa-42c2-bd16-01ab5b0e35e0)
(its not the same lyrics but you get the point)

**Comment by surfbryce** [comment]
@ImZen0x Its impossible to do this.

To turn it into a background vocal it would need to be time stamped. Since it’s a part of an already time stamped lead vocal there’s no extra metadata I can utilize to undo that.

As cool as it would be to do that, the data is just not there for it to happen.
