### ISSUE TITLE
Suggestion: Theme with the wobbly background and the nice bloom

### ISSUE THREAD

**Issue by fxyqq** [surfbryce/beautiful-lyrics#121]
Would be nice to have a theme with the wobbly background and a nice bloom and font!

![image](https://github.com/surfbryce/beautiful-lyrics/assets/75327915/6e5380f5-b593-4fbf-a207-7444e799d310)

the pink background matches the song so that with full spotify background and theme!

**Comment by surfbryce** [comment]
This is a duplicate of #37
