### ISSUE TITLE
FullScreen Error

### ISSUE THREAD

**Issue by Vvictorr4** [surfbryce/beautiful-lyrics#124]
When I start Spotify I don't get the option to put full screen unless I uninstall and reinstall the "beatiful lyrics"

**Comment by surfbryce** [comment]
Fullscreen I just found out is actually limited to Premium only for some really weird reason. So if you don't have force premium on it wouldn't show.

I've changed this so now I create my own custom button and remove the existing one from Spotify. It should work now in the latest version: 3.1.13
