### ISSUE TITLE
Fullscreen With Comfy (Legacy) theme is broken

### ISSUE THREAD

**Issue by ByntoYT** [surfbryce/beautiful-lyrics#125]
![Screenshot (65)](https://github.com/surfbryce/beautiful-lyrics/assets/112349339/0a012c74-d626-4797-a52d-d35b44702e35)
For some reason, the album art and title are shrunken with the **legacy** comfy theme

**Comment by ByntoYT** [comment]
I have also discovered that on 1440p the buttons are right above the progress bar

**Comment by surfbryce** [comment]
This should be fixed now in 3.1.13

**Comment by ByntoYT** [comment]
> This should be fixed now in 3.1.13

Yes it is, thank you!
