### ISSUE TITLE
Black when lyrics on

### ISSUE THREAD

**Issue by BenjiDEFI** [surfbryce/beautiful-lyrics#126]
https://github.com/surfbryce/beautiful-lyrics/assets/143656659/6f012127-78c7-49f4-b9c0-cd513dd1a548

**Comment by surfbryce** [comment]
@BenjiDEFI I'm assuming this might be because of the latest Spotify update. Try restarting Spotify and seeing if the latest update (3.1.13) works for you!

**Comment by FlimixST** [comment]
I have the same thing, I updated beautiful lirycs and spicetify, but still this stuff remains

![image](https://github.com/surfbryce/beautiful-lyrics/assets/57029290/27047bf8-8a66-4e3b-af91-578b9e91b46d)

**Comment by FlimixST** [comment]
I just realized that my Spicetify didn't update, but I updated it, and now everything is working xD, nice joke. I just need to update Spicetify.

**Comment by surfbryce** [comment]
Alright will close this then! Thanks!

**Comment by brusvv** [comment]
I got black screen after ~ 3 hours of using, my friend getting that more often. What could be the problem?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/55412131/3c62b744-daf6-4e75-9e86-b43f34391f4c)

**Comment by surfbryce** [comment]
@brusvv not related to the extension, update spicetify and spotify

**Comment by brusvv** [comment]
@surfbryce 
Spotify for Windows (32 bit)
1.2.33.1039.g8ddb5918
Spicetify v2.34.1

**Comment by surfbryce** [comment]
@brusvv again this issue isn't related to the extension, I can't do much to help you out here, it may be helpful to go to the Spicetify discord and ask for help there
