### ISSUE TITLE
Plugin autostarting playing music

### ISSUE THREAD

**Issue by DJkefo** [surfbryce/beautiful-lyrics#128]
Everytime I start Spotify, it automaticly starts playing music. This only happens when this Plugin is installed and enabled.

**Comment by surfbryce** [comment]
Sorry forgot to respond to this, this should be fixed now if you have your Spicetify/Spotify updated. Thanks!

**Comment by DJkefo** [comment]
Sorry, I've missed your answer. I tried updating everything but the music still plays on startup of spotify
