### ISSUE TITLE
Fullscreen Edition

### ISSUE THREAD

**Issue by sealants** [surfbryce/beautiful-lyrics#13]
simply what the title says, i think you should add a fullscreen option just expanding what is already there. sent an image for reference for what to put in fullscreen.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/41653586/9b43b319-ba4a-4987-aacd-50d0a5fba68e)

**Comment by surfbryce** [comment]
I've completed this and it will be a major feature in the next update tomorrow (Saturday July 1st).

I needed to redo the card and cinema-view components to make full control of the experience.

So now when you click the maximize button in the card it will open it in the main-view first (lyrics that take up the main page). There will be another maximize button that you can press that will bring you to the "Cinema" view. This view takes up the entirety of Spotify and only exposes the Now-Playing bar (for media-controls).

I hope you enjoy the changes I've made in the new update and thank you for the suggestion!

**Comment by sealants** [comment]
I think the design looks great, but it could be even cleaner. This is just some constructive criticism. To start, I suggest removing everything except the media controls. You could place the volume slider vertically on the right or left side. Album art isn't necessary, but it could be an option. The "fullscreen" mode still shows the 3-dot menu bar on the top left and looks a bit too busy. Instead, you could use the same hover feature you used for the cinema open/close to display the media controls and everything else on the screen. Essentially, I think it should just be the background art and the lyrics until the user interacts/hovers on the screen with their mouse to display and interact with the media controls.
