### ISSUE TITLE
(Suggestion) Can you add a floating lyrics option. So the lyrics window pops out?

### ISSUE THREAD

**Issue by sarthak9793** [surfbryce/beautiful-lyrics#131]

**Comment by surfbryce** [comment]
@sarthak9793 Do you have any references you are specifically thinking of?

Like do you want the lyrics window to popup only in the Spotify window or have it be its own separate window?

I can make it so it can pop out in Spotify but that's about it. There is no support in Spotify for other/outside windows.

**Comment by sarthak9793** [comment]
I was thinking about a separate window. Cuz right now you have to keep the entire spotify application on the screen if you want to see the lyrics while multitasking. And you cannot minimize spotify window below a certain size. But I guess that is not beyond the scope of this extension. Thanks anyway for replying.

**Comment by surfbryce** [comment]
Yeah @sarthak9793 that is currently not possible in Spotify. Once it becomes possible I'll definitely put some work into making it a feature!

**Comment by Davoleo** [comment]
@surfbryce 
that's strange, there's an official spicetify extension that does exactly that: https://github.com/spicetify/spicetify-cli/blob/master/Extensions/popupLyrics.js
![image](https://github.com/surfbryce/beautiful-lyrics/assets/24458276/b6d02827-446e-493a-96fc-57fee90e3647)
it's not exactly a window and works more like a PiP player
but you can use it with spotify minimized which is the usecase the OP mentioned
![image](https://github.com/surfbryce/beautiful-lyrics/assets/24458276/ff72e9b3-9ebd-4ad9-8166-c82c7cbcb58b)
