### ISSUE TITLE
Any way to disable the auto play music thing from this extension?

### ISSUE THREAD

**Issue by Aeropro4** [surfbryce/beautiful-lyrics#135]
this extension brings the now playing view pane to life but i have auto start spotify on log in enabled that' why when spotify opens the recently palyed song starts which is kinda annoying

**Comment by surfbryce** [comment]
@Aeropro4 I'm going to mark this as a duplicate and move this over to #127. It's good to know someone else is running into these issues.

**Comment by Aeropro4** [comment]
K
