### ISSUE TITLE
Custom Lyrics/Scroller (Syllable-Lyric/Live-Lyric/Static-Lyric support)

### ISSUE THREAD

**Issue by surfbryce** [surfbryce/beautiful-lyrics#14]
There's a few significant problem with Spotifys implementation of Lyrics;
- Lack of Syllable-Synced lyrics
- Lack of Background Vocal Synced Lyrics
- Lack of properly associated Lyrics (Lyrics appearing on songs they have nothing to do with)
- Laggy Lyric Movement
- Hardcoded Lyric Scrolling

However, Apple Music also has problems with their more technical details:
- Background lyrics often get skipped when the next lead-vocal starts (this is the same for other lead vocals that leak into the next)

The plan is to completely overhaul Spotifys implementation while also fixing the issues Apple has with theirs (while maintaining the same feature-set).

We'll be using a mix of Spotifys and Apple Musics lyrics APIs to do this (both of these lyrical databases combined will be more than enough to cover a majority of songs with the best lyrics possible).

Spotify returns a JSON object which is rather easy to parse, Apple Music however returns a ttmlXML file which requires a DOMParser and then additional checks/search.

Lyrics have these known specific attributes;
- Opposite-Alignment relative to Natural-Alignment (for example, in English a lyric is naturally aligned left and this attribute forces right alignment, in Arabic it would be naturally aligned right but forced left) 
- Background Lyric

Whether they are a syllable is easily identifiable in both APIs - it's these specific characteristics that are more difficult to figure out. Luckily Spotify doesn't have syllables yet and only line-synced lyrics - so this concern is only with Apple Music.

After examining a few songs that have all the bells and whistles - mainly the works; "Little Saint Nick", "God Only Knows", "Good Vibrations", "Wouldn't It Be Nice", and "Odyssey" - which, I've determined a few things from.

Apple Music has differing lyric identifiers for syllables/line synced lyrics.

Background-lyrics only exist on Syllable-synced songs and are represented as span elements branded as ttm:role="x-bg" with their own individuals spans representing their spoken-words. They are apart of the same list that other regular span elements are found in when navigating the paragraph element.

In both Syllable/Line synced lyrics though the Opposite-Aligned lyrics will always be ttm:agent="v2". This is always applied to the paragraph element itself.

**Comment by surfbryce** [comment]
For anybody watching this for updates, I've finally started work on this entire portion of the update.

Today I finished the live-text lyric effect (this is applied to Syllable-Synced lyrics - Background Lyrics obviously are Syllabled Synced by default so they also get this).

Not all syllables will split up into individual letter. Only those that are deemed "emphasized" enough will. The "I," and "wears" are examples of this.

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/8e2be0cc-4683-4a90-a4fc-73b917de1543

I plan on making sure the Background Lyrics look correct as well (these are always syllable synced) alongside making the line-sync effect tomorrow.

**Comment by surfbryce** [comment]
Another update; I've cleaned up the code for syllable line animation so that I can construct a class which builds and handles the set of lyrics itself.

This allows me to easily construct this class for a background and lead vocal layer. As seen in the video below;

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/320583f8-f42d-4c8b-b622-8c2dc6b77906

You also see three states in the video; Idle, Active, and Sung. You can see these in the opacity changes. The opacities match what I've configured in Spotify.

What's to come is the line sync animation.

Once that is complete then I will work on a parser for the data retrieved via my endpoint. After that I will then create a small demo which won't involve scrolling but just the entire thing put together. Once I've done that custom-scrolling will be next - and shortly after that starting to implement this into the extension itself.

For anyone watching - I would expect to see this finished within the next week or so.

**Comment by baraql** [comment]
This is dope— any way I can get involved and help out?

**Comment by surfbryce** [comment]
> This is dope— any way I can get involved and help out?

Thank you for the comment and your interest!

As of right now I don't know if there's any direct way you could pitch in at this moment since everything is pretty much downhill at this point. The endpoint stuff has already been finished and is currently running in the extension (#15) - so in relation to that there is only the parsing - which I have a specific data-structure in mind (and the parsing shouldn't be too difficult anyways).

The animating aspect is pretty much finished. The line-sync animation is just going to reuse the base word scale/y-translation effect so that will be trivial.

So for this aspect of the 3.0.0 update I don't think I'll need any help - but feedback is always welcome and will be considered.

In the future though (the first iterative update for 3.0.0 - most likely) I will be adding a custom lyric syncer to create synced lyrics for songs that don't have syllable-synced lyrics. This will include a front-end to do so - which when finished it will save locally for that song and in addition send that custom set to my backend. There'll be a review frontend in the extension for me and possibly future candidates that can be considered "reviewers" or something.

That'll be a much larger task than this though so most likely that would be the best point to jump in on.

I really appreciate your interest though, thank you!

**Comment by surfbryce** [comment]
Another update, I've gotten the Line-sync lyric animations in. Of course really simple - I've decided to drop the size/y-displacement effects and stick to basically what I did in the existing extension.

I kept the glow though. So it's just a glow, state change, and font-size change.

Will get to parsing on Thursday and then seriously start working out the entire lyrics-display as well.

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/7104dcdb-9fd8-491b-83b5-09cb4717774b

**Comment by surfbryce** [comment]
Alright so here's another update; the parser is now completely finished. So tomorrow I'll work on the lyrics display demo.



![Image](https://github.com/surfbryce/beautiful-lyrics/assets/80861823/40699cf8-7e0d-4e07-b461-cbfb788ecdae)



![Image](https://github.com/surfbryce/beautiful-lyrics/assets/80861823/f7368ee5-82bf-4471-90b3-9abd7d0a1284)

**Comment by surfbryce** [comment]
Alright so we're basically in the home-stretch of all this. Spent some of today visually refining everything - pretty much all the time for today was towards that.

Since everything was already built it was super easy to get the demo up and running.

There are still some visual kinks that I will fix tomorrow but everything is functionally perfect so thankfully there won't be any working going towards that.

For the line-synced lyrics I was a little frustrated that I wasn't able to really tell when the lyric would end without the audio! This is of course not an issue with you're listening to the audio but I feel like it's a nice touch to add. So I thought about the gradient again - you can't have it go horizontally because that applies those words are being said there and then - but, you can do it vertically! Upwards seems the most natural but I went with going down because it follows the direction the lyrics are going in! I even prefer downwards motion in this case surprisingly! I really do prefer this effect over just have the lyrics come out at you with big white text since it gives a sense of time whilst not being too distracting.

I also added support for the Aligned-Opposite lyrics - which again - are lyrics aligned opposite to their natural alignment (Arabic/Hebrew/etc. are aligned right naturally but many other languages are aligned left naturally).

I also noticed in Apple Music the lyrics will never take up the full width so I made it so they only take up 75% of the containers width. When I do further refinements tomorrow though I will make it so this only happens when there are lyrics that are aligned-opposite as it doesn't make sense otherwise to lose all that space.

Anyways here are all the lyrics setup (these are using live data from the endpoint);

Syllable:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/de598d66-ad99-4f17-ae3b-257c50f49f49

Line:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/f18e0a6b-6f11-48ba-8d03-5e443b943e19

Static:

![Image](https://github.com/surfbryce/beautiful-lyrics/assets/80861823/573aed55-be26-409a-8a4d-4c4cbe8aae86)

**Comment by surfbryce** [comment]
Alright so I actually went ahead and decided to do the refinements tonight since I had some free-time.

I solved the major issues which were the gradient bleed in and text-wrapping changes in the Line-Sync. Static lyrics obviously needed no change and Syllable-Lyrics were pretty much already there.

A major part of these refinements were creating better CSS Class names for those that needed them and taking often cloned parts and putting them into a shared CSS class controlled by properties.

All the visual components I would say are now production-ready (both backend and frontend wise). Tomorrow I will work on the auto-scrolling aspect and then work on getting these integrated. I would expect a release sometime this coming week. Most likely by Friday. I want to work on the Fullscreen mode first so I can really utilize these new lyric visuals.

Here are the previews of what I can consider the finalized versions;

Syllable-Synced:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/758abad3-3c11-4df2-ace0-1affc025e53e

Line-Synced:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/0eaf3cbe-bf35-4e68-a48d-ab36cee41722

**Comment by surfbryce** [comment]
Alright so I've completely implemented Auto-Scrolling. I had to use a custom-scrollbar solution since the built-in browser one is impossible to use for this kind of stuff.

It allows free-scrolling and only starts auto-tracking once you've stopped scrolling and an active lyric comes into view. By default it auto-tracks however so you don't need to do anything there.

Nothing more to say here other than it all just works!

Auto-Scrolling:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/e55a1998-7aa7-4c41-ad94-7b07b5b6de85

Free-Scrolling and then Auto-Scrolling:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/507763f7-3942-424f-97b1-f3894cc683f1

**Comment by surfbryce** [comment]
Alright so I got a lot less done today than I had wanted since I spent a lot of time debugging and tweaking. The biggest issue was that the spline library I was using was not all that great at creating paths from a set of points. I then tried my own solution from my Game Development experience which may not have come across in translation (from Luau to Javascript) or just doesn't perform well with smaller numbers.

I then found an incredible package on NPM called CurveInterpolator which is the greatest thing I've ever found. It's incredibly robust and includes a ton of useful methods - which more importantly - it has an intersect method. I use this now for the interlude indicator to get the current point on the animation curve at the time we are requesting.

Unfortunately now the extension will use two spline libraries since I don't want to interfere with nor change the prior animation constants for everything else.

But! Now I can say that every aspect of the vocals is now properly implemented. This did come with some internal changes to the typings and data-structure that the parser spit out so that it can return a set of vocals that are either interludes or their respective types (Syllable/Line).

This means the scroller didn't need anything else additional to support interludes since they all synced items work the same (they're all implementations of the SyncedVocal interface). The same goes for updating/animating them - nothing additional is required.

So this system is really robust overall and well planned out - which I am very happy with! I haven't talked much about how this entire system handles different dimensions, timings, and etc. but mainly all you need to know is that this is a completely responsive implementation that focuses on the best user experience no matter the container-size.

The interlude timing is also the only animated vocal element that is actually dependent on the physical time rather than a time-scale. So the amount of times it pulses is based on how long the interlude is. The fade out and fade in timings are also the same.

My goal is that Tuesday I will aim to get the blurring/hovering working and also the player wrapper. I might integrate it the very same day or save that for Thursday. Either way I'm very excited and it looks like I should be able to get this shipped out this week!


https://github.com/surfbryce/beautiful-lyrics/assets/80861823/b34163d9-7ca1-497e-b678-7ae7793a177f



https://github.com/surfbryce/beautiful-lyrics/assets/80861823/a46d46ce-5268-4f36-9cf5-431ceaa5041b



https://github.com/surfbryce/beautiful-lyrics/assets/80861823/4fd7f83b-109f-4034-8034-33142ff51c53



https://github.com/surfbryce/beautiful-lyrics/assets/80861823/eb66a9f6-a6c1-4709-97bc-7b7971cdc3c8

**Comment by surfbryce** [comment]
Alright so I'm going to go out on a hike now but putting out a small update. Almost everything that needs to be done visually/functionally is implemented! Which will make the rest of this process so so much easier and might be able to implement it all tonight!!

I got the blur, hover, and clicking to work. To be fair the hover and clicking weren't difficult to implement at all and really the clicking are just exposed click events for each vocal (not lyrics - which in syllable are broken up - vocal is the entire lead/background).

I did a really good job designing this system since everything just needs to be plugged into the right stuff and it'll all work no problem. Completely responsive, completely performant, just pure awesomeness!

Also about the performance, I made some much needed CSS performance updates. A major performance part was changing it so when lyrics aren't active they aren't using the background-gradient and are instead just using a text-shadow to render with the color set to the result that the background-gradient would have given. This allows me to reuse the same blurring functionality that I was using in the extension already. Plus we aren't spending a ton of time rendering a background-gradient for each damn lyric when 99% of them are a solid color!

Anyways after my hike I'll work on the player wrapper and then work on integrating everything.

Here's a video as always (showcases better scrolling functionality, blurring being disabled while scrolling, hovering and clicking, and etc.);


https://github.com/surfbryce/beautiful-lyrics/assets/80861823/58be348b-acdc-4939-bd6a-5e1320f96eab

**Comment by surfbryce** [comment]
I've got it up and running in Spotify for now. Not implemented in the card yet or anything since there are a few things to work out. I worked out a kink in the backend where on the Apple Music side it would accept things that couldn't really be played songs anymore.

Planning to work out most of the kinks in the morning!


![Image](https://github.com/surfbryce/beautiful-lyrics/assets/80861823/404da179-e946-4d57-ba7a-6e3775899559)

**Comment by surfbryce** [comment]
Alright so another update - most of the issues were actually just forgetting to change variable names and having to account for one stupid spotify thing.

Otherwise, everything was pretty straight forward to get going correctly. Still haven't put it in the side-card but that's next now!

Biggest thing changed since that last one is being able to click on the vocals and it setting the timestamp to that the start of that vocal-group.

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/8b444b8c-c9f5-4726-a78c-98a2f4be6d2f

**Comment by surfbryce** [comment]
The whole thing is now integrated!! Big milestone in this extensions history.

Made a lot of minor adjustments in getting this to look right. As of today this will be the farthest I go (not like there's much more after this anyways). It'll be mainly small refinements as I see fit for this until release. The next thing I want to work on is a full-screen variant potentially. I'll have to consider whether or not I would want to implement this though.

Also you might see in one of the previews a little visual glitching - this is because I'm running on a developer beta of MacOS and somehow they absolutely destroyed the stability of WebKit rendering. This isn't something the extension will have naturally though - unless your webkit is completely botched as well.

I'm planning to put out this update Friday - depending on if there's anything else that I would want to add prior.

Previews;

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/79b6c2e4-a57b-4427-a498-c85990b5683a

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/f9b552fe-6631-4dba-a5f4-e1438c82c6ae

**Comment by CodedNil** [comment]
Amazing!! Super excited to try this, looks incredible
