### ISSUE TITLE
extremely laggy in macos

### ISSUE THREAD

**Issue by kairiane** [surfbryce/beautiful-lyrics#141]
it's just really really laggy in macos for me, maybe it could be optimised a little better idk

**Comment by IdkWhatToCallMe123** [comment]
On every platform I used this extension on it makes spotify kinda laggy.

It's prob bc spotify is already crappy and this extension adding all the effects makes the performance even worse

**Comment by kotobuki09** [comment]
Even in windows as well

**Comment by surfbryce** [comment]
Answered this one on #159
