### ISSUE TITLE
Question: Where is the data sourced from?

### ISSUE THREAD

**Issue by Riceblade** [surfbryce/beautiful-lyrics#143]
Where are the lyrics and the info on how long each word is and stuff sourced from?

**Comment by surfbryce** [comment]
@Riceblade Everything at its core is provided by Musixmatch which in turn is given its data by the Artists/Label (and sometimes by community curators).

Some services (like Apple Music, Tidal, and Spotify) will have their own services in conjunction with Musixmatch to have artists submit directly to them and their own curation teams.
