### ISSUE TITLE
(Help) Cant figure out to config

### ISSUE THREAD

**Issue by DaddyBlueUWU** [surfbryce/beautiful-lyrics#145]
Ive been using this for quite some time now (Both on macOS and Windows 11) And i love this so much! But i saw on the download page that theres variants of the way lyrics is being showed? I looked around spotify but cant seem to find the place to configure the way the lyrics is being showed? Does anyone know where it is? ^^

**Comment by surfbryce** [comment]
@DaddyBlueUWU Those variants you are seeing are the lyric types (Static, Line, and Syllable) which are present on different songs.

These lyric types are determined by the submitted lyrics from the artist/label. Whether a song is synced by word/letter, by line, just has the lyrical text, or nothing at all is completely up to the artist/label.

I'm assuming this is what you're talking about. There is no configuration for this extension beyond the UI toggle in Cinema mode.

**Comment by DaddyBlueUWU** [comment]
Ah okay! Thank you so much!
