### ISSUE TITLE
Icons color goes black after resetting Experimental features

### ISSUE THREAD

**Issue by Firmeteran** [surfbryce/beautiful-lyrics#147]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/377b8034-4d19-41d8-8a81-d7a4ced4ac09)
Hi, it's me again. 
Actually I forgot why I was doing that, is there some settings that makes the icon appears normally?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/3a855b29-dcc6-4637-a93b-19b5c4582040)
Since normally I don't use any themes, here's Sleek theme with Wealthy scheme.

**Comment by surfbryce** [comment]
@Firmeteran I actually just noticed this myself, I think it's because of a Spotify update so I'll look into this right now. I just solved another issue so this will be in a patch in the next hour or so.

**Comment by surfbryce** [comment]
Fullscreen button also had this issue, they are both fixed now and will be in the next update.

**Comment by surfbryce** [comment]
The new update is out, restart Spotify and it should be there - or wait for it to auto-update
