### ISSUE TITLE
(bug) Text glow effect cut off in fullscreen mode 

### ISSUE THREAD

**Issue by GalexY727** [surfbryce/beautiful-lyrics#149]
This is what text looks like when glowing when clicking the "Lyrics Page" button 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/65139378/e4324c6f-50e1-433a-be8a-009001e97e9b)
And this is what text looks like when clicking the fullscreen button on the bottom right of Spotify (notice the left edge)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/65139378/d400e4d9-57de-4e62-8f05-65c0af9b5199)

I haven't done a whole lot of CSS work, but this appears to be an issue where there is a `<div>` used instead of a `<span>` (but don't take my word for it I don't know)

**Comment by surfbryce** [comment]
Duplicate of #100

**Comment by GalexY727** [comment]
Sorry!

**Comment by surfbryce** [comment]
also this is not an issue with div/span, it's an issue with scrolling content - I've solved this before but it seems like I've changed something which caused it to come back again.

**Comment by GalexY727** [comment]
I see, I wish you the best on it and might try to tackle it on my own if you don't beat me to it, it could be a good opportunity to learn CSS

**Comment by surfbryce** [comment]
@GalexY727 It's a relatively easy solution and it just requires adding some padding to the left side (which is what I did before). There's already a property for that padding so I just need to add some units to it.
