### ISSUE TITLE
(Using Bloom theme) How to get rid of default lyrics button?

### ISSUE THREAD

**Issue by AeonIsLost** [surfbryce/beautiful-lyrics#153]
I don't want the old lyrics button when I already have the new one, how do I get rid of it? I'm using Bloom theme but I don't think it's relevant 'cause the button is still there without any theme. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/140863305/d0a6906d-cfcb-4cd9-9f31-c54a290e21f7)

**Comment by Tseshongfeeshur** [comment]
Hmmm… Did `beautiful-lyrics` work well with the theme `Bloom`? It seems have some trouble on my Spotify…
By the way, maybe you could use the tool in Marketplace called `Hide now playing view button`, and edit its code to hide the lyric button. :smile:

**Comment by surfbryce** [comment]
@AeonIsLost Enable "Show lyrics in Side-bar" or something like that. It'll remove Spotifys lyric-button.
