### ISSUE TITLE
Theme Bloom Issues

### ISSUE THREAD

**Issue by Tseshongfeeshur** [surfbryce/beautiful-lyrics#154]
Hi! This is the screenshot. As you see, the lyric has not be shown. The theme is `Bloom`. Thanks!
I am sure that the Internet connection is believable. :smiley:
![Screenshot_20230924_112824](https://github.com/surfbryce/beautiful-lyrics/assets/99335871/6a32b4b5-a547-46fb-9750-5cd58bce985d)

**Comment by surfbryce** [comment]
@Tseshongfeeshur This is not an issue with Bloom, it's an issue with the extension since it seems like the added icons are not visible. Does this happen to you always or just this once?

**Comment by Tseshongfeeshur** [comment]
It goes well now. Thanks! :smile:

在 2023-09-29 12:09:11，surfbryce ***@***.***> 写道：


@Tseshongfeeshur This is not an issue with Bloom, it's an issue with the extension since it seems like the added icons are not visible. Does this happen to you always or just this once?
