### ISSUE TITLE
Translate button duplication

### ISSUE THREAD

**Issue by PeterStark000** [surfbryce/beautiful-lyrics#156]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/40671520/6cb4c0bb-aae6-4e56-b90f-cb45fce60f46)

**Comment by surfbryce** [comment]
@PeterStark000 Do you have any replication steps? Like what did you do that caused this?

**Comment by PeterStark000** [comment]
> @PeterStark000 Do you have any replication steps? Like what did you do that caused this?

The bug occurs unexpectedly, here it happened when I usually open it in fullscreen mode on TV or sometimes it just starts duplicating multiple times... There isn't a very consistent replication step.
