### ISSUE TITLE
High CPU usage in linux

### ISSUE THREAD

**Issue by EmpireFugee** [surfbryce/beautiful-lyrics#159]
spotify cpu usage spikes to >10%  when beautiful lyrics is installed, which causes fans to go louder.

is there any specific problem causing this issue? can the cpu usage be minimized?

spicetify version: 2.23.2
garuda linux: 6.5.4-zen2-1-zen

**Comment by surfbryce** [comment]
@EmpireFugee This has been a known issue that the extension requires more CPU and GPU usage. This is the downside to A) the browser engine Spotify uses and B) rendering in a web-browser.

For now there are some optimization stuff that have to do with the background to help ease the performance but that won't be out for a while.
