### ISSUE TITLE
Display Errors

### ISSUE THREAD

**Issue by ubeann** [surfbryce/beautiful-lyrics#16]
I don't know why my Spotify interface looks like this. I have tried uninstalling Spotify and updating Spicetify to version `2.18.1`. Could this extension be conflicting with the theme I'm using? Currently, I'm using the Bloom theme, and I believe it should match the extension's preview. Is there anyone who can help me resolve this issue? I'm using a Mac device with the latest macOS. I apologize if this issue stems from the theme or something else. I'm quite confused about where to ask for assistance.

1. Header (Back, Next, Profile, and Friends Button)
<img width="1138" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/76271600/2d847064-7d81-4a5f-953c-a7dcfc334672">

2. Font Lyrics
<img width="1160" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/76271600/b28222b1-9bf7-495b-a05b-25d00510ef0e">

3. Card Color (doesn’t transparent)
<img width="1138" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/76271600/0cccd55d-f075-4f64-a388-7a8691a892dd">

**Comment by surfbryce** [comment]
My extension is not the source of these problems you are experiencing.

It's most likely that your theme has not updated to the changes Spotify has made internally in the latest update. Additionally, the lyrics panel not being the transparent as seen in my images is something the theme you have applied is changing.

I would recommend going to the GItHub of your theme and writing up an issue there about the Header issue; the font lyrics and card transparency is just something you'll have to deal with as that is what is a part of the theme.
