### ISSUE TITLE
Remove blur

### ISSUE THREAD

**Issue by wotikama** [surfbryce/beautiful-lyrics#162]
What do i have to edit to remove blur

**Comment by surfbryce** [comment]
@wotikama It depends on what blur you are talking about.

If you are talking about the lyric depth-blur you will have to edit the lyric CSS in a snippet and set the blur to always be 0.

If you are talking about the background you simply just need to set the visibility of the background container to hidden.

You can experiment with this by turning on the developer mode in spotify, run the command "spicetify apply enable-devtools", then right click on any free space that doesn't trigger the Spotify menu, once you're there you can open up the Developer Tools window.
