### ISSUE TITLE
Theme Comfy Issues

### ISSUE THREAD

**Issue by R3alHumanBe1ng** [surfbryce/beautiful-lyrics#165]
When using the Comfy theme the fullscreen window does not display correctly
Album art is lower than it should be
![image](https://github.com/surfbryce/beautiful-lyrics/assets/72706772/9adcfeca-87dc-45dd-b278-c6f0e2c46f9e)

**Comment by ohitstom** [comment]
I have fixed this within comfy but you need to come up with some sort of way to block all css from themes on these elements otherwise problems like this will keep cropping up

**Comment by surfbryce** [comment]
@ohitstom I don't think that's even possible since CSS is quite literally cascading. I don't mind putting in patches in the CSS for this I just haven't gotten to the ones still listed in Issues because I've been incredible busy recently

**Comment by ohitstom** [comment]
> @ohitstom I don't think that's even possible since CSS is quite literally cascading. I don't mind putting in patches in the CSS for this I just haven't gotten to the ones still listed in Issues because I've been incredible busy recently

you could remake them or change their classnames or move the entire playbar to be a part of the overlay instead, idk just that there's a lot of themes that mess with the playbar lol

**Comment by surfbryce** [comment]
@ohitstom yeap, the pain and suffering of using what's already there ⚰️

**Comment by ohitstom** [comment]
> @R3alHumanBe1ng This should now be fixed, thanks for reporting!

may I ask if you tested this on current comfy since it's not really a fix if we are actively supporting the extension already, hope to not have to do a check for the extension if possible lol

**Comment by surfbryce** [comment]
@ohitstom Yeah ideally it would be best if you didn't add specific stuff for this extension just for your sake so you don't have to update your codebase for somebody elses stuff (my case is an exception here since I'm using components that are modified by themes, which is something I accepted when going into this). It should be fine now, but if the issues comes back after you remove the extension specific stuff I'll just fix that since I'm freed up a little more time wise now.

**Comment by ohitstom** [comment]
awesome, just since I'm in the middle of refactoring our extension so if it's something I can remove at the same time that would be handy. and yeah keeping compatibility between extensions and themes are hard when using existing classnames I understand the struggles 🥲

**Comment by jrvgr** [comment]
@surfbryce issue not fixed for me on macos

![CleanShot 2023-10-31 at 08 30 23@2x](https://github.com/surfbryce/beautiful-lyrics/assets/30769091/f1bb8770-c3ab-4862-94e3-40ee98c7ab17)
