### ISSUE TITLE
What snippet do I have to add to remove lyrics blur

### ISSUE THREAD

**Issue by wotikama** [surfbryce/beautiful-lyrics#167]

**Comment by surfbryce** [comment]
@wotikama I cannot tell you the snippet as I don't have the time to go through and look.

I suggest enabling Developer Tools by running the command "spicetify apply enable-devtools", right clicking on any open space in Spotify that doesn't enable the Spotify right click menu, and then going to Developer Tools and opening that up. Using inspect-element you can then figure out how to properly affect what you're looking for.
