### ISSUE TITLE
[Question] Where does the extension source lyrics data from?

### ISSUE THREAD

**Issue by AgentMonkey00** [surfbryce/beautiful-lyrics#173]
The extension is great, but I've noticed a lot of songs that I play on Spotify are synced word-by-word on Musixmatch. However, these songs aren't synced word-by-word on the extension and only show line-by-line. Does anyone know why this is, and is there a way that I can change it?
The only explanation I can think of is that the extension doesn't use Musixmatch and sources lyrics elsewhere. 

Thanks :)

**Comment by surfbryce** [comment]
@AgentMonkey00 I'm going to send you over to #171 since this is the exact same issue, can you (over on that issue) comment the songs that are not having their best version put up and available? I've described the issue over on that issue

**Comment by AgentMonkey00** [comment]
Thanks!

Sorry for the repeat issue, I should have looked before I posted.
