### ISSUE TITLE
Playbar details are in the middle of the screen

### ISSUE THREAD

**Issue by The-Unknown-Programming-Student** [surfbryce/beautiful-lyrics#177]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/116381063/85bc20f8-18ec-4589-84fd-a081312c3ed1)

**Comment by surfbryce** [comment]
@The-Unknown-Programming-Student What theme are you using here?

**Comment by The-Unknown-Programming-Student** [comment]
> @The-Unknown-Programming-Student What theme are you using here?

I am using Matte by darkthemer

**Comment by surfbryce** [comment]
@The-Unknown-Programming-Student This should now be fixed, thanks for reporting this issue!
