### ISSUE TITLE
Question regarding how you created this colorful wave effect

### ISSUE THREAD

**Issue by BigLadDylan** [surfbryce/beautiful-lyrics#179]
Hello, I am a really big fan of this sort of style/theme and I would like to know how or if I could possibly replicate it in similar/other applications to have a sort of "ecosystem" with this theme universally. 

Most notably, I am a big fan of linux ricing and although I am just starting out, I really want to implement this sort of theme systemwide, that changes dynamically based on the song, and therefore, the theme spotify is showing.

This sounds like an enormous task and I know I can read the source code but its really quite hard to understand what exactly is going on. If you wouldn't mind, could you maybe walk me through how this theme works:
- how it fetches the color of the song
- where it outputs them to so i can get scripts to grab the colors from that output to dynamically change the colors of my system.
- how to do that glass, psuedo-transparent wave effect.

I would greatly appreciate any insight you could give me!! If I were to implement this vision then I would for sure make it available for everyone on github or something.

Thanks alot! :)

**Comment by surfbryce** [comment]
Two copies of the cover art blurred with one on top of the other. Both infinitely spin. That’s it.

**Comment by BigLadDylan** [comment]
@surfbryce could you please tell me how you managed to do that? How could i replicate that. Apologies if its obvious in the code, i'm sort of learning... 

How are you able to take the cover art? and then set it as the background and make them spin?
I am going to use this  https://github.com/JulienMaille/spicetify-dynamic-theme/tree/main to get the colors. 

The plan is to take the colors from the dynamic theme and import them into a css file so i can set ui elements. No clue how I'm going to do the spinning thing using things like https://github.com/polybar/polybar.
