### ISSUE TITLE
romanization problems

### ISSUE THREAD

**Issue by Marlon8732** [surfbryce/beautiful-lyrics#180]
When activating the commanization mode it is not applied, in Japanese it only goes from hiragana to katakana and in Korean no change is applied

**Comment by surfbryce** [comment]
@Marlon8732 What songs are you experiencing this with? It would be best if you told me the songs for each case (Japanese and Korean). It's possible the Japanese lyrics are actually being converted by the Chinese romanizer on accident. I'll only be able to tell once you tell me which songs are the issue though.

**Comment by hachihanashi** [comment]
I'm having the same issue as well, just updated spicetify and now it doesn't romanize it.

Here are the few japanese songs I tried but I think any of them faces the same issue.

https://open.spotify.com/track/2vzWcPxen1WvYbkGXpDilH?si=b3b07ee1b77f4acf

https://open.spotify.com/track/6g93YtKKHU2H1qIqhLIL0Y?si=36f8b76d97c343a8

https://open.spotify.com/track/2ZT6eELxeETGamaiXu6vmk?si=3cebb89f46884e4c

**Comment by crackheadakira** [comment]
What version Spicetify do you have? I'm currently not experiencing this on the aforementioned songs on latest extension version & Spicetify version 2.25.2

**Comment by hachihanashi** [comment]
> What version Spicetify do you have? I'm currently not experiencing this on the aforementioned songs on latest extension version & Spicetify version 2.25.2

I'm also running v2.25.2

**Comment by surfbryce** [comment]
Hi @hachihanashi they all properly romanize for me. Can you send screenshots of what all the songs look like to you?

I also want to state that I've had issues in the past where for some reason the Furigana package would convert japanese to a different sub-variant for no reason, so it's possible that's the case here.

Here is what they look like for me:
<img width="412" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/5513f543-abba-4316-8649-e93154df0ffd">
<img width="405" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/aa9aa814-e6ad-4018-9be7-83aacdf24df9">
<img width="409" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/ced74792-ffce-4b47-9566-80767bb8301e">

**Comment by Marlon8732** [comment]
Today I am testing and it is working correctly with the same playlist as yesterday
![image](https://github.com/surfbryce/beautiful-lyrics/assets/134746443/24debb29-b043-40c3-9a64-b9ba72d4c411)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/134746443/2204b7ee-d358-4d53-bee7-abd236460580)

**Comment by surfbryce** [comment]
@Marlon8732 Good to hear! Will see what the others say and if it works for them now too I'll assume it was a minor bug that occurred from the auto-update thing (which happens sometimes)

**Comment by hachihanashi** [comment]
@surfbryce This is what mine looks like

This is when its enabled
![enabled](https://github.com/surfbryce/beautiful-lyrics/assets/149466033/54d48887-ccbc-4836-ae6b-c25283ef5ad9)

This is when the romanization is disabled
![disabled](https://github.com/surfbryce/beautiful-lyrics/assets/149466033/04702556-1fb6-4987-afc8-fad018123e74)

**Comment by sTiKyt** [comment]
How do you even enable that...
