### ISSUE TITLE
Lyrics Page's button on top are not working

### ISSUE THREAD

**Issue by kutawhat** [surfbryce/beautiful-lyrics#197]
These buttons disappears right when I hover on them
![Снимок экрана 2023-11-14 в 21 48](https://github.com/surfbryce/beautiful-lyrics/assets/64655969/d4b9cb74-507b-4628-826b-05e731f670ef)

**Comment by surfbryce** [comment]
Duplicate of #186

**Comment by Samplayz2007** [comment]
issue still persist
