### ISSUE TITLE
Beautiful Lyrics is laggy

### ISSUE THREAD

**Issue by ralee0110** [surfbryce/beautiful-lyrics#199]
a week ago everything was fine with the extension, after a couple of days I noticed that my extension was lagging a lot and it started to annoy me... is there any fix ?

**Comment by ragh111** [comment]
It's so laggy! I can't even enjoy my songs
:<<... how can it be fixed?

**Comment by surfbryce** [comment]
Duplicate of #185

**Comment by bhxp** [comment]
recently started getting this issue, why is it?
