### ISSUE TITLE
Rotational Blur does not Work

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#2]
Hi, installed your extension and after installing it did not notice anything new except blurring in full screen mode. What should i do?
Spotify and Spicetify are the latest version. Installed the extension through Marketplace.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/c92f30ab-1fbe-42a1-b361-e4dea7ec8d1e)

**Comment by surfbryce** [comment]
Can you enable the right-side card for me to see if it's working in that?

To do that you go to your PFP, click on Experimental Features, and then search for "side" you should have the option to enable it.

If the background doesn't show up there then there might be a bigger problem for some reason

**Comment by Blankk02** [comment]
Background is not animated, only blurred
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/f6319aeb-8271-4371-adef-f1404e1a9c9e)

**Comment by surfbryce** [comment]
@Blankk02 Alright good to know that the right-side card is working properly; what are your installed extensions/themes/snippets if any? You can see those in the Installed tab of the Marketplace.

Also do you have Lyrics-Plus enabled at all?

Just trying to narrow down specifically what's occurring here

**Comment by Blankk02** [comment]
@surfbryce (Sorry for the wait)
I have only 4 extensions (on screenshot) but with or without them, this extension still does not work
No, I don't have Lyrics-Plus installed

**Comment by surfbryce** [comment]
@Blankk02 If possible could you send the experimental-features that you have on?

I also noticed you're on Windows; that possibly could be an issue - since I look for a specific property that determines what the Full-Screen lyrics background is - and that property could be different on Windows. I am on MacOS so I'll have to test it out on Windows to see if it happens at all for me.

**Comment by red1105** [comment]
@Blankk02 try enabling the Extract background color on Experimental features because mine was fix when i enable it
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93867876/e0b4bdff-c119-4b1b-919a-5883bdf51b2a)

**Comment by Blankk02** [comment]
@surfbryce There will be a lot of screenshots
But in short, I have everything as standard and additionally enabled Side Card and Extract background color

**Comment by Blankk02** [comment]
@red1105 This option changed the background slightly when using the Side Card and nothing else.
My app is updated, so I don't know what to do.

**Comment by Blankk02** [comment]
I also noticed that when I go into the Lyrics menu, there's a slider
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/c33497c0-9397-4762-a695-9155d08520a5)

**Comment by Blankk02** [comment]
Changes before and after installing the extension:
Before:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/64d8c69e-53e2-40a4-8bda-038e2dbdc472)
After:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/2b7a61cd-f270-4cb7-8618-f052c0355650)

**Comment by red1105** [comment]
can you also try enabling the Show lyrics in the right sidebar on Experimental features

**Comment by surfbryce** [comment]
@red1105 That’s a very good point - I completely forgot the lyrics being in the sidebar was an experimental feature since I’ve had it on since day 1 😓

Was wondering how they were able to have the side card and full-screen lyrics at the same time!

I’ll have to try that when I get back online and see if there’s a difference in the stuff i’m checking - it’s most likely that if anything

**Comment by surfbryce** [comment]
> I also noticed that when I go to the Lyrics menu, there is a slider that does not scroll through the lyrics
> ![image](https://user-images.githubusercontent.com/67868803/239519254-c33497c0-9397-4762-a695-9155d08520a5.png)

Yeah as red just pointed out the side-card lyrics option probably changes a lot of stuff internally when it comes to the lyrics themselves - that scroll bar works with it on most likely. I’ll be able to take a more in depth look when I wake up

**Comment by Blankk02** [comment]
@red1105 Thanks, this is already more like the truth but there is no animation
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/210670a7-393e-4b9c-bfbf-1419453bf22b)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/0faa2789-7fb0-4e3c-aff6-f08ed04303ea)

**Comment by Blankk02** [comment]
Now if we could just figure out how to turn on the animation as the author's GIF and the color near the song title on the bottom left
But I already like this extension, thanks for that <3

**Comment by Blankk02** [comment]
@surfbryce All list of experimental-features:
![2023 05 19 vgZd](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/6d6854c1-50b8-4855-828c-18830c129bb6)

**Comment by surfbryce** [comment]
> Now if we could just figure out how to turn on the animation as the author's GIF and the color near the song title on the bottom left
> But I already like this extension, thanks for that <3

The color towards the bottom is another extension called “Cover Ambience” - that is not a part of my extension.

Is the animation working on the side-bar? Or are both the full screen and side bar animations not working?

Another thing is to make sure you have Hardware Acceleration on - right click on the top of the Spotify window (where you would drag it) and see if it’s checked off or not

**Comment by Blankk02** [comment]
> > Now if we could just figure out how to turn on the animation as the author's GIF and the color near the song title on the bottom left
> > But I already like this extension, thanks for that <3
> 
> The color towards the bottom is another extension called “Cover Ambience” - that is not a part of my extension.
> 
> Is the animation working on the side-bar? Or are both the full screen and side bar animations not working?
> 
> Another thing is to make sure you have Hardware Acceleration on - right click on the top of the Spotify window (where you would drag it) and see if it’s checked off or not

I have hardware acceleration enabled, but the animation does not work anywhere

**Comment by surfbryce** [comment]
Alright I’ll have to investigate that when I wake up then - I’m not sure why it’s not animating for you; realistically that’s the one part that shouldn’t fail at all - so it’s either something really weird with my extension or Spotify itself messing up the rendering.

Just for good measure restart spotify and see if that fixes it - otherwise I’ve got no clue without getting on and checking it out.

Also if it doesn’t work after the restart - and if you don’t mind sharing - what are your computer specifications? You can find that by right clicking on “My PC” in the File Explorer and clicking details

**Comment by Blankk02** [comment]
> @Blankk02
> 
> Alright I’ll have to investigate that when I wake up then - I’m not sure why it’s not animating for you; realistically that’s the one part that shouldn’t fail at all - so it’s either something really weird with my extension or Spotify itself messing up the rendering.
> 
> Just for good measure restart spotify and see if that fixes it - otherwise I’ve got no clue without getting on and checking it out.
> 
> Also if it doesn’t work after the restart - and if you don’t mind sharing - what are your computer specifications? You can find that by right clicking on “My PC” in the File Explorer and clicking details

No, unfortunately restarting didn't help
I have a laptop and here are its specifications:
GTX 1060 6GB
I7-8750H
8 GB RAM

**Comment by surfbryce** [comment]
Just an update @Blankk02. I did try this on a windows-laptop; although, one that has significantly more memory than what you are provided - I did not run into the same issue you were.

So unfortunately I'm not sure how to proceed given that this seems to be a rendering issue rather than anything else - so I'm assuming Spotify isn't deciding to do certain things possible because of the amount of memory you have.

Again this is pure speculation - I would highly suggest updating to the newest version of the Extension to see if it fixes it for you.

If it doesn't let me know!

**Comment by Blankk02** [comment]
@surfbryce I updated to the latest version and it still doesn't work.
I also checked if it works on Windows Sandbox but nothing there either.
Maybe the problem is in Windows 11?

**Comment by Blankk02** [comment]
But thanks anyway for the extension, even though it didn't reveal itself fully for me :)

**Comment by surfbryce** [comment]
> @surfbryce I updated to the latest version and it still doesn't work.
> I also checked if it works on Windows Sandbox but nothing there either.
> Maybe the problem is in Windows 11?

Definitely not Windows 11 since the laptop I tried it on was Windows 11. It may be something else - hopefully, it will reveal what that is soon.

**Comment by surfbryce** [comment]
> But thanks anyway for the extension, even though it didn't reveal itself fully for me :)

I'm sorry that the rotation isn't working for you - I just wish I could figure out what is causing it. I'll do some research today and see if I can find anything about it.

Thank you for your kind consideration though - it's really appreciated!

**Comment by Blankk02** [comment]
I helped a friend install the extension and it works for him
I'm afraid there's something wrong with my system, if I find out this is the case I'm very sorry for your time

**Comment by Blankk02** [comment]
The reason was in the effects of Windows, which I turned off to optimize the laptop, turning everything on by default, I worked animation
Thank you very much and I apologize very much for your time in solving this problem
