### ISSUE TITLE
Crossfade desynchronizes lyrics

### ISSUE THREAD

**Issue by vilewired** [surfbryce/beautiful-lyrics#200]
Hey, I've used beautiful lyrics for quite the while now and I wanted to thank you a lot for it. I just noticed that when having crossfade enabled and listening to a single song on repeat, once it repeats the lyrics and song are out of sync. I just tested and this doesn't happen if you listen to 2 different songs. My crossfade is set to 2 seconds if that should help. I'll turn it off for now, if you need any more information just let me know :)

**Comment by Blacklight2k** [comment]
how do u alter it??

**Comment by viledissociation** [comment]
> how do u alter it??

alter what?

**Comment by surfbryce** [comment]
Should be fixed due to new Player module functionality, re-create the issue if it still happens

**Comment by vilewired** [comment]
I'll check, btw nice glasses 😭🙏
