### ISSUE TITLE
Theme Ziro Issues

### ISSUE THREAD

**Issue by dumpstrlvr** [surfbryce/beautiful-lyrics#207]
![imagen_2023-12-06_154633416](https://github.com/surfbryce/beautiful-lyrics/assets/153099681/f944fd51-7553-4c41-8466-7398d778ac6c)
![imagen_2023-12-06_154652873](https://github.com/surfbryce/beautiful-lyrics/assets/153099681/deb0a036-0986-49a5-add3-c34516ba2753)

As you can see, the lyrics do not appear as they should
any solution please

**Comment by surfbryce** [comment]
Duplicate of #193
