### ISSUE TITLE
Extension Not Working? GO TO MY COMMENTS IN THIS POST!

### ISSUE THREAD

**Issue by NocturnalPerson** [surfbryce/beautiful-lyrics#208]
Beautiful lyrics button not showing and also not on the now playing view
![Screenshot (32)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/141494ff-8b4d-43fb-9b29-e11ce61c8446)
Also not in fullscreen mode
![Screenshot (34)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/38c8cb00-c807-4559-ae5d-cf885dcf418c)

**Comment by ruizxzx** [comment]
which theme are you using??
also mine not working too

**Comment by PornAddiction** [comment]
> which theme are you using?? also mine not working too

I use a theme called sleek and changed it to ultra black
![Screenshot (36)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/ac83dc5a-aac5-415e-bad0-26ff774f2e7f)
![Screenshot (38)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/87852efb-0422-4c23-bd62-3eadbed1bbda)
Also my spotify updated and it was working again so you just probally need to update spotify for it to work again
![Screenshot (35)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/e844163d-952d-467f-95e4-ae9ba282d886)
![Screenshot (37)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/ded00451-5454-413c-a244-6ef4ebf826f7)

**Comment by ruizxzx** [comment]
mine still not working, in spotX mod. are u using original spotify?

**Comment by NocturnalPerson** [comment]
> mine still not working, in spotX mod. are u using original spotify?

Im using original spotify

**Comment by NocturnalPerson** [comment]
> > > mine still not working, in spotX mod. are u using original spotify?
> > 
> > 
> > Im using original spotify
> 
> Are you able to show what version of Spotify you're using? Having the same issue. I'm currently on 1.2.25.1011.

My version of spotify is 1.2.26.1187
![Screenshot (40)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/e7f65b06-bd00-4ed3-aa6a-8ffdf83a2ea4)

**Comment by AbhayXV** [comment]
same issue here, cant see an option for the lyrics page
any idea on how to fix it?

**Comment by AbhayXV** [comment]
hmm yea weird, I did the same and its still the same version

**Comment by NocturnalPerson** [comment]
I downloaded the installer for spotify, it seems to still be on 1.2.25.10.11, my current version of spotify is 1.2.26.1187...
![Screenshot (41)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/1f149afd-ee2f-4e39-972b-011888a62883)

**Comment by AbhayXV** [comment]
ah I see guess we will have to wait it out then

**Comment by ruizxzx** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/128290052/0fc3f509-87df-4600-87f8-cb5f4271334b)
still not working, (i am using spotX (a spotify mod for desktop works with spicetify too))

**Comment by belt276** [comment]
I'm on 
Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
Spicetify v2.28.0
Doesn't work for me 😞🫠

**Comment by frankiln929** [comment]
how do i update spotify manually as iam also on 1.2.25.1011.g0348b2ea and extension is not working

**Comment by surfbryce** [comment]
For anybody who is coming to this. The extension is officially fixed. There is a service called JSDelivr that Spicetify Marketplace uses to get my extension so that it can run. JSDelivr is taking unusually long to update my extension on their side, so for now, you will have to wait for JSDelivr to update the file.

The issue the extension had was that the file was over 20MB, JSDelivr has a hard limit where it doesn't allow files over 20MB. This is because I changed how I bundle the package which unknowingly caused the file size to explode.

So it's not a Spotify version issue or Spicetify version issue. Just wait a day or so and it'll be fixed.

**Comment by m4ulana** [comment]
Still ?

**Comment by NocturnalPerson** [comment]
Also doesn't work for me
![Screenshot (42)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/bde5171c-fe15-4662-a0a1-be18053627e2)
![Screenshot (44)](https://github.com/surfbryce/beautiful-lyrics/assets/153107290/1573e32b-b457-4eef-ab89-7f9fad082b0f)

**Comment by surfbryce** [comment]
> For anybody who is coming to this. The extension is officially fixed. There is a service called JSDelivr that Spicetify Marketplace uses to get my extension so that it can run. JSDelivr is taking unusually long to update my extension on their side, so for now, you will have to wait for JSDelivr to update the file.
> 
> The issue the extension had was that the file was over 20MB, JSDelivr has a hard limit where it doesn't allow files over 20MB. This is because I changed how I bundle the package which unknowingly caused the file size to explode.
> 
> So it's not a Spotify version issue or Spicetify version issue. Just wait a day or so and it'll be fixed.

Everyone please refer to this, it won't be auto updated for another day or more. Give it a while.

**Comment by AbhayXV** [comment]
thanks @surfbryce for the quick reply also for the great extension(its v good!)

**Comment by surfbryce** [comment]
@FranssMukti07 Yes, as I stated here:

> > For anybody who is coming to this. The extension is officially fixed. There is a service called JSDelivr that Spicetify Marketplace uses to get my extension so that it can run. JSDelivr is taking unusually long to update my extension on their side, so for now, you will have to wait for JSDelivr to update the file.
> > The issue the extension had was that the file was over 20MB, JSDelivr has a hard limit where it doesn't allow files over 20MB. This is because I changed how I bundle the package which unknowingly caused the file size to explode.
> > So it's not a Spotify version issue or Spicetify version issue. Just wait a day or so and it'll be fixed.
> 
> Everyone please refer to this, it won't be auto updated for another day or more. Give it a while.

**Comment by FranssMukti07** [comment]
> @FranssMukti07 Yes, as I stated here:
> 
> > > For anybody who is coming to this. The extension is officially fixed. There is a service called JSDelivr that Spicetify Marketplace uses to get my extension so that it can run. JSDelivr is taking unusually long to update my extension on their side, so for now, you will have to wait for JSDelivr to update the file.
> > > The issue the extension had was that the file was over 20MB, JSDelivr has a hard limit where it doesn't allow files over 20MB. This is because I changed how I bundle the package which unknowingly caused the file size to explode.
> > > So it's not a Spotify version issue or Spicetify version issue. Just wait a day or so and it'll be fixed.
> > 
> > 
> > Everyone please refer to this, it won't be auto updated for another day or more. Give it a while.

Ok thank u very much for the reply

**Comment by Sakshamproboy** [comment]
so do we have to do anything like uninstall or wait for the icon to appear automatically?

**Comment by surfbryce** [comment]
@Sakshamproboy When it starts working you'll know that JSDelivr fixed their stuff.

**Comment by Sakshamproboy** [comment]
ok thank you

**Comment by JxseDelRey** [comment]
Avisen D:

**Comment by LazerSkar** [comment]
my lyrics had been gone for longer than this month...

**Comment by Delusoire** [comment]
🀄🀄🀄

**Comment by xnfernx** [comment]
It still doesn't work for me. i alr update my spotify and spicetify

**Comment by frankiln929** [comment]
i also updated my spotify and spicetify but still the magic lyrics button is not showing up

**Comment by oldschoolvirgo** [comment]
Another option is to install the extension locally but you won't receive updates automatically. If you're familiar with how to install extensions via the command prompt, you can go this route.

> If you want to install it locally - all you need to do is go to the dist directory on the website and to the javascript file located in it. Copy the code there and create a new file somewhere on your computer and paste the code in it. Then follow these steps on how to actually use/install it ([instructions](https://spicetify.app/docs/advanced-usage/extensions))

**Comment by Sakshamproboy** [comment]
any idea when it will get fixed?

**Comment by Samplayz2007** [comment]
could someone ping me if it works? cuz i installed it locally using the extensions method so i would need to go back to the market place version after it starts to work
thank youu

**Comment by surfbryce** [comment]
Ok everybody, it should now work (try it out here: https://cdn.jsdelivr.net/gh/surfbryce/beautiful-lyrics@main/dist/beautiful-lyrics.js just in case you want to see)!

Just refresh/reload Spotify and it should properly load, if it doesn't give it a little bit of time for it to force refresh itself on your end. But it is now confirmed to be working again!
