### ISSUE TITLE
doesnt work on 1.2.25.2011

### ISSUE THREAD

**Issue by sou0npercs** [surfbryce/beautiful-lyrics#209]
i tried updating and reinstalling and this worked on this theme before the update

**Comment by MoonVxbesZ** [comment]
Same here

**Comment by BurnMyName** [comment]
I thought only I was having this issue. Here, too, the button is missing.

**Comment by Eingla** [comment]
I think they removed it, I saw that they did the latest update today.

**Comment by surfbryce** [comment]
I haven't removed anything and the update I made wasn't an update. I made some commits to GitHub; when an update is made you will see it in the Releases section.

I'm working on a lot of things at the moment, so I will take a look at everything breaking today and fix that.

**Comment by Eingla** [comment]
d
![Uploading Screenshot 2023-12-06 215356.png…]()
o you also see the lyrics as black like this?

**Comment by Eingla** [comment]
ok everything understood, thanks

**Comment by surfbryce** [comment]
also duplicate of #208
