### ISSUE TITLE
Mic Symbol from "Beautiful Lyrics" in right corner usually beside the "Now Playing View" button doesn't appear in theme "Hazy"

### ISSUE THREAD

**Issue by FranssMukti07** [surfbryce/beautiful-lyrics#213]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92196581/e5fb5455-6290-4a3b-8cf7-1410d9f24f0e)

I get this bug after i updated my Spicetify from V 2.27.x to 2.28.0 . I really like lyrics version from Extensions "Beautiful Lyrics" but i can't use it now because the bug make it dissapear. I've been reinstalling the extensions and the theme but still get the bug. Can anyone give me suggestion to fix it or its bug pure from the dev? Thanks. (Sorry if my english is bad)

**Comment by surfbryce** [comment]
Refer to #208
