### ISSUE TITLE
Beautiful Lyrics isn't working at all

### ISSUE THREAD

**Issue by Avijit098** [surfbryce/beautiful-lyrics#214]
"I have tried everything that was instructed to me, but nothing seems to be working. Regardless of what I do, I don't see any results. And the toggle is gone."
![Screenshot (32)](https://github.com/surfbryce/beautiful-lyrics/assets/119599186/7944159e-3081-439f-890c-0318b2f5d18f)

**Comment by surfbryce** [comment]
@Avijit098 Please look at the painfully obvious issue that I made in the Issues category which you must've had seen prior to making your issue. Here: #209
