### ISSUE TITLE
DONT SEE BUTTON 

### ISSUE THREAD

**Issue by xnfernx** [surfbryce/beautiful-lyrics#216]
i dont see button "Beautiful Lyrics",  but i already update my spotify and spicetify
![изображение_2023-12-07_184031266](https://github.com/surfbryce/beautiful-lyrics/assets/140259283/12451349-e6aa-4409-92b8-0e48a5bdd8f2)

**Comment by xnfernx** [comment]
i dont know what to do

**Comment by surfbryce** [comment]
Please refer to #208, it's very obvious that I'm trying to redirect everybody there in the Issues category where you made your issue request.
