### ISSUE TITLE
Theme Catppuccin Issues

### ISSUE THREAD

**Issue by itsarahhh** [surfbryce/beautiful-lyrics#217]
Hi, i wanna ask why the lyrics button didn't appear? i've used the theme before and had no problems. Then yesterday when i opened my spotify the lyric's button suddenly dissapeared. Thank u
<img width="960" alt="Screenshot 2023-12-08 111907" src="https://github.com/surfbryce/beautiful-lyrics/assets/153256084/68aaf31d-bca1-4e67-b945-e7d86da55a1a">
<img width="960" alt="Screenshot 2023-12-08 144156" src="https://github.com/surfbryce/beautiful-lyrics/assets/153256084/e7cf2dff-91fa-4e6c-bd05-b5d42e094c86">

**Comment by Oreniscool** [comment]
Please reference #208, it should fix itself soon enough.

**Comment by surfbryce** [comment]
What @Oreniscool said
