### ISSUE TITLE
Please, you must've seen the first issue that exists in the issues page prior to making this. Refer to #208 !

### ISSUE THREAD

**Issue by syphervhs** [surfbryce/beautiful-lyrics#218]
Please, you must've seen the first issue that exists in the issues page prior to making this. Refer to #208 !

_Originally posted by @surfbryce in https://github.com/surfbryce/beautiful-lyrics/issues/215#issuecomment-1845194519_

**Comment by surfbryce** [comment]
I appreciate the duplicate message to help guide people, but if they don't see the first issue they're definitely not going to see this, it's just better if I guide people once they make the issue and close them!
