### ISSUE TITLE
Spotify Card Layout (not right side bar)

### ISSUE THREAD

**Issue by Aeases** [surfbryce/beautiful-lyrics#22]
Just wondering what theme causes the card layout (and slight colour bleeding next to the right of the media player inh the bottom left) or if it's an experimental feature like the right side card

![image](https://github.com/surfbryce/beautiful-lyrics/assets/96164686/337ac58a-190a-43a9-bfcb-d38d5180c292)

**Comment by surfbryce** [comment]
The color-bleed is an extension called "Cover Ambience".

The collapsed panel on the right is the new Library-X which should be default for everybody now - but if it's not you can search for that in the experimental features menu and enable it. It might also not be collapsed like that by default so you'll need to resize it to that by simply dragging on the edge of that panel over to the left.
