### ISSUE TITLE
Sry for another issue opened but japanese not being translated

### ISSUE THREAD

**Issue by Blacklight2k** [surfbryce/beautiful-lyrics#222]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153313149/60803f98-704c-41f8-89fb-28f006006fd2)

**Comment by surfbryce** [comment]
@Blacklight2k Japanese, Chinese, and Korean do not get translate. They get romanized. There is a button when you hover over the page to romanize it if it can be romanized. Same with the card view, cinema view, and fullscreen view.
<img width="665" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/68057cb5-0461-4977-9adf-1b8caae0cf72">

**Comment by Blacklight2k** [comment]
@surfbryce it doesnt exist for me
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153313149/170297be-e263-4ace-9615-0952c6a05f67)
