### ISSUE TITLE
full screen beautiful lyrics 

### ISSUE THREAD

**Issue by syphervhs** [surfbryce/beautiful-lyrics#224]
![Screenshot 2023-12-11 025041](https://github.com/surfbryce/beautiful-lyrics/assets/153188247/8dce3123-9dde-4c4f-830f-5f7763d1f988)
what is this in every nexrt song hazy theme beautiful lyrics in cnemia mode

**Comment by syphervhs** [comment]
what solution?

**Comment by surfbryce** [comment]
I have to fix it on my end and push an update out it. Please do not self-close this issue.

**Comment by syphervhs** [comment]
> I have to fix it on my end and push an update out it. Please do not self-close this issue.

what happend why is showing

**Comment by syphervhs** [comment]
> I have to fix it on my end and push an update out it. Please do not self-close this issue.

solution ???

**Comment by syphervhs** [comment]
> I have to fix it on my end and push an update out it. Please do not self-close this issue.

you fix it what happend ? any solution

**Comment by syphervhs** [comment]
> Owner

fixed problem having with cover ambience extenction
