### ISSUE TITLE
Beautiful Lyrics isn't working at Spicetify v2.28.1

### ISSUE THREAD

**Issue by cryptomehedi** [surfbryce/beautiful-lyrics#226]
"I have tried everything that was instructed to me, but nothing seems to be working. Regardless of what I do, I don't see any results. And the toggle is gone"

### _Thank you in advance_

![image](https://github.com/surfbryce/beautiful-lyrics/assets/96647104/32cc122f-b4da-4610-9b1a-9de82a38a0ef)

**Comment by surfbryce** [comment]
@cryptomehedi Can you go into the developer console and show me the errors? I'm not getting this issue at the moment.

Run "spicetify apply enable-devtools", then click on the three dots in the left and navigate to "Developer" and then "Developer Tools". Then click on the "Console" tag and screenshot everything there for me and send it here, thanks!
