### ISSUE TITLE
No border and "show lyrics" button aligned to left

### ISSUE THREAD

**Issue by kutawhat** [surfbryce/beautiful-lyrics#227]
There's no more border at closed lyrics section and button is aligned to left now

![Снимок экрана 2023-12-12 в 01 14](https://github.com/surfbryce/beautiful-lyrics/assets/64655969/0412ad85-4998-475e-9099-c892bc3bf8a7)
![Снимок экрана 2023-12-12 в 01 14 2](https://github.com/surfbryce/beautiful-lyrics/assets/64655969/b6e5cdf4-52ae-4bc7-92b4-380eb70b3d15)

**Comment by kutawhat** [comment]
I'm actually not using any theme at all

I'm on Spicetify v2.28.1

**Comment by surfbryce** [comment]
Hmmn, weird. I am also on Spicetify v2.28.1.

Can you tell me if we're on the same Spotify version or not?
<img width="298" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/604ff612-f926-4e75-adaa-fe337e585e27">

This is what it looks like for me right now:
<img width="416" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/e28aba5b-9b20-4e14-9bad-c048c95772e1">

**Comment by kutawhat** [comment]
Yeah, I got the same Spotify version as well.

**Comment by kutawhat** [comment]
> Can you tell me if we're on the same Spotify version or not?

Yeah, I got the same Spotify version as well

> At least, by border I assume you mean the background for the lyrics card?

That's what I meant, yes

Is it possible that there may be some conflicts with other extensions or with Experimental features?
