### ISSUE TITLE
Weird things about Experimental features 

### ISSUE THREAD

**Issue by joeyscave** [surfbryce/beautiful-lyrics#23]
1. I don't have these two entries in my Experimental features
<img width="421" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/72662648/603ae47b-1ab2-46b3-80ab-f04c18bdfbeb">
<img width="667" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/72662648/60153009-eca5-4e4a-9a96-1fe49ace1a2b">

2. (maybe not related to this project) I enabled the Library X view of the left sidebar, but the effect is not the same as the one on the github page
<img width="1512" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/72662648/61d2d7f9-5f1d-4dfb-b623-ebebb80d358a">

**Comment by surfbryce** [comment]
The instructions explicitly state to search up “side” not “sidebar”; see if that changes anything in the search results.

Also you have to resize the left panel by dragging it to the left.

**Comment by joeyscave** [comment]
> The instructions explicitly state to search up “side” not “sidebar”; see if that changes anything in the search results.
> 
> Also you have to resize the left panel by dragging it to the left.

1. search "side"
![image](https://github.com/surfbryce/beautiful-lyrics/assets/72662648/0033e817-4fc3-4b81-ad85-700b61ca9795)

2. resize the left panel to the left most
![image](https://github.com/surfbryce/beautiful-lyrics/assets/72662648/acf036fd-fe42-46fa-a139-19bffe401243)

😭😭😭

**Comment by surfbryce** [comment]
@joeyscave I would make sure your spotify is updated to the latest version and that you have Spicetify updated to the latest version as well.

It seems to be the issue. Also enable "Enable panel size Coordination" as well - it should fix the issue you have in the second image

**Comment by joeyscave** [comment]
@surfbryce You're right, thank you.
