### ISSUE TITLE
Stops working when spicetify is unable to access the marketplace.

### ISSUE THREAD

**Issue by Afterlifepro** [surfbryce/beautiful-lyrics#230]
Occasionally my WiFi loses internet access, and when it does so my spotify UI reverts to default (themes, extentions, snippets, etc) but most fix themselves after reconnecting (and occasionally opening the marketplace)
Beautiful lyrics, however, does not re-enable, although it still shows as installed. I have tested uninstalling and reinstalling the extention although this does not fix the issue. I have been able to restore it, however I cannot remember what the sollution was. If I find a work around I will update this issue, however it would be greatly appreciated if this was fixed. Thanks.

Edit: solution is to close and re-open spotify.

**Comment by surfbryce** [comment]
Not an issue with the extension; Spicetify/Marketplace specifically
