### ISSUE TITLE
Add to playlist button is misplaced/covering name of artist

### ISSUE THREAD

**Issue by MaryWanna5** [surfbryce/beautiful-lyrics#231]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115578692/cd385ef7-d2ba-45a8-a00a-d009d9a35b7b)

**Comment by Jeroitsme** [comment]
okay but how do i fix it

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
