### ISSUE TITLE
beautiful lyrics extenction problem 

### ISSUE THREAD

**Issue by syphervhs** [surfbryce/beautiful-lyrics#232]
![Screenshot 2023-12-13 233645](https://github.com/surfbryce/beautiful-lyrics/assets/153188247/c4c51625-7ad2-4f63-8d78-e39fa73f211e)
 all slideing down whem click full screen hazy theme beautiful lyrics

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
