### ISSUE TITLE
While using Default Dynamic theme - Album name and year are not aligned properly in fullscreen

### ISSUE THREAD

**Issue by Sufilevy** [surfbryce/beautiful-lyrics#236]
This is while using the [Default Dynamic](https://github.com/JulienMaille/spicetify-dynamic-theme) theme.

When in fullscreen mode, the name and the year of the album are not aligned properly (they are aligned left instead of centered below the name of the artist).

For example:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/61206445/23b52e64-c87b-452a-823a-d9fe0ef960ed)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/61206445/e4b3e9bf-7e0c-473c-affe-61e8838a1f51)

**Comment by Sufilevy** [comment]
Apperenatly this was a problem with Default Dynamic (another theme from the Marketplace) that didn't work 100% with this extension.

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
