### ISSUE TITLE
Syncing songs word-for-word

### ISSUE THREAD

**Issue by LoganWolfie** [surfbryce/beautiful-lyrics#238]
Id just like to know if theres a way anybody could make a tutorial on how to sync songs word-for-word because as some song are synced word-for-word 90% of them are synced _bar-for-bar._

Im sure this is just because somebody hasnt decided to make it word-for-word yet??
or unless spotify does it themselves then you guys update it off that.

**Comment by Euro-pol** [comment]
Yeah I'd like to know too

**Comment by surfbryce** [comment]
@LoganWolfie Syllable synced lyrics (and same with Line Synced and Static Synced) are all done by the Artists/Record Companies, none of the work is done by me or anyone in particular.

The Artists/Record Companies will send lyrics to Music Providers/Lyric Gatherers like Apple Music and Musixmatch and then Spotify and other Streaming Platforms will get the lyrics from them to display to you. That is why some are Syllable synced, some are Line synced, and some are just text.

It's completely up to the Artists/Record Companies on what level of detail they go for.
