### ISSUE TITLE
Some songs don't show lyrics that work without the extension with no message

### ISSUE THREAD

**Issue by BikoInnit** [surfbryce/beautiful-lyrics#240]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90649639/902bf919-236b-409e-ae4a-f3e878042fc3)

This happens to a few songs and it has nothing to do with explicit lyrics and they work without the extension, while other songs work perfectly with the extension.

**Comment by surfbryce** [comment]
Duplicate behavior of #239

**Comment by surfbryce** [comment]
This should be fixed in the latest update by the way, lyrics should be back in working order, thanks for reporting!
