### ISSUE TITLE
The lyrics seem to be in a completely AWFUL font.

### ISSUE THREAD

**Issue by Tencta** [surfbryce/beautiful-lyrics#246]

**Comment by Tencta** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/85408331/8000be96-2f76-4c37-b75e-196c661dd804)

**Comment by surfbryce** [comment]
Duplicate of #245

**Comment by surfbryce** [comment]
@Tencta This tends to be an issue with internet connection/loading, is this still happening for you?

**Comment by surfbryce** [comment]
New update has different mechanism for CSS, might fix issue, re-create the issue if it happens again

**Comment by adhamdawild** [comment]
did you ever figure it out?
