### ISSUE TITLE
Set up a donation page

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [surfbryce/beautiful-lyrics#248]
Maybe something like kofi?
would be nice if i could chip in a couple of bux for this awsome project

**Comment by surfbryce** [comment]
I really do appreciate the sentiment, but I make more than plenty to keep myself sustained for quite a while and to fund this entire project, I don't need anymore from anybody, so thank you, the suggestion/thought is definitely worth the equivalent of a couple of bucks!
