### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by tekaruku28** [surfbryce/beautiful-lyrics#25]
After I restart the spot the background was already disappear and just all black background please back the background video the blur background that moving behind those lyricss pleaseee
![image](https://github.com/surfbryce/beautiful-lyrics/assets/108468529/204b0fcd-b4d9-437e-ba1f-0a3cfa8d3ed6)

**Comment by surfbryce** [comment]
Just fixed this in surfbryce/beautiful-lyrics@8f9334e

Forgot that the Query for the Modern Fullscreen lyrics container is not the same for the Legacy Fullscreen lyrics container.

Since you're on the new version it should automatically update - thanks for the report!

**Comment by tekaruku28** [comment]
itss okay bro it's already thanks a lot to your work i did recommend it to
my other friends they amaze of your work.. Keep it up bro!!
