### ISSUE TITLE
Instead of having the text fade in have it jump in, similar to apple music.

### ISSUE THREAD

**Issue by jamiejama** [surfbryce/beautiful-lyrics#252]
when beautiful lyrics doesn't apply any effects to the text, it instead just makes it fade in and glow.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/137530760/d3eb7a76-d02a-42be-a7be-faf600a7504f)

maybe, if possible, it could jump in similar to apple music with no effects on top to give it a cleaner look.
like this 
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmtlaGRrazJkdHFkeWtjeXR4d21jb2E0Z3F4bnJib3d0ZGk0aTBzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Jk5ZbWH20aNvr0MNTq/giphy.gif
not sure if this is possible but I thought I might as well make a suggestion.

**Comment by surfbryce** [comment]
The fade won't be going away, that's a visual only indicator for getting a feel for the pace of each line-synced lyric (which is an accessibility thing as well). The vertical fade will always feels much more responsive and real than a simple on/off shade.

However, what you're asking for is what was requested in #64, so I'll mark this as a duplicate
