### ISSUE TITLE
Change Style

### ISSUE THREAD

**Issue by tuputamadre12316** [surfbryce/beautiful-lyrics#254]
Hi, i have a question, how i can change the style of the lyrics same like the gifs? i mean when he sings, highlight that word he says, my effect is like a waterfall and when the verse ends the whole word lights up and that's how I don't like it.
![image_2024-01-21_192040147](https://github.com/surfbryce/beautiful-lyrics/assets/139811326/17afa77f-078b-4842-980c-7043367ddc91)

**Comment by tuputamadre12316** [comment]
If you're only going to put a fucking dislike, it's better not to put anything unsuccessful, I hope something happens to you

**Comment by KarterIsEpic** [comment]
if you play a very popular song it will most likely have the fancy-er lyrics. im not sure if its a bug or if its because someone has to manually make the fancy-er versions, but most songs that are less popular dont have fancy lyrics.

**Comment by surfbryce** [comment]
@tuputamadre12316 Lyrics are submitted by the Artists/Record Companies to other Companies that run Lyrical Databases (like Apple Music and Musixmatch). So it's up to them if they want Syllable synced lyrics, Line Synced lyrics, or just Static text (or none at all). The extension just retrieves these lyrics and displays them. There are no "styles". Just the type of syncing method.
