### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by Siddhj2206** [surfbryce/beautiful-lyrics#255]
My GPU usage goes from 1-2% without the lyrics page open to 70-75% when the lyrics page is open.

Without lyrics page open:
![Screenshot 2024-01-22 111629](https://github.com/surfbryce/beautiful-lyrics/assets/72146190/620208b8-1607-4543-b3a8-4a7fb293cbbb)

With lyrics page open:
![Screenshot 2024-01-22 111749](https://github.com/surfbryce/beautiful-lyrics/assets/72146190/1eff57c7-be4b-459e-ab37-608b0df48819)

OS: 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎3.‎11.‎23
OS build	22621.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

Device Specs:
Processor	AMD Ryzen 5 7530U with Radeon Graphics            2.00 GHz
Installed RAM	16.0 GB (15.4 GB usable)

**Comment by dxcvvxd** [comment]
for me on linux it only jumps up from 100mb to 120-140 so it may as well be a windows drivers issue with how it handles graphics

**Comment by surfbryce** [comment]
Will redirect this to #185
