### ISSUE TITLE
Galaxy theme issues

### ISSUE THREAD

**Issue by DawarTheDastardly** [surfbryce/beautiful-lyrics#270]
The playbar controls aren't aligned properly on the galaxy theme in fullscreen mode, and there is a small gap on the right of the screen in both cinema mode and fullscreen mode

### Fullscreen

- No Theme

![Spotify_jpWmmFJEEE](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/75c534c7-16d5-4e7d-b887-99bf9fc0d7f5)

- Galaxy Theme

![Spotify_SMLHakfA5n](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/f1f239fb-e764-4c43-b91d-c1ce636608e8)

### Cinema

- No Theme

![Spotify_zjnRmTWqxo](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/3dc3d7a2-6e36-4244-bf9c-502ac491a712)

- Galaxy Theme

![Spotify_FdXnf019JG](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/a454b623-fa93-47ee-8df8-07fa4de9d5b8)

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
