### ISSUE TITLE
Font Size on Sidebar

### ISSUE THREAD

**Issue by dankehh** [surfbryce/beautiful-lyrics#278]
title, i'd like to make the font lyrics a bit smaller, how can i do it?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/95983733/131d3129-9b60-4ec5-b19e-6e4cac805fad)

**Comment by surfbryce** [comment]
You'll have to do it through CSS by changing the font-size for the .Lyric class. There will be no options to edit the size built-in anytime soon.

**Comment by CherubicBoot** [comment]
I'd like to do the same thing, may I know where the class file is located? ^^
