### ISSUE TITLE
[Suggestion] Option to have Fullscreen View without Fullscreen Window

### ISSUE THREAD

**Issue by ShirowLeBG** [surfbryce/beautiful-lyrics#279]
Hi,

It would be great if we could have an option to enable/disable full screen mode for the page view, i.e. we'd have the page view interface while being able to move and resize the window, just like when the app isn't in full screen mode.

If you know of a way to do what I've just said without necessarily needing to update the extension, I'd be interested.

Thanks!

**Comment by surfbryce** [comment]
@ShirowLeBG Can you elaborate on this? What do you mean enable/disable fullscreen module for the page-view? The page view takes up the main page area, you can do that by clicking the lyrics icon at the bottom or the button in the lyrics-card on the sidebar.

Images would help to make your point as well.

**Comment by ShirowLeBG** [comment]
@surfbryce Yeah sorry it was maybe not very clear, the goal is to have the interface like when you click on the "fullscreen" button, but not taking the entire screen space
I did a little image to make it clearer :

![Sans titre](https://github.com/surfbryce/beautiful-lyrics/assets/61913454/30253881-3bb2-4f0e-92ae-4907a8f37118)

**Comment by surfbryce** [comment]
@ShirowLeBG I'll make it so if you shift click the fullscreen button it'll do that, won't be hard since all I have to to do is make it so the window doesn't go fullscreen (which is just disabling that really).

**Comment by surfbryce** [comment]
@ShirowLeBG I actually completely got rid of the Cinema view layout and now just use one Fullscreen layout for both Cinema and True Fullscreen. So hope you enjoy it!
