### ISSUE TITLE
Artist Banner on Lyrics Screen (Bug)

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#28]
Hi, I found a bug (or feature) when you sit on the page of the artist and open the lyrics on the full screen, you see that the artist's banner went to the subtitles, I don't know if I explained well but in the screenshot all can be seen:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/df4a417a-2a45-40bd-aa5c-4a2647cf6481)
![2023 05 30 uE3](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/2c3a7aac-a34a-4808-a6a1-53a3ab1183ed)

**Comment by surfbryce** [comment]
Well now I definitely know what the "under-main-view" container is used for.... thanks for the report will get this fixed right now! You should see the extension update itself in a couple minutes.

Also thank you for responding to other posted issues - it helps alleviate some of the task for me - it's very much appreciated!
