### ISSUE TITLE
Lyrics Not Showing

### ISSUE THREAD

**Issue by hysterCAL** [surfbryce/beautiful-lyrics#280]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/160075720/1bca87cc-d167-4380-a3bb-203a9e0ca11f)
Hello, this just randomly happened, it was working before but randomly just stopped and now it doesnt show the lyrics.

**Comment by asdfcx2345** [comment]
yeah same thing happened to me

**Comment by Stew4theWin** [comment]
same with me

**Comment by LisuxOG** [comment]
It's happening to me in almost all the songs

**Comment by wmgaertner** [comment]
Did you update the spotify client? According to [spicetify](https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.3), with v1.2.31 of the client, Spotify has changed a function that seems to impact lyric extensions.

**Comment by surfbryce** [comment]
Duplicate of #240
