### ISSUE TITLE
My extension isn't working the same as described

### ISSUE THREAD

**Issue by EILLOxX** [surfbryce/beautiful-lyrics#29]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/128436412/e0e90552-bc85-49ed-911d-76c32a0ac162)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/128436412/c5fe6fd8-f001-4c24-b710-006e5e43e6fe)
I don't have the artist description, transparent lyrics, and hidden lyrics button
how do I get them ?

**Comment by Blankk02** [comment]
You can enable it in "Experimental features" menu by searching "sidebar"
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/e2bbc331-aa9f-40fe-8aea-910f2bc84c95)

**Comment by Blankk02** [comment]
As I understand it, the description of the artist is enabled by default because I can't find it in these settings, but it's better to wait for the author of the extension to say exactly what to do

**Comment by EILLOxX** [comment]
Okay I'll do that because for some reason my experimental features don't match yours 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/128436412/a2e4e28e-62c8-4f92-93b2-b53e89f33424)

**Comment by Blankk02** [comment]
> Okay I'll do that because for some reason my experimental features don't match yours ![image](https://user-images.githubusercontent.com/128436412/242090337-a2e4e28e-62c8-4f92-93b2-b53e89f33424.png)

Strange, I don't know what this could be about.

**Comment by surfbryce** [comment]
@EILLOxX Make sure your Spotify AND Spicetify are both updated to their latest versions. Someone else had reported this exact issue where their experimental features did not match the latest available ones and all they had to do was update.

**Comment by EILLOxX** [comment]
> @EILLOxX Make sure your Spotify AND Spicetify are both updated to their latest versions. Someone else had reported this exact issue where their experimental features did not match the latest available ones and all they had to do was update.

Okay will do, I'll go check.

**Comment by EILLOxX** [comment]
yeah, my spicetify is updated already to the current one and my Spotify is showing no updates.

**Comment by surfbryce** [comment]
> yeah, my spicetify is updated already to the current one and my Spotify is showing no updates.

Can you share your Spotify and Spicetify versions so I can make sure you're on the latest? On MacOS you click Spotify in the top-bar and click "About Spotify". On Windows you right-click the top and click "About Spotify"
