### ISSUE TITLE
Korea Romanized Lyrics Broken

### ISSUE THREAD

**Issue by Vyxzernova** [surfbryce/beautiful-lyrics#290]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/139006793/1e83ebd9-55fe-42cb-abba-bce30d20438c)
Here the picture approve that romanzied broken.... idk other songs broke or not.

**Comment by surfbryce** [comment]
Duplicate of #288, if you could repost your image there @Vyxzernova that'd be great, I'll be giving instructions to both you and that other person on what I'll need from you guys to help fix this.
