### ISSUE TITLE
beautiful lyrics button gone

### ISSUE THREAD

**Issue by 9-ab** [surfbryce/beautiful-lyrics#292]
start spotify, play song, click on lyrics button, get blank screen (says that extension is upgraded too,) button disappears. 😁 will attach images

happens with every song, ive tried like 8 different songs

![screenshot1](https://github.com/surfbryce/beautiful-lyrics/assets/160395646/fdcf6318-9b5a-4c7b-82c0-dedf2de6f8c3)
![screenshot2](https://github.com/surfbryce/beautiful-lyrics/assets/160395646/b0f474cf-e4b7-47ce-9d1e-16e89e8eb6b4)

**Comment by surfbryce** [comment]
@9-ab Send your Spotify/Spicetify version. It's located in the "About Spotify" card. You might also want to try restarting Spotify/Fresh-Install. Will have to see after the version check.

**Comment by 9-ab** [comment]
> @9-ab Send your Spotify/Spicetify version. It's located in the "About Spotify" card. You might also want to try restarting Spotify/Fresh-Install. Will have to see after the version check.

spicetify ver. v2.23.0
will re install spotify now since ive just realised i'm 4 months behind ty <3

**Comment by surfbryce** [comment]
@9-ab No problem, let me know if it fixes the problem for ya

**Comment by 9-ab** [comment]
sorry for bothering u bro, ty for pointing out my stupidity though lol

**Comment by surfbryce** [comment]
@9-ab All good man, just checking, works now yeah?

**Comment by 9-ab** [comment]
yea works just fine ty
