### ISSUE TITLE
Can I upload lyrics for songs that dont have lyrics yet?

### ISSUE THREAD

**Issue by sussyskibidisigma** [surfbryce/beautiful-lyrics#295]
Hello,

Umm.... is there any way i can upload my own lyrics for songs that dont have lyrics yet?

**Comment by surfbryce** [comment]
No, not at the moment, there is an editor planned for the future but no work has begun on it.

**Comment by surfbryce** [comment]
@sussyskibidisigma but can you include the song that doesn't have lyrics? I would like to check my providers and see if they do have lyrics for that song. If you check #291 I talk about some cases where no lyrics are shown but they do exist, it's just a problem with how Spotify/Apple Music/Musixmatch handle which songs have what lyrics (and which versions more importantly)

**Comment by sussyskibidisigma** [comment]
Well that was fast...

But no, the issue isnt on you its juts new song and is phonk/funk so if it isnt possible then its alright. I just love the UI and love to listen songs while im at the gym, it really is awesome. 

Btw the song: BRODYAGA FUNK - (Ultra Slowed  + Reverb) by Sigma Forever

**Comment by sussyskibidisigma** [comment]
Uhm it is closed i guess....

**Comment by surfbryce** [comment]
@sussyskibidisigma yeah you're right, there are no lyrics for this anywhere it seems like, so just look out in the future for the lyrics editor update, that'll make it so you can submit lyrics for a song and moderators can eventually approve it so it shows up like that for everybody (and your submitted lyrics will be what you see immediately, unless your version gets denied, then your version locally will revert back to whatever the server has)

**Comment by sussyskibidisigma** [comment]
@surfbryce ok thx for answering all my questions. really helped me. id search for lyrics for hours good to know it now
