### ISSUE TITLE
Fullscreen Song Information Incredibly Small

### ISSUE THREAD

**Issue by Janostar213** [surfbryce/beautiful-lyrics#296]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/59266111/4469fd0f-f536-4e52-a57d-56eadcb2d370)

Song information like name and artist are very small, overlap with each other and the like button as well.

**Comment by surfbryce** [comment]
There are already issues relating to the like/add-to-playlist button being messed up so I'll rename this to just the other core issue which doesn't have a dedicated issue yet.

Btw, are you using a theme at all, or just default?

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
