### ISSUE TITLE
Sync lyrics taking bluetooth delay into account

### ISSUE THREAD

**Issue by benwillrob** [surfbryce/beautiful-lyrics#298]
Hi, 
First of all, love the project and practically everything works as it should.
I have one suggestion/issue. If you have a wireless speaker setup, there can be significant delay between the computer and speakers and Im wondering if you could add a way to offset the lyrics to be a bit ahead so its in time with the speakers.
Many thanks
Ben

**Comment by surfbryce** [comment]
Thanks for the kind words @benwillrob, this is a duplicate of #223, this is something I'm wall aware of and have experienced myself. It is planned don't worry!
