### ISSUE TITLE
Transparent Background Lyrics

### ISSUE THREAD

**Issue by FranssMukti07** [surfbryce/beautiful-lyrics#299]
Just want to know if i can make my background lyrics transparent, not a bug or error or anything negative. Thank u for anyone answering.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92196581/416202f5-7761-41b2-8ba6-0c401f385f57)

**Comment by alan7383** [comment]
I have the same problem

**Comment by surfbryce** [comment]
@FranssMukti07 What theme are you using?

**Comment by FranssMukti07** [comment]
> @FranssMukti07 What theme are you using?

im using Hazy Theme

**Comment by surfbryce** [comment]
Invalid in new update due to new page interface
