### ISSUE TITLE
Word-by-word support for songs written in hindi and punjabi scripts

### ISSUE THREAD

**Issue by NAXRAY** [surfbryce/beautiful-lyrics#305]
Hi, this is just a suggestion to please add word-by-word lyric support for lyrics written in Hindi and Punjabi scripts? Some of the songs have word-by-word lyrics on Musixmatch but they don't come up as word-by-word inside of beautiful lyrics

**Comment by surfbryce** [comment]
@NAXRAY Syllable Lyric support is done through the Artists/Music-Labels, I'd be happy to look into the songs and see why they aren't showing lyrics, but you have to give me the song names first.

There is no direct support for any language, whatever lyrics my service can get is what it'll display.

**Comment by NAXRAY** [comment]
Hi sorry for the last response,

for example the song "Thumkeshwari" has word-by-word lyrics on Musixmatch app but on beautiful lyrics they only show up as line-by-line. This happens for all songs shown in the Hindi alphabet, if the song is romanzied then the romanized lyrics do have word by word lyrics.

**Comment by NAXRAY** [comment]
Any updates?

**Comment by surfbryce** [comment]
@NAXRAY This is an issue with Apple Music and not Beautiful Lyrics specifically, so unfortunately I cannot do anything about it, sorry!

**Comment by NAXRAY** [comment]
Ohh okay, if it doesn’t work thats fine.

But doesn’t the extension use Musixmatch as a lyrics provider alongside Apple Music as well? Musixmatch does have syllable support for these scripts so I was wondering if the extension could take the word-by-word from this app (for example Instagram does correctly show word-by-word lyrics in hindi scripts for songs that have it on musixmatch) I do know that Apple Music doesn’t support it but Musixmatch does and is used as a lyric provider for the extension so I was wondering if it were possible to add the syllable support from Musixmatch as well

**Comment by surfbryce** [comment]
@NAXRAY It does not use Musixmatch and it probably won’t for a long while; also Apple Music DOES support it, there is no language specific support for syllable synced lyrics. It’s just that Apple Music doesn’t have the syllable synced versions
