### ISSUE TITLE
lyric timestamps in lyrics

### ISSUE THREAD

**Issue by Sgesa** [surfbryce/beautiful-lyrics#307]
![image_2024-03-01_192058701](https://github.com/surfbryce/beautiful-lyrics/assets/116733627/430b519c-57dd-4c51-b815-6edcf1fa3003)
uh

**Comment by surfbryce** [comment]
@Sgesa What song is this? The lyrics are provided by an external source so it's possible that is how the Artist/Music Label provided the lyrics.

**Comment by Sgesa** [comment]
> @Sgesa What song is this? The lyrics are provided by an external source so it's possible that is how the Artist/Music Label provided the lyrics.
@surfbryce 

https://open.spotify.com/track/0dK0wVKuQvdnLzhlsGK0VH?si=f022404e512d4d97

**Comment by surfbryce** [comment]
@Sgesa Yeah so this is actually a part of the lyrics, not an issue on my end, thanks for the sending though!
