### ISSUE TITLE
Option To Switch Lyrics Source

### ISSUE THREAD

**Issue by GODDASUR** [surfbryce/beautiful-lyrics#308]
Can add option to switch between sources of lyrics bcs some of the songs don't have synced lyrics word by word.

**Comment by surfbryce** [comment]
@GODDASUR It automatically chooses the best source available to the algorithm I use, so there will be no "switching" of sources because it already tries to find the best option. If there are songs that don't have syllable lyrics but should, make a new issue listing those songs.
