### ISSUE TITLE
Lyrics not visible anywhere outside of fullscreen mode

### ISSUE THREAD

**Issue by LuukOriginal** [surfbryce/beautiful-lyrics#31]
After the most recent update (v2.4.3) my lyrics suddenly disappeared on both the lyrics+ window and the built-in lyrics window, in Fullscreen it does work tho. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/51383330/1dbfb6e3-376a-401c-9b98-b6e971e9fb1c)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/51383330/2b1bbbac-936f-4391-8172-2eaf959d3744)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/51383330/6281241c-e1f6-44ed-87a6-9f22a4236659)

 Also every time I startup my Spotify I keep getting the update notification every single time I startup my Spotify (I assume it should only be once)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/51383330/25eff9b0-e9fc-43d1-af8b-cc7cb2b0e3cf)

Is it just me having this issue or is this noticeable for other users too? Already tried reinstalling, reapplying spicetify and even reinstalling lyrics-plus

**Comment by surfbryce** [comment]
You are correct! I made this update to fix #28 but it seems like it broke the other stuff!! So I'll work on this and push out another update!
