### ISSUE TITLE
Song "Slow Jamz" by Twista is missing lyrics.

### ISSUE THREAD

**Issue by BariIsStupid** [surfbryce/beautiful-lyrics#310]
The song "Slow Jamz" by Twista has an intro section that is not included. Spotify does have those lyrics though. This makes the lyrics extremely displaced.
Proof:
[https://youtu.be/vekQpDZsC5Y]

**Comment by surfbryce** [comment]
@BariIsStupid This is fixed in the next update coming soon, thanks for reporting
