### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by Jeroitsme** [surfbryce/beautiful-lyrics#312]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92041067/d5168ff3-f8b5-48fe-8a29-4efc733f86c9)

there's this weird line on the right side, idk what's up with it.

**Comment by surfbryce** [comment]
@Jeroitsme What theme are you using?

**Comment by samuelkimin** [comment]
the control is messed up in full screen, and please give some gap between lyrics-line, it's too close and too many lyrics... (copy apple music design)

**Comment by SudhanFromGithub** [comment]
> ![image](https://private-user-images.githubusercontent.com/92041067/310608901-d5168ff3-f8b5-48fe-8a29-4efc733f86c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTU2MzQsIm5iZiI6MTcxMjQ5NTMzNCwicGF0aCI6Ii85MjA0MTA2Ny8zMTA2MDg5MDEtZDUxNjhmZjMtZjhiNS00OGZlLThhMjktNGVmYzczM2Y4NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEzMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGRmYmFlN2RhMTFiMTRkOTVmYzdmMDMxZTQ4OTE5MmU1YmQ0Mjc5MWQ1NjA5OWQ2MzRlNzRlNjIwYWQ1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdGWL2GF6YDEymfAP9amwqYDrkuuv_h4nYSMLo2svFk)
> 
> there's this weird line on the right side, idk what's up with it.

Please Tell what theme are you using

**Comment by Joemama069420** [comment]
![Screenshot 2024-05-12 181239](https://github.com/surfbryce/beautiful-lyrics/assets/152177661/69adcbfd-5526-40d3-9d09-33a4a95ac756)
lyrics wont show up in full screen but otherwise

**Comment by surfbryce** [comment]
Invalid until next update
