### ISSUE TITLE
Cache Blurred Cover Art

### ISSUE THREAD

**Issue by surfbryce** [surfbryce/beautiful-lyrics#32]
Basically right now a lot of performance is subtracted because we have to apply a 40px blur to three (used to be two) images of the cover-art at runtime.

Luckily there is an optimization in chrome (like anything that uses textures) that reuses the image-buffer for the first cover-art that we render - however - we still need to apply blur to all three; there is no optimization built-in that Chromium has for that (since it's impossible to determine when to apply such an optimization).

Originally the idea was to do this on the Backend since we already built it up. The issue is that Cloudflare runs in a V8 runtime instead of a Node Runtime and therefore does not have access to anything that we could use for this.

So the idea has now shifted to doing this all on the Client. What we'll do is;
- Create an OffscreenCanvas based off the loaded Cover-Arts size; which is scaled to create room for the blurs added pixels
- Then clip the Canvas using a circle that is the same width/height as our Image (to replicate the border-radius effect in CSS)
- Then load our image onto the center of the Canvas (which will now be clipped by the circle)
- And finally, apply our blur filter to it

Once all those steps are done we can then extract the data from the canvas and cache it as a png.

This will gain a TON of performance since we no longer need to do these effects on the runtime. We also save on having to deal with a backend and the additional requests/storage needs.

**Comment by surfbryce** [comment]
This is postponed until I find a proper way to get this to look like it does currently.

The main issue which I forgot to account for is that the blur effect is applied to the enlarged image - which means we get more detail out of it. We can't do that with caching so it's just not worth it at the moment.

**Comment by surfbryce** [comment]
I've reopened this since I want to take another crack at this and see if I can get them to match. I've realized it's going to better to recalculate the blur when the size changes - most likely the effect will be redone once the size of the container stabilizes. This should allow me to properly replicate the effect without an issue.

This should allow the blurred image to be exactly like the image that CSS computes every frame (since now the sizes will be properly representative). The only thing from there will then be the issue of figuring out how to get the position the same.

**Comment by surfbryce** [comment]
Closing this again - I've solved the size/position issue. Literally the only thing stopping this is that filters applied in canvas are not the same as filters applied in CSS. I have no idea why it's like this given that in any other web browser they render the same. This might be hierarchal or something - but it's unfortunately not viable at this moment.

It's really sad as well since everything else is exactly the same and the image without the filters - is also - exactly the same. It's just how the filters get applied that ruins the coloring when using the canvas. This isn't just an OffscreenCanvas issue either since this happens with the canvas element as well.

**Comment by Kouki002** [comment]
Ok May Bad But Ya You Got A point Its Not Affect All Of Them But Its Affect Some Of Them I Don't Mind If You Solve It After This Patch I Will Be Good I Just Want To Be Your Extension More Refined Cause Its So Good And I Don't Want To Loos This One Because Of Its Minor Bugs And Problems That Why Told You !!!! And Ya Lyrics Not Showing On Some Song Its More Important Than Smoothness Cause Without Lyrics What's The Point Of Smoothness ! LOL !
