### ISSUE TITLE
wrong lyrics

### ISSUE THREAD

**Issue by Thealbul678765** [surfbryce/beautiful-lyrics#320]
i have a song that has the complete wrong lyrics bongo bong-je ne t'aime plus (francis mercer remake)

**Comment by surfbryce** [comment]
@Thealbul678765 please provide what the proper lyrics should be in contrast to what they are currentlty using screenshots

**Comment by Thealbul678765** [comment]
[image: image.png]
I′m the king of bongo bong

I'm the king of bongo bong








*Je ne t'aime plus, mon amourJe ne t′aime plus tous les joursJe ne t′aime
plus, mon amourJe ne t'aime plus tous les joursJe ne t′aime plus, mon
amourJe ne t'aime plus tous les joursJe ne t′aime plus, mon amourJe ne
t'aime plus tous les jours*


Mama was queen of the mambo

**Comment by surfbryce** [comment]
@Thealbul678765 Unfortunately, this is an Apple Music issue which cannot be resolved via Beautiful Lyrics, sorry!

**Comment by Thealbul678765** [comment]
? this is spotify with beautiful lyrics itis not a snapshot of apple music
