### ISSUE TITLE
Missing lyrics on "That’s What I Like" and "I don’t like it, I love it" by Flo Rida

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#325]
![Screenshot 2024-03-19 165645](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/72ea1ef4-25b3-4001-b5fe-5fc62dccf06b)
![Screenshot 2024-03-19 165706](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/0b5370f9-79e5-407a-9c32-7fd5bb3e5643)
I know That's what i like isn't that popular but how could you miss the lyrics to a song that Pikachu danced to?!?

**Comment by Zyanbob** [comment]
i'm from australia so maybe it just Australian being screwed over here but i would like to see the lyrics to songs regardless of region

**Comment by surfbryce** [comment]
@Zyanbob What I'm assuming is happening here is that my service can't find the lyrics through the provider I'm using (not that the provider doesn't have the lyrics, but that it's not finding a version that matches for some reason) and so it's defaulting to whatever lyrics Spotify may have. Lyrics on Spotify are region bound dependent on the copyright/trademarks and etc. So it's possible Australia just doesn't have access to those lyrics for whatever reason.

Very very soon, this month, I'll be pushing out an update for my lyrics service that should drastically increase the accuracy of lyrics matching and so hopefully these songs are one of those that are improved by it.

I'll use these songs as a test to validate the accuracy and if it works well.

**Comment by surfbryce** [comment]
@Zyanbob Both of these songs will have lyrics in the next update, thanks for putting in the request
