### ISSUE TITLE
beautiful lyrics causes crazy puff podcast to sink to the underworld

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#326]
How it should work: 
![Screenshot 2024-03-21 155829](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/9078f3f9-cf34-439d-825a-7890d488c603)
How it works with beautiful lyrics:
![Screenshot 2024-03-21 155745](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/58d85760-7bb6-4cbf-acf2-cb295d9f9071)

**Comment by surfbryce** [comment]
@Zyanbob does this happen with every podcast? I would assume so, just making sure it's not a one-off here

**Comment by Zyanbob** [comment]
![Screenshot 2024-03-21 160525](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/0b38a4e1-c73c-46dd-a15d-73a8d4e9c1b0)
![Screenshot 2024-03-21 160646](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/7e8c3ab9-fc79-4a98-8afe-8b10a6dd8617)
![Screenshot 2024-03-21 160743](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/6d70ede7-50bd-44ca-9803-97da0e5a0ac7)
It's not even limited to podcasts:
![Screenshot 2024-03-21 160915](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/3191c3bc-80fa-4e7b-a8f9-d090040dc85d)
Or Been in Fullscreen:
![Screenshot 2024-03-21 160656](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/222d02d1-07cc-4798-93a7-d02435b8f586)

**Comment by surfbryce** [comment]
@Zyanbob can you send your current spotify/spicetify version? This might not be an issue of the extension

**Comment by Zyanbob** [comment]
Spotify for Windows (64 bit)
1.2.33.1039.g8ddb5918
Spicetify v2.34.1
xpui_2024-03-08_1709865429512_8ddb591
cef_122.1.8+g40272b5+chromium-122.0.6261.69
Runtime: Chrome

**Comment by Zyanbob** [comment]
I've checked, the extension IS the problem
![Screenshot 2024-03-21 161910](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/3ee4fad1-2b87-48d9-a9b0-6b94e655ec9f)
![Screenshot 2024-03-21 161937](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/275261dc-078d-4d2f-a0e2-9d72ce80bb6c)
![Screenshot 2024-03-21 161949](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/430a5866-a5cf-4bc2-92a9-fe676e704b8a)
![Screenshot 2024-03-21 161957](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/2396fa08-ef6c-47fe-b79b-5e3e16887476)

**Comment by surfbryce** [comment]
@Zyanbob Well I wasn't saying the problem was coming from Spotify/Spicetify itself, I was mainly checking to see if the version being out of date could have caused the styling for Beautiful Lyrics to have not been applied correctly.

It seems like you're on the completely same versions as I am though, not for sure what could be causing this for you since I'm not getting this at all...

There are a few other things we should probably check, first, are you using Spotify downloaded from the website or the windows store?

**Comment by Zyanbob** [comment]
website, blockthespot deletes the window store version if you have it download

**Comment by surfbryce** [comment]
@Zyanbob Alright so then the next thing I would ask is, can you run the command "spicetify apply enable-devtools", and then click on the three dots in the top left, go to Develop and then "Developer Tools". Once that is open click on the console tab and screenshot everything there.

**Comment by Zyanbob** [comment]
![Screenshot 2024-03-21 163620](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/4901d393-44b9-44b8-bc1d-10559e0479aa)
Spotify With beautiful lyrics with Broken Fullscreen
![Screenshot 2024-03-21 163700](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/4c2ed6ec-632e-427c-b7b1-54ae0a3999c4)
Spotify without beautiful with normal Fullscreen

**Comment by surfbryce** [comment]
@Zyanbob All I need is the "Console" tab from that window, so click that tab and then screenshot all of that please!

**Comment by Zyanbob** [comment]
![Screenshot 2024-03-21 164216](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/fab6b147-717d-40f2-a6d4-aaa1f2cfbc7a)
console tab with just Beautiful Lyrics coming at you

**Comment by surfbryce** [comment]
@Zyanbob is there anything more you can scroll through, or is that the entire output?

**Comment by Zyanbob** [comment]
entire output

**Comment by Zyanbob** [comment]
![Uploading Screenshot 2024-03-21 164726.png…]()

**Comment by Zyanbob** [comment]
are you going to change the label to [investigating](https://github.com/surfbryce/beautiful-lyrics/labels/investigating) now?

**Comment by surfbryce** [comment]
@Zyanbob I usually only switch to investigating when it's something that I can actually reasonably reproduce myself, there's nothing in the output showing that the extension shouldn't be working in the intended way. So if I were to investigate, I would probably end up nowhere because this seems to be localized to you.

The only thing left I can suggest is to reinstall Spotify from the website and to reapply Spicetify. Typically, this works in most cases to fix any issues.

Otherwise, I'm out of ideas of how to figure things out from your side.

**Comment by Zyanbob** [comment]
i've redownloaded and now i can't download spicetify at all
![Uploading Screenshot 2024-03-21 172504.png…]()

**Comment by surfbryce** [comment]
@Zyanbob I think you have to backup the new version of Spotify first, then apply it

**Comment by Zyanbob** [comment]
could you just run through me the commands for windows because i still base Spotify. here's my command line (Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\zyanb> Spicetify backup
spicetify v2.34.1
info Spicetify up-to-date
info There is available backup.
info Clear current backup:
warning After clearing backup, Spotify cannot be backed up again.
info Please restore first then backup, run "spicetify restore backup" or re-install Spotify then run "spicetify backup".PS C:\Users\zyanb> Spicetify restore backup
spicetify v2.34.1
info Spicetify up-to-date
success Spotify is restored.
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
PS C:\Users\zyanb> Spicetify apply
spicetify v2.34.1
info Spicetify up-to-date
Copying raw assets:
OK
Overwriting themed assets:
OK
success Custom CSS is updated
Applying additional modifications:
OK
Transferring custom apps:
OK
success Spotify is spiced up!
PS C:\Users\zyanb> Spicetify backup
spicetify v2.34.1
info Spicetify up-to-date
info There is available backup.
info Clear current backup:
warning After clearing backup, Spotify cannot be backed up again.
info Please restore first then backup, run "spicetify restore backup" or re-install Spotify then run "spicetify backup".
PS C:\Users\zyanb> spicetify restore backup
spicetify v2.34.1
info Spicetify up-to-date
success Spotify is restored.
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!)

**Comment by surfbryce** [comment]
Invalid in new update due to custom fullscreen interface
