### ISSUE TITLE
Lyrics decided The middle of screen suck

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#328]
![Screenshot 2024-03-22 074359](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/fb042d43-cbf8-4c1e-91e5-0f00b95e756f)
And here is console:
![Screenshot 2024-03-22 074340](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/adcb43ba-f9ec-4b16-ba3f-2b2fc5f6f095)

**Comment by Zyanbob** [comment]
![Screenshot 2024-03-22 080737](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/65adaaee-2e90-4509-a595-7295b78ad0b9)
right side of screen seems fine though

**Comment by Abdullahon2006** [comment]
so haven't it been fixed?

**Comment by Mjswitch** [comment]
> so haven't it been fixed or any updates?

check this bug issue: [https://github.com/surfbryce/beautiful-lyrics/issues/441]

**Comment by surfbryce** [comment]
Should be fixed due to a change in how these elements are detected
