### ISSUE TITLE
Spotify does better job at providing lyrics for English Cover of JoJo's bizarre adventure's "Crazy noisy Bizarre town" then beautiful lyrics  

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#331]
beautiful lyrics version:
![Screenshot 2024-03-22 at 9 19 10 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/e4485a9e-29ca-4ef3-a3d6-26b44f97a682)
spotify's version:
![Screenshot 2024-03-22 at 9 27 36 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/5c0b05ae-24f4-44ff-a00f-407f40bcd0cf)
remember, THERE LYRICS ARE FOR THE SAME SONG!

**Comment by surfbryce** [comment]
@Zyanbob I will have to see what's causing this specifically, it should technically be impossible for non-english lyrics to appear for a song if its sung in english.

**Comment by michaelpopi1** [comment]
> @Zyanbob I will have to see what's causing this specifically, it should technically be impossible for non-english lyrics to appear for a song if its sung in english.

it looks like its grabbing the lyrics of the original song (which is japanese)

**Comment by surfbryce** [comment]
@Zyanbob Alright, so going through and testing out all these songs, and there's nothing I can do for this at the moment. It seems like the song incorrectly has japanese lyrics set on the Apple Music side; so I can't do anything in this case
