### ISSUE TITLE
Beautiful Lyrics shows an js error

### ISSUE THREAD

**Issue by Robinjaquez** [surfbryce/beautiful-lyrics#335]
when i clic on the beautifil lytick button wheres an js erros saying to report it to here :/

![fullscrean error](https://github.com/surfbryce/beautiful-lyrics/assets/124253217/97be3f4a-412c-4890-a2e7-44982fbfaeed)
![error](https://github.com/surfbryce/beautiful-lyrics/assets/124253217/a8bae975-05cd-443d-a937-e55bcf52135f)

**Comment by surfbryce** [comment]
@Robinjaquez That is for the fullscreen extension not for Beautiful Lyrics
