### ISSUE TITLE
page lyric display is missing or not working When you press the logo below it doesn't appear instead it displays black

### ISSUE THREAD

**Issue by ravidinejad** [surfbryce/beautiful-lyrics#338]
![Screenshot 2024-03-26 081137](https://github.com/surfbryce/beautiful-lyrics/assets/125472137/003102b6-c3a0-4d94-832c-c811100a7509)

**Comment by iPixelGalaxy** [comment]
Same issue here, I think newest Spotify version broke it

**Comment by jeremybosma** [comment]
Same issue here

**Comment by oussamario** [comment]
Same issue here

**Comment by Zyanbob** [comment]
Isn't this the same as #328 ?

**Comment by surfbryce** [comment]
@Zyanbob I guess you could say that, a recent Spotify update caused this to happen to *everybody* though, so I'm going to close this one and re-open one specifically for the Spotify update issue
