### ISSUE TITLE
dynamic color background not working on now playing view in new update

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#348]
![Screenshot 2024-04-05 085309](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/0994611b-9b7d-48e4-8538-850a4a092c8c)
![Screenshot 2024-04-05 085420](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/93b8961f-f4ec-4868-a7dc-fd6e798a676a)

**Comment by surfbryce** [comment]
Duplicate of #340

**Comment by Zyanbob** [comment]
but beautiful lyrics works (on the side) there just isn't any colors like before

**Comment by Zyanbob** [comment]
![315659639-65adaaee-2e90-4509-a595-7295b78ad0b9](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/1c2798e3-5603-4133-88b6-6cbca95f4613)
like this
