### ISSUE TITLE
No lyrics when fullscreened - Haze theme

### ISSUE THREAD

**Issue by wn7r** [surfbryce/beautiful-lyrics#351]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/91768237/a006a28a-7091-40d1-8111-403f59f3cb51)

**Comment by bleghj** [comment]
Similar issues

**Comment by shaadmhd** [comment]
same issue on haze theme

**Comment by surfbryce** [comment]
Duplicate of #340
