### ISSUE TITLE
Lyrics not showing on main screen

### ISSUE THREAD

**Issue by Szcreen** [surfbryce/beautiful-lyrics#352]
Any song lyrics dont show up on the main page only on the sidebar this is what opens when i try to open the main lyrics page
![firefox_8fCTOu6DhT](https://github.com/surfbryce/beautiful-lyrics/assets/155769198/5a4c5911-b0a8-4a75-88a8-577ccfc04be1)

**Comment by SidhantPratap** [comment]
please let me know if its fixed

**Comment by SudhanFromGithub** [comment]
Same here 
<img width="1589" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/166127509/32cd843f-f522-4841-89f4-9a73e61883dc">

**Comment by surfbryce** [comment]
Duplicate of #340
