### ISSUE TITLE
I click the Beautiful lyrics and everything turns grey

### ISSUE THREAD

**Issue by dysterus** [surfbryce/beautiful-lyrics#353]
I click the beautiful lyrics button and everything turns grey. This happened randomly beacsue I did not add or remove any extensions and I do not have any themes.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/166157553/6852ba61-1878-4ee5-9a14-53c87d4351fc)

**Comment by dysterus** [comment]
Btw i have reinstalled spicetify and the beautiful lyrics extension as well

**Comment by crispim6aL** [comment]
man, i got the same issue... idk why

**Comment by arya070104** [comment]
Same bro i am also facing that same problem.

**Comment by arya070104** [comment]
![Screenshot 2024-04-05 230754](https://github.com/surfbryce/beautiful-lyrics/assets/166160461/d07f393e-9efd-4e96-b3c8-97e60cb99551)

**Comment by bunnyboyshawn** [comment]
Same for me!! Needs an update immediately :((

**Comment by surfbryce** [comment]
Duplicate of #340
