### ISSUE TITLE
Spicetify beautiful-lyrics

### ISSUE THREAD

**Issue by Darkpheonix1234** [surfbryce/beautiful-lyrics#354]
Lyrics arent showing for beautiful lyrics at all js a black screen Doesnt even show that I clicked the lyrics button
![image_2024-04-05_172628714](https://github.com/surfbryce/beautiful-lyrics/assets/166180336/8d6521b2-cb47-4c21-9915-da554efa117b)

**Comment by surfbryce** [comment]
Duplicate of #340

**Comment by tteryrm** [comment]
i´m having this problem too. have you managed to resolve it yet?
