### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by jonathankonda** [surfbryce/beautiful-lyrics#355]
Screen jus shows up as gray now whenever I try using it. Happened after updating Spotify
![image](https://github.com/surfbryce/beautiful-lyrics/assets/72086553/1faaa2f2-156e-4039-9f2c-9e79c3d371c1)

**Comment by WaredXO** [comment]
Same...

![Captura de pantalla 2024-04-05 213656](https://github.com/surfbryce/beautiful-lyrics/assets/166191941/c77e25f9-75a7-4f33-afe5-8ab1f0f0977d)

**Comment by surfbryce** [comment]
Duplicate of #340
