### ISSUE TITLE
Lyrics page no longer has a backdrop nor lyrics

### ISSUE THREAD

**Issue by tmtiedeck** [surfbryce/beautiful-lyrics#356]
When beautiful lyrics is being used it doesn't show anything
<img width="715" alt="beautiful no lyrics" src="https://github.com/surfbryce/beautiful-lyrics/assets/166197344/2295c06e-ecdd-45dc-bdd5-e8f8e9dee54c">

**Comment by Partvision** [comment]
same

**Comment by surfbryce** [comment]
Duplicate of #340
