### ISSUE TITLE
Clashes with full app display extension

### ISSUE THREAD

**Issue by Krim4444** [surfbryce/beautiful-lyrics#360]
if both beautiful lyrics and full app display extension by spicetify are turned on then the fullscreen button neither maximizes lyrics nor enters the normal fullscreen mode, the lyrics do work on sidebar. Let me phrase it better,if only b-lyrics is turned on, fullscreen lyrics dont work only sidebar lyrics work, if both extensions are turned on then on top of these the fullapp extension is also unable to work

**Comment by surfbryce** [comment]
Yeah that makes sense, Beautiful Lyrics has its own full screen, there shouldn’t be compatibility there. The other thing is related to #340
