### ISSUE TITLE
Theme dribbblish/catppuccin-frappe issues

### ISSUE THREAD

**Issue by CharlesNewsom** [surfbryce/beautiful-lyrics#362]
Beautiful lyrics renders a basic screen, without lyrics.

![Spotify_uG33zRB190](https://github.com/surfbryce/beautiful-lyrics/assets/142063597/5fed87ce-c5c4-494a-820e-5dca689d416d)

**Comment by DerHK** [comment]
The author has to update the extention. The last update was in February. Just wait it will get updated eventually.

**Comment by CharlesNewsom** [comment]
> ### THE EXTENTION IS NOT UP TO DATE WITH LATEST SPOTIFY VERSION.
> 
> Just wait and spicetify should automatically update the extention.

Ahhhhh, okay. Thank you for the response man <3

**Comment by surfbryce** [comment]
Duplicate of #340
