### ISSUE TITLE
The "Now playing view" doesn't have blurred album cover

### ISSUE THREAD

**Issue by goldenwario** [surfbryce/beautiful-lyrics#363]
Since the latest update of Spotify, there is no blurred album cover on the "Now playing view" on the right side.
It instead just shows a plain gray color.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/84575859/869c0eda-6ce3-4e58-830b-d6d2a3eee9fa)

**Comment by surfbryce** [comment]
Duplicate of #340
