### ISSUE TITLE
problema al intentar abrir beatiful lyrics 

### ISSUE THREAD

**Issue by 17killer** [surfbryce/beautiful-lyrics#365]
no me aparecen las letras de las musicas y hice todo lo que sugieren ya desinstalé spotify y volvi a instalarlo igual con la extension ya las actualice a las mas recientes 
![Captura de pantalla 2024-04-07 025338](https://github.com/surfbryce/beautiful-lyrics/assets/166288869/f7fc83d3-3bbc-42e6-8c16-96ceac17da79)

**Comment by Akame-Kohler** [comment]
Si! Es un problema que no te afecta a ti solo, afecta a todos los usuarios que lo usan y creo que es debido a una actualización de Spotify, esperemos lo solucionen pronto.

**Comment by surfbryce** [comment]
Duplicate of #340
