### ISSUE TITLE
The lyrics don't load and stay on a screen with nothing showing

### ISSUE THREAD

**Issue by LeginioS** [surfbryce/beautiful-lyrics#376]
Without forgetting that Spicetify and Spotify are up to date.
This is the error:

![Captura de Tela (14)](https://github.com/surfbryce/beautiful-lyrics/assets/98649381/24ad8ca5-b267-41cb-9bff-a0ec865ffc9b)

**Comment by fastnlight0** [comment]
Duplicate of #340

**Comment by surfbryce** [comment]
Duplicate of #340

**Comment by LeginioS** [comment]
> Duplicate of #340

Do you already have a solution for this problem?
