### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by Jo20pxd** [surfbryce/beautiful-lyrics#382]
My lyrics only appear small on the ‘Listening Now’ tab. On the fullscreen tab, it just turns gray and doesn’t work.
![Captura de tela 2024-04-10 212917](https://github.com/surfbryce/beautiful-lyrics/assets/105810290/128da92b-c22e-4aba-91c9-dfa07b4fa63f)

**Comment by PikzAlex** [comment]
Same issue but I'm also missing the lyrics on the 'Listening Now' sidebar.

**Comment by CRYPTIX-hub** [comment]
Same issue with me.

**Comment by AndrewMaged814** [comment]
same issue

**Comment by lopyo-art** [comment]
Exactly the same.

**Comment by surfbryce** [comment]
Duplicate of #340
