### ISSUE TITLE
Lyrics not showing up at all

### ISSUE THREAD

**Issue by ItzGhenes1s** [surfbryce/beautiful-lyrics#386]
**I have uninstalled spotify and re downloaded it multiple times but the lyrics still aren't popping up**

![image](https://github.com/surfbryce/beautiful-lyrics/assets/166799451/945669b4-31cd-4a90-b46e-380e20e3dc7b)

**Comment by kzin123** [comment]
I have same issue

**Comment by christiancandelario** [comment]
same isssue here it's been a week since that happened

**Comment by AADI777BH** [comment]
I AM HAVING SAME ISSUE THE LYRICS NOT SHOWING 3 DAYS AGO PLEASE FIX IT :(

**Comment by surfbryce** [comment]
Duplicate of #340
