### ISSUE TITLE
Full Screen mode for lyrics not working

### ISSUE THREAD

**Issue by kushagra-patel11** [surfbryce/beautiful-lyrics#390]
Wheenever i tri to open immersive mode for lyrics it always shows a blank/black screen. Only card lyrics is showing,no full screen lyrics is working. Even whenever i tried to do normal full screen mode it again show me a blank screen with zero response.

![Screenshot 2024-04-13 184236](https://github.com/surfbryce/beautiful-lyrics/assets/83807382/d665c327-9ee2-4f1e-b5b4-f487d42d160d)

**Comment by SteelyxYT** [comment]
I have the same issue :(

**Comment by surfbryce** [comment]
Duplicate of #340
