### ISSUE TITLE
Theme Comfy Issues

### ISSUE THREAD

**Issue by litevrsx** [surfbryce/beautiful-lyrics#395]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166982042/7e9f4931-d664-4808-a7c3-68fd4467b3f1)
Lyrics not showing on click
Restarted spotify a few times already

**Comment by Taeronn** [comment]
Have the same issue, but no matter what theme, on default theme doesn't work too
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71982053/98231e96-fe95-470c-a957-136bcc0e9aaa)

**Comment by Zyanbob** [comment]
repeats of #340

**Comment by surfbryce** [comment]
Duplicate or #340
