### ISSUE TITLE
Background moves with the lyrics

### ISSUE THREAD

**Issue by SunsetTechuila** [surfbryce/beautiful-lyrics#4]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115353812/6035dff7-a56f-44e6-89f0-942f6e04d8cb)

Can be fixed by moving `lyrics-background-container` inside `under-main-view`:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115353812/4ee2e19a-3194-4cee-aa6c-ad26f4f79354)

**Comment by surfbryce** [comment]
@SunsetTechuila under-main-view doesn't existing in Cinema mode so this is not a valid implementation that can be considered; however, I do have a question that could lead to an easy resolution here.

Do you have the "Lyrics in the right sidebar" experimental feature enabled? If not support for the "classic" lyrics container does not exist yet - but I created #3 for that reason and I am implementing support for it right now

**Comment by SunsetTechuila** [comment]
> under-main-view doesn't exist in Cinema mode

no, it does
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115353812/f165f56e-e222-4a9d-9640-faf7d38d4b82)

**Comment by SunsetTechuila** [comment]
> Do you have the "Lyrics in the right sidebar" experimental feature enabled?

moves even with "classic" lyrics

**Comment by surfbryce** [comment]
> > under-main-view doesn't exist in Cinema mode
> 
> no, it does ![image](https://user-images.githubusercontent.com/115353812/239641188-f165f56e-e222-4a9d-9640-faf7d38d4b82.png)

Ah you're right - it does exist. I glossed over that when looking through the DOM.

I'll make a change to move it there since that'll cover both Cinema and "Classic" containers rather easily - although, still not sure why the lyrics are affecting the background for you in the first place 🤷

**Comment by SunsetTechuila** [comment]
> still not sure why the lyrics are affecting the background for you in the first place

What do you mean?

**Comment by surfbryce** [comment]
> > still not sure why the lyrics are affecting the background for you in the first place
> 
> What do you mean?

Well this issue doesn't happen for me or anybody else - at least from what I've seen in Discord and GitHub channels. It's just interesting that it's happening in the first place is all.

I'll have this fix pushed out momentarily!

**Comment by SunsetTechuila** [comment]
It has always been like this for me, on all devices and OS.  And as far as I learned how stock lyrics work while working on the Bloom theme, this is how it should be

**Comment by SunsetTechuila** [comment]
Nord theme has lyrics background inside `under-the-main-view` too

**Comment by SunsetTechuila** [comment]
Pretty fast 👍🏿
Nice extension you made! A creative approach to animating background

**Comment by surfbryce** [comment]
@SunsetTechuila Thank you!

I appreciate you writing up the issue! Had no idea that container even existed - so much better to use!

**Comment by SunsetTechuila** [comment]
Also I see that you are using many observers, do you know that you can use Spicetify History API for everything except right sidebar and lyrics cinema?
