### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by joicelss** [surfbryce/beautiful-lyrics#403]
when i press the full screen button it just shows as blank there isnt anything
![Näyttökuva 2024-04-16 231835](https://github.com/surfbryce/beautiful-lyrics/assets/167249819/298fb2c4-d05a-4fec-a282-0d2fa5719993)

**Comment by bharataddagatla** [comment]
I am facing the same problem too,

**Comment by surfbryce** [comment]
Duplicate of #340
