### ISSUE TITLE
A bug with the extension

### ISSUE THREAD

**Issue by 404Mohammed** [surfbryce/beautiful-lyrics#41]
Hi i hope you are doing well i have a problem with beautiful lyrics extension it is not working with me no matter what i do i have spotify spicetify and marketplace up to date and i have reinstalled everything just in case but still not working hope you can help me and thank you

**Comment by surfbryce** [comment]
@404Mohammed Can you continue this over in #40 thank you! Also when you are commenting over there can you say what is specifically not working?
