### ISSUE TITLE
The lyrics does not show up in the big screen 

### ISSUE THREAD

**Issue by lunarruu** [surfbryce/beautiful-lyrics#411]
![Screenshot 2024-04-19 003516](https://github.com/surfbryce/beautiful-lyrics/assets/167462947/ab8d8d44-1c3f-4acd-8a88-5595fb4dfa57)
hi, can you help me? the lyrics does not show up in the big screen. only in small right screen. i already reinstall spotify and spicetify but it does not work for me. i tried many tips, but they not work. pls fix this or help me to solve this. thank you!

**Comment by surfbryce** [comment]
Duplicate of #340
