### ISSUE TITLE
(Suggestion) Dark lyrics for bright cover arts

### ISSUE THREAD

**Issue by Endg4meZer0** [surfbryce/beautiful-lyrics#42]
Is there any possibility to make lyrics in darker colors like black or dark grey for cover arts that are very bright? Some cover arts of albums in my playlist are even pure white, and that makes lyrics invisible until you hover on them (example below).

![image](https://github.com/surfbryce/beautiful-lyrics/assets/65147948/ca8b606b-6776-479b-8ba9-1e7fd4cdbce0)

**Comment by surfbryce** [comment]
Yeah I've noticed visibility can be hard as well with albums similar to that, I particularly had this problem with Childish Gambino's 17.10 but it wasn't terrible.

I think visibility should massively improve in the upcoming update but I definitely think having the lyrics change color based off the brightness being overall too high is a good idea - so I'll look into that for a future update

**Comment by Endg4meZer0** [comment]
nice! thanks for the answer!

**Comment by Endg4meZer0** [comment]
the visibility really did improve a lot in the new major update, so I'm gonna close this issue, as I don't see the need in dark lyrics now

![image](https://github.com/surfbryce/beautiful-lyrics/assets/65147948/fa6b45e9-35a6-46d1-b858-122261aee88d)

**Comment by Endg4meZer0** [comment]
ok i'm messing this up, sorry

**Comment by Endg4meZer0** [comment]
first time github user, i forgot there are bots and stuff that sort it out for you

**Comment by surfbryce** [comment]
@Endg4meZer0 That's perfectly fine! I agree that the visibility has increased drastically to the point where we don't need this feature necessarily so I'll close it out for you again!
