### ISSUE TITLE
issue with the lyrics 

### ISSUE THREAD

**Issue by IIcydi** [surfbryce/beautiful-lyrics#421]
i use theme DefaultDynamic
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167888838/f13918f5-a302-40ab-983e-7ca81b312163)
Lyrics are not displayed & when full screen
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167888838/2241f0a8-01a9-4000-b7bd-bb9fda4ec04c)

**Comment by surfbryce** [comment]
Duplicate of #340
