### ISSUE TITLE
THEME Default Dynamic issues

### ISSUE THREAD

**Issue by Tyrannous** [surfbryce/beautiful-lyrics#427]
![Screenshot 2024-04-24 041130](https://github.com/surfbryce/beautiful-lyrics/assets/23184602/7e7580b0-a4a5-41f0-bed7-8eda0129b705)

Lyrics aren't showing up when program is just maximized/main window, just the animated background.

**Comment by RedolentHalo** [comment]
I've the same problem this is after the spotify update

**Comment by srijithmass** [comment]
Even full screen too not working.

**Comment by RedolentHalo** [comment]
> Even full screen too not working.

Yea

**Comment by surfbryce** [comment]
Duplicate of #340
