### ISSUE TITLE
LYRICS SHOWING UP AS BLANK

### ISSUE THREAD

**Issue by Amirali153** [surfbryce/beautiful-lyrics#431]
![Screenshot 2024-04-25 111136](https://github.com/surfbryce/beautiful-lyrics/assets/107568740/53563bf7-89a6-471c-bbc5-0589af0b6963)
If you look carefully, the corner is showing, but the bigger one is showing a black screen

**Comment by Amirali153** [comment]
What should I do ?

**Comment by riquelmovski** [comment]
> What should I do ?

I uninstalled spotify and downloaded version 1.2.31.1205 from the internet on uptodown and installed it. After that I opened powershell and applied spicetify. When I opened it, there were no extensions, I went to the marketplace and installed this plugin and others and it appeared again as before.

**Comment by riquelmovski** [comment]
I uninstalled spotify and downloaded version 1.2.31.1205 from the internet on uptodown and installed it. After that I opened powershell and applied spicetify. When I opened it, there were no extensions, I went to the marketplace and installed this plugin and others and it appeared again as before.
