### ISSUE TITLE
It doesent work

### ISSUE THREAD

**Issue by kalichT** [surfbryce/beautiful-lyrics#434]
I need help with my lyrics it does not work when I click on it it stays blank
![obrázek_2024-04-25_234644826](https://github.com/surfbryce/beautiful-lyrics/assets/96803579/787db0ef-c892-4b3f-8051-e7c0991f9f1f)

**Comment by kalichT** [comment]
I feel like ive tried everything

**Comment by surfbryce** [comment]
Duplicate of #340
