### ISSUE TITLE
Issue when opening the lyrics

### ISSUE THREAD

**Issue by nickolas2805** [surfbryce/beautiful-lyrics#440]
After the last spicetify update, the lyrics are not opening!

In this image, I pressed the button for the beautiful lyrics, but it was showing like this, and the same is in all the songs.

![Spotify issue](https://github.com/surfbryce/beautiful-lyrics/assets/104525321/894889e4-2f8d-4382-98de-27efb29a60b5)

**Comment by surfbryce** [comment]
Duplicate of #340
