### ISSUE TITLE
Lyrics only shows in the side bar but not in fullscreen mode and other modes

### ISSUE THREAD

**Issue by rawniee** [surfbryce/beautiful-lyrics#442]
![Screenshot 2024-04-28 061935](https://github.com/surfbryce/beautiful-lyrics/assets/168313805/9154eccb-3e05-49a9-83f6-602ce6ad489e)

EDIT: i downloaded the lyrics plus plugin as well but it got removed as i installed beautiful lyrics

hopefully you will reach out soon<3

**Comment by surfbryce** [comment]
Duplicate of #441
