### ISSUE TITLE
Lyrics not showing

### ISSUE THREAD

**Issue by zazeer** [surfbryce/beautiful-lyrics#443]
I've followed the suggestions, but my Spotify still doesn't display lyrics. The sidebar shows up when I activate the extension, but not the 'beautiful' lyrics, and if I want to use the larger mode, there are no lyrics. I'm using the Comfort (Legacy) theme.

Thanks in advance
![Screenshot 2024-04-28 195358](https://github.com/surfbryce/beautiful-lyrics/assets/135493061/5e6263c6-4be8-4245-b242-8d495dd4c61f)

**Comment by virtualgurel** [comment]
@zazeer please take a look at #441. And before you post another bug somewhere maybe check if it's already known.

**Comment by zazeer** [comment]
Ahh i see my bad, thanks
