### ISSUE TITLE
Full Screen Bugged

### ISSUE THREAD

**Issue by RocraftGamerYT** [surfbryce/beautiful-lyrics#444]
https://github.com/surfbryce/beautiful-lyrics/assets/79378601/ab6f8887-498b-4f64-a764-0f7d46ad855c

**Comment by borxxo** [comment]
i have the same problem

**Comment by J-from-Nucleon** [comment]
Known issue
Refer #441

**Comment by surfbryce** [comment]
Duplicate of #441

**Comment by RocraftGamerYT** [comment]
@surfbryce so, its gonna get fixed this month?
