### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by momentumhmz** [surfbryce/beautiful-lyrics#446]
In Spotify(desktop app), the lyrics show on the right side the lyrics do show, but when I click the Lyrics Page(the one with the stars around it which is the plugins one) it doesn't show up.
![Ekran görüntüsü 2024-04-28 224658](https://github.com/surfbryce/beautiful-lyrics/assets/168372636/51b70f09-808b-4132-91f8-702a06e1b3bf)

**Comment by surfbryce** [comment]
Duplicate of #441
