### ISSUE TITLE
Blank lyrics and fullscreen page

### ISSUE THREAD

**Issue by KragenZ** [surfbryce/beautiful-lyrics#450]
When I click the "Lyrics Page" or the "Enter Full Screen" the page is just void.
<img width="960" alt="Screenshot 2024-04-30 212134" src="https://github.com/surfbryce/beautiful-lyrics/assets/138899018/ff8bc268-9674-45e9-ab76-342f5b4bffb6">
 
The lyrics only show in "Now Playing View" and yes I redownloaded both spotify (from web) and spicetify.

**Comment by articiceberg97** [comment]
Known issue, no fix yet
Check #441

**Comment by surfbryce** [comment]
Duplicate of #441
