### ISSUE TITLE
full screen problem

### ISSUE THREAD

**Issue by SenpaiNeedsHelp** [surfbryce/beautiful-lyrics#452]
![Spotify Free 5_1_2024 1_32_39 PM](https://github.com/surfbryce/beautiful-lyrics/assets/117751391/0371e509-4960-493e-8ac3-461e4a0f76da)
 
the lyrics shows up in the side view but when i click on full screen its just blank.
i have tried reinstalling everything but its still not working.

**Comment by Anonoymity** [comment]
Update will be out in 24 hours. This is an issue for the newer version of spotify. You can download an old version if you want an early fix tho

**Comment by surfbryce** [comment]
Duplicate of #441
