### ISSUE TITLE
Theme 'marketplace' Issues

### ISSUE THREAD

**Issue by Wart050** [surfbryce/beautiful-lyrics#454]
Use to work with this theme but for a few updates now it has stopped working, well the side lyrics work but not the full screen, when I do click on the lyrics full screen, this is what I see:
![image_2024-05-01_203125886](https://github.com/surfbryce/beautiful-lyrics/assets/101201581/97b2fded-31b6-42ae-9071-7c95d121a019)

**Comment by surfbryce** [comment]
Duplicat of #441
