### ISSUE TITLE
wheres the update

### ISSUE THREAD

**Issue by technicows** [surfbryce/beautiful-lyrics#456]
its may 2nd n it still hasnt released? what happened

**Comment by Joeeeeb5** [comment]
still waiting..

**Comment by painfulbunny** [comment]
Sometimes things don't pan out. Give the developer some time! Better to have an unrushed released than a bunch of issues piling up :)

**Comment by Zaitooo** [comment]
Yes, no problem, but he did give us his word when he said he'd publish it on 1 May, but that's all right.

**Comment by Joeeeeb5** [comment]
while lyrics are available on countless websites for free..

**Comment by s4ifyz** [comment]
spotify is never beating the money-hungry allegations... cause how are you charging people for LYRICS 😭

**Comment by RabjamX2** [comment]
> Its still not updated does anybody know which version of spotify and spictify is compatible with beautiful lyrics working

If you want a temporary fix, [this](https://github.com/heheleo/beautiful-lyrics/blob/main/dist/beautiful-lyrics.js) fork works. You can simply download the javascript file and install the extension manually like you would any other spicetify extension

**Comment by surfbryce** [comment]
[It *should* be coming out today, I ran into a few bugs due to the changes that I made which I am working on](https://github.com/surfbryce/beautiful-lyrics/issues/441#issuecomment-2091293539)
