### ISSUE TITLE
Theme comfy Issues

### ISSUE THREAD

**Issue by b0neth** [surfbryce/beautiful-lyrics#462]
When I lyrics pag with the beautiful lyrics its just a blank screen
![image](https://github.com/surfbryce/beautiful-lyrics/assets/124420482/d8eaba13-d22c-4c6e-91dd-f0f6074812b1)

**Comment by surfbryce** [comment]
Duplicate of #441

**Comment by b0neth** [comment]
> Duplicate of #441

ty!
