### ISSUE TITLE
no lyrics full view? and songs that has lyrics dont appear

### ISSUE THREAD

**Issue by Videogame-Oscar** [surfbryce/beautiful-lyrics#464]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78685277/f7d6cda1-3045-4fe9-8db4-74489f0b8923)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/78685277/d3b16995-74f4-4f8c-8856-4a217758e4cc)
no lyrics appear

**Comment by MrMcNuggie** [comment]
Bro the post right at the top of this is addressing that

**Comment by Videogame-Oscar** [comment]
i already tried what it says

**Comment by Videogame-Oscar** [comment]
or nvm ill just wait i guess
