### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Videogame-Oscar** [surfbryce/beautiful-lyrics#467]
I just want to ask a question how come some songs with  lyrics has like the sliding effect with each letter being synced to the song but for some songs its like a sliding down effect

**Comment by Rifaque** [comment]
idk for sure but I think there's a large library of songs that support that effect (syllable-synced songs), although it's large it doesn't include every song. The developer probably does it manually, but I may be wrong.  The syllable-synced songs are awesome but they require a lot of work, perhaps the only more recent and more popular songs support it.

On the bright side, the developer has said that the upcoming update is going to increase the number of these songs. The slide-down effect doesn't require much work, so it's available for (almost) every other song that doesn't have the syllable-sync support.

**Comment by Videogame-Oscar** [comment]
fair  but i think their should be a thing to sync your own songs :D

**Comment by surfbryce** [comment]
@Videogame-Oscar My service internally uses Musixmatch to retrieve lyrics, nothing is done manually. For the most part, it is primarily up to the artist/record company on what type of syncing is used on their lyrics. Some artists go through the time to do syllable synced lyrics, others may only do line, some may not even sync it at all and leave it at static text.

**Comment by Videogame-Oscar** [comment]
> @Videogame-Oscar My service internally uses Musixmatch to retrieve lyrics, nothing is done manually. For the most part, it is primarily up to the artist/record company on what type of syncing is used on their lyrics. Some artists go through the time to do syllable synced lyrics, others may only do line, some may not even sync it at all and leave it at static text.



hey @surfbryce this makes it easy to understand but i also found out . its not just artists is the community or msuexmatch who makes word by word sync  i am able to make some songs sync with word by word as well witch is a good thing
just telling ya this
