### ISSUE TITLE
Theme green-dark Issues

### ISSUE THREAD

**Issue by yashraj8990** [surfbryce/beautiful-lyrics#468]
The extension was working fine till today until I updated spicetify. After updating spicetify using powershell, when I clicked on the lyrics icon stating "Lyrics Page", a blank panel opened and the lyrics are now showing up. Other than that, the lyrics are being shown in the right sidebar, with glowing text and animations but with black background only. Hope to get a fix on this issue.

![Screenshot 2024-05-06 032432](https://github.com/surfbryce/beautiful-lyrics/assets/104300238/365e19d6-fef7-4f0a-a05f-aa47fff5b4fb)

**Comment by yashraj8990** [comment]
the current opened panel is the lyrics page.

**Comment by surfbryce** [comment]
Duplicate of #441
