### ISSUE TITLE
cover art bug in full screen

### ISSUE THREAD

**Issue by Seiyuas** [surfbryce/beautiful-lyrics#469]
it does look like this
![Screenshot (3)](https://github.com/surfbryce/beautiful-lyrics/assets/71611053/fa1bc0f8-5299-4b57-9a4e-9e7af97c68dc)
i used comfy theme
[](https://github.com/Comfy-Themes/Spicetify)
btw overall, really great extension!

**Comment by surfbryce** [comment]
Not going to be relevant when the next update comes out, so not a concern
