### ISSUE TITLE
did the latest auto update break the extension?

### ISSUE THREAD

**Issue by theliamking** [surfbryce/beautiful-lyrics#47]
![image_2023-07-01_215932921](https://github.com/surfbryce/beautiful-lyrics/assets/99769726/bd312ff8-e81c-4c5f-b7c9-e5aa13faa5c3)

Nothing really works, the album art is solid and lyrics aren't showing. All options in the FAQ are ticked on.

**Comment by surfbryce** [comment]
Play another song and it should fix itself, for some reason it doesn't work on an already playing song when it auto-updates. I can see the lyrics-button at the bottom so it's definitely working - I just think it's what I described. I can't find out why it's doing that at the moment so there will be no fix for that today.

But it won't be a problem once JSDelivr updates and it's automatically on the new version every time you launch Spotify

**Comment by theliamking** [comment]
hey man, switching the song didnt seem to do anything but I reinstalled spicetify entirely and that fixed the issue. 
👍
