### ISSUE TITLE
[ISSUE] No lyrics page in beautiful lyrcics

### ISSUE THREAD

**Issue by hubneega** [surfbryce/beautiful-lyrics#471]
The Lyrics page doesnt open.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169062456/c72a2aef-a165-4764-a69c-831b207a1a72)
Even when clicked on this "Open Lyrics Page" button (image attached below ), all i get is the blank page in the above image.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169062456/387d8f61-47bb-41a8-83cb-0ade42846d71)

I have tried uninstalling and reinstalling spicetify, removing, adding and changing themes, even reinstalling "Beautiful Lyrics" but nothing seems to work. Please look at the issue-
Thanks!

**Comment by Joeeeeb5** [comment]
goddamn read the posts first we've been talking about this issue for a month

**Comment by iseeface** [comment]
read another post, and you will know what happened during this time

**Comment by surfbryce** [comment]
Duplicate of #441
