### ISSUE TITLE
How to add live lyrics

### ISSUE THREAD

**Issue by MattiaPARRINELLO** [surfbryce/beautiful-lyrics#472]
I know this is not supposed to be here, but I don't know where it's supposed to be, so I was wondering, where can we add live lyrics for a song that doesn't have it. I did my research but I found nothing.
If anyone have an idea it would be cool!

(If i'm not wrong live lyrics is when it show the lyrics word by word like in the screenshot bellow 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/66528113/f53d05df-edac-4766-a6dc-db8ec08cc4bb)
)

**Comment by enzon19** [comment]
On Musixmatch.

https://www.musixmatch.com/

**Comment by surfbryce** [comment]
There is a planned Lyrics Editor update during the summer, but at the moment, there is now way to directly add syllable synced lyrics via the extension
