### ISSUE TITLE
new cinema and page view wont work 

### ISSUE THREAD

**Issue by cuxtiie** [surfbryce/beautiful-lyrics#474]
card lyrics are the only one working 
![Screenshot (846)](https://github.com/surfbryce/beautiful-lyrics/assets/169271820/8d696c0a-05a1-472c-93d1-2723eb1acce4)
The empty part in the middle is what appears when i try putting lyrics in cinema view or the new page view

**Comment by enzon19** [comment]
https://github.com/surfbryce/beautiful-lyrics/issues/441

**Comment by surfbryce** [comment]
Duplicate of #441
