### ISSUE TITLE
Sidebar lyrics work perfectly but full screen lyrics/visuals refuse to show up

### ISSUE THREAD

**Issue by thev216** [surfbryce/beautiful-lyrics#476]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/84483419/7dda6555-7e39-4138-877e-aa9d7d5bb48b)

should i still reinstall the client/mods?

**Comment by aseluxna** [comment]
this is apart of the no lyrics bug, the dev is fixing it.

**Comment by 5OBHAN** [comment]
_Refer to_ → **#441**

**Comment by 5OBHAN** [comment]
Duplicate of #441

**Comment by surfbryce** [comment]
Duplicate of #441
