### ISSUE TITLE
[Suggestion]Beautiful-lyrics in fullscreen mode

### ISSUE THREAD

**Issue by ProchyGaming** [surfbryce/beautiful-lyrics#48]
I was wondering if it would be possible to replace the lyrics in full-screen mode with beautiful lyrics instead, or if there's a way how to make the cinema mode full-screen.
Thank you!

**Comment by surfbryce** [comment]
@ProchyGaming What full-screen mode are you referring to? Also if you are talking about my version of the Cinema mode where it takes up all of Spotify - I think making Spotify fullscreen would be enough to do that I think

**Comment by ProchyGaming** [comment]
Thank you for the quick reply, if i enter cinema mode and go to full-screen with the button in the bottom right corner it switches to the full-screen that spotify has and i meant replacing that for example. It's handy when it comes to having spotify open on a 2nd monitor.

**Comment by surfbryce** [comment]
Oh I see @ProchyGaming, yeah that's totally doable! Thanks for the suggestion it'll be implemented sometime this coming week!

**Comment by ProchyGaming** [comment]
Thank you a lot! I'll be looking forward to it!

**Comment by surfbryce** [comment]
@ProchyGaming Sorry for the really long delay on this. I actually decided just to override the fullscreen functionality of Spotify and provide a new lyric-view (to complement the Cinema/Page lyric views).

Here's what it'll look like:
<img width="1727" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/da21052a-85fb-40a3-ab7c-9b049b3a51c3">

**Comment by surfbryce** [comment]
I've put out the update now so you can enjoy this - thanks for the suggestion! If you have any feedback it would be much appreciated!
