### ISSUE TITLE
Second Optimized Version / Alternate Background Option?

### ISSUE THREAD

**Issue by boochySans** [surfbryce/beautiful-lyrics#480]
Hey! I have a question, I saw that you wouldn't want to make a toggle for the background to do like apple would and keep it "as it is" 
But I was wondering if it was possible to create a second version without the background 
I can understand if you can't, since you would have to update both of the versions and keep track of issues

I was also wondering if it was possible to make another type of background, I was thinking just a blurred **AND / OR** darker image of the Album Art In the background as an alternate option which would Definitely decrease the resource usage.

BLURRED BG PREVIEW : 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90515114/03a8a86b-7116-49b1-824f-8d08b0dc099e)

DARKER BG PREVIEW : 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90515114/596b452b-9576-440a-83b7-f74db088b720)

BOTH BG PREVIEW : 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90515114/0eb5534b-05a4-4ee1-b948-b9f00e2bf8fe)

Thanks in advance!

**Comment by surfbryce** [comment]
@boochySans The goal is to keep it like the way Apple does it without sacrificing anything for people, there are a lot of ways to do this effect in a more optimal way, I just haven’t had the time to make those optimizations. I want to do it right and the proposed ways here aren’t what I would consider the right way.

There won’t be a simplified version or alternative, but in the future, there will be optimizations made! In the update coming out soon there will be a small optimization made but the real ones will take a bit longer
