### ISSUE TITLE
Can't open lyrics page in spotify

### ISSUE THREAD

**Issue by uiutkrisht** [surfbryce/beautiful-lyrics#481]
I am not able to open the lyrics page, I even tried re-installing both spotify and Spicetify  but that didn't helped. The lyrics are visible on the left hand side but when I click the lyrics icon that opens a black page with nothing. Also the now playing view has color issues PFA but please fix that lyrics problem, at first when I installed Spicetify and then your extension I could see the lyrics but now I can't. Also I haven't installed any themes as well.
![Screenshot 2024-05-09 194744](https://github.com/surfbryce/beautiful-lyrics/assets/91411783/eaa99e42-f67c-4437-8ad1-82411258497e)

**Comment by RazzerDE** [comment]
same here

**Comment by RazzerDE** [comment]
https://github.com/surfbryce/beautiful-lyrics/issues/441

**Comment by surfbryce** [comment]
Duplicate of #441
