### ISSUE TITLE
Hey, i updated my spiciefy to the latest version today, but the lyrics still dont show up on the main screen, only the sidebar does, please help :)

### ISSUE THREAD

**Issue by JoddIsamazing** [surfbryce/beautiful-lyrics#482]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169358188/5d057f45-6fd9-4ba3-8051-15f0690ded12)

**Comment by MrSandy01** [comment]
This appears to be a recognized issue in recent Spotify versions. The development team is actively working on a fix. You can track progress and updates on this issue in #441

**Comment by nhth31** [comment]
_same_

**Comment by surfbryce** [comment]
Duplicate of #441

**Comment by JoddIsamazing** [comment]
> Duplicate of #441

I did check it,  but it still doesnt help
