### ISSUE TITLE
Lyrics page button does nothing.

### ISSUE THREAD

**Issue by crazeyyoungster** [surfbryce/beautiful-lyrics#484]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/69756297/c804ef47-1ae8-4a92-9fb0-3aace27945b8)
Clicking the "lyric page" button makes the screen blank.

**Comment by crazeyyoungster** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/69756297/032503cd-f7e3-49e9-8951-7b9db6a1ae38)
I mean this one and enabling the extension

**Comment by surfbryce** [comment]
Duplicate of #441

**Comment by crazeyyoungster** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/69756297/0929238b-da69-44ef-b03d-3ea304456055)
I mean this one and also enabling the extension makes spotify go laggy.
