### ISSUE TITLE
Songs without lyrics or without synced lyrics recently started having other songs' synced lyrics override them

### ISSUE THREAD

**Issue by ziIIas** [surfbryce/beautiful-lyrics#486]
Examples
https://open.spotify.com/track/4cuY1KZrFVxJJXQiT3C49L?si=a33bf6a708f94cb4
https://open.spotify.com/track/5eJdfH8OuSfB4qpjhi6SHy?si=2c31a04af8e744eb

**Comment by ziIIas** [comment]
https://open.spotify.com/track/6Kj17Afjo1OKJYpf5VzCeo?si=a16758b5a9f94f08

**Comment by surfbryce** [comment]
Not valid until new update
