### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by EvilMortyyyy** [surfbryce/beautiful-lyrics#487]
I reinstall, update, etc and the lyrics not found
<img width="955" alt="Sin título" src="https://github.com/surfbryce/beautiful-lyrics/assets/169542353/5c3d92be-b99f-4ca9-9514-a9fc9d7ff953">

**Comment by wangpengcBob** [comment]
same issue, this happened about 1 month ago, tried reinstall spotify, spicetify, this extension for several times but still not working till now. Both Windows and macOS.

**Comment by wangpengcBob** [comment]
please refer to #410 and #340

**Comment by nhth31** [comment]
duplicate of #441

**Comment by surfbryce** [comment]
Duplicate of #441
