### ISSUE TITLE
ONLY showing the lyrics for "i like the way you kiss me"

### ISSUE THREAD

**Issue by ShuitOnDiscord** [surfbryce/beautiful-lyrics#488]
why???
![image](https://github.com/surfbryce/beautiful-lyrics/assets/106796864/da67800a-2146-417f-8822-d147592f8b4c)

if its another plugin messing with it then it will be hell to figure out which one

**Comment by surfbryce** [comment]
Invalid until next update

**Comment by ziIIas** [comment]
Is there a temp fix before next update for us using old spotify where beautiful lyrics worked fine? It's fine if not, I can wait

**Comment by ziIIas** [comment]
Nevermind. Now see the progress thread, considering update should be out tomorrow, there's no need to make a temp fix.
Keep up the good work
