### ISSUE TITLE
Suggestion: beautiful-lyrics inspired background theme

### ISSUE THREAD

**Issue by DeveloLongScript** [surfbryce/beautiful-lyrics#489]
What if there was a theme, similar to something like [Hazy (a spicetify theme)](https://github.com/Astromations/Hazy), but with the gradient component of beautiful lyrics as the background. I feel like something like that would be really cool as a theme, because Hazy's gradient, well, isn't the best.

Thanks! :D

**Comment by surfbryce** [comment]
Duplicate of #37
