### ISSUE TITLE
Could anyone help me to update to the new version of the extension?

### ISSUE THREAD

**Issue by Zdadang** [surfbryce/beautiful-lyrics#5]

**Comment by surfbryce** [comment]
@Zdadang What are you specifically having issues with?

Is something in the extension not working - or are there other things that are making you think it's not updated?

As far as I am aware the extension is fully available to be updated by everyone - so if you try to reinstall it now it should be the latest version.

**Comment by Zdadang** [comment]
Thanks, just had to reinstall. though it didnt work yesterday I reinstalled and it was fixed
