### ISSUE TITLE
Languages Incorrectly being marked as Right to Left

### ISSUE THREAD

**Issue by NEVARLeVrai** [surfbryce/beautiful-lyrics#50]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/63956787/6dbea5fd-6ca9-446e-a383-00c468882fcd)
it is displayed from right to left when it is supposed to be from right to left?

**Comment by surfbryce** [comment]
I did notice this on another song myself, it does support RTL if it detects it but it does that incorrectly at times. You should see a fix sometime today

**Comment by IrepY** [comment]
The name of the song on my screenshot was Azahriah - Kaotikus Egy Ház!
But this issue persists in all hungarian songs (Basically all songs from Azahriah could be an example)

**Comment by surfbryce** [comment]
@IrepY @NEVARLeVrai Ok so on my development version I'm actually not seeing these issues - so I'm assuming the cache hasn't updated so I've updated the version locally.

When you guys are available please see if it still occurs after the extension update!

**Comment by NEVARLeVrai** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/63956787/2d6733a1-c18b-412e-8ebb-ab3c7ace2cc1)
got fix
