### ISSUE TITLE
Half of the Karaoke Synced songs I've tested don't work... 

### ISSUE THREAD

**Issue by HannistHK** [surfbryce/beautiful-lyrics#501]
As the title suggests... 
![IMG_20240516_114914_367.jpg](https://github.com/surfbryce/beautiful-lyrics/assets/144600078/32b6c360-4f53-42b4-91fa-1357d7104fc9)

(This song used to have synced lyrics)

**Comment by surfbryce** [comment]
@HannistHK Can you provide more examples, don't have to do a screenshot for all of them, just a list of songs and what type of synced lyrics they should have (karaoke or line synced)

**Comment by HannistHK** [comment]
Actually a weird thing happened... I restarted spotify to just double check if the lyrics works and it fixed like 99% of the songs with no lyrics, the song i mentioned above though still has none.

**Comment by Blankk02** [comment]
> @HannistHK Can you provide more examples, don't have to do a screenshot for all of them, just a list of songs and what type of synced lyrics they should have (karaoke or line synced)

This song have lyrics with your previous version of Beautiful Lyrics but don't have now, so:
open.spotify.com/track/6wcRv0UBvEH9NCIA3IVyQs

**Comment by surfbryce** [comment]
@HannistHK It's possible that there was an error that prevented any more lyrics from loading, if this happens to you again please open the console (there will be a readme on how to do this Thursday) and let me know with a screenshot

**Comment by surfbryce** [comment]
Going to close this one since the plenty of other requests with more information should hopefully aid in fixing this issue even for other songs you run into
