### ISSUE TITLE
Blurred album overrides Main Page

### ISSUE THREAD

**Issue by hilmymajid791** [surfbryce/beautiful-lyrics#502]
Spotify version = 1.2.31.1205.g4d59ad7c amd64
![image](https://github.com/surfbryce/beautiful-lyrics/assets/69564470/6bb195ae-3640-4261-a86a-fdc5b840dd72)

**Comment by bestgio** [comment]
I'm also seeing this issue on Windows
![image](https://github.com/surfbryce/beautiful-lyrics/assets/34141617/b2ba8e98-a532-443c-a5d4-7927c2544ca9)

**Comment by OverStyleFR** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/94577363/f0ee3977-3b1e-42c1-9157-75feb08e10c3)
I have the same thing, how can i unistall so ?

**Comment by Danulal** [comment]
> I have the same thing, how can i unistall so ?

![grafik](https://github.com/surfbryce/beautiful-lyrics/assets/74148862/dd28052f-865a-4845-81c3-144ce6b9099b)
Try to find the marketplace settings button there, it should open the menu where you can reset

**Comment by surfbryce** [comment]
@hilmymajid791 Can you recreate this issue following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics, thanks!
