### ISSUE TITLE
No lyrics on MARINA songs.

### ISSUE THREAD

**Issue by asvhz** [surfbryce/beautiful-lyrics#503]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169973783/936abecf-14bf-4645-9434-33e0b91678fa)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/169973783/56ffd0cb-dac9-4e8c-a60f-8decf0d3029b)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/169973783/414885a0-d6e9-4b91-92b6-0d6af642d748)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/169973783/4f8d5b80-929a-4245-acbf-6c9cb8522425)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/169973783/0e366ee8-180e-4e04-8f9e-4b92a9ec9dff)

alright, i also noticed that on Love + Fear and Ancient Dreams In A Modern Land every song has lyrics, but they're not syllable synced.

**Comment by surfbryce** [comment]
@asvhz This will be fixed in the next update, super simple fix which fixes all the songs you mentioned. Primadonna is actually the only one that has syllable synced lyrics on Apple Music. The rest are all just line synced (same with the albums you mentioned)
