### ISSUE TITLE
Songs That no longer have lyrics or are just wrong now idk 🤷‍♂️

### ISSUE THREAD

**Issue by LifelikeRylie** [surfbryce/beautiful-lyrics#504]
All these first ones that I will list were all previously karaoke-synced songs: (I'm 99% sure all these were karaoke-synced before at some point but I may have mistaken a couple.... Hopefully not). Link to the folder which I have been putting karaoke-synced songs as I find them in https://open.spotify.com/playlist/4S3CF7KQgoZo5g7pjFQ2M5?si=fbb0028d336d45ae  there are about 2 I didn't add in here cause I was too lazy and all others are fine currently and work blaaaaaaaaaaaaaaaa.

This song from my memory had properly karaoke-synced lyrics but seem to be wayyy off now https://open.spotify.com/track/39LLxExYz6ewLAcYrzQQyP?si=468ac67dbfd34fcb  Levitating

This song used to have properly karaoke-synced (I assume I'm not Japanese so I can't vouch for how well they were synced per word😭)
https://open.spotify.com/track/2XpV9sHBexcNrz0Gyf3l18?si=dc8773b195b44500  ブルーバード

This song was properly karaoke-synced but now displays nothing
https://open.spotify.com/track/2gQPv5jvVPqU2a9HhMNO1v?si=15fab92d02d94d9f  Toxic

This one was also properly karaoke-synced (to my knowledge again I'm not Japanese) but now displays nothing
https://open.spotify.com/track/4Mo0vn7a03pJ19uESUrH5a?si=619acbbac811434b  Kawaikutegomen

This song is basically a copy of the one above same thing
https://open.spotify.com/track/2xBibqkmXJ4NQCe8lJeZco?si=fd0d8a5ddb754806  可愛くてごめん

This song was properly karaoke-synced (again can't fully say not Japanese) but displays nothing now
https://open.spotify.com/track/0pQm5AbAaVy9XrOLf7rgSF?si=6506065215a34b95  スターマーカー

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/6ZYv8ozQzQr1ClAe8dnUZN?si=63a5419cab0f474f  Running Out Of Time

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/6rPO02ozF3bM7NnOV4h6s2?si=696a8cfa43794d76  Despacito - Remix

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof?si=30b457c97c744234  Get Lucky (Radio Edit) [feat. Pharrell Williams and Nile Rodgers]

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/4h4QlmocP3IuwYEj2j14p8?si=df15a9f1221e4f8d  Sunroof

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/5jjZikDrEd0by1o7V3fO4y?si=1ef3d1b8045d4420  overwhelmed

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/3P6OwCX7Ofiaaqtvujb6i5?si=794329e4042548d1  Sixteen Tons

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/5z46NBsndcpz5sdywfdqul?si=e64d7d3d3b014950  Popular - From "Wicked" Original Broadway Cast Recording/2003

This song I'm like 99% sure it was karaoke-synced but it isn't now (I'm prob tripping srry)
https://open.spotify.com/track/43DHLzDkncpby82Po5jlOZ?si=f9d9830121d84679  Don't Stop Me Now - Remastered 2011

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/2wSAWEYUHkt92X4SBAPqZE?si=1d3c5327f6c244c0  Karma Chameleon - Remastered 2002

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/0qMip0B2D4ePEjBJvAtYre?si=e7554f6265c9408d  紅蓮華

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/3ChPJQvs0HvyNy7j3AbBzK?si=69e22b17d473495d  Iden Teitei Meltdown

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/62Lv9WcrfzJqhvYDbilJy3?si=cd05fd1012cb43af  たぶん

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/5aHfGUxRec6c41luxkDqhX?si=67b97f95d71642da  ピースサイン - Peace Sign

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/3dPtXHP0oXQ4HCWHsOA9js?si=176c3712bd554e8e  夜に駆ける

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/6CIQOFf01zQ9qJaqhD6rlH?si=279d87e2c04b4c00  ラビットホール

This song has always been off sync but still karaoke-synced so idk
https://open.spotify.com/track/6nTiIhLmQ3FWhvrGafw2zj?si=4d21325b1d39494f  American Idiot

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/1f6HC5dTviPmopQjYi4uVT?si=bc210a40c4db488d  ポラリス

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/6g93YtKKHU2H1qIqhLIL0Y?si=70ab5aec8ecd4b2a  カタオモイ

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/7HneEBTvTra2CRYsxgMOAi?si=043f9d4aea7544c1  ハルジオン

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/1r9xUipOqoNwggBpENDsvJ?si=5c690d0b03694c8f Enemy (with JID) - from the series Arcane League of Legends

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/1sUdq3kWa9dJXHu3eYOUll?si=392c6461eea64b89  Spooky, Scary Skeletons - Undead Tombstone Remix

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/3QHDivsy0bGD93ecNUb8NS?si=5b1c382f62f74537  He'll Have to Go

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/3nfMOTjl5Ts1GZScRKuQnF?si=dfd2e087feff499e  So Much Better

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/2L9N0zZnd37dwF0clgxMGI?si=c3f725190f754444  ceilings

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/24SUWisv2lYQiB3bVpE1sn?si=120001d4dc884026  Virtual Insanity

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/6sT9MWlJManry3EQwf4V80?si=ed7845ab8b074620  Push It

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/6hTBP6QLwJdxbKyLlLXrGo?si=e201655a80fe4dea  Let's Talk About Sex

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/1PckUlxKqWQs3RlWXVBLw3?si=0e86874a6d494e07  About Damn Time

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/3GPFWYiSU3CVJLqxiRt31n?si=09b0ed9c3b714fa9  ソングオブザデッド

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/2vOAHp8PBBFYqvQUWSoITY?si=12dec8c0a0554e08  インフェルノ

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/0UREO3QWbXJW3gOUXpK1am?si=ef3a780a970c4429  The Fresh Prince of Bel-Air

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/5P8lyudWE7HQxb4ludLbEm?si=67401cf1ee3042a0  恋愛サーキュレーション

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/7FIWs0pqAYbP91WWM0vlTQ?si=5dc399fd88dc42ca  Godzilla (feat. Juice WRLD)

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/3UL6Lzsocv9Ucizgzid2B0?si=1f401ea2871b4a23  We like to Party! (The Vengabus)

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/1ko2lVN0vKGUl9zrU0qSlT?si=f8da1026e695450d  Just the Two of Us (feat. Bill Withers)

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/40NRm1ZLvZpUSCUXAGGZ8J?si=26c9c99994eb4fa5  Kung Fu Fighting

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/0gmbgwZ8iqyMPmXefof8Yf?si=0469bdd6bd364ed0  How You Remind Me

This song was properly karaoke-synced but now again does not display anything (Japanese so can't vouch for how well it was)
https://open.spotify.com/track/4AullfDGRGGp4DHyQqIWdG?si=8169971d53ea41ec  スターマーカー

This song was properly karaoke-synced but now again does not display anything
https://open.spotify.com/track/64esxZlUbri6tBjSjBS1zK?si=897fa02f979747cd  Ain't Got Rhythm

**Comment by surfbryce** [comment]
@LifelikeRylie Checked American Idiot out and it seems like there are two versions of the song, one version is correctly synced but the other is seconds off. I'm assuming they are both using the same lyrics source, will have to look more into it.

**Comment by LifelikeRylie** [comment]
@surfbryce Thanks for starting to look into these, but please don't worry about it much. Overall most work while some don't, and you just updated it after weeks of work. Please take breaks if you need lol don't overwork yourself!

**Comment by ayushmath07** [comment]
yes they indeed are two of them are
So high - doja cat
Khuda jaane- kk
they had it before

**Comment by surfbryce** [comment]
Alright so @LifelikeRylie, I'm going through these and so far it's going great. Karma Chamelon (at least the 2002 remastered version) is slightly out of sync, I can't do anything to fix this at the moment, the problem is that there is a slight pause at the beginning of the song compared to Apple Music (which starts instantly).

I might be able to do something in the future for this, but at the moment, nothing can be done

**Comment by surfbryce** [comment]
Ok so @LifelikeRylie, every single song is fixed!

Only two standouts that I need to keep note for myself, that one version of American Idiot is still out of sync (again, probably wont be able to do anything about that for a while). AND THEN there is Kung Fu Fighting, the version you linked is way out of sync with the new changes but I know this is one that I can fix so I'll be looking at that shortly.

THANK YOU SO MUCH FOR REPORTING ALL OF THESE TO ME!!! Genuinely this helped me fix so much with my algorithm that I'm almost certain with the next patch will actually make a huge difference in how many songs have karaoke lyrics and which do not

**Comment by surfbryce** [comment]
Alright @LifelikeRylie so checked that one version of Kung Fu Fighting again, there's really nothing I can do. Apple Music has a delay on their version but Spotify does not.

Weirdly enough, this is actually the complete opposite of the American Idiot situation, where Apple Music has no pause but Spotify does.

I know somebody who might be able to give me some code so I can fix this on the extension side for any song, but I'll have to investigate with them more on this possibility.

But as far as I'm concerned on what is ***fixable***, we should be good in the next patch! Again, thanks for reporting!

**Comment by LifelikeRylie** [comment]
@surfbryce Thanks so much for taking time to look into these and all!!! I have been busy with finishing up school, sorry I haven't seen these till now. I'm glad I've been able to help even a tiny bit, and I hope you are doing well! (Late night Ramble by me lol)
