### ISSUE TITLE
Still no lyrics page

### ISSUE THREAD

**Issue by jeremybosma** [surfbryce/beautiful-lyrics#506]
The new sidebar appears though

<img width="1407" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/68130184/818d31be-cb34-4586-a0e8-16c862a6de70">

**Comment by surfbryce** [comment]
@jeremybosma Disable the new nav bar in expiremental features, I don't have access to that feature so I unfortunately can't fix it for those that have it, so you have to just disable it: https://github.com/surfbryce/beautiful-lyrics/issues/441#issuecomment-2114137939
