### ISSUE TITLE
Lyrics page blank

### ISSUE THREAD

**Issue by HummerBlaster** [surfbryce/beautiful-lyrics#507]
![Screenshot 2024-05-16 113618](https://github.com/surfbryce/beautiful-lyrics/assets/71684797/774b9452-6656-42c2-9260-9403269a7389)
Update didnt fix the bug for me please help

**Comment by surfbryce** [comment]
@HummerBlaster You have multiple Beautiful Lyric extensions installed, uninstall each one, make sure you are on the latest Spotify and Spicetify. Then reinstall the extension again
