### ISSUE TITLE
Word Per Word Lyrics not found?

### ISSUE THREAD

**Issue by boochySans** [surfbryce/beautiful-lyrics#508]
Hi Again, First things first **congrats on the update!!!** 
I hope there was not much _**pressure**_ getting onto you the past weeks.

https://github.com/surfbryce/beautiful-lyrics/assets/90515114/c62fa6f5-6353-44f5-9b8d-92f978bd9f20

### [**- Issue -**]

So basically, [Lyrics Plus](https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus) is able to find syllable synced  lyrics (Surprisingly, since there was almost NO lyrics that were syllable synced last week) but not Beautiful Lyrics : 

https://github.com/surfbryce/beautiful-lyrics/assets/90515114/4d8ba02f-bc35-43b0-a774-af0cda0573cc

[Lyrics Plus](https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus) Found the lyrics from Musixmatch

**Comment by LoganWolfie** [comment]
There are way too many songs that do this too. Also if it's taking from musixmatch im confused on why there are still songs without lyrics, syncing or bar for bar syncing because people on musixmatch work FAST.

**Comment by AgentMonkey00** [comment]
Just want to add that on the Lyric Plus page, they only state that they get syllable-synced lyrics (on the karaoke tab) from NetEase, not Musixmatch

I will also say though that I'm getting lyrics not syllable-synced on BeautifulLyrics but I am on the Musixmatch mobile app, so there defo might be something there to look into.

**Comment by surfbryce** [comment]
@boochySans Unfortunately, Apple Music does not have this song syllable synced and only line synced, in the future Musixmatch will be considered, but its accuracy is a little dodgy sometimes. So I'll have to look into it more.
