### ISSUE TITLE
Add Support for External Translation Extensions (Romaji/Romaja (Korean/Japan) ex.)

### ISSUE THREAD

**Issue by Yudistiraz** [surfbryce/beautiful-lyrics#51]
I really like the animated lyrics update but, Somehow the romaji / romaja translation for korean and japan lyrics extension stopped working after updating to the newest version

![image](https://github.com/surfbryce/beautiful-lyrics/assets/127931443/7483e7b8-e4a8-4a3a-bbe4-1965acd19837)

**Comment by surfbryce** [comment]
This is due to the change in structure of the lyrics, I’ll take a look into these extensions to see what I can do to support them

**Comment by surfbryce** [comment]
btw @Yudistiraz I am beginning work on Romanization of Korean/Japan/Chinese.

This is how I plan for it to be toggled.

A button with a google translate like icon will be available in every single lyric view. This button will only appear when the primary/dominant language in the song is one of these three languages.

Now the this toggle button will remember its state just like the rest of the toggles. However, how it remembers its state is a little different. Each language that can be romanized (for future languages as well) will have its own state.

This allows you to say have Japanese romanized but Korean not romanized and etc. So let's say you just got the update. You play a song with japanese characters as the lyrics and you want them to be romanized, all you have to do is press the toggle for it and now every set of Japanese lyrics will be romanized from there on out.

Now let's say you come across a Korean song but you don't want those romanized, that's fine because the romanization was only enabled for Japanese. You would have to enable it for Korean as well (same goes for any other support romanized language).

I think this is a super simple but effective to toggle between these modes independently. I will let you know and send screenshots once I've gotten it up and running!

**Comment by Yudistiraz** [comment]
Thank you for your reply! keep up the good work bud

**Comment by ImLunaUwU** [comment]
👀

**Comment by FlimixST** [comment]
I hope this update comes out in the next few days, I really like listening to Japanese tracks and I don't like the look of Spotify lyrics in general with the translation extension <3

**Comment by daniilberkut** [comment]
Still waiting

**Comment by BhaturaGuy** [comment]
+1 for this feature

**Comment by joyfransm** [comment]
+1

**Comment by FlimixST** [comment]
He seems to have forgotten about this topic altogether xD.

**Comment by surfbryce** [comment]
Let's try to keep any unwarranted negativity or sarcastic remarks out of the comments please.

Just to remind everybody this is a free product that I work on during my free-time. I manage 10+ people on my own while also still getting my hands dirty alongside them.

If any of you have the experience to work with the project I am always open to people making pull-requests to get certain features implemented faster and working with you to get that done faster. Otherwise, I would wait patiently or learn how to contribute. Thanks!

**Comment by Joeeeeb5** [comment]
How is it coming along? Any progress?

**Comment by surfbryce** [comment]
@Joeeeeb5 No progress to report. I will send progress when I've made something of mention as I do with any other suggestion that I've already acknowledged. I am extremely busy atm so any development from me is highly unlikely.

**Comment by Joeeeeb5** [comment]
> @Joeeeeb5 No progress to report. I will send progress when I've made something of mention as I do with any other suggestion that I've already acknowledged. I am extremely busy atm so any development from me is highly unlikely for the time being. It's possible I'll get to it sometime this month but no promises.

Thanks for the response and keep up the good work! 🙌

**Comment by surfbryce** [comment]
Alright everyone, I am soft-releasing the Romanization feature in Beautiful Lyrics today. You should get it in update 3.2.0.

I'm not going to announce it officially yet until I get some feedback from you guys (@ImLunaUwU @Joeeeeb5 @daniilberkut @FlimixST @BhaturaGuy @Yudistiraz @joyfransm) and whether or not you guys think it's in a good state or not.

I'll go over how it works here so you guys know what's up.

First off, there are three supported languages for romanization: Chinese, Japanese (includes Hiragana, Katakana, Kana, and Kanji), and Korean.

As I explained earlier, when you toggle Romanization it only affects that one language you are toggling it on. This is so you can have romanization off for Korean but on for Japanese.

Just like any other toggle feature in the extension your toggle saves. So if you want romanization on for Japanese forever, all you have to do is press the button once and that's it. It'll always be there for you if you change your mind as well.

So how do you toggle this feature on/off? Well there are three locations where you can do so.

In the card view:
<img width="349" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/b8fe1ae2-3092-4f2b-9231-99327ea7367f">

In page/cinema view:
<img width="910" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/1929d57c-7667-4488-ba3b-6c34bb290f5e">
<img width="1015" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/0d9f3cac-8974-454d-a3c8-1c6d54fbf264">

And finally, in Fullscreen:
<img width="670" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/76e6712b-4c6b-4236-8b23-3b72ba457859">

As you can see in these screenshots I made sure to show you guys the different toggle states. You will get the script symbol if you haven't turned it on yet. It will be an english character if you have it enabled. I think these two icons are clear enough to indicate the current state.

Really appreciate the patience guys, I got a burst of inspiration today so figured I would just knock it out today. Hope you guys enjoy and I am looking forwards to your feedback/thoughts!

**Comment by FlimixST** [comment]
Wow

**Comment by Yudistiraz** [comment]
> 

> Alright everyone, I am soft-releasing the Romanization feature in Beautiful Lyrics today. You should get it in update 3.2.0.
> 
> I'm not going to announce it officially yet until I get some feedback from you guys (@ImLunaUwU @Joeeeeb5 @daniilberkut @FlimixST @BhaturaGuy @Yudistiraz @joyfransm) and whether or not you guys think it's in a good state or not.
> 
> I'll go over how it works here so you guys know what's up.
> 
> First off, there are three supported languages for romanization: Chinese, Japanese (includes Hiragana, Katakana, Kana, and Kanji), and Korean.
> 
> As I explained earlier, when you toggle Romanization it only affects that one language you are toggling it on. This is so you can have romanization off for Korean but on for Japanese.
> 
> Just like any other toggle feature in the extension your toggle saves. So if you want romanization on for Japanese forever, all you have to do is press the button once and that's it. It'll always be there for you if you change your mind as well.
> 
> So how do you toggle this feature on/off? Well there are three locations where you can do so.
> 
> In the card view: <img alt="image" width="349" src="https://user-images.githubusercontent.com/80861823/269258814-b8fe1ae2-3092-4f2b-9231-99327ea7367f.png">
> 
> In page/cinema view: <img alt="image" width="910" src="https://user-images.githubusercontent.com/80861823/269258934-1929d57c-7667-4488-ba3b-6c34bb290f5e.png"> <img alt="image" width="1015" src="https://user-images.githubusercontent.com/80861823/269258988-0d9f3cac-8974-454d-a3c8-1c6d54fbf264.png">
> 
> And finally, in Fullscreen: <img alt="image" width="670" src="https://user-images.githubusercontent.com/80861823/269259066-76e6712b-4c6b-4236-8b23-3b72ba457859.png">
> 
> As you can see in these screenshots I made sure to show you guys the different toggle states. You will get the script symbol if you haven't turned it on yet. It will be an english character if you have it enabled. I think these two icons are clear enough to indicate the current state.
> 
> Really appreciate the patience guys, I got a burst of inspiration today so figured I would just knock it out today. Hope you guys enjoy and I am looking forwards to your feedback/thoughts!

Oooohhh this is a good news really exctited to try this! Keep on the good work sir 👍

**Comment by surfbryce** [comment]
Alright I've pushed out the update. Will be awaiting all your responses. Thank you!

**Comment by Yudistiraz** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/127931443/cefc44d1-2526-46ee-bf7d-c224d58a442b)
Works perfectly just like i expected it even have the animation, thank you!

**Comment by surfbryce** [comment]
Alright I'm going to close this now, the feature is now in and I'm going to make it official - if you encounter any bugs please report them as a separate issue! And remember avoid duplicates, if there is already a report comment under that one!

Thanks everyone! Glad we got this out!

**Comment by Joeeeeb5** [comment]
Just when this dropped, Spotify started making lyrics premium only. For now, some newly uploaded songs don't have free lyrics available and they're getting to older music too. Check out Sprinter for example. It's one of the affected songs that says "failed to load lyrics"

**Comment by surfbryce** [comment]
@Joeeeeb5 This update only affects Beautiful Lyrics lyric-views by the way. If you are using Spotifys lyric-views the update will not apply to you.

Which Sprinter song are you talking about btw? The first one I checked has synced lyrics not from Spotify. I am aware of lyrics becoming Premium only though and will be working on a way to get Spotify provided lyrics back for everybody. I first will have to assess a lot of different options before this though of course.

**Comment by FlimixST** [comment]
Hello, I recently noticed that some words in the lyrics of songs are not translated correctly or some characters are not translated at all (remain as in the original). For example in the track YAOSOBI - Idol (Japan ver). If you can fix this it would be nice :)
