### ISSUE TITLE
double lyrics icon

### ISSUE THREAD

**Issue by k117-png** [surfbryce/beautiful-lyrics#510]
<img width="146" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/113661499/f92a0503-8335-4119-80b9-d8de1606f3ae">

it shows two lyrics icons both of which are the beautiful lyrics one
the first one works, 2nd one doesn't

**Comment by surfbryce** [comment]
@k117-png This is a marketplace bug, you have to uninstall Beautiful Lyrics, then uninstall it again. If you have it installed locally you also have to remove it there. This isn't an issue with Beautiful Lyrics directly
