### ISSUE TITLE
Lyrics available thru Netease or Musicxmatch not show up in this plugin, but in others

### ISSUE THREAD

**Issue by miccmike** [surfbryce/beautiful-lyrics#512]
IDK if this is an issue you can do anything on, but it seems a lot of songs that spotify and other spice plugins have lyrics for from Netease or Musicxmatch don't show up in beautiful-lyrics. Example being https://open.spotify.com/track/6SKHd2gYjTeGU7SvdTiYDV?si=8385873ef6764538 where the extra mic icon
![image](https://github.com/surfbryce/beautiful-lyrics/assets/112952233/2d2dd709-5897-48b9-878c-b31c03c679bb)n gives me Netease lyrics, but beautiful says there are none. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/112952233/6197f22d-24e7-419a-a71f-041f0a8a2768)

**Comment by surfbryce** [comment]
@miccmike If you could provide the songs this is happening for you on I would be more than happy to look into why

**Comment by miccmike** [comment]
Honestly theres a lot, id say like 50% of my favorites playlist. It would be impossible to list them all, but heres a few
https://open.spotify.com/track/4MYb7NWLwXNDB7bYs3HeX8?si=e452e4c0cb5f4e8f Foghat - Slowride 
https://open.spotify.com/track/18ohWhzbMCynq5QJ68ifkW?si=4135652234ce41e8 Eminem - Criminal
https://open.spotify.com/track/7oUCnXgsxD2jyW4LTg3mNI?si=14df7904115643e8 
https://open.spotify.com/track/6fTt0CH2t0mdeB2N9XFG5r?si=6a9c538161054998 Lil Nas X - Panini
https://open.spotify.com/track/7rCiNfdCXS543KD6anhvJt?si=69ae69da56c6402a Słoń, The Returners - Yeah Bwoy
https://open.spotify.com/track/5e3YOg6fIkP0wD5TyxcHOH?si=0621eb1c322d464a Living Color - Cult of Personality
https://open.spotify.com/track/6KIFja6dizWkI7IpY0vmr8?si=226046e0412249f7 Yes - Roundabout

it really feels random

**Comment by miccmike** [comment]
I would like to add that certain songs, like https://open.spotify.com/track/1dXbAXvUfyXIH4bQsPZK2a?si=1e3b4501f8b4458b have synced lyrics in the default spice client while not being synced in beautiful-lyrics

**Comment by theolensky** [comment]
@surfbryce I wanted to say I'm also experiencing the above issue.

Most songs have lyrics through other plugins but beautiful lyrics is saying no lyrics available 

Most of the songs I'm having issues with are in foreign languages. But there's been a few popular English songs that do not display lyrics. 

It seems very random and temperamental. How can I help you find out what causes this? Is there any error logs I can share?

**Comment by miccmike** [comment]
maybe it would be easier to have this and #523 merged since they seem to be the same issue

**Comment by surfbryce** [comment]
@miccmike Unfortunately Pistol Pistol doesn't have any lyrics on Apple Music.
Criminal also doesn't have any lyrics on Apple Music.

That Lightsabre Blues song actually had its title censored by Apple Music so you gave me an interesting edge-case here.

Yeah Bwoy also doesn't have lyrics on Apple Music.

The rest you linked however that I did not mention will be fixed in the next patch, thank you for reporting!

**Comment by surfbryce** [comment]
@miccmike Also, that do Broni song you listed does not have Synced lyrics on Apple Music, so that one is working as expected.

Also as per issues, its better for me to have separate ones like these since it's easier for me to go through and digest and doesn't become overwhelming
