### ISSUE TITLE
Album covers are ever so slightly transparent.

### ISSUE THREAD

**Issue by DawarTheDastardly** [surfbryce/beautiful-lyrics#513]
There's just the slightest bit of transparency on the album cover in both the fullscreen mode and the sidebar, which causes the dynamic background to sort of bleed into the image. It's not really a massive issue but it is a bit annoying.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/7c05a171-ef7e-4879-80aa-ef5ef14da30b) 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/89464296/5d742d23-9fc7-468b-bf15-22d87a9057e0)

The first image is from the main album page, the second is from the sidebar, as you can see the background does influence the colour of the image slightly.

Aside from the orange, you can see that the white part of the image is a bit darker, and the black of the t shirt is slightly brighter and a bit washed out looking.

**Comment by surfbryce** [comment]
@DawarTheDastardly That is on purpose and a part of the design, it helps it not stand out too much and detract from the rest of the contents. Is this more noticeable to you in the panel view, cinema/fullscreen view, or both?

**Comment by surfbryce** [comment]
I'll have to think about it, I'm not a fan of options for the most part, especially those that are this granular that 99% won't touch; so it's going to be an either or situation here. I'll keep this open for the time being

**Comment by surfbryce** [comment]
@DawarTheDastardly I've made some changes, you'll see how it looks in the next patch.
