### ISSUE TITLE
Fullscreen Artists text animation moving independently

### ISSUE THREAD

**Issue by Alehaaaa** [surfbryce/beautiful-lyrics#515]
https://github.com/surfbryce/beautiful-lyrics/assets/105360073/e492e9bb-b9e3-417b-9cd6-a6a5372816f0

Basically what the title says.
When the artists line is too long to fit, instead of the animation affecting the whole block of artists moving them back and forth, the names are moved independently, which makes them overlap.

**Comment by surfbryce** [comment]
@Alehaaaa This will be fixed in the next patch
