### ISSUE TITLE
Lyrics glitching (glitch effect)

### ISSUE THREAD

**Issue by jeremybosma** [surfbryce/beautiful-lyrics#516]
i assume this is not intended behaviour

https://github.com/surfbryce/beautiful-lyrics/assets/68130184/66aaa7be-1c6f-4830-8770-dbc69d630f37

**Comment by surfbryce** [comment]
@jeremybosma I assume you are on Mac? This isn't an issue with Beautiful Lyrics unfortunately and is just an overall rendering issue with the browser renderer
