### ISSUE TITLE
Fullscreen Information won't load in Countries that Spotify is not allowed in

### ISSUE THREAD

**Issue by bebrriko** [surfbryce/beautiful-lyrics#519]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/a20a932a-1797-4563-b281-2e8110469be4)
Fullscreen doesnt show any info about the song.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/1ba2ea37-ee35-4725-b0eb-1c4605bb8a39)
Cinema mode shows nothing but black screen

**Comment by surfbryce** [comment]
@bebrriko You'll need to disable the new nav bar in experimental features. Check #441 for the post on how to do it (it's at the bottom)

**Comment by bebrriko** [comment]
fullscreen still doesnt show info

**Comment by surfbryce** [comment]
@bebrriko I'll reopen this temporarily

**Comment by bestgio** [comment]
I'm having a similar but slightly different issue. Toggle the Now Playing View basically blocks the UI entirely
![image](https://github.com/surfbryce/beautiful-lyrics/assets/34141617/dd8410d1-3c14-4a64-8450-aa11e73a2f43)

**Comment by bebrriko** [comment]
I enabled vpn and then cinema mode worked well. 
Could be cuz it now asks the spotify for the info, but before it asked the computer?
I'm in Russia.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/562e1b33-89b4-49fd-8fab-856397971fe5)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/613144c5-3ffe-4a8d-9f66-6ac706d59e00)

**Comment by bebrriko** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/2061656d-da9b-4716-a521-8796daee2aec)
Got it to work installing proxy in chromium spotify uses, but it's a client-side fix.

**Comment by surfbryce** [comment]
@bebrriko I'll look into seeing if I can load the track information without using the API link directly.

Just to make sure, everything else in Spotify works right? Like it works normally with your VPN without having to do anything like you did with Beautiful Lyrics?

**Comment by bebrriko** [comment]
@surfbryce 
Yes, it works well. Everything works except for the ads.

**Comment by surfbryce** [comment]
@bebrriko I've changed the way Beautiful Lyrics gets the track information, it should be using the same method that Spotify uses internally, you'll have to let me know when you get to the next patch

**Comment by bebrriko** [comment]
Works perfectly fine!
