### ISSUE TITLE
middle screen still broken.

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#520]
![Screenshot 2024-05-16 at 9 07 25 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/d518ea17-1263-4dc0-b821-501d8235f0bb)

**Comment by bebrriko** [comment]
You'll need to disable the new nav bar in experimental features. Check https://github.com/surfbryce/beautiful-lyrics/issues/441 for the post on how to do it (it's at the bottom)

**Comment by surfbryce** [comment]
@Zyanbob Disable the top nav bar shown at the bottom of #441
