### ISSUE TITLE
Lyrics sometimes opening in cinema instantly

### ISSUE THREAD

**Issue by jeremybosma** [surfbryce/beautiful-lyrics#521]
Also when i close the cinema mode using the X it sometimes makes my right sidebar way wider than i set it.

https://github.com/surfbryce/beautiful-lyrics/assets/68130184/160ae91e-6e5b-4695-b455-7a70a189ef91

**Comment by jeremybosma** [comment]
It's not even sometimes anymore it's now every single time

**Comment by surfbryce** [comment]
@jeremybosma Are you pressing shift down at all? Shifting clicking that lyrics icon will open in Cinema view, might be a bug I ran into earlier on that causes this, but I never ran into it again.

The sidebar issue is not related to Beautiful Lyrics, could possibly be because of going into fullscreen and then leaving fullscreen

**Comment by jeremybosma** [comment]
I'm pretty sure i was not holding shift but it doesn't do it anymore now that i'm sure im not pressing it

**Comment by jeremybosma** [comment]
I will reopen when I'm fully sure im not pressing shift when it happens again

**Comment by jeremybosma** [comment]
Oh boy i knew i wasn't crazy (also i know i have to clean my screen)


https://github.com/surfbryce/beautiful-lyrics/assets/68130184/31ac9ec8-8302-4126-8fbc-8b1ae99458b4

**Comment by surfbryce** [comment]
Yeah like I said I've ran into this myself at one point, couldn't replicate it, might be that the shift trigger just doesn't get released and thinks you are always pressing shift. Javascript doesn't give me a good way to detect this more properly, I've got to rethink how the Cinema mode is entered anyways. But I'll look into seeing if I can make the shift click more stable

**Comment by surfbryce** [comment]
@jeremybosma Forgot to mark this one as being fixed in the next patch, this should be fixed now, recreate the issue if it still happens
