### ISSUE TITLE
Lyrics don't work

### ISSUE THREAD

**Issue by Buotoko** [surfbryce/beautiful-lyrics#522]
Hello, I've mentioned before that lyrics only worked for me when the VPN was turned on, but now they've stopped working altogether. They only work on the side panel. What could be the reason for this?

**Comment by surfbryce** [comment]
@Buotoko Make sure you are on the latest version of Spotify and Spicetify, that you have the topbar navigation turned off (look at the bottom of #441 for this), and that you have fully reinstalled Beautiful Lyrics via Marketplace and are not running a local installation of it.

**Comment by Buotoko** [comment]
@surfbryce I just reinstalled Spotify, and it worked for me. Thank you for this extension it’s very difficult for me to imagine Spotify without it.
