### ISSUE TITLE
Vertigo by u2 doesn't have any lyrics even though it's has lyrics on both spotify base and apple music

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#523]
![Screenshot 2024-05-16 at 9 20 38 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/6f073c0a-1d6f-4cb4-80f3-a9f9c5373055) 
![Screenshot 2024-05-16 at 9 22 34 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/886126b8-adc2-4ba1-b9b0-a9ba43545ac1)
![Screenshot 2024-05-16 at 9 27 43 pm](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/67b24b14-62c1-4b39-9319-5aaea808c29f)

could you do at least give the 10th most popular song from tim cook's favorite band some lyrics?

**Comment by Zyanbob** [comment]
![Screenshot 2024-05-17 090054](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/d40cc117-e885-47c6-9ce9-419e88483e01)
![Screenshot 2024-05-17 090126](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/33072baf-d3fe-4912-8457-c99c31d511d4)
back in time and a real life have just joined the ranks of "Popular songs that have lyrics on everything except beautiful lyrics

**Comment by enzon19** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/89558747/f3a47804-84c8-4988-892f-8895abad05c1)
another one

**Comment by Zyanbob** [comment]
how did this even happen?

**Comment by surfbryce** [comment]
@Zyanbob A lot of changes on the Lyrics Service side and major changes to the algorithm, there were a lot of factors that weren't considered in the best way possible and just overall some parts that could have been done better.

This post: https://github.com/surfbryce/beautiful-lyrics/issues/504
really helped me see how to improve it, it should be pretty near perfect now, in the next update hopefully everybody sees those major improvements

**Comment by Zyanbob** [comment]
when do you think the next patch will be released?

**Comment by surfbryce** [comment]
@Zyanbob I still have to look at #586 and #590, it'll probably be out this Wednesday, could be Tuesday dependent if I can get through those two (and the additional stuff I want to do).

**Comment by Zyanbob** [comment]
man this is a really long Wednesday we've been having for the last 48 hours
