### ISSUE TITLE
a lot of Chinese song doesn't show the lyric

### ISSUE THREAD

**Issue by Kirbytronic** [surfbryce/beautiful-lyrics#524]
![{5F6E8CAB-8234-456f-AA8B-BF5BA60F5F37}](https://github.com/surfbryce/beautiful-lyrics/assets/40047753/80d0d34b-1a18-4940-abf2-81a80e8d9825)
![{233DBC16-ED4E-4ac7-996E-E4583B885731}](https://github.com/surfbryce/beautiful-lyrics/assets/40047753/ba050e94-17b5-4f21-9df8-5fff4c72a0a5)

**Comment by surfbryce** [comment]
@Kirbytronic Should be fixed in the next patch, thank you for reporting!
