### ISSUE TITLE
No Lyrics Showing Up At All

### ISSUE THREAD

**Issue by true-Grand** [surfbryce/beautiful-lyrics#525]
Background is completely blank. Spotify is updated, Spicetify is updated, the extension is also updated. 

<img width="925" alt="Screenshot 2024-05-16 at 9 02 49 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/78011648/79dc5b49-2500-4632-931b-3784c32e1e5a">

**Comment by HarpyCZOFFICIAL** [comment]
Yeah I have the same problem

**Comment by PinguRandom** [comment]
you need update spicetify or spotify i think

**Comment by PinguRandom** [comment]
reinstall spotify and spicetify?

**Comment by bebrriko** [comment]
@true-Grand 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/17c7756d-6f12-4b46-a944-8fac2266bef9)
Set nav bar option to control. (Click on your pfp - experemental settings)

**Comment by capynw** [comment]
@bebrriko thank you, now it's working

**Comment by OverStyleFR** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/94577363/9694338c-d123-40a8-8c37-6109ee5677cd)
Not working with me...

**Comment by uasaad** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/102511630/a1c6a0f7-4e32-4fea-8fc9-ee9cecbe8fb2)
I worked finally!!! after months omg
just installed spotify again as soon as I saw this extension got updated!!

**Comment by surfbryce** [comment]
@m1sscl1ck That is not the latest extension, you are still running the old version!

and what @bebrriko said (thank you for replying with the image, it helps me a lot, I'll have to mention this in the README I'm making for this stuff)

**Comment by true-Grand** [comment]
Nope still doesn't work for me...

**Comment by bebrriko** [comment]
Have you tried reinstalling spicetify and all extensions?
@true-Grand

**Comment by true-Grand** [comment]
Aight I fixed it, but now the album art and text in cinema is awfully gigantic
