### ISSUE TITLE
Lyrics in Now Playing View are not automatically scrolling

### ISSUE THREAD

**Issue by GusRyan487** [surfbryce/beautiful-lyrics#526]
Since the new update came out, none of the lyrics in the Now Playing View automatically scroll with song. Here is an example: 

https://github.com/surfbryce/beautiful-lyrics/assets/36928503/14969485-b0a0-4843-b9a1-46d4e7dd1cc0

___
Spotify for macOS (Apple Silicon)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
Theme: Bloom / darkmono
Extensions: power-bar.js, spotifyGenres.js, quickQueue.js, imageOpener.js, fullAlbumDate.js, songstats.js, fullScreenWrapper.js, beautiful-lyrics.mjs, theme.js
Custom apps: marketplace

**Comment by theolensky** [comment]
I am experiencing this on two different windows PCs, lyrics not scrolling in any view

**Comment by GusRyan487** [comment]
Sometime last week an update fixed this issue, thanks!
