### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by RG007JM** [surfbryce/beautiful-lyrics#527]
I booted up Spotify to find out that the hotfix that heheleo published suddently didn't work cause of a HTTP Error 401, I made my way here to find out that the famous 4.0.0 was finally out, so I updated the extension (deleted the file and replaced it with the new one, Marketplace is rubbish and I will never use it) just to find out that it also suffered from the same issue.
Anyone knows what's happening?
Thanks

![image](https://github.com/surfbryce/beautiful-lyrics/assets/53452689/114b2955-b867-49eb-9272-86bb5ae33eda)

**Comment by theolensky** [comment]
The extension in GitHub is not the newest version

Try getting the newest version from the marketplace.

**Comment by RG007JM** [comment]
> The extension in GitHub is not the newest version
> 
> Try getting the newest version from the marketplace.

I used the one in the Builds/Release folder, which was uploaded about 11 hours ago, when the 4.0.0 update was release, so I really think it's the latest one.

**Comment by RG007JM** [comment]
I unfortunately need to admit that the Marketplace version works fine...
