### ISSUE TITLE
Two icons showing up

### ISSUE THREAD

**Issue by CrazyGreekGR** [surfbryce/beautiful-lyrics#528]
I installed the update for Beautiful Lyrics and now I have one icon that works(new update) and another that doesn't work(old update).

![image](https://github.com/surfbryce/beautiful-lyrics/assets/40838464/3ee7bc9b-7ff6-453b-83d9-917e61004896)

Red is the working one and blue is the broken one

**Comment by prodbyeagle** [comment]
maybe reinstall the ext?

**Comment by surfbryce** [comment]
@CrazyGreekGR you have to FULLY uninstall the extension, on Marketplace you have to uninstall it twice, you also have to uninstall it locally if you installed a local version of the extension!
