### ISSUE TITLE
Lyrics dont work at all

### ISSUE THREAD

**Issue by Sevenare** [surfbryce/beautiful-lyrics#529]
When I press the show lyrics button it doesnt show anything, straight up blank. Everything is up to date and this issue has been happening for a while now it works normally from time to time but only with the side card thing
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170037498/d71ba6dd-c75a-464d-8045-6398406512f6)

**Comment by LayerCZ** [comment]
Similiar thing happening to me, except i see some blurred background moving while i cant access literally anything as the background stays. And i cannot find any way to uninstall this (it stayed after i reinstalled both spicetify and spotify)

**Comment by prodbyeagle** [comment]
uninstall beautiful-lyrics and reinstall it (if you didnt to that)

**Comment by LayerCZ** [comment]
That's the thing I can't find how, I cannot access the marketplace (cuz of the background) and it's nowhere in the files I literally searched everywhere

**Comment by prodbyeagle** [comment]
> Similiar thing happening to me, except i see some blurred background moving while i cant access literally anything as the background stays. And i cannot find any way to uninstall this (it stayed after i reinstalled both spicetify and spotify)

remove the extension in the marketplace 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/124641014/5c7b6a2d-30fd-4bec-81dd-10867e0e9aa5)

**Comment by LayerCZ** [comment]
I CAN'T access the marketplace, all I see is the blurred background no matter on what I click

**Comment by surfbryce** [comment]
@Sevenare You have to FULLY uninstall Beautiful Lyrics, you have to uninstall it TWICE, when you click remove, it'll still be there, uninstall it again.

A good way to do this is to uninstall it and then restart spotify, then reinstall it
