### ISSUE TITLE
Dot is Bugged (view picture)

### ISSUE THREAD

**Issue by prodbyeagle** [surfbryce/beautiful-lyrics#530]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/124641014/fb59e3b5-2445-4000-b941-ad23a2aa4deb)

**Comment by surfbryce** [comment]
@prodbyeagle That is how the dot should be, it acts like a microphone wire

**Comment by prodbyeagle** [comment]
> @prodbyeagle That is how the dot should be, it acts like a microphone wire

Ohhhh
