### ISSUE TITLE
Lyrics are not being synced when track plays on a diffrent device

### ISSUE THREAD

**Issue by xhos** [surfbryce/beautiful-lyrics#531]
When I play tracks on a different device the lyrics just stay at the initial state as if the tracks is paused at 0 seconds. See the screenshot, I'm actually more then halfway through the track, but the lyrics are not. Hope my description is not confusing lol. 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/60789741/d0d83755-7680-4747-867c-a874758a4bbb)

P.S.
Good job on the update, it looks great, loving the cinema view :)

**Comment by surfbryce** [comment]
@xhos Someone told me about this, I changed the way the sync works but apparently that doesn't get updated to the actual stream itself when controlling from another device, I will have to find a way to make all of this work properly

**Comment by HannistHK** [comment]
I streamed to 3 of my devices and three worked flawlessly so far...

**Comment by surfbryce** [comment]
@xhos This will be fixed in the next patch
