### ISSUE TITLE
Friend List is now transparent with Album Cover

### ISSUE THREAD

**Issue by domi-btnr** [surfbryce/beautiful-lyrics#532]
Since the update, the friends list gets transparent with the album cover:

<img width="437" alt="Screenshot 2024-05-16 at 22 22 23" src="https://github.com/surfbryce/beautiful-lyrics/assets/50876016/41b02c5b-d715-424d-a795-b1ed18eb13a5">

---
Spotify for macOS (Apple Silicon)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
Theme: Catppuccin / mocha
Extensions: hidePodcasts.js, QueueTime.js, css-editor.js, fullScreenWrapper.js, scannables.js, queuePanel.js, playing-source.js, copy-lyrics.js, beautiful-lyrics.mjs, theme.js
Custom apps: marketplace, spicetify-library, history-in-sidebar

**Comment by surfbryce** [comment]
@domi-btnr Album Cover is intentional as seen in #513, I'll check out the friends list thing

**Comment by surfbryce** [comment]
@domi-btnr Friends List having transparent items and the Dynamic Background applied will be fixed in the next patch
