### ISSUE TITLE
Big lyrics not working

### ISSUE THREAD

**Issue by pheological** [surfbryce/beautiful-lyrics#533]
when clikcing on the icon/ pressing open lyrics page,its not showing anything
<img width="1680" alt="Screenshot 2024-05-16 at 2 16 28 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/162748832/a7ef76ce-a32d-4e2d-8938-d4b428c80e0f">

**Comment by surfbryce** [comment]
@pheological You have to disable the new top nav bar by going to expiremental settings and searching "nav bar"
