### ISSUE TITLE
Completely breaks my Spotify when using along with SideBar

### ISSUE THREAD

**Issue by Aki65RU** [surfbryce/beautiful-lyrics#535]
I'm not sure how else this I could explain this, It just breaks itself when im using side bar. Weird thing is I was using this perfectly fine for like a month now along with the Default Dynamic theme by JulienMaille but now even on its own it doesnt work. Ill attach a vid for clearer explanation.
  (sorry for the quality GitHub required me to heavily compress the video)

https://github.com/surfbryce/beautiful-lyrics/assets/129411243/e3f8a743-9846-4cfb-8479-a24891ac2738

**Comment by surfbryce** [comment]
@Aki65RU Make sure you are on the latest version of Spotify/Spicetify, there is no backwards compatibility with older versions

**Comment by Aki65RU** [comment]
thats odd tho it was working perfectly fine for a whole month or more..
