### ISSUE TITLE
Dynamic background covers everything (including other songs and menus

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#536]
![Screenshot 2024-05-17 080909](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/91c45f17-2779-4264-bfda-7f7e2cf0b5ff)

**Comment by surfbryce** [comment]
@Zyanbob Make sure you are on the latest version of Spotify/Spicetify, if you think you are, send the version numbers to me and I'll make sure

**Comment by Zyanbob** [comment]
just updated it and now it crashes

**Comment by surfbryce** [comment]
@Zyanbob as in? Spotify crashes or?

**Comment by Zyanbob** [comment]
everything seems to be fine now
