### ISSUE TITLE
Compability issue?

### ISSUE THREAD

**Issue by vilewired** [surfbryce/beautiful-lyrics#539]
I have no idea why this is happening, I'm using the [spicetify dynamic theme](https://github.com/JulienMaille/spicetify-dynamic-theme) and after updating beautiful lyrics this happened..?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/85312115/c010c736-6f3b-4ec7-9ab3-52e0ddc03115)

the theme alone without the extension works fine, I also just checked if the extension works fine without the theme
![image.png](https://cdn.hoeless.com/img/20240517034456.png)
and it kind of works fine, but as soon as I turn on the now playing button, it again looks like this:
![image.png](https://cdn.hoeless.com/img/20240517034706.png)

**Comment by surfbryce** [comment]
@vilewired Update both spotify/spicetify to the latest version and disable global nav bar in expiremental features

**Comment by vilewired** [comment]
Doesn't seem like I have the option to fully disable it ![image.png](https://cdn.hoeless.com/img/20240517045836.png)
Spicetify is up to date, my spotify is managed through the AUR, so I hope it should be the latest version available. Any other ideas?
