### ISSUE TITLE
Vietnamese text displayed in wrong format

### ISSUE THREAD

**Issue by snowsharkt** [surfbryce/beautiful-lyrics#54]
In Viet Nam, we align text from left to right, like in English. But here it looks like in Arab. Hope you would fix that.
![2023-07-03_212111](https://github.com/surfbryce/beautiful-lyrics/assets/91777904/04046fe8-9aa4-4525-8866-83f526edbb04)
This is what it supposed to be
![2023-07-03_212127](https://github.com/surfbryce/beautiful-lyrics/assets/91777904/30de6da1-a680-41e9-a2c3-94af17cb5846)

**Comment by surfbryce** [comment]
Alright, I just pushed out a fix that should have better detection for Right-To-Left languages so that it doesn't cause other languages to be incorrectly marked as such. Please let me know if this fixes it for you!

**Comment by snowsharkt** [comment]
Thank you, it works perfectly now!
