### ISSUE TITLE
Wrong/Different UI and no clue how to switch it

### ISSUE THREAD

**Issue by cayndy** [surfbryce/beautiful-lyrics#540]
Hello! I was using beautiful lyrics before but had to reinstall spotify + spicetify and when I downloaded the extension again this is what my ui looks like instead of the one showed in the preview. Does anyone have any clue on how to change it to match the one in the preview? I personally love the other ui and I'd much rather would continue using it.

I currently have Shuffle+, Beautiful Lyrics, Oneko and Cat-Jam Synced if it matters.

Current:
![Screenshot (437)](https://github.com/surfbryce/beautiful-lyrics/assets/136207857/c6dc556a-fc67-4710-8d21-23dd4960d394)

What I want:
![Screenshot (435)](https://github.com/surfbryce/beautiful-lyrics/assets/136207857/a9457540-6433-4ba2-9bf2-26a149364b9a)

**Comment by rawniee** [comment]
ur current ui is the new ui and i think theres no way to revert to the old one

**Comment by surfbryce** [comment]
@cayndy The older UI will not be returning, the new UI is considerably much cleaner and better to look at. IF you have suggestions for it please feel free to make a separate request, but there is no way to revert and there never will be.
