### ISSUE TITLE
Beautiful Lyrics is not working even after reinstalling the extension

### ISSUE THREAD

**Issue by Timrap2** [surfbryce/beautiful-lyrics#544]
help pls
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153293433/9b88c8e9-9f6f-468f-b551-5eb02b8c7c98)

**Comment by Abdullahon2006** [comment]
how did u fix that?

**Comment by Abdullahon2006** [comment]
I mean mine isn't still working so I would like learn why?
