### ISSUE TITLE
No beautiful lyrics button 

### ISSUE THREAD

**Issue by StorFaxe** [surfbryce/beautiful-lyrics#547]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166634707/df74a2a4-ae0d-4284-8ece-f1a341a0e95a)

**Comment by IamFastre** [comment]
have you tried reinstalling it?
I had that same issue after updating and seemed to have fixed it, also do `spicetify auto`

**Comment by Guonejo** [comment]
Same problem here, I tried reinstalling the app and Spicetify, and nothing. Any solution?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/82884497/0537aec6-ed99-4715-921e-d9e33da13a53)

**Comment by 0V3RL3G4L** [comment]
Solves it by changing the navegation experimental feature , search "nav" feature and switch to "control", it will restart Spotify and the lyrics button should appear.

**Comment by Guonejo** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/82884497/08f2b09a-375b-45e3-b944-cd76063ce21d)


I was able to make the app reappear, but it doesn't follow the song, it did before.

**Comment by ayyneya** [comment]
Same issue here, using mac OS. Updated, reinstalled, already had the navbar thing at Control, changed it back and forth either way, no luck. Simply no button.

**Comment by Lolen10** [comment]
I possibly found a workarround.
The button also disappeared for me ( after updating spicetify and spotify it still wouldn't appear).
Then I manually updated the spicetify-marketplace and then the button appeared again (you still need to set the experimental setting mentioned by @0V3RL3G4L , otherwise it still appears but it won't show any lyrics)

**Comment by ayyneya** [comment]
> I possibly found a workaround. The button also disappeared for me ( after updating spicetify and spotify it still wouldn't appear). Then I [manually updated](https://github.com/spicetify/spicetify-marketplace/wiki/Installation#manual-install-recommended) the spicetify-marketplace and then the button appeared again (you still need to set the experimental setting mentioned by @0V3RL3G4L , otherwise it still appears but it won't show any lyrics)
> 
> edit: fixed typo

Tysm, that seemed to have worked. It seems a TON of lyrics are missing though. Idk if that's a bug or intentional. Like no surprises from radiohead.

**Comment by surfbryce** [comment]
@StorFaxe Recreate this bug report following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version
