### ISSUE TITLE
Lesser songs are having lyrics right now

### ISSUE THREAD

**Issue by IamFastre** [surfbryce/beautiful-lyrics#548]
Have you changed your lyrics provider?
Some songs that I recall having lyrics with the plugin now do not.

**Comment by brokenkie** [comment]
Facing the same issue here. Some lyrics that I used to have aren't there anymore, and even lyrics which vanilla Spotify/browser Spotify can pull for me aren't there when I use Beautiful lyrics.

**Comment by Monoverde888** [comment]
yeah the same is happening to me, some persona songs used to have lyrics but now dont.

**Comment by surfbryce** [comment]
@IamFastre Lyrics Provider hasn't changed, the algorithm I use has, there are changes being made to refine it more and more; but remake the issue request with exact songs, I can't fix stuff if you don't tell me what needs fixing
