### ISSUE TITLE
problem to open lyrics page?

### ISSUE THREAD

**Issue by flozxx** [surfbryce/beautiful-lyrics#550]
i already redownload the spotify and do clean install on spotify and spicetify but lyrics page just blank, any idea how to fix it?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/142338999/c42c1409-9cae-457a-b267-eda432d802e9)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/142338999/099053ad-16c4-4bb7-9bdd-9933a2711115)

lyrics gone when i press the lyrics page
![image](https://github.com/surfbryce/beautiful-lyrics/assets/142338999/3afdbdcd-915f-4e6e-94f5-46c2aad02191)

**Comment by Rudani** [comment]
same but mine doesnt even have the button, worked fine yesterday and i havent updated spotify nor nothin, running on 1.2.32.997 rn

**Comment by ethanjaeda** [comment]
girl me tooo im annoyed

**Comment by bebrriko** [comment]
Try this:

Set nav bar option to control. (Click on your pfp - experemental settings)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/122726991/17c7756d-6f12-4b46-a944-8fac2266bef9)

**Comment by Rudani** [comment]
mine already was like that, did not fix :(

**Comment by HHomadi** [comment]
> same but mine doesnt even have the button, worked fine yesterday and i havent updated spotify nor nothin, running on 1.2.32.997 rn

reinstall the extension?

**Comment by Rudani** [comment]
ofc i already tried that
and yea doesnt work

**Comment by NormTurtle** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/108952834/edc9adf5-1040-4d0a-8643-e421c20a3bdd)
here mine is weird too.
no lyric at all

**Comment by LoganWolfie** [comment]
> same but mine doesnt even have the button, worked fine yesterday and i havent updated spotify nor nothin, running on 1.2.32.997 rn

Restart spotify.

**Comment by flozxx** [comment]
> Try this:
> 
> Set nav bar option to control. (Click on your pfp - experemental settings) ![image](https://private-user-images.githubusercontent.com/122726991/331293617-17c7756d-6f12-4b46-a944-8fac2266bef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjEyNjIsIm5iZiI6MTcxNjAyMDk2MiwicGF0aCI6Ii8xMjI3MjY5OTEvMzMxMjkzNjE3LTE3Yzc3NTZkLTZmMTItNGI0Ni1hOTQ0LThmYWMyMjY2YmVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwODI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmMyMGRmYjc2NmJkMWFmY2IwZGU3ZDljMzY5ZDk2MTAxOTJkN2VlMDkzYjlmMDUwMTY1ZDI4NzA5YzA5M2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m_m7pSVtd2OhIcWpELvXlPf3ubfqRcFPJ_jd4kMtpxg)

whoa this works! thanks man!

**Comment by flozxx** [comment]
> ![image](https://private-user-images.githubusercontent.com/108952834/331736516-edc9adf5-1040-4d0a-8643-e421c20a3bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjEyNjIsIm5iZiI6MTcxNjAyMDk2MiwicGF0aCI6Ii8xMDg5NTI4MzQvMzMxNzM2NTE2LWVkYzlhZGY1LTEwNDAtNGQwYS04NjQzLWU0MjFjMjBhM2JkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwODI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzNmMjcxYThiYWQxMzI5OGQzMWQ1NjQ3ZWI0ZjY4NGJhMTIyY2Y2M2FjOTk4YTc3NjEwYTU4ZGVlMTQ4NDQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.94NhdnTCNAz_rIzvanXjL-F_Zy6NNmg2whiN6JDcL6E) here mine is weird too. no lyric at all

what theme you using?

**Comment by stebo02** [comment]
I have the same issue regardless of what theme I'm using...

> Try this:
> 
> Set nav bar option to control. (Click on your pfp - experemental settings) ![image](https://private-user-images.githubusercontent.com/122726991/331293617-17c7756d-6f12-4b46-a944-8fac2266bef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY1MjIsIm5iZiI6MTcxNjAyNjIyMiwicGF0aCI6Ii8xMjI3MjY5OTEvMzMxMjkzNjE3LTE3Yzc3NTZkLTZmMTItNGI0Ni1hOTQ0LThmYWMyMjY2YmVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwOTU3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTZjMDJkMmM3YzA0NmIxMzUyMzQzMTliMTk5MTBiNmJmMGQ3YTI3NWY0MjFiYzlmM2ZlNWRmYTVkODVhZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tDZMEKjA1ZAsvauL82kNVdYm1NlEo7V_c17QhO8l3kw)

That experimental feature isn't showing up for me

**Comment by NormTurtle** [comment]
> what theme you using?

none @flozxx

**Comment by flozxx** [comment]
> > what theme you using?
> 
> none @flozxx

whoa but how can u make the background full like that? 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/142338999/611d37a8-7b02-4168-9fd8-9d12902dc60d)
and how to enable this 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/142338999/4d93b97a-0a23-444f-9fad-6df282d3dd76)

**Comment by EndCod3r** [comment]
New version is out so update and it should be fixed.

**Comment by surfbryce** [comment]
@flozxx Recreate this bug-report following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version
