### ISSUE TITLE
Theme Default Dynamic Issues

### ISSUE THREAD

**Issue by PrimeMr67** [surfbryce/beautiful-lyrics#552]
FAQ said to make an issue if I'm using a theme. As of right now, "Default Dynamic" does not work with Beautiful Lyrics. 

Also, this may be related to the theme, but I have the extension installed and neither the button nor the side-car panel work. It's just Spotify's default lyrics. Yes, I am up to date on everything.

**Comment by surfbryce** [comment]
@PrimeMr67 Not an issue with Default Dynamic
