### ISSUE TITLE
Can't acces anything, only see the moving blurred background

### ISSUE THREAD

**Issue by LayerCZ** [surfbryce/beautiful-lyrics#553]
After installing the plugin, no matter what i do or what i click on i only see the blurred moving background thingy. Makes it impossible to use the app. Tried reinstalling everything bunch of times
![image](https://github.com/surfbryce/beautiful-lyrics/assets/70105041/4ede5c1c-fec2-4ede-ab90-ca38d1773806)

**Comment by garryspins** [comment]
Duplicate #541

**Comment by surfbryce** [comment]
Duplicate of #541
