### ISSUE TITLE
Bad FPS

### ISSUE THREAD

**Issue by pheological** [surfbryce/beautiful-lyrics#554]
before, when i used beautifulLyrics, the fps was fine, and it worked fine. Now, when i use it, its so delayed and the fps is like 2. I have an m1 macbook air, so i dont think its a performance issue.

**Comment by pheological** [comment]
also, this issue only applies to fullscreen mode, when its small, it works fine.

**Comment by surfbryce** [comment]
Duplicate of existing performance issues
