### ISSUE TITLE
Extension no longer appears

### ISSUE THREAD

**Issue by Guonejo** [surfbryce/beautiful-lyrics#555]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/82884497/9baae12c-4123-4f11-8c23-2a91edf1673d)

Suddenly the app disappeared. I tried reinstalling the extension and Spicetify (from powershell) and it didn't work.

**Comment by 0V3RL3G4L** [comment]
I reinstall the extension it does not appear, I enter full screen and the lyrics appears and then exiting full screen the extension also appears. Also it solves it by changing the nav experimental feature, search "nav" feature and change to "control" option.

**Comment by LoganWolfie** [comment]
Just restart spotify and it will show back up

**Comment by ayyneya** [comment]
> Just restart spotify and it will show back up

Obviously people do that, it doesn't fix it.

**Comment by surfbryce** [comment]
@Guonejo Recreate this bug-report following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

**Comment by sTiKyt** [comment]
Dude, it just went away
