### ISSUE TITLE
No Smooth Scrolling

### ISSUE THREAD

**Issue by Yoruiopz** [surfbryce/beautiful-lyrics#556]
The extension does not feature smooth scrolling in between lyrics both in the side panel and in the full lyric window.

**Comment by surfbryce** [comment]
@Yoruiopz It does smooth-scroll but it doesn't do it like Apple Music does. There is already an issue requesting similar staggered scrolling effect.

**Comment by Yoruiopz** [comment]
> @Yoruiopz It does smooth-scroll but it doesn't do it like Apple Music does. There is already an issue requesting similar staggered scrolling effect.

There is absolutely no scroll animation on my client, both on the lyric page and on the side bar. I wasn't talking about apple music or any other client either.
