### ISSUE TITLE
Looks really werid if song has canvas video.

### ISSUE THREAD

**Issue by yodaluca23** [surfbryce/beautiful-lyrics#558]
Don't get me wrong, I love the background album art blur gradient thingy, but it tries to do it when the canvas is playing, and it looks really weird... Add some boarders or something, please.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/67206487/3e3bca48-4513-49a3-bcad-05475c580ba2)

**Comment by surfbryce** [comment]
@yodaluca23 Canvas is not supported, but it seems like most people don't know how to turn it off, so I'll make it so it gets force disabled

**Comment by yodaluca23** [comment]
> @yodaluca23 Canvas is not supported, but it seems like most people don't know how to turn it off, so I'll make it so it gets force disabled

No, I like the canvas, I would just like it to have some borders, so the song title isn't just in between the two.

**Comment by surfbryce** [comment]
@yodaluca23 I'll work on something, borders are not the right solution here, if anything, I'll try to see if I can get the two to merge into each other.

**Comment by surfbryce** [comment]
@yodaluca23 It will now be officially supported in the next patch!

<img width="292" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/f828beaf-5df2-4a4c-96d1-a5829bd58290">
