### ISSUE TITLE
[Feature Request] Automatically toggle lyrics dropdown on sidebar.

### ISSUE THREAD

**Issue by yodaluca23** [surfbryce/beautiful-lyrics#559]
Could we have an option to automatically click the "show lyrics" button? I hate having to click it on every song...
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67206487/7fca5dd6-7d8b-471d-8a90-124160569d5c)

**Comment by surfbryce** [comment]
@yodaluca23 If you click it once it should remember that option for you, is it not doing that for you?

**Comment by yodaluca23** [comment]
> @yodaluca23 If you click it once it should remember that option for you, is it not doing that for you?

Ah it does, it must have been reset from the update, and I didn't realize, thank you!
