### ISSUE TITLE
more than half of the songs have lost their lyrics and the sidebar and fullscreen works only the main screen doesnt work

### ISSUE THREAD

**Issue by AFcoder10** [surfbryce/beautiful-lyrics#560]
pls fix this issue cant live without the extension . ive been waiting for this from the last month and a new issue is there. try to fix it by your schedule. thank you!

**Comment by lefretti** [comment]
When I noticed this too along with the beautiful lyrics icon being gone I just kind of figured the developer could've removed them from use so that they can fix the bugs and add more accurate lyrics to more songs. I obviously could be wrong but this is what I took from it.

**Comment by surfbryce** [comment]
@AFcoder10 Make a new issue with the exact songs, I can't fix anything if I don't know what is not working for you
