### ISSUE TITLE
sync and effect not working 

### ISSUE THREAD

**Issue by Asher-1971** [surfbryce/beautiful-lyrics#561]
![Screenshot 2024-05-18 142039](https://github.com/surfbryce/beautiful-lyrics/assets/127295261/e4889969-3a35-4f3d-8ef2-6ae8764e5d14)

i cant see effects and the song is not in sync

**Comment by surfbryce** [comment]
@Asher-1971 This song doesn't have synced lyrics of any kind on Apple Music
