### ISSUE TITLE
No lyrics on "Memories of You -Reload-" on album Persona 3 Reload Original Soundtrack

### ISSUE THREAD

**Issue by Monoverde888** [surfbryce/beautiful-lyrics#567]
[song link](https://open.spotify.com/track/3R0XM0PaKh2R7WYF8UJYe0?si=95d6ce27e2384034) some other songs from the album like it’s going down now and full moon full life also used to have lyrics but with the update they no longer have any.

**Comment by surfbryce** [comment]
@Monoverde888 This should be fixed in the next patch, thank you so much for reporting!
