### ISSUE TITLE
Idk, it doesn't work anymore

### ISSUE THREAD

**Issue by kishichiki** [surfbryce/beautiful-lyrics#568]
Fresh version of spotify, but I have this instead of lyrics 
![Untitled](https://github.com/surfbryce/beautiful-lyrics/assets/143482473/aabd6765-38fe-406a-9840-4e9d7d602be0)
what to do?

**Comment by EndCod3r** [comment]
New version is out so update, so it should be fixed.

**Comment by surfbryce** [comment]
@EndCod3r There is no new version, it’s just a release tag, the 4.0.0 version has been out for days (like I said in the release, a patch is coming soon)

**Comment by kishichiki** [comment]
> New version is out so update, so it should be fixed.

hi, idk how to update this extension, but I tried to remove it and reinstall but nothing changed... same as screenshot above :/

**Comment by surfbryce** [comment]
@kishichiki Recreate this bug report following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version
