### ISSUE TITLE
Nothing but grey / blank screen (4.0.0)

### ISSUE THREAD

**Issue by Msprg** [surfbryce/beautiful-lyrics#570]
![obrázok](https://github.com/surfbryce/beautiful-lyrics/assets/18015488/e529267d-a750-47d8-bfed-69b503323999)

Any tips?

**Comment by lopyo-art** [comment]
make sure you have the latest Spotify and spicetify upgrade. (nice Neko btw)

**Comment by Lolen10** [comment]
Go into experimental settings and search for "nav". 
Then set the following setting to control:

![Screenshot 2024-05-19 111203](https://github.com/surfbryce/beautiful-lyrics/assets/24716055/eaf831a1-a721-40a1-96f0-a4bd6036a15b)

Then it should work again.

**Comment by Equinoxx4978** [comment]
Same problem for me and I have the global nav set to control too
New release new bugs ig 🤷‍♂️

**Comment by i3Lone** [comment]
same issue for me, even tho i think spotify verion has nothing to do with it beacouse i locked mine to never update and still i have the same problem so spotify isint the problem here, probly the update

**Comment by Msprg** [comment]
> Go into experimental settings and search for "nav". Then set the following setting to control:
> 
> ![Screenshot 2024-05-19 111203](https://private-user-images.githubusercontent.com/24716055/331860223-eaf831a1-a721-40a1-96f0-a4bd6036a15b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjIzOTksIm5iZiI6MTcxNjEyMjA5OSwicGF0aCI6Ii8yNDcxNjA1NS8zMzE4NjAyMjMtZWFmODMxYTEtYTcyMS00MGExLTk2ZjAtYTRiZDYwMzZhMTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMzQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDZkYTU3ZDAxNDI5OGMxMTMxOWM3MWMzM2Y4YjA5MjA4ZjFlMTNiMGMwMmQ1ZGIxNzlmYTc1YWYzMWE3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhRyYt9NtNPRokoHoxdHcWD4dTFoFgDOGwMvW02yfiY)
> 
> Then it should work again. (At least it did fix it for me)

I don't have this option in my client. I would like to avoid upgrading as it breaks soggfy right now.

**Comment by surfbryce** [comment]
@Msprg Recreate this bug report following these instructions: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version
