### ISSUE TITLE
Update from 4.0.0 breaks spotify's UI

### ISSUE THREAD

**Issue by Harleythetech** [surfbryce/beautiful-lyrics#571]
So before i updated to V4 i was on the release from April 2024 that one worked well until it didn't work anymore. whenever i go full screen i only see the original player screen. Now updating to V4 fixes things except the UI on the homescreen which looks like this:

Note: Im using an older version of spotify where plugins still works properly
![image](https://github.com/surfbryce/beautiful-lyrics/assets/51787264/c3b99930-d17f-45f5-baa1-36cb718ec0f1)

**Comment by surfbryce** [comment]
Duplicate of #502
