### ISSUE TITLE
song lyrics not available 

### ISSUE THREAD

**Issue by itsjoexd** [surfbryce/beautiful-lyrics#572]
![Spotify Premium 5_19_2024 12_46_52 PM](https://github.com/surfbryce/beautiful-lyrics/assets/170227291/b64f2bc5-c00b-45c0-b42d-649192f96bc1)
![Spotify Premium 5_19_2024 12_46_38 PM](https://github.com/surfbryce/beautiful-lyrics/assets/170227291/33ba036d-4efc-4f17-8210-352b5b15f716)
![Spotify Premium 5_19_2024 12_46_31 PM](https://github.com/surfbryce/beautiful-lyrics/assets/170227291/3489bfe4-90e4-47f9-8d41-8b41e4c6edbc)
![New Issue · surfbryce_beautiful-lyrics - Opera 5_19_2024 1_45_50 PM](https://github.com/surfbryce/beautiful-lyrics/assets/170227291/c288c227-6ee5-46ea-ae00-2d974c6aae09)

**Comment by Lolen10** [comment]
I have this problem too. Not with all songs, but lots of songs which should have lyrics (e.g. Alone - Alan Walker) just doesn't.

**Comment by catb0x** [comment]
i think it might be related w tencent but idk if beautiful lyrics stopped getting lyrics from tencent... might also have to do w musixmatch but im not sure

**Comment by catb0x** [comment]
i think it might be related w netease but idk if beautiful lyrics stopped getting lyrics from netease... might also have to do w musixmatch but im not sure

**Comment by itsjoexd** [comment]
whatever was being used previously worked perfectly fine, musixmatch didnt give lyrics to the first song, but before the update beautiful lyrics worked on the first song.

**Comment by ayushmath07** [comment]
Noticed the same thing most songs lost their lyrics after the update, how can i install the old one? and how long would it take to fix this ig its a really minor bug

**Comment by surfbryce** [comment]
@itsjoexd "Taunt - Acoustic" does not have lyrics on Apple Music.

The rest should be fixed though in the next patch, thank you so much!

**Comment by dani1113** [comment]
Just as a suggestion, I downgraded the spotify version and the extension works perfectly. It can be a temporary solution until next patch get released. =)
BTW, I also blocked spotify auto updates, its so annying to get an update which even sometimes doesnt seem that change anyhting (atleast on the frontend) and that suddenly every extension starts failing.

This is what I used to downgrade: https://github.com/amd64fox/Rollback-Spotify
You can search all the versions in the internet, the last one before lyrics started missing and the one that works for me is: 1.2.37.701
Also, my Spicetify version is: 2.36.11
