### ISSUE TITLE
fullscreen doesnt work

### ISSUE THREAD

**Issue by typakon4** [surfbryce/beautiful-lyrics#573]
fullscreen does not work in any song, does not load the cover and song title, but the lyrics are displayed(the problem is not the 21:9 aspect ratio, 16:9 has the same problem)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/100871491/dd446239-b27a-4692-9a81-0462ac204861) 21:9
![image](https://github.com/surfbryce/beautiful-lyrics/assets/100871491/65bb1f69-4c64-47e3-baf0-29bf10cc75af) 16:9

**Comment by surfbryce** [comment]
@typakon4 Recreate this issue following the instructions here: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version
