### ISSUE TITLE
Beautiful Lyrics keep overriding themes on the Friend Activity tab 

### ISSUE THREAD

**Issue by itsthea1** [surfbryce/beautiful-lyrics#578]
I don't know if this is an indented feature but, the extension keeps overriding any theme I do install with the cover mashed up colors and if it is a indented feature is there any way to remove/turn it off? If not having that added would be appreciated since I am literally going crazy 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170280139/9fb66428-1ed2-48d8-ac9b-2a995729d8e7)

**Comment by surfbryce** [comment]
@itsthea1 It's only supposed to be applied to the "Now Playing" view, this will be fixed in the next patch

**Comment by surfbryce** [comment]
@itsthea1 This will be fixed in the next patch and not apply to any panel that isn't  the "Now Playing" view
