### ISSUE TITLE
New update doesnt show lyrics

### ISSUE THREAD

**Issue by RamDz** [surfbryce/beautiful-lyrics#579]
I installed the latest version of spotify and the extension is not loading lyrics at all
![image](https://github.com/surfbryce/beautiful-lyrics/assets/37937794/960b3264-5aa1-46a6-a881-0cc6b5dc88ad)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/37937794/1611cd59-b6de-481a-a268-0a2bae8b1631)

and the theme isnt there anymore

**Comment by surfbryce** [comment]
@RamDz Please follow the instructions before making the bug-report, you will be deleted every time until you do so.
