### ISSUE TITLE
Missing lyrics in the right sidebar

### ISSUE THREAD

**Issue by AylenSK** [surfbryce/beautiful-lyrics#581]
Hi.

Since the last update, I have to open fullscreen mode in order to see the lyrics, otherway they don't appear in the right sidebar.
![Bug lyrics spotify 1](https://github.com/surfbryce/beautiful-lyrics/assets/170281615/f563254a-a699-4331-b93b-942592b00c40)
![Bug lyrics spotify 2](https://github.com/surfbryce/beautiful-lyrics/assets/170281615/af9ce91e-7f72-4dad-b140-ded31de997e6)

**Comment by surfbryce** [comment]
@AylenSK PLEASE FOLLOW THE INSTRUCTIONS TO POST BUG-REPORTS, you will be deleted every time if you do not
