### ISSUE TITLE
lyrics Animations

### ISSUE THREAD

**Issue by Kouki002** [surfbryce/beautiful-lyrics#582]
Ok So For MacBook And Other Laptop Who Has **120hz Refresh Rate** (Even 60hz Too) Display The **Lyrics Animation Feel Leggy** ! Its Beautiful And Leggy At Same Time 🥲 You Know How Annoying That You Find Great Thing That Its So Amazing But Not Well Refine ( Its So Annoying Its Such A Great Extension But Legs Smoothness 🫥) **Please Refine This Extension As Soon As Possible** And Bring The Great Experience Out Of It !!! I'm Developer Too If You Need Any Suggestion Or Help Let Me Know !!!

**Comment by surfbryce** [comment]
Duplicate of existing issues on this matter

**Comment by Kouki002** [comment]
So Are You Going To Solve This Or Not ??
