### ISSUE TITLE
All songs lyrics just have lyrics blank

### ISSUE THREAD

**Issue by Reksely** [surfbryce/beautiful-lyrics#584]
<img width="1512" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/69013710/37fce4b6-b6f9-458e-968b-bf5a3407660e">

spotify version: 1.2.37.701
spicetify version: 2.36.11
Spotify for macOS (Apple Silicon): Sonoma 14.2.1

**Comment by surfbryce** [comment]
@Reksely PLEASE FOLLOW THE INSTRUCTIONS WHEN MAKING A BUG REPORT

**Comment by Reksely** [comment]
i did lmao
