### ISSUE TITLE
No Lyrics on almost ALL Japanese songs that were named by japanese or chinese character

### ISSUE THREAD

**Issue by ZoydePvP** [surfbryce/beautiful-lyrics#585]
Almost all japanese songs that were named by japanese or chinese character have no lyrics, while the songs that were named by english letter have lyrics.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/63500842/183dc162-597e-4e0b-a413-770e0748677f)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/63500842/3e5a4ba5-460e-4520-a912-76fe08d6560d)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/63500842/c0e3fe91-f7e6-419e-81cf-e6f1d202793a)

**Comment by surfbryce** [comment]
@ZoydePvP PLEASE FOLLOW THE INSTRUCTIONS WHEN MAKING A BUG REPORT
