### ISSUE TITLE
[Big Batch] Missing Lyrics and Not Best Synced Lyrics

### ISSUE THREAD

**Issue by iPixelGalaxy** [surfbryce/beautiful-lyrics#586]
Playlist of songs:
https://open.spotify.com/playlist/2Sdz4CQsMsEcDNSIu9j6O3

Missing Lyrics:
Don't Let Me Down - The Chainsmokers: https://open.spotify.com/track/1i1fxkWeaMmKEB4T7zqbzK
Sacrifice Tomorrow - Alec Benjamin: https://open.spotify.com/track/5H4y5thHDJUAxwiclrSXc1
Beauty and a Beat - Justin Bieber: https://open.spotify.com/track/190jyVPHYjAqEaOGmMzdyk
Paper Crown - Alec Benjamin: https://open.spotify.com/track/2fB0qwP98V9Yrv3mgR6IJJ
It's Okay If You Forget Me - Astrid S: https://open.spotify.com/track/312zSwwbPU7C3sTmro4Wx9
Geronimo - Sheppard: https://open.spotify.com/track/0qt5f5EL92o8Snzopsv0en
Life is a Highway - Rascal Flatts: https://open.spotify.com/track/5gB2IrxOCX2j9bMnHKP38i
Letting Go - Yonetro: https://open.spotify.com/track/6myqRcz9EPifaFQ6fAZ8cs (lyrics aren't synced on musixmatch, I'll probably do that at some point)
STAY - The Kid LAROI, Justin Bieber: https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20
Weapon - Grant: https://open.spotify.com/track/2rK7ZlIdlCetWZbQ6PD1e0
One - Sleeping At Last: https://open.spotify.com/track/76nlq5gomu49Yn5dfmtv0C
Orbit - Good Kid: https://open.spotify.com/track/2TkdbIVzSjtdBBqU7hp4pv
fuck this town - glaive: https://open.spotify.com/track/1kADZJDyRUbmlLxYiqi077
We Are The Lights - Rico & Miella: https://open.spotify.com/track/29djmwXYaxGUZIg5FBjFH8
LUV U NEED U - Slushii: https://open.spotify.com/track/0VbUNUwSXJ4hMdPiO7Ov0c
I Sent My Therapist To Therapy: https://open.spotify.com/track/6ofVkSSWsDcnzRCNwrvpXB
Enemy (with JID) - Imagine Dragons: https://open.spotify.com/track/1r9xUipOqoNwggBpENDsvJ
Fly Again - Kisma: https://open.spotify.com/track/0g27hRJFlaNtAVpPw40btc
Break Me - Trivecta: https://open.spotify.com/track/61wWlx9A7791rnvfzBkK18
Fallen Kingdom - CaptainSparklez: https://open.spotify.com/track/0gYnzvD4ktjOm8EWPN9vhh
My Love - Kuba Oms: https://open.spotify.com/track/0JMj1bPZ2hUWFOsFZOH1YG
Castle in the Sky - Adon: https://open.spotify.com/track/2HrZq3Z11Jfc7HJysagg1R
It Is What It Is - Jamie Miller: https://open.spotify.com/track/2kHcMUgIqU3t87wjoGhrd6
Faceplant - LOLO: https://open.spotify.com/track/4wbAmTycr1Og1f99P1ttiL
Animals - Maroon 5: https://open.spotify.com/track/2bL2gyO6kBdLkNSkxXNh6x
Wonderwall - Oasis: https://open.spotify.com/track/1qPbGZqppFwLwcBC1JQ6Vr
Moments - MitiS: https://open.spotify.com/track/4mj0eDXQaPjTIub0CI9dpW
Angel Pt. 2 - JVKE (and others): https://open.spotify.com/track/0ApadYqa3GRQkJJ3E7pQDJ
Make You Move (James Roche Remix): https://open.spotify.com/track/105W4dhENS7sgUSMLMEWGh
How to Love (Boombox Cartel Remix): https://open.spotify.com/track/2FqVzWFKR7qmztn81ynKtM
Sunroof - Nicky Youre: https://open.spotify.com/track/5YqEzk3C5c3UZ1D5fJUlXA
不可思議のカルテ: https://open.spotify.com/track/2Zj2AqmjkgpBix8cZAu6iY
Sweet but Psycho - Ava Max: https://open.spotify.com/track/7DnAm9FOTWE3cUvso43HhI
Be Better - Raven & Kreyn: https://open.spotify.com/track/4e2P3L9Ov7Z9FMVtTeR4XF
Wildfire - HOYO-MiX: https://open.spotify.com/track/2CUSdI74D2yqrvEXRQq2Xl

Not Best Sync:
LAST THING ON YOUR MIND - Romance Planet: https://open.spotify.com/track/1FTKL3b6TqEuDh2fw68kbh
Butterflies - William Black: https://open.spotify.com/track/0Rz2MaUfMUkWZR6jbhtRkP
One More Night - NIO: https://open.spotify.com/track/5F00YTcguy7LICneJYbI89
Happi - Mangoo: https://open.spotify.com/track/2ZgohtyqMXzziMV7rDZoRw
Aurora- Synthion: https://open.spotify.com/track/4nsl0V5EIDEHxmK6kdSpGf
Somewhere Out There - acloudyskye: https://open.spotify.com/track/13X0MbPS0WOenZsShfvI5g
Blossom - Synthion: https://open.spotify.com/track/2WethMmZCuMQM5JYmpN07p
Hate You - Jim Yosef: https://open.spotify.com/track/1ZbzOXEYMJNT1zxqLHyCfA
Howling - Cartoon: https://open.spotify.com/track/596lDSwIMzDoiq3E6jJ0wC
Safe & Sound - Novaspace: https://open.spotify.com/track/4omuC4ymnbeDkqL4e5dDlO

Infinite loading?
Motion - Smallpools: https://open.spotify.com/track/1X0EgBQrXoMlOyWNjBWs2U

**Comment by BariIsStupid** [comment]
#546 ?

**Comment by surfbryce** [comment]
@iPixelGalaxy Will check this on Tuesday, but given the progress I've made today and that every other lyrics report has been marked as fixed in the next patch, I have a good feeling about this one being the same. We'll see if there's anything new here that doesn't work

**Comment by Sonny4546** [comment]
Whole Hamilton playlist has no lyrics: https://open.spotify.com/album/1kCHru7uhxBUdzkm4gzRQc?si=ondGL8pFTDylKAICECiTEw

**Comment by surfbryce** [comment]
@iPixelGalaxy Going to close this since all the bug reports prior to this actually fixed the issues here, you'll see this in the next patch

**Comment by iPixelGalaxy** [comment]
Updated List, still has issues.

Playlist of songs:
https://open.spotify.com/playlist/2Sdz4CQsMsEcDNSIu9j6O3


Missing Lyrics:
Letting Go - Yonetro: https://open.spotify.com/track/6myqRcz9EPifaFQ6fAZ8cs (lyrics aren't synced on musixmatch, I'll probably do that at some point)
Weapon - Grant: https://open.spotify.com/track/2rK7ZlIdlCetWZbQ6PD1e0
One - Sleeping At Last: https://open.spotify.com/track/76nlq5gomu49Yn5dfmtv0C
Orbit - Good Kid: https://open.spotify.com/track/2TkdbIVzSjtdBBqU7hp4pv
fuck this town - glaive: https://open.spotify.com/track/1kADZJDyRUbmlLxYiqi077
LUV U NEED U - Slushii: https://open.spotify.com/track/0VbUNUwSXJ4hMdPiO7Ov0c
Fly Again - Kisma: https://open.spotify.com/track/0g27hRJFlaNtAVpPw40btc
Break Me - Trivecta: https://open.spotify.com/track/61wWlx9A7791rnvfzBkK18
My Love - Kuba Oms: https://open.spotify.com/track/0JMj1bPZ2hUWFOsFZOH1YG
Castle in the Sky - Adon: https://open.spotify.com/track/2HrZq3Z11Jfc7HJysagg1R
Moments - MitiS: https://open.spotify.com/track/4mj0eDXQaPjTIub0CI9dpW
Angel Pt. 2 - JVKE (and others): https://open.spotify.com/track/0ApadYqa3GRQkJJ3E7pQDJ
Motion - Smallpools: https://open.spotify.com/track/1X0EgBQrXoMlOyWNjBWs2U

Not Best Sync:
Make You Move (James Roche Remix): https://open.spotify.com/track/105W4dhENS7sgUSMLMEWGh
We Are The Lights - Rico & Miella: https://open.spotify.com/track/29djmwXYaxGUZIg5FBjFH8
LAST THING ON YOUR MIND - Romance Planet: https://open.spotify.com/track/1FTKL3b6TqEuDh2fw68kbh
One More Night - NIO: https://open.spotify.com/track/5F00YTcguy7LICneJYbI89
Happi - Mangoo: https://open.spotify.com/track/2ZgohtyqMXzziMV7rDZoRw
Aurora- Synthion: https://open.spotify.com/track/4nsl0V5EIDEHxmK6kdSpGf
Somewhere Out There - acloudyskye: https://open.spotify.com/track/13X0MbPS0WOenZsShfvI5g
Blossom - Synthion: https://open.spotify.com/track/2WethMmZCuMQM5JYmpN07p
Hate You - Jim Yosef: https://open.spotify.com/track/1ZbzOXEYMJNT1zxqLHyCfA
Howling - Cartoon: https://open.spotify.com/track/596lDSwIMzDoiq3E6jJ0wC
Safe & Sound - Novaspace: https://open.spotify.com/track/4omuC4ymnbeDkqL4e5dDlO

Super Desynced Lyrics:
Butterflies - William Black: https://open.spotify.com/track/0Rz2MaUfMUkWZR6jbhtRkP
