### ISSUE TITLE
Lyrics Don't Appear in Page View

### ISSUE THREAD

**Issue by FranssMukti07** [surfbryce/beautiful-lyrics#590]
1. Country : Indonesia
2. Spotify/Spicetify Version
Spotify for Windows (64 bit)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
Theme: Hazy / Base
Extensions: fullScreenWrapper.js, adblock.js, beautiful-lyrics.mjs, theme.js
Custom apps: marketplace

3. HTML and CSS Spotify
[Spotify_CSS.txt](https://github.com/surfbryce/beautiful-lyrics/files/15384301/Spotify_CSS.txt)
[Spotify_HTML.txt](https://github.com/surfbryce/beautiful-lyrics/files/15384302/Spotify_HTML.txt)

4. Screenshot of Console
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92196581/de60540a-4861-49f9-82d2-4c8f9cd74d75)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92196581/6a8a7a63-abdf-4cad-9bb8-553c58fbde2e)

**Comment by surfbryce** [comment]
@FranssMukti07 Thank you so much for following the instructions! I'll take a look at this ASAP

**Comment by surfbryce** [comment]
@FranssMukti07 Testing with your HTML file, this should be fixed in the next patch, thank you so much for reporting!

**Comment by FranssMukti07** [comment]
> @FranssMukti07 Testing with your HTML file, this should be fixed in the next patch, thank you so much for reporting!

thank u so much for ur response, Really appreciate it!!
