### ISSUE TITLE
Japanese Songs Lyrics aren't Showing

### ISSUE THREAD

**Issue by shashankdangi** [surfbryce/beautiful-lyrics#597]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/91678732/4cea5ad2-6b43-45e1-be81-263595b6c00a)
Ain't showing any japanese songs lyrics saying there's no lyrics but there's lyrics in spotify app and i have been listening to these songs on previous version of the beautiful lyrics . Please fix it .

**Comment by surfbryce** [comment]
@shashankdangi Duplicate of various existing song issues, this will be fixed in the next patch
