### ISSUE TITLE
Query: Choose between this and Full Screen/FAD?

### ISSUE THREAD

**Issue by teditor1** [surfbryce/beautiful-lyrics#6]
This is just a query but I'm wondering if I'm supposed to be able to get the really great dynamic background when working with other extensions, like daksh2k's "Full Screen"? Right now I'm only seeing it in sidebar. (Great extension btw)

**Comment by surfbryce** [comment]
You are not - this extension is completely separate and serves a different purpose than Full-Screen.

It looks like Full-Screen made an update to imitate my implementation so you can have somewhat the same effect but it's not the same.

You don't have to choose between either or though: my extension shouldn't affect Full-Screen. So you can have both extensions enabled without any interference.

I can look into seeing if it'll be possible for my extension to affect Full-Screen and any others that might need it. It shouldn't be too much of a change either.
