### ISSUE TITLE
I can scroll down from the fullscreen lyrics page

### ISSUE THREAD

**Issue by Joeeeeb5** [surfbryce/beautiful-lyrics#600]
https://github.com/surfbryce/beautiful-lyrics/assets/125207782/34b3ebf2-3c89-44d5-86f5-0d10f0898713

**Comment by Joeeeeb5** [comment]
uh the video doesnt show for some reason so here it is in a different format

https://github.com/surfbryce/beautiful-lyrics/assets/125207782/28b74f30-5833-45ce-9572-a6ce9f63a0fb

**Comment by surfbryce** [comment]
@Joeeeeb5 Can you provide a link to the video hosted elsewhere? I can't see either video you uploaded (which are both mp4 btw)

**Comment by surfbryce** [comment]
@Alehaaaa Thank you so much! Which version of Spotify are you on? I think this should be an easy fix hopefully

**Comment by Alehaaaa** [comment]
@surfbryce sorry, I just reuploaded the video. I don't know anything about the context of the issue :\

**Comment by surfbryce** [comment]
oh gotcha @Alehaaaa, thanks for reuploading either way, I think I know how to solve this issue regardless so I'll have to see if the next patch fixes it for @Joeeeeb5
