### ISSUE TITLE
I cant seen the music button 

### ISSUE THREAD

**Issue by guralynoel** [surfbryce/beautiful-lyrics#601]
![Képernyőkép 2024-05-21 174441](https://github.com/surfbryce/beautiful-lyrics/assets/65784557/6981e055-6bf6-4887-b6e8-c38e6d490038)

if anyone can help i would appreciate it

**Comment by surfbryce** [comment]
@guralynoel Please follow the template on the WIki before posting

**Comment by sTiKyt** [comment]
Have the same issue since recently, no idea why it changed

**Comment by bebrriko** [comment]
Try to reinstall extension from marketplace
@guralynoel @sTiKyt

**Comment by NAXRAY** [comment]
I am having the same issue and I've reinstalled the extension and it still doesn't work with the lastest spotify version
