### ISSUE TITLE
The Beautiful Lyrics extension does not load and its background covers the whole screen 

### ISSUE THREAD

**Issue by AlfyQ** [surfbryce/beautiful-lyrics#603]
I am from Kuwait

**Version:**
Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
Spicetify v2.36.11
Theme: marketplace
Extensions: adblock.js, hidePodcasts.js, playlist-icons.js, rym.js, group-session.js, savePlaylistsWrapper.js, fixEnhance.js, volumePercentageWrapper.js, seekSong.js, goToSong.js, listenTogether.js, lastfm.js, dist\search-on-youtube\prism.js, playbarClock.js, sleepTimer.js, volumePercentage.js, upcomingSong.js, fullScreenWrapper.js, fullAlbumDate.js, copy-lyrics.js, beautiful-lyrics.js, CoverAmbience.js, dist\show-the-genres\prism.js, copytoclipboard.js, fullAppDisplayMod.js, scannables.js, pip.js, playRandom.mjs, allOfArtist.js, playOnYouTube.js, spotifyGenres.js, spotifyBackup.js, skipOrPlayLikedSongs.js, popupLyrics.js, volume-plus.js, friendlikes.js, bookmark.js, quickQueue.js, npvAmbience.js, immersiveView.js, simple-beautiful-lyrics.js, QueueTime.js, SleepTimer.js, beautiful-lyrics.mjs
Custom apps: marketplace, lyrics-plus, combined-playlists

**Developer Tools:**
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15393085/Spotify.css.txt)
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15393089/Spotify.html.txt)

**Screenshotting the Developer Console:**
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170450103/1fd105e9-e66f-4123-aa26-80f7a505abde)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170450103/08462d4c-e1f3-44d9-a0d4-26cc9fcffbaa)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170450103/5fb7046c-9234-4236-9279-c15b21f37249)

**Comment by cariosa** [comment]
I'm having this issue too

arch linux
spotify 1.2.31.1205
spicetify 2.36.11

![image](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/2320c42b-020b-4438-9317-fe88e3fd6e73)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/a5b28e9f-1a23-41cb-a5a9-cb0bd8346e9a)

**Comment by surfbryce** [comment]
Ok so first things first, @AlfyQ it looks like you still have the old version of Beautiful Lyrics installed somehow:
<img width="787" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/ed52d01c-c880-4d31-9a24-2de27a0a50f5">

and actually you can see that just by looking at the extensions it says you have installed. You need to uninstall the ".js" version but keep the ".mjs", if you only installed via Marketplace, then hit uninstall on Beautiful Lyrics in Marketplace, then reload Spotify, then see if it is still installed, if it is, hit uninstall and repeat until its gone. Then reinstall Beautiful Lyrics.

I'll keep looking for anything different

**Comment by surfbryce** [comment]
@AlfyQ Also, another problem is that you didn't do the HTML file step when the "Now Playing View" was open. It's completely empty in your file, so when you can please redo the HTML file step when that view is open so I can see what is happening there.

As for the lyrics not appearing in the page view, that is now fixed for your HTML file (this means all older Spotify users will have this fixed as well I believe)

**Comment by cariosa** [comment]
The extension was automatically uninstalled for me in marketplace, I installed it again and this happened. So I think it is not properly uninstalled from marketplace or something, is there a way to completely uninstall it and install it again?

**Comment by samueljebaraj** [comment]
> Ok so first things first, @AlfyQ it looks like you still have the old version of Beautiful Lyrics installed somehow: <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/80861823/332564689-ed52d01c-c880-4d31-9a24-2de27a0a50f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTYwMjksIm5iZiI6MTcxNjM5NTcyOSwicGF0aCI6Ii84MDg2MTgyMy8zMzI1NjQ2ODktZWQ1MmQwMWMtYzg4MC00ZDMxLTlhMjQtMmRlMjdhMGE1MGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OWZmZTI3MWJhYjIzNzJmNTM0MzIzNjJiMmE1OTM5Yzk2YjA0YTMxNGJiZGI3OWU5NGJjYzVlZWZhZDZhY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ughvdc1JbHGxPzZuXvLomcaE8u2YToutdQ0gQjlgzQE">
> 
> and actually you can see that just by looking at the extensions it says you have installed. You need to uninstall the ".js" version but keep the ".mjs", if you only installed via Marketplace, then hit uninstall on Beautiful Lyrics in Marketplace, then reload Spotify, then see if it is still installed, if it is, hit uninstall and repeat until its gone. Then reinstall Beautiful Lyrics.
> 
> I'll keep looking for anything different

Hey can you please explain it more briefly and include some screenshots as well, Thanks!

**Comment by samueljebaraj** [comment]
> The extension was automatically uninstalled for me in marketplace, I installed it again and this happened. So I think it is not properly uninstalled from marketplace or something, is there a way to completely uninstall it and install it again?

Marketplace.reset("extensions")     
 Go to console and type the following code. I tried, but it didn't work for me. Maybe you can try it in your spotify,

**Comment by surfbryce** [comment]
Since this hasn't been updated and #609 provides what I need, I'll be closing this now, thanks for the initial report!

**Comment by cariosa** [comment]
> > The extension was automatically uninstalled for me in marketplace, I installed it again and this happened. So I think it is not properly uninstalled from marketplace or something, is there a way to completely uninstall it and install it again?
> 
> Marketplace.reset("extensions") Go to console and type the following code. I tried, but it didn't work for me. Maybe you can try it in your spotify,

Yeah that definitely worked for me! thank you so much.
I had to install all the extensions again though.
