### ISSUE TITLE
Lyrics loading forever

### ISSUE THREAD

**Issue by PwccaCode** [surfbryce/beautiful-lyrics#604]
Country: Brazil
Spotify for Windows (32 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11

![console](https://github.com/surfbryce/beautiful-lyrics/assets/51799102/14f501cc-2639-4b07-999d-131c4d069ea0)
![spotify](https://github.com/surfbryce/beautiful-lyrics/assets/51799102/df1b6251-8a71-432f-934b-2e068bcf7396)
Screenshots

log files 
[spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15395183/spotify.html.txt)
[xpui.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15395184/xpui.css.txt)

as you can see in the screenshot it keeps loading forever but doesn't display any lyrics even after a while

**Comment by surfbryce** [comment]
@PwccaCode Seems like this was a new Spotify update, I don't have this yet but I have a friend who does, so I'll be looking at theirs and seeing what I can do, thanks for reporting this!

**Comment by yodaluca23** [comment]
Yep, this is happening to me too, btw @surfbryce @amd64fox has a spreadsheet of direct downloads to all the latest spotify versions.

https://cutt.ly/8EH6NuH https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557

**Comment by amd64fox** [comment]
@yodaluca23 @yodaluca23 @yodaluca23 Bro, thank you for not forgetting to mention me for no reason 😉

**Comment by surfbryce** [comment]
@PwccaCode This will be fixed in the next patch, thank you for reporting!

**Comment by NAXRAY** [comment]
Hey surfbryce I just wanted to add that my english songs and any transliterated lyrics song load lyrics but any other scripts of song are perpetually loading now (not sure if this bug is language specific or if its just the provider for the songs i'm listening to)

**Comment by kleinesamogus** [comment]
I also have this problem, but the update came today, is there another update for this problem?
