### ISSUE TITLE
NPV Dynamic Background Covers all of Spotify

### ISSUE THREAD

**Issue by appcreatorguy** [surfbryce/beautiful-lyrics#609]
I am from the United Kingdom

**Version**
Spotify for Linux (Flatpak) v1.2.31.1205.g4d59ad7c
Spicetify v2.36.11
Theme: catppuccin

**Developer Tools Files**
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15407309/Spotify.css.txt)
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15407310/Spotify.html.txt)

**Screenshots of bug occuring**
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/283fe340-6933-42d5-a8ed-a3d075f4e6e5)

**Screenshot of Console**
Top Half of console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/2dc225bc-f4f0-4ec0-ac36-acaca058e4ac)
Bottom Half of console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/ee31d437-bfd2-45f7-b354-94cb5da9771a)

**Comment by appcreatorguy** [comment]
FYI, I've fully uninstalled all my marketplace extensions (using Marketplace.reset('extensions') in the console, and then reinstalled them all, including beatiful lyrics, so I should hopefully be on the latest version.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/24f1677d-381a-4a11-812a-6571b555f392)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/ce4f826e-09fa-4919-ae83-3a32a5e31fd9)


And these are the extensions I have manually installed in my spicetify config file:
`adblock.js | catppuccin-macchiato.js | shuffle+.js | keyboardShortcut.js | power-bar.js | keyboard-shortcuts.js`

**Comment by appcreatorguy** [comment]
https://github.com/surfbryce/beautiful-lyrics/assets/14041410/c4340bd7-3caf-4922-895d-f1ead8015aa7

Here's a video of how to recreate the error too, if that helps.

**Comment by appcreatorguy** [comment]
Additionally, if I try to open the Now playing view sidebar, I get a similar error of the background overflowing to the main screen, as in #603.

**Comment by surfbryce** [comment]
@appcreatorguy I checked and #590 fixes the lyrics not appearing in the page view issue. However, that background overflow issue from #603, can you do the same bug reporting process that you did earlier but do it with the Now Playing view open?

That's really the only thing I need to fix that bug

**Comment by appcreatorguy** [comment]
Here's the console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/f4ac3025-2e67-4582-a43e-a2dfa8c90515)
I noticed the failed error 403 GET request at the bottom appears about 4 times every time the now playing tab is opened.
Here are the 2 files:
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15408663/Spotify.css.txt)
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15408664/Spotify.html.txt)
Here's a screenshot of what the bug looks like for me for good measure:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/14041410/d42209a2-27cd-4ff5-b518-699ac96aeb0f)

**Comment by surfbryce** [comment]
@appcreatorguy Thank you so much! Those 403 errors are actually from Spotify themselves, I'll take a look at the overflow issue soon, thank you again!

**Comment by surfbryce** [comment]
@appcreatorguy Thank you so much for reporting! Was able to replicate your issue with the files you provided and it was a super simple fix, thanks so much I really appreciate the report! Should be fixed in the next patch

**Comment by appcreatorguy** [comment]
No worries, glad I could help.
Looking forward to getting my lyrics back!
