### ISSUE TITLE
Missing lyrics

### ISSUE THREAD

**Issue by SaKQ0** [surfbryce/beautiful-lyrics#611]
" GMFU (w/ 6arelyhuman) - odetari, 6arelyhuman "
" Those Eyes - New West " 
" All i want is you - Rebzyyx, Hoshie star "
" A new kind of love -demo - Frou frou. imogen heap, sigsworth "
" Drowning (feat. Kodak Black) - A boogie wit da hoodie, Kodak Black " 
" Akuma no ko - higuchi Ai "  [there is two of this in spotify]
" Mr. Saxobeat - Radio Edit "
" Young Girl A - Siinamota "
" Scars - Novulent "
" Look at me! - XXXtentacion "
" Fuck love - XXXtentacion, trippie redd " 
" Haven't i given enough? - whocreatedUs? "
" Lost on you - LP "
" ava - famy " 
" 不可思議のカルテ - Mai Sakurajima(CV:Asami Seto), Tomoe Koga(CV:Nao Toyama), Rio Futaba(CV:Atsumi Tanezaki) "
" Mind over matter (Reprise) - Young the giant " 
" 光るなら - Goose house " 
" アイドル - YOASOBI " 
" Died Once - ledimiknight "

**Comment by ayushmath07** [comment]
So high - Doja cat
Khuda jaane- Vishal-Shekhar

**Comment by surfbryce** [comment]
@SaKQ0 Going to close this since all the bug reports prior to this actually fixed the issue, you'll see this fixed in the next patch
