### ISSUE TITLE
Extension not loading and fullscreen not working

### ISSUE THREAD

**Issue by al3xx-rs** [surfbryce/beautiful-lyrics#614]
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11

Every song in fullscreen displays like this:
![Issue](https://github.com/surfbryce/beautiful-lyrics/assets/170454611/62359620-62b3-4760-9526-4822171b10f9)

I already tried reinstalling spicetify but didn't work

**Comment by surfbryce** [comment]
@al3xx-rs Please follow the instructions for reporting a bug
