### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by al3xx-rs** [surfbryce/beautiful-lyrics#615]
I'm from Italy

Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11

Every song in fullscreen displays like this: 
![Issue](https://github.com/surfbryce/beautiful-lyrics/assets/170454611/c3710d22-2c34-4edd-9949-58f1a57f16de)

Here are the html and css file (I extended them txt to attach them):
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15421270/Spotify.css.txt)
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15421271/Spotify.html.txt)

Console atm of the issue:
![Console](https://github.com/surfbryce/beautiful-lyrics/assets/170454611/8cdefffa-8ec6-4d2c-9280-eea78af56422)

I already uninstalled and reinstalled both spicetify and spotify

**Comment by surfbryce** [comment]
Alright sorry @al3xx-rs for making you do that just for me to close this as a duplicate, but it is of #604 . Good new is, it will be fixed in the next patch soon!
