### ISSUE TITLE
The thing never works??

### ISSUE THREAD

**Issue by Trynex01** [surfbryce/beautiful-lyrics#616]
i have never seen this work properly?? Now its just blank screen?? is the developer just under developing the extension or something?? Fix this Plz
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169169959/d8c4c79d-7574-4aa1-9e82-3f064c88cfa1)
Spotify Ver
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169169959/77f4d49b-60ff-40cc-b671-baed46557045)

**Comment by surfbryce** [comment]
@Trynex01 Firstly duplicate of several issues before hand, you could have at least looked, second, don’t go into a GitHub with that attitude, easy way to get banned
