### ISSUE TITLE
Song Lyrics are Missing

### ISSUE THREAD

**Issue by brullax** [surfbryce/beautiful-lyrics#617]
Igual que un Angel (with Peso Pluma)

This problem also happens to a few other songs. This started happening today.

And there are problems that sometimes only the letters appear, but if you remove and activate the right box view again, they disappear and do not appear again, fix that bug please. 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/c88e5378-061a-4972-8805-e546cceffc89)

![Captura de pantalla 2024-05-23 154703](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/5c7e3575-e0df-464d-b244-747db8dca2c9)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/9863510d-f17f-4373-a0eb-0351cbd054ab)

**Comment by iam-siphon** [comment]
i get the same thing

**Comment by tuputamadre12316** [comment]
Nice job bro!! 2 years for the update and still broke, nice!!!!

**Comment by surfbryce** [comment]
@brullax Will be fixed in the next patch, new Spotify update broke existing version.
