### ISSUE TITLE
The new update broke everything again????

### ISSUE THREAD

**Issue by Wart050** [surfbryce/beautiful-lyrics#619]
I just updated Spotify, and this happened, It was working perfectly a few seconds ago before I pressed update:
![image_2024-05-23_210135901](https://github.com/surfbryce/beautiful-lyrics/assets/101201581/f0cff161-f646-432f-a29c-8d2a31df1daf)

![image_2024-05-23_211218764](https://github.com/surfbryce/beautiful-lyrics/assets/101201581/e780b610-99a1-4c13-9ea0-ec73bcd68772)

And also is this part with the broken formatting from this extension or a spicetify bug: 
![image_2024-05-23_211157900](https://github.com/surfbryce/beautiful-lyrics/assets/101201581/87de96ea-8175-488c-ab13-da6a243e16c7)

**Comment by brullax** [comment]
Yes, it requires an update now

**Comment by Wart050** [comment]
Sorry, Does spicetify or beautiful-lyrics require an update?

**Comment by Wart050** [comment]
I just found out that it does still work but only for songs that were in my playlist before I pressed the update button which is just very weird

**Comment by brullax** [comment]
I meant that they patch it and make another update, just like you, it also worked for me with some songs but now with none, I hope they fix it soon

**Comment by brullax** [comment]
something you can do, and it has made it work for me again for now, is to restart all your extensions through the console, or simply uninstall spotify, install it, and redownload all your extensions, I think it has worked for me

**Comment by bleghj** [comment]
> I just found out that it does still work but only for songs that were in my playlist before I pressed the update button which is just very weird

its because those songs are in cache, the extension is unable to grab new lyrics.

**Comment by brullax** [comment]
> Something that can do, and has made it work for me again for now, is to restart all its extensions through the console, or simply uninstall spotify, install it, install Spicetify and download all its extensions again,

Follow these steps and tell me if it worked for you.

**Comment by oneqxz** [comment]
![Spotify_Yuw9jWZMdz](https://github.com/surfbryce/beautiful-lyrics/assets/148702857/c8d1680b-206b-4abe-916b-00a1b6b6fe36)
![Spotify_YvbtnXd3pd](https://github.com/surfbryce/beautiful-lyrics/assets/148702857/6969375b-0b74-492f-b547-108de5a67266)

**Comment by brullax** [comment]
did you uninstall and reinstall spotify?

**Comment by Diffle** [comment]
Damn you spotify. Can confirm that lyrics now work only for 10% of songs or even less

**Comment by oneqxz** [comment]
oh, yes @brullax

**Comment by brullax** [comment]
Well yes, it stopped working again, I think it simply needs an update and that's it.

**Comment by cl6mh7** [comment]
Happens the same to me. I reinstalled Spotify and Spicetify, but it didn't work.

**Comment by surfbryce** [comment]
@Wart050 New Spotify update broke existing version, next patch will be soon and will fix these issues
