### ISSUE TITLE
Song is Missing Lyrics: Multiple.

### ISSUE THREAD

**Issue by oldschoolvirgo** [surfbryce/beautiful-lyrics#620]
It doesn't seem like the algorithm is falling back to Spotify line synced lyrics. In these two examples, BL doesn't have lyrics but Spotify does:

Truth Hurts by Lizzo
https://open.spotify.com/track/3HWzoMvoF3TQfYg4UPszDq?si=b4273279fca84f96

Unholy by Sam Smith
https://open.spotify.com/track/3nqQXoyQOWXiESFLlDF1hG?si=c081a7c3b16b437d

My market is US.

**Comment by surfbryce** [comment]
@oldschoolvirgo Existing bug reports will fix these issues, you'll see this in the next patch, there is no fallback to Spotify line-synced lyrics. This is because they aren't available for everybody.
