### ISSUE TITLE
Lyrics broken

### ISSUE THREAD

**Issue by zmkq** [surfbryce/beautiful-lyrics#622]
many users reported that after they updated to the new Spotify version, the extension broke. and that's what happened to me.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74769232/ce01ff0c-0b14-4d00-9b3c-9c9ad5aaf698)

**Comment by Zyanbob** [comment]
![Screenshot 2024-05-25 071617](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/9647a586-496d-435b-b753-9b2e7daa03ec)
![Screenshot 2024-05-25 071647](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/b5102dc9-3e7c-4f7b-945a-67410b37766c)
![Screenshot 2024-05-25 071709](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/6f1d7be2-6dd0-4318-81f4-cd9b8c2ed529)
![Screenshot 2024-05-25 071723](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/1441cb10-988d-4799-b6ea-95c434cce8bd)
![Screenshot 2024-05-25 071742](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/7b6232d5-4842-4688-bbfd-6e4c104067e4)
![Screenshot 2024-05-25 071806](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/da598442-7673-4041-bdfe-36eae4c933e3)
![Screenshot 2024-05-25 071835](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/fe9725b8-6894-4e5e-a124-005082cfabaf)
![Screenshot 2024-05-25 071851](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/dde66dde-4be2-4e1b-b3ab-b2963791adcc)
![Screenshot 2024-05-25 071905](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/c49bf788-543f-49da-95b4-9b6b4cec02e9)
![Screenshot 2024-05-25 071931](https://github.com/surfbryce/beautiful-lyrics/assets/81934264/b37824bc-6f79-47a1-8070-85f04960ba7d)
adding to the list of songs the new update broke

**Comment by sebasflorezo** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/109894549/03aad577-7ece-4a27-8ed3-3672bb39c5ff)

**Comment by EditKey** [comment]
@zmkq Hello, off topic, but what are the themes and plugins you use?

**Comment by KurgoNoKi** [comment]
> @zmkq Hello, off topic, but what are the themes and plugins you use?

Same issue here doesn't happen in my windows 10 pc but does in my windows 11 laptop if that helps

<img width="1280" alt="Screenshot 2024-05-25 061604" src="https://github.com/surfbryce/beautiful-lyrics/assets/170800507/ff702b4a-2b01-4714-a3bf-080657c7a5b7">

**Comment by zmkq** [comment]
> @zmkq Hello, off topic, but what are the themes and plugins you use?

hey @EditKey, I use Dribblish theme (Catppuccin Macchiato)
and here are the extensions :
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74769232/649cf775-9165-4833-a958-b557a3b21e47)

**Comment by kalichT** [comment]
Any fix released yet or not ?

**Comment by kalichT** [comment]
I have the same thing

**Comment by zmkq** [comment]
> Any fix released yet or not ?

not yet, the developer of the extension hasn't responded yet

**Comment by EditKey** [comment]
> > @zmkq Hello, off topic, but what are the themes and plugins you use?
> 
> hey @EditKey, I use Dribblish theme (Catppuccin Macchiato) and here are the extensions : ![image](https://private-user-images.githubusercontent.com/74769232/333792297-649cf775-9165-4833-a958-b557a3b21e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzQwNzgsIm5iZiI6MTcxNjYzMzc3OCwicGF0aCI6Ii83NDc2OTIzMi8zMzM3OTIyOTctNjQ5Y2Y3NzUtOTE2NS00ODMzLWE5NTgtYjU1N2EzYjIxZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEwNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTUyZGI1ZTk5NmY0MTljMDdiZWNlZmIyYTUyNjc0Y2E1N2U2YjU0YzI5ZWJlNjc3ZDZmNzQ3MjI5M2Q2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDYpR6uw-a5UO8SgGFlJR5kY80wtuc279X_-pIWwqPQ)

thanks bro

**Comment by viczen994** [comment]
> > @zmkq Hello, off topic, but what are the themes and plugins you use?
> 
> Same issue here doesn't happen in my windows 10 pc but does in my windows 11 laptop if that helps I also use the same extensions in both so I don't think the issue relates to that
> 
> ![image_2024-05-25_062011634](https://private-user-images.githubusercontent.com/170800507/333790927-47b48c18-5dc8-40db-acb1-7478de3ba320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTc5NjIsIm5iZiI6MTcxNjY1NzY2MiwicGF0aCI6Ii8xNzA4MDA1MDcvMzMzNzkwOTI3LTQ3YjQ4YzE4LTVkYzgtNDBkYi1hY2IxLTc0NzhkZTNiYTMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNzIxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGNiNDdlMmJmMTU2OGU0ZDQzMzVkMzliODVlYjBiOWFhYTRhY2JhNDA5YmRmYTQ3NmRmMDdjZDExMWYwZjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qhmLIVNZd9fz6kLKqruQ-4k-bcGx2F45l4z_TWv1DfI)

kurgonoki, what theme  is  that?

**Comment by surfbryce** [comment]
@zmkq This was caused by the newest Spotify update, new patch version is coming out soon which will fix all of this and more issues
