### ISSUE TITLE
Missing lyrics

### ISSUE THREAD

**Issue by LuvEctasyy** [surfbryce/beautiful-lyrics#624]
Because what I have read, the lyrics do not appear, I don't know if they refer to the same thing as me, but I hope it is fixed, the lyrics do not appear in all my playlists, it is already something general

![imagen_2024-05-24_215542361](https://github.com/surfbryce/beautiful-lyrics/assets/163657235/7c34344b-18d7-441e-94cc-a2c86091918d)

**Comment by Zyanbob** [comment]
same as #622

**Comment by surfbryce** [comment]
@LuvEctasyy Latest Spotify update broke the extension, this will be fixed in the next patch
