### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by HANSEELE** [surfbryce/beautiful-lyrics#625]
![Morgan Wallen - Cover Me Up 5_25_2024 1_13_29 PM](https://github.com/surfbryce/beautiful-lyrics/assets/170789402/193ce7f0-bb33-4203-9e11-b677c35db4b4)
it's been a while for the issue, i try to reinstall but it still same. I need some suggestion and explanation for this

**Comment by Zyanbob** [comment]
same as #622

**Comment by surfbryce** [comment]
@HANSEELE Recent Spotify update broke the extension, this will be fixed in the next patch

**Comment by Zyanbob** [comment]
when will the patch come out?
