### ISSUE TITLE
buffering lyrics (not signal issues)

### ISSUE THREAD

**Issue by dzakidzakiaa** [surfbryce/beautiful-lyrics#632]
**If you are making a Bug Report about the Extension being broken in some way, read this**:
https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics

**If you are making a Bug Report about Lyrics in some way, read this**:
https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

**IF YOU DO NOT FOLLOW EITHER INSTRUCTIONS, YOUR BUG-REPORT WILL BE INSTANTLY DELETED**

**Comment by dzakidzakiaa** [comment]
where is the instruction

**Comment by surfbryce** [comment]
@dzakidzakiaa Most recent Spotify update broke the Extension, will be fixed in the next patch
