### ISSUE TITLE
Lyrics Are Not Refine !!!!

### ISSUE THREAD

**Issue by Kouki002** [surfbryce/beautiful-lyrics#633]
I Seen Best And smooth Animation Lyrics On blinding light by The Weeknd and else has laggy animation and justin Bieber Stay And Shawn Mandes All song And other etc... songs Lyrics are Not Loading Just Buffering Forever !!!

**Comment by surfbryce** [comment]
@Kouki002 Most recent Spotify update broke the Extension, will be fixed in the next patch
