### ISSUE TITLE
Lyrics not showing up

### ISSUE THREAD

**Issue by Drywaffle** [surfbryce/beautiful-lyrics#634]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/101133811/af5f29ef-53f3-4bbc-a314-0f476078dc24)

 ### **The lyrics are not loading please help D:**

**Comment by JustRens780** [comment]
same issue here

**Comment by RGH271** [comment]
same

**Comment by adamadong** [comment]
same issue here, except that the problem occurs when listening to Chinese songs. English songs seem working fine for me.

**Comment by mad4me** [comment]
Same

![image](https://github.com/surfbryce/beautiful-lyrics/assets/54853465/66a9270f-ed0e-4b81-bbe2-4f1d6f6782f9)

And the card part is blank 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/54853465/ce71b70f-731a-4c22-b623-9f7ab3a4337f)

**Comment by surfbryce** [comment]
@Drywaffle Most recent Spotify update broke the Extension, will be fixed in the next patch
