### ISSUE TITLE
everything keeps loading

### ISSUE THREAD

**Issue by xdBarun** [surfbryce/beautiful-lyrics#635]
when i open beautiful lyrics background loads perfectly but every other information keep loading- Song Cover, song name, Artist name, lyrics and literally everthing
i am attaching the screenshot
![Screenshot (1)](https://github.com/surfbryce/beautiful-lyrics/assets/100030972/76fef51c-c0e5-4742-8b56-e2ef3729d9c3)
![Screenshot (2)](https://github.com/surfbryce/beautiful-lyrics/assets/100030972/dd722c5e-e9ec-43ec-818a-6f3b4258cf71)
and here are the html, css and console
[spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15447283/spotify.html.txt)
[spotify css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15447299/spotify.css.txt)

(sorry i am unable to upload .css files on github please work out with .txt)

![Screenshot (3)](https://github.com/surfbryce/beautiful-lyrics/assets/100030972/d09aaf09-2a8f-4de6-961f-878527a809bb)
![Screenshot (4)](https://github.com/surfbryce/beautiful-lyrics/assets/100030972/b4748e2b-f402-44af-850c-3558af91d9d6)

Please fix this ASAP
Thank you.

**Comment by Lazylllama** [comment]
Same thing for me.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74909150/353d9d17-14ee-4103-8d45-bd49a89de833)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74909150/3210ffdc-2c07-4eb2-aa08-99b18ea4f0e6)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74909150/685dad3f-6b49-40f7-90df-aaf687a6ced7)

**Comment by bxg5** [comment]
same.

**Comment by PikzAlex** [comment]
Same here

**Comment by surfbryce** [comment]
@xdBarun Spotifys most recent update broke the Extension, this will be fixed in the next patch
