### ISSUE TITLE
Lyrics button not showing up (404)

### ISSUE THREAD

**Issue by PassiHD2004** [surfbryce/beautiful-lyrics#637]
OS: Arch Linux
Spotify Version (pacman): 1:1.2.37.701-1
Spicetify cli version(pacman): 2.36.11-1
Marketplace version: 1.0.2-1

Country: Germany 
DNS (if applicable): 1.1.1.1 (cloudflare)

Console: 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/59457929/1f546112-4be2-4e59-b76a-71310d4b3704)

Link that 404's: https://cdn.jsdelivr.net/gh/surfbryce/beautiful-lyrics@main/dist/beautiful-lyrics.js?time=1716732787050

Screenshot of button not showing up:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/59457929/9dd41bb1-40bb-4a4d-b6ac-d61ea466b697)

It works fine on windows btw, so it must be something with linux

**Comment by surfbryce** [comment]
@PassiHD2004 You have the wrong version of Beautiful Lyrics installed, it should be ".mjs" not ".js"

**Comment by PassiHD2004** [comment]
So i just did some testing and double checked and i DO have the correct version installed.......
