### ISSUE TITLE
when will the next patch come?

### ISSUE THREAD

**Issue by Zyanbob** [surfbryce/beautiful-lyrics#642]
with some many issues with the label "in next patch" many more days since "this wednesday" i just want to ask when the 15+ issues will be fixed in 4.1 of beautiful lyrics

**Comment by surfbryce** [comment]
@Zyanbob For the time being I'm probably just going to stop giving out dates or times and just say "it comes out when it comes out", it is pretty much ready though so I'll hopefully get it out very soon
