### ISSUE TITLE
[Bug]: Lyrics not loading

### ISSUE THREAD

**Issue by MFM929** [surfbryce/beautiful-lyrics#652]
### Bug Report Checklist

- [X] **If you are making a Bug Report about the Extension being broken in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics
- [X] **If you are making a Bug Report about Lyrics in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

### What happened?

The lyrics are not showing up completely, only blank "boxes" or lines like they're not loading. 

### The country you are from

Argentina

### Spotify/Spicetify Version

Spotify for Windows (64 bits) 1.2.38.720.ga4a70a0e / Spicetify v2.36.11

### What os are you seeing the problem on?

Windows

### Screenshot of the entire Console

![Captura de pantalla 2024-05-28 215816](https://github.com/surfbryce/beautiful-lyrics/assets/171102990/e306070a-a00b-48bb-aa58-5cd9c00bc72a)

**Comment by theliamking** [comment]
Same issue but with sidebar aswell.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/99769726/be115cc3-327a-43f2-ba1e-a8e83bb9c6ed)

**Comment by poibear** [comment]
This issue could be related to Spotify testing out a feature that requires free users to have Spotify Premium to access lyrics (if Beautiful Lyrics is only accessing Spotify's lyrics database). I am also facing the same issue right now for well-known songs that I have seen lyrics posted for before.

**Comment by 1RehmanAli** [comment]
Same happening to with me
![image_2024-05-29_091016847](https://github.com/surfbryce/beautiful-lyrics/assets/111075277/c7eeecb8-1342-42cd-ad45-1f652b0219ec)
![image_2024-05-29_091036348](https://github.com/surfbryce/beautiful-lyrics/assets/111075277/53dedd1a-3a56-4d88-be20-a646ddfab23c)

**Comment by surfbryce** [comment]
Duplicate, closing all bugs until next patch comes out
