### ISSUE TITLE
Background showing on every page, makes spotify unusable

### ISSUE THREAD

**Issue by benomat** [surfbryce/beautiful-lyrics#655]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

all pages look pretty much the same(see image), lyrics page also doesnt show any lyrics

![image](https://github.com/surfbryce/beautiful-lyrics/assets/71938735/5d9609e6-0995-422f-91ba-feadabf2771b)

### What Country are you from?

Germany

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Shortcut doesnt do anything (if there's a different way to get this information please reply with how)

### Spotify HTML/CSS and Console Screenshots

Shortcuts for html and css dont't do anything  (if there's a different way to get this information please reply with how)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71938735/ad4367ef-a8f5-4458-8a20-2afda47afc60)

### Information Checklist

- [ ] Spotify/Spicetify Information
- [ ] Spotify HTML File
- [ ] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@benomat Yeah sorry about the shortcuts not working yet, that's because the newest patch isn't out, so bug reporting is on freeze, I think everything is ready for it to come out today, you'll find out soon!
