### ISSUE TITLE
It's All blank, no lyrics.

### ISSUE THREAD

**Issue by Prithivi2139** [surfbryce/beautiful-lyrics#656]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

It used to work really well until last week when i clicked the lyrics button it was just blank, I found a workaround to still get the lyrics by entering fullscreen until today, it just loads and loads and the lyrics don't ever appear.

I can't even get the spotify/spicetify information.

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Can't get this

### Spotify HTML/CSS and Console Screenshots

![Screenshot (237)](https://github.com/surfbryce/beautiful-lyrics/assets/70689835/eb51b7cf-d5d4-4447-8474-a01a33d67232)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Prithivi2139 Sorry for the shortcuts not working yet, they won't be available to use until the next patch (which fixes all these bugs), that should be coming out today so just look out for it
