### ISSUE TITLE
Multiple artists in Fullscreen not displaying correctly

### ISSUE THREAD

**Issue by Alehaaaa** [surfbryce/beautiful-lyrics#658]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The placement of the artists list (when there are enough to trigger the horizontal back and forth animation), looks wrong or doesn't animate at all.

https://github.com/surfbryce/beautiful-lyrics/assets/105360073/9fa3e3a7-c911-4ae2-b1e3-d20f8033b006

### What Country are you from?

Germany

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.36.959.g04bf500c
Spotify Runtime: cef_122.1.13+gde5b724+chromium-122.0.6261.130
Spicetify Version: 2.36.11
Spicetify Theme: Simple Outline / Default
Spicetify Extensions: [utilities.js, quickQueue.js, power-bar.js, adblock.js, beautiful-lyrics.mjs, volume-plus.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15490184/Spotify.html.txt)
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15490185/Spotify.css.txt)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/105360073/1fb2d25c-b49e-4e79-bff6-b3fd627c57b3)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Alehaaaa** [comment]
Hope i didnt miss any critical information.
Anything else you need, dont hesitate to ask for.

**Comment by surfbryce** [comment]
@Alehaaaa I've replicated it using the songs you showed. I'll work on this and there should be patch very soon

**Comment by surfbryce** [comment]
@Alehaaaa Should be published now, reload Spotify or wait for it to auto-update
