### ISSUE TITLE
Side card background not displaying correctly

### ISSUE THREAD

**Issue by magnusssz** [surfbryce/beautiful-lyrics#662]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The background is only being shown on top, where the playlist title is

![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/9fc9d063-e5c2-4892-8f2c-ecf154b0fbf0)

### What Country are you from?

Brazil

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify para Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11

### Spotify HTML/CSS and Console Screenshots

[Spotify.zip](https://github.com/surfbryce/beautiful-lyrics/files/15491043/Spotify.zip)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/ca871c46-3230-4355-b31b-694147034cbd)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by iam-siphon** [comment]
same

**Comment by MS-64** [comment]
Try disabling the experimental feature called "Extract Background color based on artwork image". When I enable this I get the exact same issue but but disabling this fixes it.

**Comment by magnusssz** [comment]
> Try disabling the experimental feature called "Extract Background color based on artwork image". When I enable this I get the exact same issue but but disabling this fixes it.

yes that's it. fixed! thank you

**Comment by surfbryce** [comment]
@MS-64 Thank you for pointing out what causes it and thank you @magnusssz for confirming that is the issue, I'll make sure to have a fix pushed out for this tomorrow so you don't have to disable it (causes confusion either way)

**Comment by surfbryce** [comment]
@magnusssz Tried out your files and it should be fixed in the next patch, thank you for reporting!
