### ISSUE TITLE
[Feature Request] Add Local .lrc files

### ISSUE THREAD

**Issue by iPixelGalaxy** [surfbryce/beautiful-lyrics#663]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Want to be able to add lyric files for local songs.

### What is your Suggestion?

A feature like in Lyrics-Plus to import .lrc files.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@iPixelGalaxy Will never be added, there will be a Lyrics Editor update in the future but there will never be support to add lyric files.
