### ISSUE TITLE
Extension not launching on spotify v1.2.15.826.g633ad967

### ISSUE THREAD

**Issue by DrasticT** [surfbryce/beautiful-lyrics#664]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

This has been an ongoing issue for a few week now. Before, the extension did launch but there were no lyrics and the button on the playbar was broken. Now it just outright not there anymore, even the full screen! So I cant use the shortcut to get the CSS and HTML file.

https://github.com/surfbryce/beautiful-lyrics/assets/95600216/26f18e98-271c-4197-813f-3125aa446088

I love this extension and I hope there is a fix to this!

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify for Windows (64 bit)
1.2.15.826.g633ad967
Spicetify v2.36.11
Theme: Bloom / darkmono
Extensions: shuffle+.js, adblock.js, beautiful-lyrics.mjs, theme.js
Custom apps: marketplace, better-local-files, lyrics-plus, stats, ncs-visualizer, history-in-sidebar

### Spotify HTML/CSS and Console Screenshots

![Spotify_sEL1OuM3kH](https://github.com/surfbryce/beautiful-lyrics/assets/95600216/56b7d5d6-a803-4523-92c2-418b241fc350)
![Spotify_2R3o1JGDHl](https://github.com/surfbryce/beautiful-lyrics/assets/95600216/73e55a48-b18c-468c-8bc3-ba821e3feeb1)
![Spotify_sudkvIRGNa](https://github.com/surfbryce/beautiful-lyrics/assets/95600216/bf2747f3-1b9a-4b05-b507-3bdb0abf798d)
![Spotify_hUh8x5FLMJ](https://github.com/surfbryce/beautiful-lyrics/assets/95600216/6bf78364-c8e9-4726-aed5-1a7dab80315a)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@DrasticT I'll see what I can do, the good thing is that there is an error, but your version of Spotify is EXTREMELY outdated. Do you have a reason for why it's so outdated? Not even Linux users are this far behind.

**Comment by DrasticT** [comment]
I used to be always up to date with Spotify but my extension kept breaking. As a result, I stopped updating which happens to be on this ancient version. Why fix it if it ain't broke (Well it is now)? 

As I said, Beautiful-Lyrics was working for me and most extensions/themes still work so I don't see the point in updating.

**Comment by AylenSK** [comment]
Same here.

I have Spotify for Windows (64 bit)
1.2.5.1006.g22820f93
Spicetify v2.36.11

In my case, I have Windows 8.1 and I can't update Spotify 'cause the most recent versions aren't compatible with my operating system.

**Comment by AylenSK** [comment]
@surfbryce Thanks a lot! :)

**Comment by DrasticT** [comment]
Confirmed working, thanks @surfbryce! 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/95600216/6147c39b-611d-4da1-9993-ed15c76a9caf)
