### ISSUE TITLE
[Bug Fix/Improvement] Spotify DJ Fullscreen State

### ISSUE THREAD

**Issue by iPixelGalaxy** [surfbryce/beautiful-lyrics#665]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

Sometimes I like to put on the Spotify DJ because I get bored of the stuff I'm putting on. Currently if you turn on DJ it exits fullscreen, it used to stay in fullscreen and be bugged then go onto lyrics.

https://github.com/surfbryce/beautiful-lyrics/assets/42526028/008104a8-109f-479f-a4fd-e7b7cd116edd

### What is your Suggestion?

DJ gets his own fullscreen state and doesn't kick out of fullscreen.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@iPixelGalaxy This should work in the next patch, thanks for suggesting!

**Comment by emmaphoto** [comment]
hey how did you get the search bar at top with the home buttons n stuff there?

**Comment by iPixelGalaxy** [comment]
> hey how did you get the search bar at top with the home buttons n stuff there?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/42526028/09ac6750-5e6e-466e-9dc3-9ec780400e30)
