### ISSUE TITLE
Add option to disable Dynamic Backgrounds

### ISSUE THREAD

**Issue by AegeanExe** [surfbryce/beautiful-lyrics#669]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

_Some themes use their own background / theme layout, the Dynamic Backgrounds sometimes do not fit well with the custom theme._

**Example:** Theme hazy uses the track background through the whole interface, Beautiful Lyrics' Dynamic Backgrounds just don't fit well sometimes as seen in example below.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/97281673/f1bc2800-7817-4134-872f-c9c226b2c8f3)

### What is your Suggestion?

An option to disable Dynamic Backgrounds would be a great addition.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by cariosa** [comment]
This option also allows users to minimize cpu usage (useful when running a laptop on battery), which is a must feature in my opinion.
