### ISSUE TITLE
Cover-Art Not Aligned properly

### ISSUE THREAD

**Issue by Firmeteran** [surfbryce/beautiful-lyrics#67]
Hi. Really like the new Fullscreen Mode thing, but just the position of cover image and now playing need to be adjust more to the right.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/1a1f151d-3c08-484b-a6c9-04af04dce606)

**Comment by surfbryce** [comment]
@Firmeteran This is super weird - it shouldn't look like this at all. Can you send a screenshot of the entire screen?

I need to see what your aspect-ratio looks like as well as anything else that can help me figure out why this is happening for you. Also do you have a theme applied? 

The theme could be messing my stuff up - so if you have one please send the name of it so I can test with it and see how I can make this theme-tamper proof.

**Comment by Firmeteran** [comment]
Sure. Also I don't have any theme installed, just default one. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/17ab0076-7a8c-4275-b857-19a719a2ca5f)

**Comment by surfbryce** [comment]
@Firmeteran Can you restart Spotify and make sure it's not a fluke? I'm just trying to think how it could get like this.

Also if you could provide the resolution of the monitor you have it fullscreen on that would be awesome - it would help me replicate your exact view.

For example, this is what mine looks like on the Apple Mackbook 16:10 screen:
<img width="1728" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/364121c8-b4f4-4822-8396-ab9ef3a228ba">

**Comment by Firmeteran** [comment]
@surfbryce Sure. Already try restart the Spotify and still the same thing. Also, my resolution are 1920x1080 (ofc on 16:9).
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/6e828513-7ba9-4b5c-89f2-41ab9dbf1334)

**Comment by surfbryce** [comment]
@Firmeteran And one more thing - what version of Spotify/Spicetify are you on?

You can find that out via this;
- If you are on windows, click the three dots in the top left and go to about and screenshot that
- If you are on mac, just go to Spotify in the navigation bar and click about and do the same

**Comment by Firmeteran** [comment]
@surfbryce Always up-to-date. Anyway, here's the full thing that i've installed.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/59782fd6-446f-4a68-bb3b-c83ed259e64e)

**Comment by surfbryce** [comment]
@Firmeteran Alright I'll have to look into this more tomorrow (for me).

It doesn't seem to be the resolution that is the issue so there's definitely something else funky going on.

Are you on Windows or Mac? I am on Mac so if you're on Windows it could be a Windows issue.

**Comment by Firmeteran** [comment]
> @Firmeteran Alright I'll have to look into this more tomorrow (for me).
> 
> It doesn't seem to be the resolution that is the issue so there's definitely something else funky going on.
> 
> Are you on Windows or Mac? I am on Mac so if you're on Windows it could be a Windows issue.

Don't worry, take your time. Forgot to mention that, I'm on Windows 10.

**Comment by surfbryce** [comment]
Alright @Firmeteran - tested on windows and this might be a you-only issue. I am pushing out an update for better theme support and some of the changes made might fix this issue for you. I'm pushing the update out soon so by the time you try this out hopefully it's fixed for you. Make sure you're on 3.1.2 or greater.

**Comment by Firmeteran** [comment]
> Alright @Firmeteran - tested on windows and this might be a you-only issue. I am pushing out an update for better theme support and some of the changes made might fix this issue for you. I'm pushing the update out soon so by the time you try this out hopefully it's fixed for you. Make sure you're on 3.1.2 or greater.

Hi again, after reinstalling everything,
I think we're good now, right?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/12680810/2d13ea36-99c0-4149-84e8-eedc539d2cbc)

**Comment by surfbryce** [comment]
@Firmeteran Yep that looks right! Glad it's working for you now - thanks for reporting and helping me out - I appreciate it thank you!

I'll close this now since it seems like it works for ya - if you run into any issues please lmk
