### ISSUE TITLE
Lyrics do not return to Sidebar when switching between NPV and Play Next views

### ISSUE THREAD

**Issue by HRTK92** [surfbryce/beautiful-lyrics#672]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The lyrics are not displayed in the sidebar. Also, the background gradient is disabled.

How to reproduce
This problem occurs when the song and lyrics are displayed in the sidebar, click “Play Next” and return to the “Playing View”.

https://github.com/surfbryce/beautiful-lyrics/assets/70054655/b0b910d4-0206-49c4-9e16-49f66959951f

### What Country are you from?

Japan

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.38.720.ga4a70a0e
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.11
Spicetify Theme: 
Spicetify Extensions: [Vibrant.min.js, beautiful-lyrics.mjs, adblock.js]
Spicetify Custom Apps: [marketplace, lyrics-plus]

### Spotify HTML/CSS and Console Screenshots

[Spotify.zip](https://github.com/surfbryce/beautiful-lyrics/files/15500767/Spotify.zip)
Sorry, HTML and css cannot be uploaded, so I zipped the file.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/70054655/3f8dd171-528c-4773-af51-4fa115c43b65)

### Information Checklist

- [x] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Droppisalt** [comment]
Same issue over here on Fedora (located in Canada)

**Comment by surfbryce** [comment]
@HRTK92 Tested this on multiple versions and this will be fixed in the next patch, thank you for reporting!
