### ISSUE TITLE
Option to enable dynamic background in friend activity too

### ISSUE THREAD

**Issue by GamablobYT** [surfbryce/beautiful-lyrics#676]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I noticed there was an issue #578 which was fixed where the dynamic background was being applied to the friend activity tab. I quite liked it and was disappointed to see the plain old friend activity tab after the latest update

### What is your Suggestion?

Add an option to enable dynamic background to the friend activity tab too

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@GamablobYT Won't be supported, background is for media related elements only.
