### ISSUE TITLE
Option to choose a font (such as the new Spotify font)

### ISSUE THREAD

**Issue by aquakira** [surfbryce/beautiful-lyrics#679]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Since I used the mobile app for Spotify I noticed the updated font, and actually really liked it. I have been wanting to experiment with other fonts as well

### What is your Suggestion?

As a quick button in full-screen view or at the top in the regular view there could be a sub menu with a drop-down including a bunch of fonts, whether installed on your computer or a set list. (including the two Spotify fonts)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/81239909/2daacf9b-e1ab-4216-abeb-2b61be66c026)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/81239909/49e16e63-dfe6-4435-ad56-762486bc291e)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by hubertheodore** [comment]
If possible we can add our custom font, like the one Chinese Characters with the Pinyin writings on top.

**Comment by surfbryce** [comment]
@aquakira There won't be an option for this ever, this is more the job of a CSS Snippet through Marketplace.
