### ISSUE TITLE
Incorrect extension version after Specetify Marketplace update

### ISSUE THREAD

**Issue by baechooYT** [surfbryce/beautiful-lyrics#68]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/66154521/4abd50ec-e2a0-42cc-a65e-979f3b7137e7)
Using 3.1.1 but shows 3.0.9

![image](https://github.com/surfbryce/beautiful-lyrics/assets/66154521/b41171ad-e089-47ed-90c7-377f9c5f50f8)
Specetify Marketplace 0.8.7

Downloaded from: Spicetify Marketplace
I tried:
Re-installing from marketplace
Installing by CLI
Downloading from Github Releases

It was not saying me to upgrade it before i didn't update specetify marketplace.

**Comment by baechooYT** [comment]
I am sure i'm on v3.0.9 because it has fullscreen mode that only exists on 3.1.0 or higher
![image](https://github.com/surfbryce/beautiful-lyrics/assets/66154521/8c8c95e6-254e-4765-b5d3-ae105d94dc82)

**Comment by surfbryce** [comment]
@baechooYT It says it right in the screenshot. It went from the Marketplace version of 3.0.9 to 3.1.1

Marketplace uses a cached version (basically an older version) of the extension for like an entire day - so my auto-updater goes around that.

Marketplace will always be a day behind but my auto-updated always uses the latest version. So it's just telling you that you went from version 3.0.9 to 3.1.1
