### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by PwccaCode** [surfbryce/beautiful-lyrics#681]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

After the new release the extension stopped showing the button to open the lyrics page.

the shortcuts also dont work to capture the html and css file. so imagine the extension is not even loading

### What Country are you from?

Brazil

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify for Windows (32 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
xpui_2024-05-17_1715913620018_a4a70a0
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake

### Spotify HTML/CSS and Console Screenshots

![console](https://github.com/surfbryce/beautiful-lyrics/assets/51799102/a54aa111-67b1-41ca-94e5-f920508539e3)
[element.txt](https://github.com/user-attachments/files/15508066/element.txt)
[xpui.css.txt](https://github.com/user-attachments/files/15508068/xpui.css.txt)
i grabbed the html and css the old way since from what i remmember the first time opening an issue here.
If its wrong please let me know how to grab properly

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by benomat** [comment]
same here

**Comment by PwccaCode** [comment]
started working again today, no changes were made go figure,

**Comment by benomat** [comment]
still not working for me
