### ISSUE TITLE
Add more lyrics sources

### ISSUE THREAD

**Issue by Satanarious** [surfbryce/beautiful-lyrics#682]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

There are a lot of songs with no synced lyrics.

### What is your Suggestion?

Sources that you can add for synced lyrics:
- [Musixmatch](https://www.musixmatch.com/)
- [Deezer](https://www.deezer.com/)
- [Lrclib](https://github.com/tranxuanthang/lrcget/issues/2#issuecomment-1326925928)
- [Netease](https://music.163.com/)
- [Megalobiz](https://www.megalobiz.com/)

Alternatively, you can checkout [this](https://github.com/moehmeni/syncedlyrics) repo I found that implements all these in a python application

Sources that you can add for unsynced lyrics:
- [lyrist](https://github.com/asrvd/lyrist)
- [Genius](https://genius.com/)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Satanarious A lot of these actually have HUGE issues with reliable lyrics, the only one not necessarily being inaccurate most of the time being Musixmatch.

I plan in the future to have Musixmatch be the fallback to Apple Music, but the rest will never be supported.

**Comment by Satanarious** [comment]
I was suggesting them as a chain of fallbacks
