### ISSUE TITLE
beautiful lyrics button disappearing right after start

### ISSUE THREAD

**Issue by benomat** [surfbryce/beautiful-lyrics#689]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

the beautiful lyrics button in the bottom right is not visible. It disappears right after the launch of spotify. If you click it in that short time it shows loading lyrics and then closes.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/71938735/8d5711d2-3899-4e70-8fdc-1f7fd8c32b23)
^^this is what it looks like after spotify completely launching

Clicking the icon when its visible:

https://github.com/surfbryce/beautiful-lyrics/assets/71938735/16961aee-ce8c-41d1-969a-5353b8946bc3

### What Country are you from?

Germany

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.13.661.ga588f749
Spotify Runtime: undefined
Spicetify Version: 2.36.11
Spicetify Theme: marketplace
Spicetify Extensions: [adblock.js, beautiful-lyrics.mjs, playlist-icons.js, quick-add-to-queue.js, css-editor.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

The shortcuts for these dont seem to be working. If you need them you can probably check out #681 as its the same issue just that it resolved for him after a day.

Console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71938735/27a1d93d-bfc8-4338-bbb5-f01f9fab8d7d)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@benomat Had to look into this first to determine if it is a duplicate, but it is one of #664
