### ISSUE TITLE
blank screen after clicking "enter cinema"

### ISSUE THREAD

**Issue by Dr0mus** [surfbryce/beautiful-lyrics#69]
I tried the extension but whenever I go to a song and click "enter cinema" all that appears is a blank screen with nothing.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/38384816/562b7c94-f2c1-41a5-8713-c59f8d2d6578)

**Comment by surfbryce** [comment]
@Dr0mus Have you tried restarting Spotify? Also what version of Spotify/Spicetify are you on?

You can find this on Windows by going to the three dots in the top left and clicking About or on Mac by going to Navigation bar -> Spotify -> About Spotify

**Comment by Dr0mus** [comment]
Yes I have tried restarting Spotify, the issue persists. "Spotify for unknown
1.2.16.947.gcfbaa410
Spicetify v2.21.0"
just copied and pasted

**Comment by surfbryce** [comment]
@Dr0mus It's weird that it says unknown, are you on Linux by chance?

Also do you have Library X enabled - or are you using a theme to restore the old look? If so let me know the theme so I can see if there are any conflicts.

Additionally, if you could run the "spicetify apply enable-devtools" command and then right click on an open space that doesn't trigger Spotifys content-menu and open up "Developer Tools" and go to the Console tab and then screenshot everything there that would be awesome - thanks!

**Comment by Dr0mus** [comment]
I am not on linux, I am on windows 11. I don't think I have Library X enabled (?). I am not using a theme to restore the old look. I have no themes installed. The only extensions I have enabled are 'Adblock", "beautiful lyrics" plus a few snippest: "Fix Liked icon", "Fix episodes icon", "Rounded now playing bar", "Fix main view width", "Hide upgrade button". Which are all from the marketplace and popout lyrics which is from .js file. Here's a screenshot of console. An error did appear when I tried to click cinema mode (believe the last 2 or 3). 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/38384816/f4b1112c-e960-48dd-a50f-97cfcc7622b9)

**Comment by surfbryce** [comment]
@Dr0mus I think one of those errors are mine so I'll have to take a deeper look.

What I would recommend is going into Experimental Features and searching up "Library X" and see if that shows anything.

The main issue is that your Spotify still looks like this when it shouldn't:
<img width="825" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/ca5d3bf2-83d2-4580-804f-db51f7a4b85d">

Spotify doesn't officially have this edge-edge panel layout anymore - they're all resizable and gap-based. So try searching that up - otherwise try reinstalling Spotify.

**Comment by Dr0mus** [comment]
1. I did see library x
2. Reinstalled spotify and spicetify and it solved the issue, ty!
I don't know if you want to keep this open or not.

**Comment by surfbryce** [comment]
@Dr0mus Perfect - glad it's working now! I think for some reason your Spotify was still running an old version of the interface even when it said it was on the latest version!

I'll close the issue since this isn't typically an issue with the extension - I'll add this to the FAQ though. Thank you!
