### ISSUE TITLE
Lyrics in NPV are glitching out.

### ISSUE THREAD

**Issue by MS-64** [surfbryce/beautiful-lyrics#693]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Lyrics in Now Playing View are glitching out and makes clicking the lyrics very difficult. I have also just done a complete reinstall of Spotify and Spicetify but the bug is still present. Closing and reopening the Now Playing View seems to fix until switching songs. This bug also seems to lag spotify a lot. Did not happen before 4.1.2.

https://github.com/surfbryce/beautiful-lyrics/assets/141533012/f07470b3-26a6-4b0c-a7a8-b4aaf43f828f

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.38.720.ga4a70a0e
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/surfbryce/beautiful-lyrics/assets/141533012/f8c38eda-fa15-4f05-89be-fa3e35f1fd56)
[HTMLCSS.zip](https://github.com/user-attachments/files/15543482/HTMLCSS.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Marmur2020** [comment]
#694 here's the reason for this error (recommend reviewing)

**Comment by kilyabin** [comment]
same problem

**Comment by TechnoStone** [comment]
https://github.com/surfbryce/beautiful-lyrics/assets/26044948/cac37039-3a5b-402b-a02c-c4634c801083

looks funny lul

**Comment by Videogame-Oscar** [comment]
same problem here
