### ISSUE TITLE
[Bug] Forever update background in "Open lyrics page" 

### ISSUE THREAD

**Issue by Marmur2020** [surfbryce/beautiful-lyrics#694]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

**Video:** https://youtu.be/Ap7upLWz42c
Open the "Now playing view" -> Open lyrics page -> Enter cinema -> Close. Foverev update background in "Open lyrics page" and text doesn't change color and not shine

### What Country are you from?

Ukraine

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.37.701.ge66eb7bc
Spotify Runtime: cef_122.1.13+gde5b724+chromium-122.0.6261.130
Spicetify Version: 2.36.11
Spicetify Theme: marketplace
Spicetify Extensions: [adblock.js, beautiful-lyrics.mjs, volumePercentageWrapper.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/surfbryce/beautiful-lyrics/assets/109208530/0e174748-9af7-4ceb-9cf7-b075c0c59ff6)
[Spotify css html.zip](https://github.com/user-attachments/files/15546596/Spotify.css.html.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by kilyabin** [comment]
You don't have to enable fullscreen lyrics for glitch, it happens even after just switching tracks
