### ISSUE TITLE
Font lyrics just outline

### ISSUE THREAD

**Issue by abdulsfat** [surfbryce/beautiful-lyrics#70]
![Screenshot (11)](https://github.com/surfbryce/beautiful-lyrics/assets/91750942/6f16afa3-e890-4d17-bcdb-ce47e4973497)

**Comment by abdulsfat** [comment]
ziro by schnensch

**Comment by surfbryce** [comment]
@abdulsfat yeah I'm almost certain this is a rendering issue on your side. There's nothing on my code that can do that and in terms of other extensions/themes affecting it I use completely different set of lyric CSS classes/ids/objects to what Spotify uses so none should affect the lyrics themselves.

I am assuming you must have inverted/contrast settings enabled which causes anything chromium to do that. I would also just recommend restarting Spotify and seeing if that fixes it.

**Comment by abdulsfat** [comment]
Okay, thanks, I'll try.

**Comment by abdulsfat** [comment]
I've tried restarting Spotify, but it still looks the same.
![Screenshot 2023-07-24 144648](https://github.com/surfbryce/beautiful-lyrics/assets/91750942/4159c7ab-dbb8-4f5d-847c-9b04f3f291a3)

**Comment by surfbryce** [comment]
@abdulsfat Well I know it's not my extensions fault direct - so there has to be something else messing with it. Can you go to the Installed tab in Marketplace and screenshot everything you have installed?

**Comment by abdulsfat** [comment]
sure
![Screenshot (13)](https://github.com/surfbryce/beautiful-lyrics/assets/91750942/0b12ac6b-3706-4554-b6c3-a68a414aaf53)

**Comment by surfbryce** [comment]
@abdulsfat I'm not sure what I can to be honest - this isn't an issue with my extension and is a rendering issue with your Windows installation. The only thing I can think of is that your windows performance settings are messing up the rendering. You can try toggling some stuff by searching up Advanced System Settings -> Performance Section -> Settings Button. Check to see if "Animate controls and elements inside Windows" is enabled as well
