### ISSUE TITLE
Beautiful Lyrics icon isn't showing

### ISSUE THREAD

**Issue by SkeJm** [surfbryce/beautiful-lyrics#705]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The icon just isn't there. The extension doesn't work for me since around a week.
It's a fresh install spotify from website + spicetify cli

### What Country are you from?

Poland

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

It doesn't work

### Spotify HTML/CSS and Console Screenshots

Doesn't work also.

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@SkeJm Use the three dots in the top left to get your spotify/spicetify information from "About Spotify", also the console should work, are you following the instructions correctly?

**Comment by SkeJm** [comment]
Spotify na Windows (64-bitowa wersja)
1.2.39.578.g0ea3f38b
Spicetify v2.36.12
xpui_2024-05-31_1717155884878_0ea3f38
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake

**Comment by SkeJm** [comment]
@surfbryce I have it installed with marketplace now. Still doesn't work.

**Comment by surfbryce** [comment]
@SkeJm Ok, well I still need you to do that "Screenshotting the Console" step, that should absolutely work since you are on Windows

**Comment by SkeJm** [comment]
@surfbryce  ![image](https://github.com/surfbryce/beautiful-lyrics/assets/36744236/58578267-2a20-46c7-a6b0-f0504686a3a0)

**Comment by surfbryce** [comment]
@SkeJm What was at the top of the console prior to you scrolling? If you could include a screenshot of that as well that would be great

**Comment by SkeJm** [comment]
@surfbryce here,
![image](https://github.com/surfbryce/beautiful-lyrics/assets/36744236/eee3633d-2da9-4f32-b9c0-fcf04726ed8e)

**Comment by surfbryce** [comment]
@SkeJm Can you hover over this link or copy it (maybe by right clicking) somehow? I'm wondering if this is the link to my extension that Marketplace uses, if you could somehow get the full link that would be great.
<img width="665" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/346f299f-b80f-4b95-9387-d9d295a2f205">

**Comment by SkeJm** [comment]
@surfbryce cdn.jsdelivr.net/gh/…me=1717771374286:24

**Comment by SkeJm** [comment]
@surfbryce wait, can't copy it

**Comment by SkeJm** [comment]
@surfbryce It's like this in log also, can't copy it

**Comment by surfbryce** [comment]
@SkeJm are you able to click the link itself? And if you can, does that bring you to the "Sources" tab in the "Developer Tools" window

**Comment by SkeJm** [comment]
@surfbryce I can't open it, but when right clicked it shows "hide messages from beautiful-lyrics.js" so it's your extension

**Comment by surfbryce** [comment]
@SkeJm I'm not sure why it's saying "beautiful-lyrics.js" it should be "beautiful-lyrics.mjs", I kind of assume that was the issue because of the error message.

Make sure that marketplace is fully updated (rerun the install command from the website for Marketplace)

**Comment by SkeJm** [comment]
@surfbryce it says ".mjs" sorry i misspelled it.

**Comment by surfbryce** [comment]
@SkeJm Still, make sure that Marketplace is fully updated. That error isn't possible if it's being loaded in correctly, if you're using an older version of Marketplace it's probably trying to load it in the old way.

**Comment by SkeJm** [comment]
@surfbryce Shouldn't marketplace update when updating spicetify via cli? How do i update it?

**Comment by surfbryce** [comment]
@SkeJm No marketplace does not update with Spicetify, Marketplace is just another extension just like Beautiful Lyrics; run the command to install Marketplace from the Spicetify websites install page

**Comment by SkeJm** [comment]
@surfbryce Alright, now it works, Thank you! Is there any way to update all extensions in one go?

**Comment by surfbryce** [comment]
@SkeJm Beautiful Lyrics automatically updates, all the other extensions will automatically update via Marketplace eventually (if you installed them that way), if you installed the extensions manually, Beautiful Lyrics is likely the only one that will update automatically, otherwise you have to update them manually yourself.

**Comment by SkeJm** [comment]
@surfbryce okay thank you for help.
