### ISSUE TITLE
Full screen mode issue

### ISSUE THREAD

**Issue by sagardroid007** [surfbryce/beautiful-lyrics#707]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I'm not able to get the song details in the full screen mode , but i can see the lyrics very well 

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

![Uploading Screenshot (107).png…]()

### Spotify HTML/CSS and Console Screenshots

..

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@sagardroid007 Please remake this bug-report with everything done correctly
