### ISSUE TITLE
Canvas feature reduces screen real estate to display lyrics (when the sidebar is bigger)

### ISSUE THREAD

**Issue by cariosa** [surfbryce/beautiful-lyrics#708]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

with canvas turned on and depending on sidebar size it currently looks like this:
![spotify_beautiful_lyrics_screenshot](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/79bef7e8-ed6b-4249-873e-168665ca0d8f)
where you can't view the lyrics fully.

### What is your Suggestion?

In my opinion it would look much better if these parts are removed as they're redundant:
![redundant_part_screenshot](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/9275986e-8cee-4fbd-bee2-03645df79a72)

so it would just be lyrics without borders and the bar, while the hoverable buttons would appear in front of lyrics, 
Of course consider this suggestion only if it's doable and it doesn't look worse.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@cariosa I probably won't hide that track information in the sidebar just because some people would argue it's not as redundant as you state.

Although I agree that when canvas is enabled it does needlessly push the lyrics down too far, so I'll work on moving those items up when canvas is enabled so that it looks good.

**Comment by surfbryce** [comment]
@cariosa Alright so it looks like Spotify made a change so that this information is lifted up by default, and if you click on the canvas video it'll move down, and clicking it will toggle between these two states.
