### ISSUE TITLE
Support Genius lyrics provider

### ISSUE THREAD

**Issue by cariosa** [surfbryce/beautiful-lyrics#709]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I used to like the genius provider in lyrics plus, It provides context behind the lyrics and artists. Many people seemed to use it.

### What is your Suggestion?

Is it possible to add this feature only in lyrics page or cinema mode, You can authenticate with genius and use the ID (like strawberry player does), but I don't know if it's possible with a spicetify extension.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@cariosa This will never be supported and there is no plan to.
