### ISSUE TITLE
Theme Incompatibility with Fullscreen Mode

### ISSUE THREAD

**Issue by Harjuuso** [surfbryce/beautiful-lyrics#71]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/69907019/2b3d1783-7cda-4b86-818f-a6bff6d0a2f9)

**Comment by surfbryce** [comment]
@Harjuuso That's Fullscreen mode - Cinema mode is another view-type.

What theme are you using?

**Comment by Harjuuso** [comment]
Oh! How do I enable cinema?
Ziro is my theme.

**Comment by surfbryce** [comment]
@Harjuuso When you open up the lyrics-page and you hover over it you'll see at the top the button to open it.

Also there is an issue with the Ziro theme in fullscreen so I'll push out an update soon that fixes it

**Comment by Harjuuso** [comment]
Okay! Thanks for the quick answers. Goodluck and I will be waiting

**Comment by surfbryce** [comment]
@Harjuuso Alright the update should be out - thank you for reporting this issue!
