### ISSUE TITLE
Translation for lyrics to native language

### ISSUE THREAD

**Issue by cariosa** [surfbryce/beautiful-lyrics#710]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

You can better understand foreign language lyrics.

### What is your Suggestion?

There's a feature request on [spicetify-cli](https://github.com/spicetify/cli/issues/2322) and an [extension](https://github.com/Richie-Z/romajin) (but it doesn't work for me). 

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@cariosa Translation is a very tip-toey field and it can often be completely wrong. In the future there will be a Lyrics Editor where people can submit translated versions (if they are verified translators for that specific language), this is ideally the more correct and accurate way to handle things like this.

There are a lot of languages where metaphors and etc. don't translate literally into another language (you'll often see this with English going into other languages, it's a very difficult to do it accurately and in a way that honors the original intent)

**Comment by cariosa** [comment]
I think [musixmatch translations](https://www.musixmatch.com/lyrics/Natalia-LaFourcade/De-todas-las-flores/translation/english) are user contributed.

**Comment by surfbryce** [comment]
@cariosa I can't validate/ensure whether or not those are translated accurately and truthfully, when translation comes it will be done first-party and not relying on external services
