### ISSUE TITLE
I'm very lost on how to install or if it's even possible to install on mobile

### ISSUE THREAD

**Issue by Kirbo8** [surfbryce/beautiful-lyrics#713]
I found this extension while dwelling on the fact that you need premium in order to get lyrics and was immediately hooked but also confused there isn't any obvious way to install it at least not for mobile and well I just have no clue how to install it or if it's even possible to install it on mobile the only reason I ask is cuz it looks like the mobile layout in one of the gifs

**Comment by surfbryce** [comment]
@Kirbo8 This extension uses Spicetify, Spicetify is on Desktop only. This can't be installed on Mobile because those versions of Spotify are native to their platforms and don't support modifications like the Desktop version does.

**Comment by LeNerd46** [comment]
I might have something in the near future... (for Android)

**Comment by Kirbo8** [comment]
> I might have something in the near future... (for Android)

Is this possible? I've just been using x manager to patch Spotify and then genius lyrics to find them on the side but if you could find a way to get this kind of stuff to work on mobile I am all here for it

**Comment by LeNerd46** [comment]
Well it's not patching this into Spotify, but I'm making an app that does the exact same thing this does. It's not perfect, but in my opinion it's better than nothing
