### ISSUE TITLE
Weird diffrences between what's shown in the extension and what's on Musixmatch

### ISSUE THREAD

**Issue by Ammecareth** [surfbryce/beautiful-lyrics#715]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I'm wondering what could cause this issue, but some lyrics are synced only to the sentences when on musixmatch they are synced word-to-word. Since Musixmatch is your provider, as stated in another issue, why is there this problem ? Are the lyrics only updated once in a while and not constantly connected to Musixmatch ? Related to this issue, sometimes the word-to-word sync is a little to very out of timing. Again, when cheking on Musixmatch, it's synced perfectly. Do you know why the extension is behaving like that and is that something you think you could fix ?

(One very specific exmaple I have is Wife by (G)I-DLE, which is synced to the sentence in beautiful lyrics but word-to-word in Musixmatch)

### What Country are you from?

France

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.39.578.g0ea3f38b
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: Sleek / Deep
Spicetify Extensions: [beautiful-lyrics.js, beautiful-lyrics.mjs, fullAlbumDate.js, playNextWrapper.js, QueueTime.js, CoverAmbience.js, quickQueue.js, volumePercentage.js, spotifyGenres.js]
Spicetify Custom Apps: [marketplace, stats]

### Spotify HTML/CSS and Console Screenshots

Github says it doesn't support those files so here is a wetransfer with both : 
https://we.tl/t-gmFDf1Uc48 (it lasts 7 days, if it's down tell me and i'll reupload it)

![Capture d'écran 2024-06-07 193927](https://github.com/surfbryce/beautiful-lyrics/assets/105608311/a745cb53-b217-4c89-a0ab-8b7d8e761dd2)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Ammecareth Apple Music is the primary provider which indirectly uses Musixmatch, Musixmatch will be supported directly in the future as a fallback when AM does not have syllable-synced lyrics.
