### ISSUE TITLE
Bug in Fullscreen on songs with no lyrics

### ISSUE THREAD

**Issue by Nooterch** [surfbryce/beautiful-lyrics#720]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Album Art, and controls moved slightly offscreen when on a song with no lyrics.
I have tried with several different themes, and no theme at all, but the issue still persists. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93746692/834de9c4-8a10-4a30-87d2-d385865ef655)

(This is my first time doing a GitHub bug report, so apologies if I missed anything)

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.39.578.g0ea3f38b
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: Hazy / Base
Spicetify Extensions: [beautiful-lyrics.js, beautiful-lyrics.mjs, QueueTime.js, quickQueue.js, theme.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify HTML.zip](https://github.com/user-attachments/files/15750477/Spotify.HTML.zip)
[Spotify CSS.zip](https://github.com/user-attachments/files/15750479/Spotify.CSS.zip)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93746692/154e643a-ff78-4794-b466-ca896657abee)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Nooterch Just want to make sure that you are running the latest version of Spicetify Marketplace.

This error shouldn't be possible and the file name definitely not ending with ".js", it should be ".mjs".
<img width="574" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/0ac9311a-8e81-43d1-bb2b-910cb26be51f">

This is leading me to believe your Spicetify Marketplace is out of date, can you update that for me and report back if it still happens.

**Comment by Nooterch** [comment]
Bit of a dumb question, but how would I go about doing that?

**Comment by surfbryce** [comment]
@Nooterch Just run the Marketplace install command from the Spicetify install page

**Comment by Nooterch** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93746692/d15f4ea1-61b2-41f9-bd11-74004b666cdc)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93746692/77e4e1a3-6dc7-4683-a1c7-a3b1e6d08c98)
Running the command did not seem to help.

**Comment by surfbryce** [comment]
@Nooterch Actually, I know what is happening here. I should've looked at this first, BUT your Spicetify extensions: "[beautiful-lyrics.js, beautiful-lyrics.mjs, QueueTime.js, quickQueue.js, theme.js]" has the old beautiful lyrics installed, so what I recommend you to do is to go to the "Installed" tab in Marketplace, and uninstall Beautiful Lyrics. Once it is removed, restart spotify, go back to that same tab and if it is still there, uninstall it again. That should fix it I think.

**Comment by Nooterch** [comment]
That didn't work, but I did find the file after digging through file explorer for a few mins. It's working again, thanks :D
![image](https://github.com/surfbryce/beautiful-lyrics/assets/93746692/7e622136-8c15-4948-a2fe-5a59036c4ed7)
