### ISSUE TITLE
Where can i find the extension  js / modify the extension

### ISSUE THREAD

**Issue by wotikama** [surfbryce/beautiful-lyrics#724]
Is there any way i can get the  `beautiful-lyrics.js`  file to edit it? The version i had doesn't work anymore. It was a large file with all the chinese characters, the animation, blur, etc... I tried downloading form spicetify's marketplace and search on my pc but could not find it. I don't want this issue to be  a XY problem, my aim is to remove the blur. If there is a new way to do it, ill be glad to know.

**Comment by oldschoolvirgo** [comment]
The developer rewrote the extension without the Spicetify Creator so there is no .js file like before. 
If you want to remove the blur, you can use the Enable Local Overrides option in DevTools. 

The file you're looking for is beautiful-lyrics@<version>.css. 
It's in the Sources tab. Look for the extensions-storage.socalifornia.live node. 
Select all, and copy the code to your clipboard. 
Right-click the file and select override content. 
If it's your first time you might get prompted to create a folder, it's been a while, I cant recall.
Paste the code you copied. 
You can now make changes to the .css file and they will take priority over the original .css file.
You'll have to keep your override version up to date with any changes the developer makes. 
Good luck. 

Screenshot of blur removed:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/126725107/cc14b378-5bdf-48de-a8b0-3e826d4d0b34)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/126725107/8ce80a6c-be12-4f99-909a-f73bd41b9fb6)
