### ISSUE TITLE
wrong font for lyrics

### ISSUE THREAD

**Issue by adhamdawild** [surfbryce/beautiful-lyrics#744]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

WRONG  FONT IS SO FRUSTRATING, works just fine on my pc but on my laptop on which i edit (after effects) the font is weird for the lyrics on beautiful lyrics, the font appears to be georgia or times new roman or something, the rest of my spotify is normal even the paid lyrics are normal behind the premium pop up, can i change the font manually or is there a setting or is there any other solution 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/95062949/3fa695a3-f066-48ff-9c4c-09f6974dbc9a)

### What Country are you from?

united arab emirates

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.40.599.g606b7f29
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.36.13
Spicetify Theme: SpotifyNoPremium / Base
Spicetify Extensions: [beautiful-lyrics.mjs, adblock.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify.docx](https://github.com/user-attachments/files/15919213/Spotify.docx)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by adhamdawild** [comment]
i’m so sorry for wasting your time, all i did was restarted my laptop and it went back to normal 🤦‍♂️

**Comment by skyneli** [comment]
I want change font like this
