### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by Dirlaw** [surfbryce/beautiful-lyrics#745]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

settings for full screen or lyrics

### What is your Suggestion?

it would be good if you would add settings so that you can somehow adjust the full screen for yourself or other things

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Dirlaw A general "Settings" issue will not be accepted, if you have specific settings that you would want, like different layouts for example, they may be considered.
