### ISSUE TITLE
Мcan I become the one who adds text and synchronization to Beautiful Lyrics?

### ISSUE THREAD

**Issue by raamt6** [surfbryce/beautiful-lyrics#751]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

can I become the one who adds text and synchronization to Beautiful Lyrics?

### What is your Suggestion?

I want to help you add text and sync in your extension, 
have experience in this (1000+ points in Musixmatch)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@raamt6 There will be a Lyrics Editor update this Summer where you will be able to contribute in a way similar to that of Musixmatch, but for now it's based on my providers. Thanks for the interest!
