### ISSUE TITLE
NE MOЯ STORИ // JDFLAG

### ISSUE THREAD

**Issue by neveroyatnyyy** [surfbryce/beautiful-lyrics#752]
### Before you list your Songs:

- [X] IF you are reporting multiple songs, add ", ..." to the end of your title.
- [X] For every song you want to report, check Musixmatch or Apple Music and check to see if they even have Lyrics for the Songs you are reporting.

### List Song Links

1. https://open.spotify.com/track/2Ds4ZwUoBahuTfgIyleDMu?si=ae63b89f6632413a

[Lyrics]

Это не моя story, не моя shit
Я даю enough боли, вешаю racks shit
Даю понимать как надо
Даю понимать как надо
Даю понимать как надо (А, надо, ха)
(DJ FLAG)
Bitch, ты дэб, forever lone
Дома второй телефон
Нахуй второй телефон (Bitch, bitch)
У тебя нет денег, ты racks down
Тебе должно быть постыдно
Я гений, всем это видно (Damn, е)
Я даю на PayPal
Буду лить как из канала
Да, я faded astronaut
Да, я faded (Damn, damn)
У меня на пульсе три икса
Даю рэксы, racksed out
Бит не BNYX, no
Нах копировать FLAG'a
Вам ретироваться надо
Вам это нахуй не надо
Вам это нахуй не надо (Нет)
Это не моя story, не моя shit
Я даю enough боли, вешаю racks shit
Даю понимать как надо
Даю понимать как надо
Даю понимать как надо (А, надо, ха)
(Долбоёб, проснись!)
Bitch, ты дэб, forever lone
Дома второй телефон
Нахуй второй телефон (Bitch, bitch)
У тебя нет денег, ты racks down
Тебе должно быть постыдно
Я гений, всем это видно (Damn, е)

**Comment by raamt6** [comment]
will you be able to add synchronization?

**Comment by nullpeer** [comment]
ПОДШАRИL ZA DЖЕЙDИFLAГ
