### ISSUE TITLE
setting for sensoring explicit lyrics

### ISSUE THREAD

**Issue by Nightmare987** [surfbryce/beautiful-lyrics#764]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Kept seeing a bunch of **** that wasnt appealing to the eye. the words are being played so shouldn't be an issue being displayed, especially since its displayed in the normal default lyrics page.

### What is your Suggestion?

add a tab when you click your profile for a setting that sensors explicit lyrics.
<img width="1470" alt="Screenshot 2024-06-30 at 12 11 26 AM" src="https://github.com/surfbryce/beautiful-lyrics/assets/96702441/4a29398a-b00d-4a44-9b4e-45a258e6a275">

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Nightmare987 This is an issue with Apple Music and not with the extension, there's nothing I can do about this since I won't be modifying their lyrics (especially since there is no way to know which explicit word it is).

**Comment by Nightmare987** [comment]
ah alright i see. thanks for clarifying. just to mention its the n-word. anyway this is definetly my most usefull extension great work!
