### ISSUE TITLE
Can't enter full screen mode

### ISSUE THREAD

**Issue by harnidhskhera** [surfbryce/beautiful-lyrics#766]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/89342170/a94995b6-fc30-4fac-a001-f33c27a029ba)
Whenever my cursor hovers over the area where the full screen icon should be its not visible, but when I move my cursor away the icon is there. I have to move my cursor very fast to enter the full screen mode

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.40.599.g606b7f29
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.36.13
Spicetify Theme: marketplace
Spicetify Extensions: [shuffle+.js, quickQueue.js, keyboardShortcut.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace, ncs-visualiser]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/surfbryce/beautiful-lyrics/assets/89342170/00ea53de-50ea-461e-b2d3-98a6711906e0)
[Spotify_htmlcss.zip](https://github.com/user-attachments/files/16043735/Spotify_htmlcss.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@harnidhskhera This will be fixed in the next patch thank you for reporting!
