### ISSUE TITLE
Revert Apple Music censorship

### ISSUE THREAD

**Issue by SnowSquire** [surfbryce/beautiful-lyrics#77]
The nword is censored on every song and it's just goofy
![image](https://github.com/surfbryce/beautiful-lyrics/assets/40239844/3e3e16e6-e5b8-488f-b82b-6ddfc4ec4367)

**Comment by surfbryce** [comment]
@SnowSquire I'm not going to go out of my way to revert censorship of any kind. I do not intend on modifying the lyrics whatsoever from any lyrics-provider that I use. The only time lyrics will be presented in a manner different from the original is when translated; that is as far as I will go.
