### ISSUE TITLE
Is it possible for you to make a extension that Hides Window controls on Spotify?

### ISSUE THREAD

**Issue by Trixfinity** [surfbryce/beautiful-lyrics#770]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

The previous No Controls Extension by [ohitstom](https://github.com/ohitstom/spicetify-extensions/tree/main/noControls) hasn't been working for the past few months.

Spotify looked cleaner without them, and I realized that your Fullscreen completely removed it when activated.

### What is your Suggestion?

Seeing that when I go into Fullscreen mode using your extension, the Controls disappear, I'm wondering if it's possible for you to update or make an extension that can hide the Window Controls for Spotify while it's not in Fullscreen.

Normal Spotify
![image](https://github.com/surfbryce/beautiful-lyrics/assets/41873350/c17bb9ee-3aaf-4161-a209-11b0734b388d)

This is your Fullscreen (No Controls and area is covered)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/41873350/460689c0-3a39-465a-9c69-33c46958db2d)

another full screen (no controls, but area isn't covered)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/41873350/1877c927-48f9-42b3-98fa-e33c45ac5ade)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Trixfinity I think it's just a coincidence that it completely "removes" them, all it's doing is overlaying my fullscreen over the controls themselves I guess; I actually don't remove them in code or anything, so I won't be making an extension for it sorry!
