### ISSUE TITLE
lyrics doesn't fit the lyrics container and some kanji didn't convert to romanji 

### ISSUE THREAD

**Issue by DeathLuck578** [surfbryce/beautiful-lyrics#772]
![Screenshot 2024-07-06 150629](https://github.com/surfbryce/beautiful-lyrics/assets/137679577/7f07ccac-449d-41a6-a98f-928ecf68ca52)
![Screenshot 2024-07-06 150725](https://github.com/surfbryce/beautiful-lyrics/assets/137679577/e1c44841-8228-4893-a0b6-5303b29c12dd)

**Comment by surfbryce** [comment]
@DeathLuck578 Duplicate of #161 and #314
