### ISSUE TITLE
Beautiful Lyrics causes crash (something went wrong) on Artist page when choosing different song

### ISSUE THREAD

**Issue by RasyiidWho** [surfbryce/beautiful-lyrics#779]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Beautiful Lyrics causes crash on Artist page when choosing different song.

https://github.com/surfbryce/beautiful-lyrics/assets/19422415/a37cb90e-2e06-4fde-8239-7b8c72289769

### What Country are you from?

Indonesia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.35.663.gb699649e
Spotify Runtime: cef_122.1.13+gde5b724+chromium-122.0.6261.130
Spicetify Version: 2.36.14
Spicetify Theme: Lucid / dark
Spicetify Extensions: [popupLyrics.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [eternal-jukebox, history-in-sidebar, marketplace]

### Spotify HTML/CSS and Console Screenshots

<img width="701" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/19422415/11983998-ec30-4922-9131-cbfd3864ffff">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by 808GAZ** [comment]
I am experiencing the same problem.

Country : Qatar
Operating system : Windows 10 22H2
![image](https://github.com/user-attachments/assets/9bad631f-1211-494c-ac19-a0d2d6536486)

**Comment by Cyterg** [comment]
Same problem for me too
![image](https://github.com/user-attachments/assets/df8b9ea9-d875-49d8-86a1-7616666f1b3a)

**Comment by surfbryce** [comment]
@RasyiidWho This will be fixed in the next patch thanks for reporting!
