### ISSUE TITLE
Some way to decrease ressource usage?

### ISSUE THREAD

**Issue by Gamesnic** [surfbryce/beautiful-lyrics#79]
I don't know at much at how much FPS my Spotify renders because I have a 165Hz monitor but it draws alot of my CPU, regardless of also using my GPU. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/49643487/7d5a6dac-24d1-4b7c-a9df-ad3201e068c1)
Can I somehow make it reach acceptable levels?

**Comment by surfbryce** [comment]
@Gamesnic There is no way to reduce the levels without disabling some of the effects. The way the rendering process works on a web browser isn’t as efficient as a more direct solution.

I’ve talked in another issue request about adding a button to disable the effects and have it just be the regular text itself. It would still highlight and everything but that would be it: just a color/opacity change.

As far as I am aware there isn’t much I can do to further optimize my extension - I’ll have to take another look to ensure that - but I’m fairly certain.
