### ISSUE TITLE
Getting: SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by cestef** [surfbryce/beautiful-lyrics#794]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

This seems to be related to https://github.com/surfbryce/beautiful-lyrics/blob/3f4cfdc05c8217d37f041cc09f30376c2af27612/Builds/Release/beautiful-lyrics.mjs#L24-L36

### What Country are you from?

Switzerland

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify for macOS (Apple Silicon)
1.2.42.290.g242057a2
Spicetify v2.36.15
xpui_2024-07-12_1720793980860_242057a
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: CMake

### Spotify HTML/CSS and Console Screenshots

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/2f834e5e-89c8-4b85-851a-ab996208ef75">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@cestef You need to update marketplace, right now it is running my .mjs file as a regular .js file, if you have an updated Marketplace it will run it as a .mjs file appropriately and this error will not appear.
