### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by spidercraft** [surfbryce/beautiful-lyrics#797]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Beautiful lyrics not loading. ( tried with vpn on and off ). From the error im seeing it looks like spicetify can't downloadl beautiful lyrics??

### What Country are you from?

France

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Somehow, the shortcut doesn't work?

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/f51602ac-55af-4fac-97e7-59d163e29be8)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@spidercraft Has it been fixed for you yet? I'm not sure what's going wrong here really since the URL is correct and it does load for me, this seems to be a Spotify issue

**Comment by LaymGlitched** [comment]
i had this issue a few days ago, my internet was blocking the website

**Comment by spidercraft** [comment]
yes it has been fixed at least for me and out of nowhere, soo i dont really know what caused this tbh
