### ISSUE TITLE
Similar implementation for Yt Music

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [surfbryce/beautiful-lyrics#799]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I use Ytmusic and would to have this as a lyrics provider and host

### What is your Suggestion?

These can also be implemented in foss music streaming apps like bloome, blackhole, musify etc

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@ALMIGHTY-VC My Lyrics Service is entirely based around Spotify, so there will be no support for other platforms.
