### ISSUE TITLE
button for app is not showing

### ISSUE THREAD

**Issue by NotZachPlaysAN** [surfbryce/beautiful-lyrics#80]
i can not see any of the extra buttons including yours on the bottom where it should be - 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/140988599/d525802e-4dd9-4898-a0ef-aaa05da4132b)
and here is proof i have the app installed - 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/140988599/a94fc4ad-a56f-47a1-8e11-2c8bc388188c)

**Comment by surfbryce** [comment]
@NotZachPlaysAN It actually doesn't look like any of your extensions are working. Volume percentage is missing from the volume-bar and the genre is missing from the bottom left. Are you in a country like Egypt or a country that can be blocking JSDelivr.com?

This is not an issue with my extension but an issue with your ISP/Country (I'm assuming this is the most likely option). Check the FAQ please - the last list item has something exactly about this.

**Comment by NotZachPlaysAN** [comment]
> @NotZachPlaysAN It actually looks like none of your extensions are working. Volume percentage is missing from the volume-bar and the genre is missing from the bottom left. Are you in a country like Egypt or a country that can be blocking JSDelivr.com?
> 
> This is not an issue with my extension but an issue with your ISP/Country (I'm assuming this is the most likely option). Check the FAQ please - the last list item has something exactly about this.

i live in texas so i dont see why any of my extensions wouldnt be working, yesterday it was working just fine and i even tried the update command and backup but they didnt fix it

**Comment by surfbryce** [comment]
@NotZachPlaysAN Well let's see if we can find out what is specifically happening; can you run the command "spicetify apply enable-devtools" and then right click on any open space that doesn't trigger the spotify right click menu and open the "Developer Tools". Once you've done that click the console tab in that new Developer Tools window and screenshot everything there.

That should give us a better idea of what's going on for you.

**Comment by NotZachPlaysAN** [comment]
> @NotZachPlaysAN Well let's see if we can find out what is specifically happening; can you run the command "spicetify apply enable-devtools" and then right click on any open space that doesn't trigger the spotify right click menu and open the "Developer Tools". Once you've done that click the console tab in that new Developer Tools window and screenshot everything there.
> 
> That should give us a better idea of what's going on for you.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/140988599/e22187e8-7d86-4bba-afaf-872789f6c12b)

**Comment by surfbryce** [comment]
@NotZachPlaysAN Yeah so it's looking the extensions are failing to load in as I expected this is a Spiectify issue;
<img width="1584" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/62d0d198-2ab6-48cc-a66f-ed2d81ddafa3">

Can you try entering these two URLs into your address-bar in a web browser:
1. https://cdn.jsdelivr.xyz/gh/ohitstom/spicetify-extensions@main/immersiveView/immersiveView.js?time=1690771436115
2. https://cdn.jsdelivr.net/gh/ohitstom/spicetify-extensions@main/immersiveView/immersiveView.js?time=1690771436115

**Comment by NotZachPlaysAN** [comment]
> @NotZachPlaysAN Yeah so the the extensions are failing to load in - as I expected - this is a Spiectify issue; <img alt="image" width="1584" src="https://user-images.githubusercontent.com/80861823/257099503-62d0d198-2ab6-48cc-a66f-ed2d81ddafa3.png">
> 
> Can you try entering these two URLs into your address-bar in a web browser:
> 
> 1. https://cdn.jsdelivr.xyz/gh/ohitstom/spicetify-extensions@main/immersiveView/immersiveView.js?time=1690771436115
> 2. https://cdn.jsdelivr.net/gh/ohitstom/spicetify-extensions@main/immersiveView/immersiveView.js?time=1690771436115
> 
> and screenshotting the result of what appears when you go those URLs

1st one
![image](https://github.com/surfbryce/beautiful-lyrics/assets/140988599/9e1df5cb-bf24-41cd-a684-334cdf483c4f)
2nd one
![image](https://github.com/surfbryce/beautiful-lyrics/assets/140988599/b5ae5108-0e59-47d2-8b27-efa878b0b5cb)
looks like they are showing the same thing

**Comment by surfbryce** [comment]
alright @NotZachPlaysAN if it's loading in your browser then it's weird that it's not working in Spotify. I would highly recommend just reinstalling Spotify. But this is not an issue with my extension and some weird thing with Spotify/Spicetify.
