### ISSUE TITLE
Use Musixmatch as an alternative source for karaoke lyrics

### ISSUE THREAD

**Issue by helloryuko** [surfbryce/beautiful-lyrics#805]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

Musixmatch is an excellent service with a large community worldwide, which allows labels and casual listeners to add lyrics and sync them. It is a primary lyrics source for Spotify, Apple Music and probably a lot more other services.

From what I've seen, Beautiful Lyrics sometimes doesn't have karaoke lyrics for a specific song, while they are present on Musixmatch.

One of these songs is "Куок - Отвали, я в норме":
https://github.com/user-attachments/assets/19b197f2-2253-42e1-bdea-18ffe0a10d96

### What is your Suggestion?

On the left of the video - Lyrics Plus, an ~~extension~~ custom app for Spicetify, which uses Musixmatch as a main lyrics source. It is open-source and available on https://github.com/dompling/lyrics-plus, with all the authorization and lyrics pulling code.

You can either implement Musixmatch as an additional source for lyrics on your server, or just make the extension use it instead of connecting to Lyrics Service.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@helloryuko Already planned to be added as an additional provider to AM (where AM will be used as a backup in the cases MX does not have lyrics, which can be often). This won’t happen anytime soon as focus is being put on client side optimizations and improvements for now in preparation for my own Lyrics Editor which should be a major improvement over MX
