### ISSUE TITLE
Manifest invalid

### ISSUE THREAD

**Issue by Neax77** [surfbryce/beautiful-lyrics#806]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Hey, I am new to this and it my first time loading an external extension.
its showing that the manifest is invalid.
i try to fix it but its not working.
need help to fix it
https://github.com/user-attachments/assets/032b0bcb-0c07-478b-b070-f7a3e87a64e8
the code:
![image](https://github.com/user-attachments/assets/417fa7b2-8a96-4f31-8787-94d1c19a6544)

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

haven't yet imported the extension due to manifest problem 

### Spotify HTML/CSS and Console Screenshots

haven't yet imported the extension due to manifest problem 

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Neax77 Not an issue with Beautiful Lyrics but with your Marketplace installation, update Marketplace.
