### ISSUE TITLE
Settings Page to disable or enable Bleeping/Blurring

### ISSUE THREAD

**Issue by F5T3** [surfbryce/beautiful-lyrics#813]
### What are you Suggesting?

Features and a Fix

### What is the context behind this Suggestion?

When I am singing along a song and forget the lyrics, I look at the lyrics in Beautiful Lyrics. The problem is that it hides some swear word with ****, so I need to guess or remember which word goes there. And that is very annoying, which is why I am making this suggestion. On some song it hides all swear words,so that need to be fixed.

### Hex codes
Enabled: #1DB954
Disabled and Exit: #535353
Background: #121212
Title Text and Settings Icon: #FFFFFFF

### Original
This one shows every swear word except for the words that should be hidden ![Normal (Disabled)](https://github.com/user-attachments/assets/2d7808f0-7240-4e09-82cc-91d03f76b92b)
This one is broken and hides every swear word ![Broken (Enabled)](https://github.com/user-attachments/assets/f0a1de2f-a818-4f6d-b9e8-a25ba3999d29)

### Previews
![Disabled Settings Fullscreen Preview](https://github.com/user-attachments/assets/228265ad-26f1-4a5f-ae73-0fa9fda7dcd3)
![Disabled Settings Minimal Preview](https://github.com/user-attachments/assets/c10691da-caaa-416e-ae40-1e3049b40f74)
![Disabled Settings Preview](https://github.com/user-attachments/assets/2d582ee2-9965-45bb-97dc-03c1b0d7f1d7)
![Enabled Settings Fullscreen Preview](https://github.com/user-attachments/assets/bb776577-2102-4daa-a7fd-9a10e803154a)
![Enabled Settings Minimal Preview](https://github.com/user-attachments/assets/017067a0-8e12-4cab-a646-0686d737ef77)
![Enabled Settings Preview](https://github.com/user-attachments/assets/745a3c1f-e8ba-49ba-af51-820f006ecddc)

### Assets
![Disabled Switch](https://github.com/user-attachments/assets/75d767ca-80f8-46de-811b-42e8ca75edbb)
![Enabled Switch](https://github.com/user-attachments/assets/e3c6f4ea-562f-4528-9686-20ab966e559d)
![Exit Button](https://github.com/user-attachments/assets/475ab07b-7caf-4d60-b585-fa64c8972114)
![Settings Button](https://github.com/user-attachments/assets/0bddbc40-7f25-4f3e-9318-0d0be9784618)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@F5T3 I do not control censorship, this is controlled by the Lyric Providers. So this will not be implemented. There is also no way to undo the censorship so that will also not be implemented (I will never modify the lyrics ever).
