### ISSUE TITLE
Animation for line-by-line can be improved

### ISSUE THREAD

**Issue by 2nd1-Projects** [surfbryce/beautiful-lyrics#815]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

As of currently, songs without a word-by-word timing fade in throughout the line. In my opinion, a full top-to-bottom animation doesn't always work out looking the best, it would look a little better if it came in immediately without an animation. 

### What is your Suggestion?

Instead of lines without word-by-word synchronization having a fade in animation, lines should immediately switch to be bold and bright instead of fading into it throughout the line.

**Current, fades in throughout the timing of the line**
![image](https://github.com/user-attachments/assets/28405657-5979-4275-8322-e9007e039980)

**How it could look throughout the entirety of the timing**
![image](https://github.com/user-attachments/assets/e4d9a10c-79ec-4757-a956-11ce1f81e310)

### Worst case scenario (slightly incorrectly provided lyrics can make the animation even weirder)

It would help a little with some songs, especially when the line continues throughout a long time and the animation doesn't match with the words vertically. Sometimes a line can continue for an extended time after the line has actually ended.
(NOT YOUR FAULT)

- It happens with line-by-line synchronization. Sometimes people get it wrong, no big deal.

- Never happens with word-by-word, because people who sync word-by-word are forced to end the line when the word ends.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@2nd1-Projects If you make another issue for this with an option to switch it on/off I'll maybe consider it. My problem with the lines just popping in is that you have no idea when it will end; I saw this as a problem and chose to go with the line animation. The line animation isn't to mimic karaoke lyrics or to best guess the actual rate that the words are being sung at, but instead to give context to how long that lyric will last for.
