### ISSUE TITLE
Weird lyrics

### ISSUE THREAD

**Issue by Real0ver** [surfbryce/beautiful-lyrics#82]
Is this an issue with beautiful lyrics or the lyric source?
https://github.com/surfbryce/beautiful-lyrics/assets/68629435/84b53fb3-85b6-44a7-8c48-954a3464f691

**Comment by Real0ver** [comment]
Also suggestion, add musixmatch as source, i've seen they have more word by word lyric songs

**Comment by Real0ver** [comment]
oops accidentally closed it

**Comment by surfbryce** [comment]
Somebody made a more detailed issue write up on #83 so I'm going to close this one. This is a right-to-left recognition error - the lyrics are being displayed as right to left instead of left to right which is why it looks like that.

Please post over there thank you!
