### ISSUE TITLE
[BUG] Sometimes lead spotify blackscreen

### ISSUE THREAD

**Issue by zjns** [surfbryce/beautiful-lyrics#821]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

When I switch library items, such as artist, album or playlist, now playing view small lyric panel updating lead spotify blackscreen sometimes.

Update:
Switch tracks with now playing view opening also have same issue.
![QQ_1723003464697](https://github.com/user-attachments/assets/f3185324-b293-4ff3-b2ec-0f4207fd43ea)

After switch library item sometimes, still playing but blackscreen.
![QQ_1723004192104](https://github.com/user-attachments/assets/99284fc7-adcc-4e5d-9d07-23acd5ea68f0)

### What Country are you from?

China

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify Version: 1.2.43.420.gc7b23f70
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.37.0
Spicetify Theme: marketplace
Spicetify Extensions: [romajin.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [new-releases, marketplace]

### Spotify HTML/CSS and Console Screenshots

HTML&CSS: [Spotify.zip](https://github.com/user-attachments/files/16518131/Spotify.zip)

Console screenshot:
![image](https://github.com/user-attachments/assets/6fbd6897-6b3b-48e1-8296-853756bbdc3f)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by SupersSpartan** [comment]
same issue here, but with Windows

**Comment by surfbryce** [comment]
@zjns Will be fixed in the next patch, thanks for reporting!

**Comment by zjns** [comment]
Bravo!!! 🎉

**Comment by Dextyerz** [comment]
![image](https://github.com/user-attachments/assets/69cb0e6d-6b81-40b5-bd0a-e24d26eaa5d6)


> @zjns Will be fixed in the next patch, thanks for reporting!

![image](https://github.com/user-attachments/assets/06ef158e-0668-440b-b8f3-064b5c458369)
i still get that

**Comment by test61617** [comment]
![Screenshot 2024-09-13 174143](https://github.com/user-attachments/assets/5933076d-0d5c-47e1-8f5b-87de8baf21b8)
