### ISSUE TITLE
Lyrics font doesn't match Spotify font.

### ISSUE THREAD

**Issue by goldenwario** [surfbryce/beautiful-lyrics#823]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I am using a custom font but even with the default font it still doesn't match.
![image](https://github.com/user-attachments/assets/3776a869-e123-4fc2-9c8e-47c1f5c52628)

### What Country are you from?

Kosovo

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.43.420.gc7b23f70
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.37.0
Spicetify Theme: Comfy / Spotify
Spicetify Extensions: [beautiful-lyrics.js, fullAlbumDate.js, made-for-you-shortcut.js, adblock.js, hidePodcasts.js, wikify.js, songstats.js, spotifyGenres.js, utilities.js, beautiful-lyrics.mjs, theme.script.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

(We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.)
???

![image](https://github.com/user-attachments/assets/ab325158-6d68-444a-943f-fa3122e7f2c3)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@goldenwario Beautiful Lyrics uses a custom font, you will have to make a CSS snippet to change it, there is not a setting for this at the moment.

**Comment by goldenwario** [comment]
> @goldenwario Beautiful Lyrics uses a custom font, you will have to make a CSS snippet to change it, there is not a setting for this at the moment.

I have made a CSS snippet but the font still doesn't change and sticks to the custom font.
