### ISSUE TITLE
Dynamic Background and the "Smooth" Lyrics scrolling is not working.

### ISSUE THREAD

**Issue by lofibit** [surfbryce/beautiful-lyrics#830]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The Dynamic background and the smooth scrolling (not the Lyrics effect) was working fine few days ago (By using 40%-50% of my GPU, But that was not my concern). Even though I uninstalled and reinstall it, It's not working, So I thought it was your end, So I'm reporting this issue, please fix that. It was perfect the way it used to look.

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify for Windows (64 bit)
1.2.43.420.gc7b23f70
Spicetify v2.37.0

### Spotify HTML/CSS and Console Screenshots

![Screenshot (76)](https://github.com/user-attachments/assets/28249b78-65ea-4406-903e-14b474fcceb2)
![screencapture-file-C-Users-deeks-Downloads-Spotify-html-2024-08-10-17_03_06](https://github.com/user-attachments/assets/73a8e75a-e622-4bcf-a533-0dc5dbd74fa6)
![Uploading Screenshot 2024-08-10 170458.png…]()

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by beabadoobeeenjoyer** [comment]
may just be me but there seems to be an issue with the images attached? @lofibit 
![image](https://github.com/user-attachments/assets/71c5c6b1-7ea1-4b77-a1c7-5361e7fbe510)

**Comment by surfbryce** [comment]
@lofibit There's an issue with your bug report, please resubmit, there should be no images of the files themselves, just attach only the files no images of them.
