### ISSUE TITLE
Summarize your Suggestion Here

### ISSUE THREAD

**Issue by kyxadev618** [surfbryce/beautiful-lyrics#831]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

**Add beautiful lyrics to new songs (Lyrics That read along.)**

### What is your Suggestion?

**R.I.P Fredo (feat,Young Nudy)** by _Playboi Carti_

**i need u** by _Ken Carson_

**how u feel?** by _Destroy Lonely_

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by AMOGUSSYBEHAVIOUR** [comment]
Option to turn off the bloom effect on lyrics.
Personal preference. 
![image](https://github.com/user-attachments/assets/880db142-2399-4ce1-8d9c-e4962104ae88) With bloom
![image](https://github.com/user-attachments/assets/958b3bc0-38a0-4516-8428-5c9947c87f97) Without bloom

**Comment by beabadoobeeenjoyer** [comment]
@AMOGUSSYBEHAVIOUR make your own issue if you read thru this its someone making their own suggestion:/
