### ISSUE TITLE
Lyrics Button Not Showing/Extension not working at all.

### ISSUE THREAD

**Issue by LaymGlitched** [surfbryce/beautiful-lyrics#833]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

these errors are repeating over and over again.
the extension used to work perfectly before a couple days ago.

not only that but I am unable to use the Spicetify Info Copy Shortcut, upon using it, it does nothing, this goes the same for the Spotify HTML/CSS Files.

### What Country are you from?

United Kingdom

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

I am unable to use the Spicetify Info Copy Shortcut, upon using it, it does nothing, this goes the same for the Spotify HTML/CSS Files.

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/af2f57e8-b07e-44ab-bca6-36170ba55aeb)
![image](https://github.com/user-attachments/assets/873183d6-8563-4736-b390-e87b1f2333fd)

I am unable to use the Spicetify Info Copy Shortcut, upon using it, it does nothing, this goes the same for the Spotify HTML/CSS Files.

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by LaymGlitched** [comment]
it could be due to my internet blocking the website?

**Comment by Nano-Ocelot** [comment]
I'm having this same issue. Extension just doesn't function at all.

**Comment by LaymGlitched** [comment]
Fixed! i had to unblock the website that was in the console on my internet, my internet was blocking the website.

**Comment by AbhayXV** [comment]
could you just explain how you did it, cuz the extension still isn't working for me.
FYI
![image](https://github.com/user-attachments/assets/023210ce-54e2-4e98-98d9-144e9745ddcb)

**Comment by AbhayXV** [comment]
the lyrics or full screen button just don't show up
