### ISSUE TITLE
dark shadow in the now playng section

### ISSUE THREAD

**Issue by Leffy02** [surfbryce/beautiful-lyrics#839]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I found this strange dark shadow in the now playng section every time i open spotify:
![immagine_2024-08-14_104740514](https://github.com/user-attachments/assets/52ee2b7a-970c-47ff-9203-6fc3fc5dc0a1)
i tryed to uninstall all the others extentions i had and it still remains

### What Country are you from?

Italy

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.44.405.g81fd6352
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.37.1
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace, betterLibrary, lyrics-plus]

### Spotify HTML/CSS and Console Screenshots

[Downloads.zip](https://github.com/user-attachments/files/16610367/Downloads.zip)
![image](https://github.com/user-attachments/assets/da0335d3-0ab3-4c2f-8554-b0f695377f4d)
![image](https://github.com/user-attachments/assets/224cd9b0-c9f1-4ad0-87f5-3eacd7f9402c)
in the moment when i've get this logs beautiful lyrics was the only extention installed

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by mikecuongg** [comment]
I got the same issue was about to submit an Issue until saw this. Somebody please resolve this issue.

**Comment by iHelops** [comment]
Temporary solution:

1. Install [CSS Editor](https://github.com/FlafyDev/spotify-css-editor) extension
2. Go to Spotify settings and find the CSS Editor section
3. Click Open CSS Editor
4. Enter the following code

```css
.main-nowPlayingView-contextItemInfo:before {
  display: none;
}
```

**Comment by Leffy02** [comment]
it works now, thank you so much
