### ISSUE TITLE
Extension doesn't work at all

### ISSUE THREAD

**Issue by Nano-Ocelot** [surfbryce/beautiful-lyrics#842]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

None of the extension functions work. There is no lyric button, the lyrics don't show in the side bar, and none of the color options in the sidebar are showing anymore. It was previously working but as of last week sometime it stopped.

### What Country are you from?

United States

### What Operating System are you using?

Linux

### Spotify/Spicetify Information

Spotify Flatpak 1.2.42.290.g242057a2
Spicetify 2.37.1

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/277f596d-213b-4e2f-88a7-b416af723e88)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@Nano-Ocelot It seems your connection is being refused by my service that provides the extension in the first place, if you are using a VPN try it in a different country or wait a bit.

**Comment by Nano-Ocelot** [comment]
Odd, I'm not using a VPN at all. You're saying my ISP is blocking the connection?

**Comment by Nano-Ocelot** [comment]
Do you know of any way around this other than a vpn?
