### ISSUE TITLE
[BUG] Still lead Spotify blackscreen sometimes

### ISSUE THREAD

**Issue by zjns** [surfbryce/beautiful-lyrics#850]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Another null situation lead Spotify blackscreen sometimes, just see console screenshot.

### What Country are you from?

China

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify Version: 1.2.44.405.g81fd6352
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.37.1
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [new-releases, marketplace]

### Spotify HTML/CSS and Console Screenshots

![QQ_1724056703932](https://github.com/user-attachments/assets/63c17fce-bc46-4f57-9a27-90217d2f03be)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by raymonable** [comment]
I have this issue as well.

![image](https://github.com/user-attachments/assets/5be9d6c9-65eb-43c3-89a5-26682858f928)

Mostly happens when I switch to DJ.

**Comment by Pramissh** [comment]
This issue is not solved, i am facing it too 
![Screenshot (1580)](https://github.com/user-attachments/assets/afba4acd-b0a7-4219-8102-4db4622c368d)
