### ISSUE TITLE
Be able to add lyrics to local songs via .lrc file

### ISSUE THREAD

**Issue by JoJoBollo** [surfbryce/beautiful-lyrics#871]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

This extension is great, the only thing that I could think it lacks its support to lyrics with local songs by allowing to open your own lyrics files, it would be nice to have both custom and fancy in one place :D

### What is your Suggestion?

With this you'll be able to add your own lyrics to a local song in spotify with a local .lrc file (an example of this in spicetify is with the lyrics plus custom app (is not an extension in marketplace), even if it technically exists already the interface in that custom app is pretty bad and is a different button from other normal lyrics, (also your lyrics are cooler)

EXAMPLE OF IDEA:
![Sin título](https://github.com/user-attachments/assets/8083c139-40b6-47d2-a63c-4bb4c47fbc99)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by Real-Packet** [comment]
This would be easy, all you have to do is allow hot switching between lyrics.
You'd use something like setState in order to hot switching.

**Comment by Real-Packet** [comment]
https://github.com/surfbryce/beautiful-lyrics/blob/13074cbdf4a4d17ac794bccbc369e75866ad3d6e/Source/Modules/LyricsRenderer/Components/StaticVocals.ts#L5
Why is this dependency not included in the project tree or as a separate repo with a JSR package?

**Comment by JoJoBollo** [comment]
> https://github.com/surfbryce/beautiful-lyrics/blob/13074cbdf4a4d17ac794bccbc369e75866ad3d6e/Source/Modules/LyricsRenderer/Components/StaticVocals.ts#L5
> 
> 
> Why is this dependency not included in the project tree or as a separate repo with a JSR package?

Sry Man I don't really know

**Comment by Real-Packet** [comment]
> > https://github.com/surfbryce/beautiful-lyrics/blob/13074cbdf4a4d17ac794bccbc369e75866ad3d6e/Source/Modules/LyricsRenderer/Components/StaticVocals.ts#L5
> > 
> > Why is this dependency not included in the project tree or as a separate repo with a JSR package?
> 
> Sry Man I don't really know

I don't really expect you to know, just a general question in hopes that maybe we could get clarification.

**Comment by surfbryce** [comment]
@JoJoBollo This will never happen, not because I don't want people to be able to use lyrics in cases where there are none (or not good quality ones) from my service, but because eventually the extension will have a lyrics editor which will upload to my service and apply your own lyrics locally. If I put in .lrc files now, it will lead to people not using the lyrics editor when it comes out (because they've already applied their own lyrics locally) and if I remove it down the line it will cause frustration. So it's just better for me not to include this as a feature so that when the lyrics editor comes out I don't have to fight for its usage.

**Comment by surfbryce** [comment]
@Real-Packet Thanks for bringing this to my attention, it shouldn't be like and I believe is already in one of the JSR packages used in the extension, I'll update that and it should be fixed in the next patch push.
