### ISSUE TITLE
How do I contribute/what lyric service is being used

### ISSUE THREAD

**Issue by Lebbbbb** [surfbryce/beautiful-lyrics#875]
Hi,
I come across quite a few songs with either missing lyrics, or ones that aren't timed.
So I was wondering how I could contribute to these myself.

**Comment by surfbryce** [comment]
@Lebbbbb The lyrics are grabbed from Apple Music which uses Musixmatch, this will change soon to use Musixmatch directly alongside Apple Music. Eventually, there will be a lyrics editor that will allow people to submit lyrics for everybody else, so look out for that in the future.
