### ISSUE TITLE
Allow using Esc to exit fullscreen view

### ISSUE THREAD

**Issue by RhapsodySL** [surfbryce/beautiful-lyrics#88]
Currently, pressing Esc when in fullscreen view does nothing, which isn't consistent with the default fullscreen view's behavior. Ideally, pressing Esc should exit the fullscreen view.

**Comment by surfbryce** [comment]
Yep that makes sense to add - didn't remember about adding that - should see that in the next update.

**Comment by surfbryce** [comment]
@RhapsodySL Alright this should be pushed out in the latest updated (3.1.8).
