### ISSUE TITLE
Fallback to default Spotify lyrics data when no lyrics are available?

### ISSUE THREAD

**Issue by CaoilainnFW** [surfbryce/beautiful-lyrics#884]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

Several smaller artists I follow, or even larger bands like OKGO, don't have timed lyrics or just no lyrics at all in the extension, but do have timed lyrics in the default Spotify version.

### What is your Suggestion?

I'm unsure if this is possible, but it would be nice to have the extension fallback on the lyrics data from Spotify.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by CaoilainnFW** [comment]
Similarly, where does the extension get the lyrics? If it's a public service or open-source library, I'd love to be able to contribute to it cause many songs I listen to don't have lyrics.

**Comment by surfbryce** [comment]
@CaoilainnFW This won't happen since the goal is to not rely on Spotify for Lyrics at all so everybody gets the same lyrics experience, Musixmatch (which Spotify uses) will be included in the future as an additional source that my backend uses.
