### ISSUE TITLE
adding background play for lyric

### ISSUE THREAD

**Issue by M1nCh3** [surfbryce/beautiful-lyrics#887]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

i have difficulty to use this feature when im using resolume to display the lyric, beautiful lyric need to be show on screen, it cannot  background play, or else it will paused if i put spotify and beautiful lyric behind resolume so i cannot maximize resolume window. is there any option or anything i miss?
please help

### What is your Suggestion?

![WhatsApp Image 2024-09-13 at 17 51 29](https://github.com/user-attachments/assets/2c8dd081-d8e9-4770-bdbb-fdd0fb00bbeb)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@M1nCh3 Not an issue with Beautiful Lyrics
