### ISSUE TITLE
Minus button when listening to Release Radar is positioned improperly in fullscreen view

### ISSUE THREAD

**Issue by RhapsodySL** [surfbryce/beautiful-lyrics#90]
When listening to playlists that offer a minus button in a circle (such as Release Radar) to show that you're not interested in a song, the fullscreen view does not properly handle this, and it appears in an awkward position on top/just below the artist name.

Example without lyrics:

<img width="1536" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/8369578/d2576b85-24cd-453b-808c-09c9f749aee6">

Example with lyrics:

<img width="1536" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/8369578/58ecefa1-5a50-47a2-adfb-cc6cfb76a5ef">

**Comment by surfbryce** [comment]
@RhapsodySL I never actually used a feature that had that so I had no idea that was a thing! I'll see what I can do, the main issue is that the heart takes up the cover-art when you hover over it. I think in this instance I'll have the heart take up like 75% top to bottom and then have the other one take up that remaining 25%. This should be good enough and makes sense layout wise

**Comment by surfbryce** [comment]
Alright so this is how it'll look in this mode:
<img width="454" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/a37373c9-58c9-4257-a66a-bf2f04c0817c">
<img width="472" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/f59ceb5d-1855-4656-b080-b652294e0c0a">

You should see this in the next update

**Comment by RhapsodySL** [comment]
Looks great, thanks! I figure I'll put a somewhat related issue here (I can make this into a new issue if you want). If you're hovering over certain parts of the album art that aren't covered by the heart icon's "hitbox", you'll see the up/down arrow, which is for minimizing/maximizing the album art in the regular view. This is redundant and doesn't do anything in fullscreen view (although some of the control buttons at the bottom are too so I'm not really sure if it matters that much).

Here's an example image:

<img width="1536" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/8369578/6c173731-dd8f-4e5b-94df-3e6953dedf30">

This happens whenever the cursor is in an area not covered by the heart's hitbox, which is essentially any of the four corners (but not the top, bottom, left, or right edges).

**Comment by surfbryce** [comment]
@RhapsodySL This is already fixed on my version - so you'll see that this doesn't happen. Unfortunately, I cannot get the hitbox for the controls to override those corners for some reason so we'll have to deal with that being dead-space

**Comment by RhapsodySL** [comment]
That's completely fine, thanks for the attention to these issues.

**Comment by surfbryce** [comment]
@RhapsodySL This is now live in 3.1.9

**Comment by RhapsodySL** [comment]
This appears to have been fixed in instances such as in Release Radar, but still occurs in other locations such as radio stations:

<img width="1536" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/8369578/9e5814cb-8f82-4a8f-a1e8-6aeb6ca4ca4a">
