### ISSUE TITLE
Add Full Explicit // Uncensored Lyrics

### ISSUE THREAD

**Issue by HadesEclipse** [surfbryce/beautiful-lyrics#908]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

In the lyrics, whenever certain swear words come up its usually just " ****  ". Which is pretty annoying, but i understand some users may not want those words showing up.

### What is your Suggestion?

My way of implementing this: A simple toggle on / off button which will enable or disable the explicit lyrics. This will give everyone the choice to use (or not) the uncensored lyrics easily.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [ ] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@HadesEclipse The extension does NOT ever modify the lyrical contents themselves and never will. This is how it comes from the Lyrics Provider.
