### ISSUE TITLE
Album art/controls jitter to the left when a new song without lyrics starts in fullscreen

### ISSUE THREAD

**Issue by RhapsodySL** [surfbryce/beautiful-lyrics#91]
This may not be fixable, but when transitioning to a new song in fullscreen view, if the song doesn't have lyrics, the album art and controls briefly appear to the left (in the position it would be if it _had_ lyrics), and then snap to the middle.

**Comment by surfbryce** [comment]
@RhapsodySL Can you screen-record this so I can see what is happening visually? This doesn't occur for me

**Comment by RhapsodySL** [comment]
Sure, here you go: https://i.imgur.com/F0IzoyZ.mp4
