### ISSUE TITLE
Upload Own Lyrics

### ISSUE THREAD

**Issue by Hayloud** [surfbryce/beautiful-lyrics#910]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I have some songs that are local files, so they don't have the lyrics on Spotify.

### What is your Suggestion?

It would be good if we could upload our own lyrics for these songs using the lrc files.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [ ] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Hayloud Will never happen. A lyrics editor update is planned in the future, introducing this now would lead to less contribution or potentially lead to people overlooking the update due to having already added their own LRC file contents.
