### ISSUE TITLE
When Beautiful Lyrics cannot find lyrics, use Spotify's lyrics if available.

### ISSUE THREAD

**Issue by GeorgeBaker1** [surfbryce/beautiful-lyrics#914]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I noticed that during a few songs, Beautiful Lyrics didn't have lyrics, but Spotify's built in lyrics did. 

(The song that prompted this suggestion was "[Tongues & Teeth](https://open.spotify.com/track/7d16ACNTVHWFLRAOGL3ZiI?si=15d541bd84274546)" by The Crane Wives, as it has Spotify lyrics, but not Beautiful Lyrics)

### What is your Suggestion?

When the plugin cannot find lyrics via other sources, turn to Spotify as a source of lyrics instead.

I'm not sure what this would look like in code, but maybe adding Spotify to the sources list, at a lower priority than the others? I'm not a programmer, but that may work.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@GeorgeBaker1 Not going to happen, Spotify has a paywall for lyrics and doing this would not work for everybody. Musixmatch which Spotify uses will be added as a source eventually.

**Comment by SystematicError** [comment]
> @GeorgeBaker1 Not going to happen, Spotify has a paywall for lyrics and doing this would not work for everybody. Musixmatch which Spotify uses will be added as a source eventually.

They reverted on this decision I believe, falling back to Spotify's default would be a nice feature, considering can now work for non premium users as well.

https://9to5mac.com/2024/07/31/spotify-lyrics-free/
