### ISSUE TITLE
Chromecast support 

### ISSUE THREAD

**Issue by SpeeterYT** [surfbryce/beautiful-lyrics#916]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

The spotify app for Chromecast is not very good. Having the possibility to dispsplay the lyrics or cover (+maybe progress bar) ontop of the beautiful gradient would be an drastic improvement

### What is your Suggestion?

A way to cast the full screen lyrics and cover + prigress bar views onto a chromecast, without just mirroring the screen

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@SpeeterYT Not possible from within Spotify and is out of the scope for this extension
