### ISSUE TITLE
Censorship

### ISSUE THREAD

**Issue by drookz** [surfbryce/beautiful-lyrics#927]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

you can add the ability to uncensor censored words

### What is your Suggestion?

![image](https://github.com/user-attachments/assets/63e631c7-6a58-4a98-a7cc-48f2509fe676)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@drookz Will never modify the lyrics, this is how it comes from the Lyrics Provider, nothing I can do
