### ISSUE TITLE
N-Word + Explicit Lyrics Toggle

### ISSUE THREAD

**Issue by TLboiii52** [surfbryce/beautiful-lyrics#929]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

hello dev team, i am asking if is possible to add a n-word (UN-censorable) and add in an explicit word filter. BUT the button should be one

### What is your Suggestion?

as what i was saying, this feature is a must have if you want to listen to explicit songs and censor THE words. i hope this is possible.
Have a nice day!

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@TLboiii52 This is how the lyrics come from the Lyrics Provider I use, I will not be modifying them in any regard.

**Comment by TLboiii52** [comment]
sorry, i didn't know that. but you are doing an amazing job keeping up this project!
