### ISSUE TITLE
Create this as a Wallpaper Engine Background

### ISSUE THREAD

**Issue by bewf** [surfbryce/beautiful-lyrics#936]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I would love to have this feature available as a wallpaper, especially on wallpaper engine that would hook onto Spotify.

### What is your Suggestion?

Make the full screen lyrics page available as a wallpaper on Wallpaper Engine that would grab your Spotify's current song and do the same thing, instead constantly as a wallpaper.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@bewf Not within the scope of this project. Also not possible with the way it is currently done since it fully relies on the Browser Rendering Engine which Spotify uses.
