### ISSUE TITLE
Wrong allignment in fullscreen mode

### ISSUE THREAD

**Issue by P1zz454** [surfbryce/beautiful-lyrics#939]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Screenshot 2024-10-24 215649](https://github.com/user-attachments/assets/a6191d0d-b2ec-46c4-8f17-ac90533998b1)
The fullscreen mode appears like this qwq

### What Country are you from?

Italy

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [shuffle+.js, adblock.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[SpotifyCSS.txt](https://github.com/user-attachments/files/17512157/SpotifyCSS.txt)
[SpotifyHTML.txt](https://github.com/user-attachments/files/17512159/SpotifyHTML.txt)
![Screenshot 2024-10-24 221355](https://github.com/user-attachments/assets/75f7525c-e162-432d-a4a5-37c855408a75)
![Screenshot 2024-10-24 221426](https://github.com/user-attachments/assets/1826ba8c-3304-43ea-843d-99055eec2805)
![Screenshot 2024-10-24 221447](https://github.com/user-attachments/assets/82aef481-b4e0-4860-a00d-313368c61fb3)
![Screenshot 2024-10-24 221542](https://github.com/user-attachments/assets/f7f49392-5836-4b73-9b55-6ba667ecd033)

![Screenshot 2024-10-24 221557](https://github.com/user-attachments/assets/1fb9ed6e-5476-4f51-8878-8241322b1aae)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by httpeace33** [comment]
Same here after Spotify update probably

**Comment by lovepilled** [comment]
Same issue here

**Comment by AkiraKisaragi** [comment]
i got same issue and it's weird 
![image](https://github.com/user-attachments/assets/77b619f8-baae-4310-9952-aadf351f6904)

**Comment by pitufishy** [comment]
i got same issue and it's weird
![image](https://github.com/user-attachments/assets/99a7a0c7-800d-4e94-8d10-9feb7ff70fb0)

**Comment by jorge19832** [comment]
![ds](https://github.com/user-attachments/assets/f848fd44-c4af-4801-955e-898fb6f7c687)
The same problem too

**Comment by Mysticc28** [comment]
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool.

**Comment by jorge19832** [comment]
> Hola, hay una solución rápida para los elementos desorientados en la extensión Beautiful Lyrics disponible gracias a@sanoojes
> 
> **Paso 1: Copie el código siguiente**
> 
> ```ts
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
>     position: relative;
> }
> ```
> 
> **Paso 2: Vaya a Spotify>Marketplace>Fragmentos** ![imagen](https://private-user-images.githubusercontent.com/184191235/382589189-2decf258-2f0e-4e65-985e-d5f2ac483a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTM0MzEsIm5iZiI6MTczMDY1MzEzMSwicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5MTg5LTJkZWNmMjU4LTJmMGUtNGU2NS05ODVlLWQ1ZjJhYzQ4M2E4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxNjU4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTAwMzhlYjA4ZWJmZjU2YjYzZTMyMjNiM2U3MDIyOGIxNGM1OTZmNTc1YTgyNjc5YmQ1MmI2MzA5NmY1ZmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mL-0hUiDhDU5sDq5FHq3w2ElS-bKl6S9qTeiduWodXY)
> 
> **Paso 3: Haga clic en el botón "Agregar CSS" en la esquina inferior derecha** ![imagen](https://private-user-images.githubusercontent.com/184191235/382589254-3c156d43-7c5b-4956-8f97-ae4794aae606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTM0MzEsIm5iZiI6MTczMDY1MzEzMSwicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5MjU0LTNjMTU2ZDQzLTdjNWItNDk1Ni04Zjk3LWFlNDc5NGFhZTYwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxNjU4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTMwY2UyZWQ2ZTE1OGEyMTc3MDIxNDQyNTJhOGY0NzM1M2M4YTliMGVjYWU2YmRkYzM5MGRlNWU0OWQ0YmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MEMicQ9pkzkVD1uPlt4j0a9olu4Ji4gQfDqIfinXU6M)
> 
> **Paso 4: en CSS personalizado, pega el código que acabas de copiar y agrega un nombre y una descripción del fragmento como desees. Hasta ahora debería verse así.** ![imagen](https://private-user-images.githubusercontent.com/184191235/382589489-9e29e9b9-4293-418e-8db7-a9d97c425a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTM0MzEsIm5iZiI6MTczMDY1MzEzMSwicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5NDg5LTllMjllOWI5LTQyOTMtNDE4ZS04ZGI3LWE5ZDk3YzQyNWEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxNjU4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzYxMzlmOTJmZmVjMjY2NWYzZDFjZTkyN2VjMGJlZWY4OThkMzFhOTA3MDcxNjIxNzQ0ZDFhOWVkOTVjODk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HA4nPrKJxUZ-YQTZZHSHmc_vi6sa7A1422FqYBi4fCY)
> 
> **Paso 5: haz clic en Guardar CSS y listo.** El problema debería estar solucionado, pero en caso de que no sea así, actualiza Spotify y vuelve a comprobarlo. Una vez más, muchas gracias a@sanoojesPara solucionarlo. Echa un vistazo a sus temas, son realmente geniales.

THANKS

**Comment by Mysticc28** [comment]
@P1zz454 @lovepilled @AkiraKisaragi @pitufishy @jorge19832 - The fix is above

**Comment by P1zz454** [comment]
> Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes
> 
> **Step 1 - Copy the below code**
> 
> ```ts
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
>     position: relative;
> }
> ```
> 
> **Step 2 - Navigate to Spotify>Marketplace>Snippets** ![image](https://private-user-images.githubusercontent.com/184191235/382589189-2decf258-2f0e-4e65-985e-d5f2ac483a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjY3NzMsIm5iZiI6MTczMDY2NjQ3MywicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5MTg5LTJkZWNmMjU4LTJmMGUtNGU2NS05ODVlLWQ1ZjJhYzQ4M2E4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMDQxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjMxYWQ0MTVmMjNmN2M3ZjcxYzVjNjgxYmU1N2U2MDljMmUzZTNkMTcwNjE1N2VmMzBmMmQzOTFkN2I3ODJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5UFazOmVirnBSxyV6gRxNNGqa5HpwKI-Y3P62nY6ICw)
> 
> **Step 3 - Click the 'Add CSS' button in the bottom right corner** ![image](https://private-user-images.githubusercontent.com/184191235/382589254-3c156d43-7c5b-4956-8f97-ae4794aae606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjY3NzMsIm5iZiI6MTczMDY2NjQ3MywicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5MjU0LTNjMTU2ZDQzLTdjNWItNDk1Ni04Zjk3LWFlNDc5NGFhZTYwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMDQxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2QzMDA3YWQxZjkyYTkzNDBlYWEwZTU2MmVjY2JmYTdmNDhkMDhkNzczZmQwODYxZTM3MjhiYzMyOTcyZDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zKoiMQcGTYWdeojE7CqPYNuLwWXhBK3TIQEAyI4I2N8)
> 
> **Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** ![image](https://private-user-images.githubusercontent.com/184191235/382589489-9e29e9b9-4293-418e-8db7-a9d97c425a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjY3NzMsIm5iZiI6MTczMDY2NjQ3MywicGF0aCI6Ii8xODQxOTEyMzUvMzgyNTg5NDg5LTllMjllOWI5LTQyOTMtNDE4ZS04ZGI3LWE5ZDk3YzQyNWEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMDQxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2RkMmUwOWY0MDljMTMyODAxMmQyNTc2ZDcyMzEyYWM0YzFiYWNmZWMzMWNiMmI0ODQwZmRkZmU3Y2U5NDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0TB6OHNDwADPbuy576jgx3NFPwHGrHJn2BRCKjxRCbU)
> 
> **Step 5 - Hit Save CSS and done.** Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool.

Thank you!
