### ISSUE TITLE
Songs automatically pausing

### ISSUE THREAD

**Issue by CHRISTYRELL456** [surfbryce/beautiful-lyrics#94]
For some reason, at the beginning of songs it automatically pauses and unpauses really fast but after it stops it goes away for the rest of the song. can you guys please fix this ASAP.

**Comment by surfbryce** [comment]
@CHRISTYRELL456 It's just one person (me) working on this just letting you know.

This change was made to improve the syncing of the lyrics - for me it doesn't have any difference in it being played - is creating gaps for you?

Or what is the effect that is happening to you? Or are you just seeing it visually pause/unpause really fast?

**Comment by MrGenia** [comment]
We see it visually pausing & unpausing and so the sound constantly interrupts for the first 2 seconds of each song

**Comment by surfbryce** [comment]
@MrGenia Alright wasn't aware that it would cause interrupts in the audio. Weird that it doesn't do that for me but for other people.

**Comment by CHRISTYRELL456** [comment]
@surfbryce im having the same issue as @MrGenia it stops the audio completely

**Comment by surfbryce** [comment]
@CHRISTYRELL456 @MrGenia If you restart spotify it should function properly now

**Comment by CHRISTYRELL456** [comment]
@surfbryce ok thank you, ill try it and update you what else happens

**Comment by CHRISTYRELL456** [comment]
Working perfectly now, thank you

**Comment by MrGenia** [comment]
@surfbryce Thank you for reverting the changes. It now works as intended

**Comment by surfbryce** [comment]
Let me know if you guys run into any other issues, thanks!
