### ISSUE TITLE
Black Screen at the moment of clicking on the song and playing it. 

### ISSUE THREAD

**Issue by MaxIsDumbLoL** [surfbryce/beautiful-lyrics#940]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Black Screen on Playing Songs while having this extension enabled.

PS. I cannot upload the CSS File because i've been trying to use the "Shift + B + L + C" and it is not doing anything.

### What Country are you from?

Paraguay

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

[Spotify HTML File.zip](https://github.com/user-attachments/files/17521665/Spotify.HTML.File.zip)
[Cannot Upload CSS File due to extension bug, read "Bug/issue"]

### Spotify HTML/CSS and Console Screenshots

https://github.com/user-attachments/assets/07f03efe-1a36-4d1e-959e-082d64cde29e

I apologize for the video quality, i had to compress it to 10 MB so i can show everything including the error happening on my end.

The Screenshots of the Developer Tools Console Tab is included in the video. Time 00:29

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Pramissh** [comment]
I am facing this problem too. How to solve it?

**Comment by mrafieefard** [comment]
+1

**Comment by Rakanovan9** [comment]
Has anyone managed to fix it?

**Comment by DatNERFDude** [comment]
I had this issue for a while, but it's recently stopped happening (music video update for Spotify)

**Comment by surfbryce** [comment]
Sorry everyone forgot to close this, I have fixed this i. the latest update (I just haven’t put the release out)

**Comment by DatNERFDude** [comment]
@surfbryce, can I help update incorrect lyrics?
