### ISSUE TITLE
LETTER FONT BUG

### ISSUE THREAD

**Issue by LuvEctasyy** [surfbryce/beautiful-lyrics#944]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I don't know if it's a bug, but the font changes, sometimes it stays with one type and then changes to another, I leave a photo of what it looks like at first.
![462554130_1752846738452922_2810748535546170576_n](https://github.com/user-attachments/assets/61ce1ea3-902d-48ee-a7c6-741189e408bd)

After that it switches to the normal source.

![image](https://github.com/user-attachments/assets/9cbd5628-c926-4de5-9c3b-a7f3ef9bff87)

### What Country are you from?

Chile

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/a069486b-e4e2-46d1-887a-63cca1f9e113)

HTML

### Information Checklist

- [X] Spotify/Spicetify Information
- [ ] Spotify HTML File
- [ ] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by GAMINGCHATS** [comment]
I don't think it's a bug. (I'm not sure. I'm assuming based on your screenshots @LuvEctasyy )

**Comment by thiccguy21** [comment]
I don't think it's a bug, considering it is just a placefolder font and is probably loading in the actual font.
