### ISSUE TITLE
the fullscreen and exit button cannot be clicked

### ISSUE THREAD

**Issue by Rysu69** [surfbryce/beautiful-lyrics#945]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

the fullscreen button and exit lyric button doesn't work, its there but when i hover it, it doesnt change color and cannot be clicked 
![Screenshot 2024-10-28 141056](https://github.com/user-attachments/assets/efc53991-77b7-45bd-94a6-57ad2231c4e1)

### What Country are you from?

Indonesia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: SpotifyNoPremium / Base
Spicetify Extensions: [beautiful-lyrics.mjs, adblock.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![Screenshot 2024-10-28 141733](https://github.com/user-attachments/assets/67abdb5f-4299-4ec0-a6bd-26b4b68f7380)
![Screenshot 2024-10-28 141747](https://github.com/user-attachments/assets/95e487ed-0732-4410-a481-26eab4d6bc95)
![Screenshot 2024-10-28 141759](https://github.com/user-
[New folder.zip](https://github.com/user-attachments/files/17538164/New.folder.zip)
attachments/assets/928f05e3-3846-48c2-97ce-a6c79711051c)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by aksharbhat** [comment]
I'm also facing similar issues.

**Comment by rhaib** [comment]
I have this issue too.

**Comment by Mysticc28** [comment]
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool. 

@Rysu69 @aksharbhat @Rysu69 here's the fix y'all
