### ISSUE TITLE
glitchy & flickering lyrics on all songs (been happening for ~1 month now)

### ISSUE THREAD

**Issue by comfortablemilk4454** [surfbryce/beautiful-lyrics#949]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

glitchy & flickering lyrics on all songs (been happening for ~1 month now). im running macOS 15.1 (24B83). [see video](https://youtu.be/LtzDKiZvo2Q).

### What Country are you from?

USA

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify for macOS (Apple Silicon)
1.2.49.439.gfae492c7
Spicetify v2.38.4
Theme: marketplace
Extensions: beautiful-lyrics.mjs
Custom apps: marketplace

("Shift + B + L + I" did not work to get this info, i had to do spotify -> about in the menu bar to obtain this info)

### Spotify HTML/CSS and Console Screenshots

> - HTML File: Press "Shift + B + L + H"
> - CSS File: Press "Shift + B + L + C"

neither of these shortcuts put files in my downloads folder. 

![CleanShot 2024-10-29 at 14 07 09@2x](https://github.com/user-attachments/assets/35514c3b-9b6c-42aa-bd65-68b6689c6e5b)
![CleanShot 2024-10-29 at 14 07 12@2x](https://github.com/user-attachments/assets/c126c0cf-aecd-4a1b-a6c5-73d09afe4bfc)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@comfortablemilk4454 This is a MacOS issue, I unfortunately cannot do anything about this. I also suffer from this rendering bug from time to time.
