### ISSUE TITLE
Japanese song lyrics not loading (loading forever)

### ISSUE THREAD

**Issue by rhaib** [surfbryce/beautiful-lyrics#950]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Whenever a Japanese song is played, the song's lyrics do not load, and this screen is shown infinitely no matter which japanese song it is:
![image](https://github.com/user-attachments/assets/b00b7a66-080b-478a-8b89-184903eaaef2)
It works fine on English songs and songs of any language except Japanese:
![image](https://github.com/user-attachments/assets/bad5e895-9c37-4cdb-ad27-f91329e81593)
![image](https://github.com/user-attachments/assets/9ddb1438-eddb-433b-a40f-45d08c004e9c)
![image](https://github.com/user-attachments/assets/eda3727b-ee03-46d5-ba1d-81c7a92d231c)
![image](https://github.com/user-attachments/assets/9c7e9d53-fda1-4bcc-9a8b-055693ee8abb)

### What Country are you from?

United Kingdom

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Bloom / darkmono
Spicetify Extensions: [adblock.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [lyrics-plus, marketplace]

### Spotify HTML/CSS and Console Screenshots

HTML + CSS files:
[Spotify.zip](https://github.com/user-attachments/files/17570621/Spotify.zip)
Developer tools console tab:
![image](https://github.com/user-attachments/assets/cf29691b-2982-40b2-97dd-fe153ecace27)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by AlwaysBorderRadius** [comment]
I have Bloom too and it works for me

**Comment by rhaib** [comment]
I see.
