### ISSUE TITLE
 Disoriented objects in the full screen mode . 

### ISSUE THREAD

**Issue by DIVOUSS** [surfbryce/beautiful-lyrics#951]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

i downloaded the extension and when i am entering the full screen , the Album label , the pause/play ,volume bar and the circle dot on the progress bar are not on the correct position and also the circle dot on the volume bar.
![Screenshot 2024-10-30 204119](https://github.com/user-attachments/assets/7ccd9e73-d606-4310-a589-fdcaf67c1ee6)

The order is messed up 

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Sleek / BladeRunner
Spicetify Extensions: [volumePercentageWrapper.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify.zip](https://github.com/user-attachments/files/17575258/Spotify.zip)
![Screenshot 2024-10-30 205809](https://github.com/user-attachments/assets/38f749eb-e3ac-4e61-9773-37b08311ff74)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by aksharbhat** [comment]
I'm also facing similar issues.

**Comment by hellosquishies** [comment]
Yeah same thing here

**Comment by Mysticc28** [comment]
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool. 

@DIVOUSS @hellosquishies here's the fix y'all

**Comment by hellosquishies** [comment]
Isn't this just more of a workaround rather than an actual fix though?
