### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by l-estonie** [surfbryce/beautiful-lyrics#959]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

If a song has no lyrics available, instead of just hiding the "Show Lyrics" panel, it makes the panel bigger and shows a constant loading animation. If I click on the lyrics button, it doesn't say "The song has no lyrics", it shows blank "text" that's also constantly loading.
![Screenshot 2024-11-01 071852](https://github.com/user-attachments/assets/06220b7d-1a41-4ccf-9d4a-22b482603803)
![Screenshot 2024-11-01 072011](https://github.com/user-attachments/assets/6af8b617-d9c3-46bf-8070-ad018a5ab142)

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Comfy / Mono
Spicetify Extensions: [shuffle+.js, fullAlbumDate.js, volumePercentageWrapper.js, QueueTime.js, skip-after-timestamp.js, playing-source.js, oldLikeButton.js, find-duplicates.js, utilities.js, cacheCleaner.js, noTrackingLinks.js, wikify.js, songstats.js, CoverAmbience.js, seekSongKeybinds.js, NowPlayingReleaseDate.js, odesli-spicetify.js, best-moment.js, copyPlaylistInfo.js, playlist-icons.js, quickQueue.js, beautiful-lyrics.mjs, theme.script.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/b62e255d-bfb6-4d39-acba-95a6f5868348)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Byntonna** [comment]
Same problem. Error 500 indicates a server error, so I suggest we need to wait

**Comment by AlwaysBorderRadius** [comment]
Same problem here, and I listen to a lot of instrumental songs... It also doesn't fully support the Canvas feature (the short video that plays in the Now Playing bar, like on mobile) as it overrides the CSS and removes the focus effect on hover over the canvas.

**Comment by PirimTanrisi** [comment]
this means it has missing lyrics. the plugin dev didnt put any lyrics to that song

**Comment by TheE-MunozExperience** [comment]
Just noticed this issue as well. It used to not show anything for songs that didn't have lyrics, but now it's just the blank box. I've tried to reinstall via Marketplace but it doesn't do anything. I don't have any issues with the canvas feature though, they just take a bit to load.

**Comment by AlwaysBorderRadius** [comment]
so, is it fixed?
