### ISSUE TITLE
Extension stuck loading for songs without lyrics

### ISSUE THREAD

**Issue by AdrisAz** [surfbryce/beautiful-lyrics#966]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The extension loads infinitely in both the sidebar and fullscreen mode when encountering a song without lyrics.

![Screenshot 2024-11-03 221830](https://github.com/user-attachments/assets/e6ac1bb1-9c39-4c76-995f-8e304f6e8f1c)
![Screenshot 2024-11-03 221820](https://github.com/user-attachments/assets/37015f47-f77a-4a88-b3a7-036e5c41cd30)
![Screenshot 2024-11-03 222457](https://github.com/user-attachments/assets/c763fbe6-478c-4e81-819e-9988ca61625c)

### What Country are you from?

Canada

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.js, hidePodcasts.js, goToSong.js, fullAlbumDate.js, playNextWrapper.js, imageOpener.js, CoverAmbience.js, oneko.js, copytoclipboard.js, made-for-you-shortcut.js, playbarClock.js, showQueueDuration.js, spotispy.js, shuffle+.js, AnonymizedRadios.js, cat-jam.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify.zip](https://github.com/user-attachments/files/17613448/Spotify.zip)

![Screenshot 2024-11-03 222403](https://github.com/user-attachments/assets/758b398f-324c-4cbe-bb3f-e40045022681)

### Information Checklist

- [x] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by zero-mindset** [comment]
I have this same issue (MacOS Sonoma 14.1) as well. This occurs on songs without lyrics, but also songs without synced lyrics

**Comment by AdrisAz** [comment]
I think it's happening with non-synced lyrics for me too actually.

**Comment by SpikeNew7774** [comment]
It must've happened due to the server returning a 500 Errror status Code. Let me explain.
I've checked out the extension code, and found out that when the "https://beautiful-lyrics.socalifornian.live" server returns a different status code than 200, the extension doesn't know what to do and then it never hides the loading status. The only way to report it to the extension, that there are no lyrics, the server would have to return an empty body with the status code of 200.

![photo](https://github.com/user-attachments/assets/9f81a1a2-57a7-47be-88a5-5b321d183698)

**Comment by HeyitsRadinn** [comment]
+1 same issue for me, multiple computers and networks

**Comment by zero-mindset** [comment]
Could you make an option to turn off the background colors in the Now
Playing section?

**Comment by SpikeNew7774** [comment]
@zero-mindset  Do you mean that in the Beautiful-Lyrics extension or in the one that I'm making (I'm thinking of publishing it later)

**Comment by zero-mindset** [comment]
Either or. I just figured you’d take what was existing and make tweaks to
that. To me, that’s the only flaw with the current BL design

**Comment by SpikeNew7774** [comment]
I could have a look into that, but if you would want it, it would need to be externally installed and not through the marketplace. I'm probably going to edit the actual output file and not the source code in this github repo -> (PS: Its tooooooooooo complicated for me).

**Comment by Lebbbbb** [comment]
Anyone find a fix for this?

**Comment by SpikeNew7774** [comment]
Kind of. Its a problem on the server, which could be fixed by adding a check if the response status isnt 200 to just hide the lyrics in the actual client code. Also I found out that if the lyrics are static on apple music, it will return a 500 error with the content about a 429 error.

**Comment by httpeace33** [comment]
I've got same issue for few days for all lyrics tho(

**Comment by SpikeNew7774** [comment]
That means their API must be failing. I'm currently making my own Apple Musix => JSON API that's compatible with the beautiful-lyrics format (I'm using it in my own Lyrics extension)
