### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by mhnd099** [surfbryce/beautiful-lyrics#967]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Screenshot 2024-11-04 093252 png1](https://github.com/user-attachments/assets/f31e655c-fbcc-4a6d-bcaa-cfcdbbb8c5cc)
how to fix this bug in fullscreen

### What Country are you from?

jordan

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Downloads.zip](https://github.com/user-attachments/files/17614473/Downloads.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Here's the fix 
https://github.com/surfbryce/beautiful-lyrics/issues/938#issuecomment-2453500954

**Comment by mhnd099** [comment]
@Mysticc28 thanks<3

**Comment by Mysticc28** [comment]
> @Mysticc28 thanks<3

Happy to help :)
