### ISSUE TITLE
just dont work

### ISSUE THREAD

**Issue by Cornflake102** [surfbryce/beautiful-lyrics#971]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

extension just doesnt work, but a day ago it used to work well

### What Country are you from?

Russia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

cant get it, buttons dont work

### Spotify HTML/CSS and Console Screenshots

![Снимок экрана 2024-11-07 010738](https://github.com/user-attachments/assets/bbe0086d-7260-462e-86fd-eefac9108560)
![Снимок экрана 2024-11-07 010909](https://github.com/user-attachments/assets/52de8d65-07b9-4378-8e32-6001c147fa49)
![Снимок экрана 2024-11-07 010917](https://github.com/user-attachments/assets/7e9844d0-48ce-412b-8c72-97026204e1ef)
![Снимок экрана 2024-11-07 010925](https://github.com/user-attachments/assets/bf03cb6d-ecec-46a9-bf52-602070e7f04e)
![Снимок экрана 2024-11-07 010633](https://github.com/user-attachments/assets/8b3618c2-9291-49b5-8e71-1667411758be)
![Снимок экрана 2024-11-07 010657](https://github.com/user-attachments/assets/fd9cc605-5cb7-4b6a-b4a1-aa750643739d)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by SpikeNew7774** [comment]
Explanation: The app (on every launch) checks for the version on "https://extensions.socalifornian.live/version/beautiful-lyrics" and then loads the actual script from "https://extensions-storage.socalifornian.live/beautiful-lyrics@{VERSION}.mjs". If you're still having that problem, try downloading "https://extensions-storage.socalifornian.live/beautiful-lyrics@4.1.6.mjs" (currently the latest version), then putting it into "%appdata%/spicetify/Extensions", then running ```spicetify config extensions beautiful-lyrics@4.1.6.mjs``` then ```spicetify apply``` and also reccomending you to remove the extension from the marketplace until the problem is fixed. If you decide to use the marketplace version again run ```spicetify config extensions beautiful-lyrics@4.1.6.mjs-``` then ```spicetify apply``` and it should be removed. Then you can install the Marketplace version again. There's a chance that Russia blocked some Cloudflare IPs and the beautiful-lyrics server is running on the Cloudflare's edge network. Hope this helps! 👍

**Comment by Cornflake102** [comment]
I have done everything you said, but it still doesnt work(

**Comment by SpikeNew7774** [comment]
What part of it didn't work? There's a chance that Russia blocked some Cloudflare IPs and I forgot to mention that the lyrics may not work, but you can try hosting your own proxy somewhere else (on a VPS, maybe Vercel) than Cloudflare, and then it may work. For any questions about the proxy, you can just reply to this.

**Comment by klapeodetka** [comment]
Maybe including the names of sites needed for beautiful lyrics to work in dpi will help solve the problem? Could you give it to me please? I have the same problem

**Comment by SpikeNew7774** [comment]
I'll probably make a proxy for it.

Hostnames that beautiful-lyrics uses (that I know of):

extensions.socalifornian.live <- Gets the latest version tag (e.g.: 4.1.6)

extensions-storage.socalifornian.live <- To get the actual extension by the version tag

beautiful-lyrics.socalifornian.live <- To get the actual lyrics

kuromoji.socalifornian.live <- i don't know

and if there are more you can search "socalifornian.live" in the network tab.

**Comment by klapeodetka** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/7b3269b4-001f-4c33-88a1-191cfd34bcc4)
ideas?

**Comment by SpikeNew7774** [comment]
This means that the the server failed while trying to get the lyrics. The extension loaded succesfully, but the lyrics fetch failed.

**Comment by klapeodetka** [comment]
Is this a problem on my part or the extension?

**Comment by SpikeNew7774** [comment]
No. That's their server's problem.

**Comment by klapeodetka** [comment]
okk Tysm

**Comment by SpikeNew7774** [comment]
I would reccomend using a replacement for the beautiful-lyrics API (server) that uses the beautiful-lyrics format and has a fallback of getting lyrics from Musixmatch. ([SpikeNew7774/Lyrjs_CW](https://github.com/SpikeNew7774/Lyrjs_CW). (i dont mean for this to be an ad)

**Comment by Kwiixx** [comment]
> I would reccomend using a replacement for the beautiful-lyrics API (server) that uses the beautiful-lyrics format and has a fallback of getting lyrics from Musixmatch. ([SpikeNew7774/Lyrjs_CW](https://github.com/SpikeNew7774/Lyrjs_CW). (i dont mean for this to be an ad)

Hello, how can I replace the beautiful-lyrics API with SpikeNew7774/Lyrjs_CW ?

**Comment by SpikeNew7774** [comment]
@Kwiixx You will need to modify the output file of beautiful lyrics (at https://extensions-storage.socalifornian.live/beautiful-lyrics@4.2.0.mjs) and modify the url in the file from "https://beautiful-lyrics.socalifornian.live/lyrics" to "https://lyrjs.spikerko.org/lyrics/id?id=". Then uninstall the marketplace version and install the modified file externally, BUT do not forget to put something like this on top of the file to load the styles:

```js
const css = document.createElement("link");
css.href = "https://extensions-storage.socalifornian.live/beautiful-lyrics@4.2.0.css";
css.rel = "stylesheet";
css.type = "text/css";
document.head.appendChild(css);
```

And then you're all done!
