### ISSUE TITLE
Japanese/Chinese lyric displaying problem

### ISSUE THREAD

**Issue by SaharaMiyoko** [surfbryce/beautiful-lyrics#98]
Some Chinese/Japanese lyrics will not display properly if the lyrics are very long. And some Chinese/Japanese lyrics have highlighting problems,which do not conform to the Chinese/Japanese word formation rules.For example, in the second picture, the words "开始終結"(start end) are grouped as "开始終" and "結"(end) in Beautiful lyrics. "开始終" may be a combination of the Chinese words "开始"(start)and "始終"(always).But in fact, it should be split into "开始"(start) and "終結"(end).So I hope the Chinese/Japanese lyrics line breaks can be improved, and the Chinese/Japanese lyrics highlighting can be character-by-character, because the Chinese/Japanese word formation is really profound!

<img width="783" alt="屏幕截图 2023-08-05 195920" src="https://github.com/surfbryce/beautiful-lyrics/assets/104242390/c2f9af89-ab40-45a1-ac6a-7cf1060327de">

<img width="1120" alt="屏幕截图 2023-08-05 193336" src="https://github.com/surfbryce/beautiful-lyrics/assets/104242390/33785308-b0b0-4218-bbe8-ec8786f73659">

**Comment by surfbryce** [comment]
@SaharaMiyoko The lines going over the limit are an issue for any song with long lyrics. I'll see what I can do for this but I never changed this under the assumption that there doesn't exist a way to effectively wrap that.

As for the word formations: I just want you to be aware that these lyrics are not curated nor modified by the extension at all. The lyrics are created by the artists or the label the song belongs to.

So this is how they personally decided to format the lyrics. You can check this on platforms like Apple Music, Musixmatch, or Tidal and you'll find they have the same formatting.

So I will not be able to do anything that fixes this in any regard. I never intend to modify the lyrics that the extension displays and I will never stray from that.

As for character-by-character there is no implementation anywhere on the planet that exists for this. There are syllable synced lyrics that exist which synchronize syllables to a time-range (start/end time). If a song does not have these type of lyrics than the artist/label did not bother to sync them up this way. It'll then fallback to Line synced lyrics. If the artist/label did not sync them up at all it'll fall back to static lyrics (just text). In some cases artists/labels don't even submit lyrics at all which you will see that no lyrics are available.

Sorry for the inconvenience; but - as far as this issue goes - this is not a fault of the extension but of the provided lyrics by the artist/label.
