### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by nroamn** [surfbryce/beautiful-lyrics#981]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The UI is completely cooked, the time slider is at the wrong place, the album cover is at the top of the screen and you cant even use the time slider. 
![image_2024-11-09_223644241](https://github.com/user-attachments/assets/4fa7f125-9e64-404b-88da-1365776f0871)

### What Country are you from?

Sweden

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Sleek / Cherry
Spicetify Extensions: [trashbin.js, fullAlbumDate.js, volumePercentageWrapper.js, songstats.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image_2024-11-09_231053065](https://github.com/user-attachments/assets/bdb44cc3-bba1-4c95-8f3e-9dfaf4e2eb33) - console
[Spotifycsseeee.txt](https://github.com/user-attachments/files/17689526/Spotifycsseeee.txt) - CSS
[Spotifyhtmlssssss.txt](https://github.com/user-attachments/files/17689527/Spotifyhtmlssssss.txt) - HTML

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Here's the fix, hope it helps

https://github.com/surfbryce/beautiful-lyrics/issues/965#issue-2631433437

**Comment by Ibarahona73** [comment]
![a1](https://github.com/user-attachments/assets/4cb4d44a-f283-4a0b-8717-bfed1a2f6b8d)

What is the reason for this error? I have only one extension, beautiful lyrics, this happens in most of the songs.

**Comment by Mysticc28** [comment]
> ![a1](https://github.com/user-attachments/assets/4cb4d44a-f283-4a0b-8717-bfed1a2f6b8d)
> 
> What is the reason for this error? I have only one extension, beautiful lyrics, this happens in most of the songs.
> 
> 

Here's something on the topic
https://github.com/surfbryce/beautiful-lyrics/issues/966#issuecomment-2468085980

**Comment by Mysticc28** [comment]
> ![a1](https://private-user-images.githubusercontent.com/134466336/385160394-4cb4d44a-f283-4a0b-8717-bfed1a2f6b8d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDc5NDcsIm5iZiI6MTczMTUwNzY0NywicGF0aCI6Ii8xMzQ0NjYzMzYvMzg1MTYwMzk0LTRjYjRkNDRhLWYyODMtNGEwYi04NzE3LWJmZWQxYTJmNmI4ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxNDIwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTg3M2Y2ZWUxYzU2ZDQ5MDkxODhmNTkxZWI0YjkxNzY5MDNjZTQxOTY2NGU3MTFkNDJhNzljMTVmYzM0NjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q9Pd52z-xLk8347klqAAC3oADbIlMQrVac5p4BDHdSQ)
> 
> What is the reason for this error? I have only one extension, beautiful lyrics, this happens in most of the songs.

Also, try this experimental feature "Enable lyrics upsell" try changing it to "false" or "true" and see if it works
