### ISSUE TITLE
Album image doesn't view properly.

### ISSUE THREAD

**Issue by BL4Z3Blazer101** [surfbryce/beautiful-lyrics#983]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![image](https://github.com/user-attachments/assets/e727a169-89ac-475c-a610-ea36730edc2f)

The album image has been moved to the top. I attempted to reinstall both Spotify and Spicetify, along with the extension, but it appears that it didn’t resolve the issue. 

### What Country are you from?

Sri Lanka

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/26f98974-5048-4a01-bc36-eda637a92532)
![image](https://github.com/user-attachments/assets/8e254e34-0e0a-4834-8bce-e3cafa60c086)
![image](https://github.com/user-attachments/assets/e3f78046-7735-4fa2-9659-7500f0bc3a3f)
![image](https://github.com/user-attachments/assets/2f5634b4-0433-4b74-80c0-81c2281c7db8)

[Spotify.zip](https://github.com/user-attachments/files/17727055/Spotify.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Hey there, here's the fix. 

https://github.com/surfbryce/beautiful-lyrics/issues/965#issue-2631433437
