### ISSUE TITLE
Beautiful-Lyrics API returning 500.

### ISSUE THREAD

**Issue by SpikeNew7774** [surfbryce/beautiful-lyrics#984]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Whenever the extension tries to load lyrics from "https://beautiful-lyrics.socalifornian.live/lyrics/{id}" it sometimes fails, and returns a HTTP status code of 500 with the body: "Stage: AM_S, Error: 429 | Too Many Requests". Im guessing there's too many requests on the Apple Music (AM) API coming from your side.

### What Country are you from?

Slovakia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

In this case, this is pointless. There's a problem with the API and not the client.

### Spotify HTML/CSS and Console Screenshots

Again, this is pointless too.

### Information Checklist

- [x] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by RajitRoy** [comment]
Same here... Getting a Error: 429 | Too Many Requests
Happening for past 2 wks, with our without VPN

**Comment by SpikeNew7774** [comment]
Yes. I'm currently building a soon to be open-source API that transforms the Apple Music lyrics into the Beautiful-Lyrics compatible format. I already implemented that in my own lyrics extension.

**Comment by SpikeNew7774** [comment]
Thanks!

**Comment by turboA99** [comment]
Same here
`beautiful-lyrics@4.1.6.mjs:4` GET https://beautiful-lyrics.socalifornian.live/lyrics/1CsMKhwEmNnmvHUuO5nryA 500 (Internal Server Error)`
`index.html:1 Uncaught (in promise) Failed to load Lyrics for Track (1CsMKhwEmNnmvHUuO5nryA), Error: 500`

**Comment by tienspextre** [comment]
> Yes. I'm currently building a soon to be open-source API that transforms the Apple Music lyrics into the Beautiful-Lyrics compatible format. I already implemented that in my own lyrics extension (shown below). ![20241114-1503-33 2592297-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/88393630/386248108-6204986b-85bb-431b-8390-0c433aaa60f7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjY0MjUsIm5iZiI6MTczMTY2NjEyNSwicGF0aCI6Ii84ODM5MzYzMC8zODYyNDgxMDgtNjIwNDk4NmItODViYi00MzFiLTgzOTAtMGM0MzNhYWE2MGY3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGVlNTQ5NTY5ZTZjNWU3MGNmZmRlZjM0M2ZmMTM2YTA1YTg5YjhjNjRjODkxMzYxMDAzMTU0ZTY1ZjAzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ja29_km62UMK2Uo4I8w5YqkcEvZY4n5zlULA2B0CPWo) 

Excited to see this! Do you have a preview version, and when will it be ready? Wish you all the best!

**Comment by SpikeNew7774** [comment]
I started making it about 2 weeks ago, but it still needs some finishing touches.

**Comment by Ender-Wang** [comment]
Hope we can get this soon! 🫶

**Comment by SpikeNew7774** [comment]
The repo is up for info: https://github.com/SpikeNew7774/spiky-lyrics

**Comment by claymorwan** [comment]
So is just not working for no one

**Comment by SpikeNew7774** [comment]
Yes

**Comment by Mysticc28** [comment]
> The repo is up for info: https://github.com/SpikeNew7774/spicy-lyrics

Hey, do you want any suggestions with regards to building this extension about user features and customisability? Also, I may have something that can prove to be helpful to you for the gradient background customisation options eg. Speed, duration etc.

**Comment by SpikeNew7774** [comment]
Hi! Thanks I don't know how to implement the Page feature in the Extension. I really want to transfer the Custom App to an Extension, beacuse its easier to install. I tried the Spicetify.Panel, but it doesn't exist anymore. Is there any way you can make an example extension and then show the files? Thanks!

**Comment by Mysticc28** [comment]
> Thanks. Just published the souce code of it on the development branch!

 For one, I found this, hoping it can be of help

https://github.com/3raxton/spicetify-custom-apps-and-extensions

I've also asked another developer who has made extensions that are on the marketplace for help with this and they have helped me previously so let's see how this turns out. I'm really interested in your extension and I'd love to help in any way I can with it :)

**Comment by SpikeNew7774** [comment]
Thanks, but I might have found a way to do that. Updating it rn (if it works.). But Thanks!

**Comment by surfbryce** [comment]
@SpikeNew7774 Working on trying to get it back up, at first it was an Authorization issue and then it seems to be a request issue, so for now the endpoint is temporarily disabled and it'll be back up in an hour. Everything should continue working as normal after that

**Comment by SpikeNew7774** [comment]
That's Nice! I wanted to ask, How does the Beautiful-Lyrics API get it so fast? I tried making my own which got lyrics from Apple Music like yours, but It wasn't as fast.

**Comment by kokoropaint** [comment]
Just wanted to say the API is still not working for me, with or without VPN (which was able solve this problem a couple weeks/months ago.) Would love to be able to use this extension again :(

**Comment by SpikeNew7774** [comment]
@kokoropaint I made a quick uptime service on my server for beautiful-lyrics. You can go check it out: https://uptime.spikerko.org/status/beautiful-lyrics

**Comment by Borber** [comment]
> @SpikeNew7774 Working on trying to get it back up, at first it was an Authorization issue and then it seems to be a request issue, so for now the endpoint is temporarily disabled and it'll be back up in an hour. Everything should continue working as normal after that

hope everything gets better soon

**Comment by SpikeNew7774** [comment]
@Mysticc28 Spicy Lyrics is out now on the Spicetify Marketplace and on https://github.com/SpikeNew7774/spicy-lyrics

**Comment by Mysticc28** [comment]
> @Mysticc28 Spicy Lyrics is out now on the Spicetify Marketplace and on https://github.com/SpikeNew7774/spicy-lyrics

That is insaneeee!!! Let's goooo broo, omw to try it right now!! Congratulations on your new release dudee!!

**Comment by SpikeNew7774** [comment]
Thanks!

**Comment by SpikeNew7774** [comment]
@Mysticc28 Also it has settings, such as: Low Quality Mode, Custom Hosts (for other instances), Access Tokens for custom instances.

**Comment by Mysticc28** [comment]
> @Mysticc28 Also it has settings, such as: Low Quality Mode, Custom Hosts (for other instances), Access Tokens for custom instances.

Coool, how do I access it?

**Comment by SpikeNew7774** [comment]
@Mysticc28 In the Spotify settings. But that's mostly intended for when the Spicy Lyrics API is going to be open-source, so then you can route it to your instance and not to mine. (self-host it). If you want to self host, you will need to wait for the Spicy Lyrics API getting open-source and also have an Apple Music subscription (for lyrics), and a Spotify Developer app (to transform the spotify id to names and artists).

**Comment by Mysticc28** [comment]
@SpikeNew7774 great, thanks for letting me know 😁

**Comment by zydiaa** [comment]
> @Mysticc28 Spicy Lyrics is out now on the Spicetify Marketplace and on https://github.com/SpikeNew7774/spicy-lyrics

Can you maybe tell me how to use it, after that, I can write a installation guide

**Comment by Mysticc28** [comment]
@zydiaa just search for it in the marketplace

**Comment by zydiaa** [comment]
> @zydiaa just search for it in the marketplace

yeah i just found out, im stupid 🤦🏻‍♂️

**Comment by Mysticc28** [comment]
> > @zydiaa just search for it in the marketplace
> 
> yeah i just found out, im stupid 🤦🏻‍♂️

it's cool, no worries

**Comment by Ender-Wang** [comment]
> @Mysticc28 In the Spotify settings. But that's mostly intended for when the Spicy Lyrics API is going to be open-source, so then you can route it to your instance and not to mine. (self-host it). If you want to self host, you will need to wait for the Spicy Lyrics API getting open-source and also have an Apple Music subscription (for lyrics), and a Spotify Developer app (to transform the spotify id to names and artists).

Do you have any special reason for using Apple Music rather than Spotify? Since we are using Spotify, we most likely do not have an Apple Music subscription. I would also like to host it myself, though. When this repo gets vibe, the single host of this API provided by you may not be enough for an increasing user base.

**Comment by SpikeNew7774** [comment]
@Ender-Wang I use Apple Music, because they have the best word synced lyrics I've seen. Even Beautiful-Lyrics uses Apple Music. Also I've seen people asking for the now playing bar lyrics, so I may add that deeper into the future.

**Comment by Ender-Wang** [comment]
Oh, I didnot know that, hopes there will be some people with Apple Music sub provide their API, so you can do load balancing or I can help host it on my Raspberry Pi 5, which is running on my LAN 24/7. Great extension btw, thanks!🫶

**Comment by SpikeNew7774** [comment]
@Ender-Wang It's best to host it on Cloudflare Workers (a free option), beacuse it contains some Cloudflare-only features, but they can be easily removed.

**Comment by surfbryce** [comment]
The service is now back up and working properly, it should be stable for the time being. Expect updates fixing all the other updates later this coming week

**Comment by AgentMonkey00** [comment]
> The service is now back up and working properly, it should be stable for the time being. Expect updates fixing all the other updates later this coming week
LEGEND!
