### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by RF-LITDAB** [surfbryce/beautiful-lyrics#987]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The lyrics arent showing up
![image](https://github.com/user-attachments/assets/331c3af9-1a9a-491c-be1a-80720bd1a86e)
![image](https://github.com/user-attachments/assets/6132386b-269f-431d-9a85-9e0c2643fa25)

### What Country are you from?

Belize

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Lucid / dark
Spicetify Extensions: [webnowplaying.js, adblock.js, volumePercentage.js, fullScreenWrapper.js, npvAmbience.js, fullAlbumDate.js, noControls.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace, lyrics-plus]

### Spotify HTML/CSS and Console Screenshots

[Spotify(html).zip](https://github.com/user-attachments/files/17741701/Spotify.html.zip)
[Spotify(css).zip](https://github.com/user-attachments/files/17741704/Spotify.css.zip)
![image](https://github.com/user-attachments/assets/78fb5c2b-f942-403c-84ac-a83b53197621)
![image](https://github.com/user-attachments/assets/766683a9-2452-4b4c-b7c8-6b5d0b1481bd)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Red-Hood2005** [comment]
Has anyone found the solution for the lyrics?

**Comment by Mysticc28** [comment]
Hey, here's a fix for your elements being offset https://github.com/surfbryce/beautiful-lyrics/issues/965

Also, have you tried enabling lyrics upsell from experimental settings?

**Comment by Red-Hood2005** [comment]
Como arreglar el tema de las letras que no aparecen? @Mysticc28

**Comment by Red-Hood2005** [comment]
Como hago eso? Ya revise y no encontré esa opción

**Comment by Mysticc28** [comment]
> Como hago eso? Ya revise y no encontré esa opción

-Open Spotify - top right corner
![image](https://github.com/user-attachments/assets/32663db1-3f22-4f8b-8ff4-cfb6896d75a6)

-Click on profile picture

-Experimental features 

![image](https://github.com/user-attachments/assets/9a802a16-b3e6-446a-a5de-7c523f5e3b03)

![image](https://github.com/user-attachments/assets/7b4cb3e3-899d-40f5-8fd1-6d49e9bb1feb)

set this option to enabled (tick mark should appear)

**Comment by Mysticc28** [comment]
Update - can confirm that this song has no lyrics available on beautiful lyrics. You'll have to create an issue under missing lyrics for this song after checking for lyrics on Musixmatch and Apple Music

![image](https://github.com/user-attachments/assets/c22b0f8b-fd55-4ea8-b8f9-bdf7ca7ca8d7)

**Comment by Red-Hood2005** [comment]
@Mysticc28 lo hice pero no funcionó, esperare para cuando encuentren solución al problema

**Comment by RF-LITDAB** [comment]
> Hey, here's a fix for your elements being offset #965
> 
> Also, have you tried enabling lyrics upsell from experimental settings?

THANK YOU, THATS BEEN ANNOYING ME FOR SO LONG🙏🙏

**Comment by RF-LITDAB** [comment]
> Update - can confirm that this song has no lyrics available on beautiful lyrics. You'll have to create an issue under missing lyrics for this song after checking for lyrics on Musixmatch and Apple Music
> 
> ![image](https://private-user-images.githubusercontent.com/184191235/386081986-c22b0f8b-fd55-4ea8-b8f9-bdf7ca7ca8d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTA1MTYsIm5iZiI6MTczMTYxMDIxNiwicGF0aCI6Ii8xODQxOTEyMzUvMzg2MDgxOTg2LWMyMmIwZjhiLWZkNTUtNGVhOC1iOGY5LWJkZjdjYTdjYThkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODUwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWI3NjEzNDc2YmJjYzMyOTExYmVmYzczYmRhMWI4MGRhOTEyMTQyMjAwZTA5YzIzMzA0ODQzODU4NjdiYWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-0uNP72k5qKgH-rX_Wil5hV0bbWOWxZuRhP6cTDbA00)

its not just that song, i was goign through my playlist, some songs work, some dont. and honestly, i dont really have the time to ss all of the song that dont work for me so😭

**Comment by Mysticc28** [comment]
> > Update - can confirm that this song has no lyrics available on beautiful lyrics. You'll have to create an issue under missing lyrics for this song after checking for lyrics on Musixmatch and Apple Music
> > ![image](https://private-user-images.githubusercontent.com/184191235/386081986-c22b0f8b-fd55-4ea8-b8f9-bdf7ca7ca8d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTA1MTYsIm5iZiI6MTczMTYxMDIxNiwicGF0aCI6Ii8xODQxOTEyMzUvMzg2MDgxOTg2LWMyMmIwZjhiLWZkNTUtNGVhOC1iOGY5LWJkZjdjYTdjYThkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODUwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWI3NjEzNDc2YmJjYzMyOTExYmVmYzczYmRhMWI4MGRhOTEyMTQyMjAwZTA5YzIzMzA0ODQzODU4NjdiYWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-0uNP72k5qKgH-rX_Wil5hV0bbWOWxZuRhP6cTDbA00)
> 
> its not just that song, i was goign through my playlist, some songs work, some dont. and honestly, i dont really have the time to ss all of the song that dont work for me so😭

Hey there, it's noticed that the cause of the issue is the API failing as seen by another guy who created an issue on it, so its not really the songs anymore. Looks like we're gonna have to wait for it to be fixed for now
