### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by ShayanKhodadadian** [surfbryce/beautiful-lyrics#988]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

it is obvious 
![image](https://github.com/user-attachments/assets/609b7a2b-ccd8-4c3c-aa0d-ffca17784f32)

### What Country are you from?

UK

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [simple-beautiful-lyrics.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[Spotify.zip](https://github.com/user-attachments/files/17746159/Spotify.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Hey there, here's a fix 

https://github.com/surfbryce/beautiful-lyrics/issues/965
