### ISSUE TITLE
99% of all my 857 songs dont have the pretty lyrics

### ISSUE THREAD

**Issue by AccaliaAmarix** [surfbryce/beautiful-lyrics#989]
### Before you list your Songs:

- [X] IF you are reporting multiple songs, add ", ..." to the end of your title.
- [X] For every song you want to report, check Musixmatch or Apple Music and check to see if they even have Lyrics for the Songs you are reporting.

### List Song Links

I am not sending every song in a link cuz i see 20 or so songs that have pretty lyrics out of 800+ and the rest only have spotifys lame lyrics i have checked apple music, audiomack, sound cloud, musixmatch they all have lyrics. i have unadded the extension and readded it multiple times and unadded and readded spicetify multiple times as well as updated it nothing seems to work if someone could help that would be amazing

![Screenshot 2024-11-14 060902](https://github.com/user-attachments/assets/cc00a2cc-9483-4685-bf96-d35a3604a3ad)

![Screenshot 2024-11-14 060920](https://github.com/user-attachments/assets/6e968201-d1b2-4ce5-ac0a-ae464a6482e0)

**Comment by SpikeNew7774** [comment]
The beautiful-lyrics API (server) is failing. I hope that it isn't the downfall of beautiful-lyrics.

**Comment by SpikeNew7774** [comment]
Well, that's why I'm making my own extension with my own API.

**Comment by SpikeNew7774** [comment]
It's not public yet, I'm currently developing it, but it will be a custom app, which needs to be installed through the cli (like lyrics-plus by Spicetify). But there will be a guide and all that later.

**Comment by popphoenixx** [comment]
> It's not public yet, I'm currently developing it, but it will be a custom app, which needs to be installed through the cli (like lyrics-plus by Spicetify). But there will be a guide and all that later.

Great work, looking forward to it!

**Comment by SpikeNew7774** [comment]
Thanks. There's a thing that my extension has but the beautiful lyrics one doesn't. It's Low Quality mode. If you have a Lower end PC, you can turn on the Low Quality Mode, and it will eliminate: Dynamic Backgrounds, Strong Blurs, Strong shadows and Gradient on text. Also mine has its own DB, where I can put lyrics synced by myself, fix Lyrics that are wrong, etc...

**Comment by ArianaMinajj2** [comment]
> Thanks. There's a thing that my extension has but the beautiful lyrics one doesn't. It's Low Quality mode. If you have a Lower end PC, you can turn on the Low Quality Mode, and it will eliminate: Dynamic Backgrounds, Strong Blurs, Strong shadows and Gradient on text. Also mine has its own DB, where I can put lyrics synced by myself, fix Lyrics that are wrong, etc...
> 
> Example. This song has only Line lyrics on Beautiful-Lyrics, but mine has Syllable (Word) synced lyrics: (sorry but when I'm recording my pc lags).
> 
> ![GIF](https://private-user-images.githubusercontent.com/88393630/386297655-5bec6cf8-4c99-43c3-ac93-93390e79bfe5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTc4NTcsIm5iZiI6MTczMTYxNzU1NywicGF0aCI6Ii84ODM5MzYzMC8zODYyOTc2NTUtNWJlYzZjZjgtNGM5OS00M2MzLWFjOTMtOTMzOTBlNzliZmU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Y2YwMWE3NGYyZTUzY2MzMmY1Y2FhZjFkNGQ1NWE5Y2ZhOGFhMGIzOTE5YTllNjE2MzEwZTQzMmU4NzEwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.isEr4qVCZzb38W6V99UhDVrCTgUvSQR2FwfwvXG5fKA) [ ![GIF](https://private-user-images.githubusercontent.com/88393630/386297655-5bec6cf8-4c99-43c3-ac93-93390e79bfe5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTc4NTcsIm5iZiI6MTczMTYxNzU1NywicGF0aCI6Ii84ODM5MzYzMC8zODYyOTc2NTUtNWJlYzZjZjgtNGM5OS00M2MzLWFjOTMtOTMzOTBlNzliZmU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Y2YwMWE3NGYyZTUzY2MzMmY1Y2FhZjFkNGQ1NWE5Y2ZhOGFhMGIzOTE5YTllNjE2MzEwZTQzMmU4NzEwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.isEr4qVCZzb38W6V99UhDVrCTgUvSQR2FwfwvXG5fKA) ](https://private-user-images.githubusercontent.com/88393630/386297655-5bec6cf8-4c99-43c3-ac93-93390e79bfe5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTc4NTcsIm5iZiI6MTczMTYxNzU1NywicGF0aCI6Ii84ODM5MzYzMC8zODYyOTc2NTUtNWJlYzZjZjgtNGM5OS00M2MzLWFjOTMtOTMzOTBlNzliZmU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Y2YwMWE3NGYyZTUzY2MzMmY1Y2FhZjFkNGQ1NWE5Y2ZhOGFhMGIzOTE5YTllNjE2MzEwZTQzMmU4NzEwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.isEr4qVCZzb38W6V99UhDVrCTgUvSQR2FwfwvXG5fKA) [ ](https://private-user-images.githubusercontent.com/88393630/386297655-5bec6cf8-4c99-43c3-ac93-93390e79bfe5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTc4NTcsIm5iZiI6MTczMTYxNzU1NywicGF0aCI6Ii84ODM5MzYzMC8zODYyOTc2NTUtNWJlYzZjZjgtNGM5OS00M2MzLWFjOTMtOTMzOTBlNzliZmU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Y2YwMWE3NGYyZTUzY2MzMmY1Y2FhZjFkNGQ1NWE5Y2ZhOGFhMGIzOTE5YTllNjE2MzEwZTQzMmU4NzEwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.isEr4qVCZzb38W6V99UhDVrCTgUvSQR2FwfwvXG5fKA)

hello, if you're gonna revive beautiful lyrics is there a way to keep us updated on your work? Thanks in advance!

**Comment by AccaliaAmarix** [comment]
> Thanks. There's a thing that my extension has but the beautiful lyrics one doesn't. It's Low Quality mode. If you have a Lower end PC, you can turn on the Low Quality Mode, and it will eliminate: Dynamic Backgrounds, Strong Blurs, Strong shadows and Gradient on text. Also mine has its own DB, where I can put lyrics synced by myself, fix Lyrics that are wrong, etc...
> 
> Example. This song has only Line lyrics on Beautiful-Lyrics, but mine has Syllable (Word) synced lyrics: (sorry but when I'm recording my pc lags).
> 
Now is this going to be highly customizable or customizable at all ? I would like to know if i would be able to change the speed or blur etc.

**Comment by SpikeNew7774** [comment]
Actually, You gave me an idea. Thanks, I may add that.

**Comment by rhaib** [comment]
Please do keep us updated on this, so many songs that had lyrics before just don't have them anymore and it's quite annoying because I'm used to a lot of popular songs having them but now almost none of them have it, and I thought it was an issue on my end :(

I hope development goes smoothly and an alpha or beta release is available to test soon :)

**Comment by SpikeNew7774** [comment]
@rhaib It's out now! https://github.com/SpikeNew7774/spicy-lyrics

**Comment by rhaib** [comment]
Thanks! I installed from the Spicetify Marketplace as it was easier, it functions well and I'm thankful for your hard work.
