### ISSUE TITLE
Beautiful Lyrics has recently stopped working on the side card 

### ISSUE THREAD

**Issue by magnusssz** [surfbryce/beautiful-lyrics#99]
after the last spotify update, the extension stopped modifying the right side card

![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/964bdc38-ad50-4f2b-a0bf-5ec3f955f02e)

Spotify para Windows (64 bit)
1.2.17.834.g26ee1129
Spicetify v2.22.1
Brazil

**Comment by surfbryce** [comment]
@magnusssz I think I know what's causing the issue. I'm going to move this to #89 and mark this as a duplicate and then close it. You can find more information there.
