### ISSUE TITLE
Lyrics are not showing for any songs

### ISSUE THREAD

**Issue by FlyN-Nick** [surfbryce/beautiful-lyrics#994]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Lyrics are no longer showing up for any songs.

### What Country are you from?

United States

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Ziro / rose-pine-moon
Spicetify Extensions: [keyboardShortcut.js, loopyLoop.js, popupLyrics.js, shuffle+.js, trashbin.js, fullAppDisplay.js, adblock.js, wikify.js, spotifyGenres.js, beautiful-lyrics.js, CoverAmbience.js, volumePercentage.js, sortByPlayCount.js, skipStats.js, fullAlbumDate.js, fullScreenWrapper.js, songstats.js, copy-lyrics.js, beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

# HTML
[https://paste.mozilla.org/LSaq8Hoq](https://paste.mozilla.org/LSaq8Hoq)

# CSS
[https://paste.mozilla.org/kJV43UNZ](https://paste.mozilla.org/kJV43UNZ)
					
# Console
<img width="1576" alt="Console Screenshot" src="https://github.com/user-attachments/assets/9d244e65-343f-49ba-829e-697bd5c3f2be">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by nucelo123** [comment]
it seems that the api is not working properly. for **most of the songs** lyrics aren't showing but there are some that still manage to load their lyrics. for me its "guess" charli xcx ft. billie eilish, "genesis pt. ii" raye, "arachnophobia" jann, "rincon" milo j, etc.

**Comment by SpikeNew7774** [comment]
More Context: https://github.com/surfbryce/beautiful-lyrics/issues/984#issue-2656016755
