### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by S0vellus** [surfbryce/beautiful-lyrics#995]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

the full screen button doesn't work

### What Country are you from?

Kazakhstan

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

spicetify

### Spotify HTML/CSS and Console Screenshots

/.

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Mysticc28** [comment]
Could you provide any additional info on this, such as when do you face this issue or a screenshot of the button and it's problems?
