### ISSUE TITLE
How can I run the first ever Beautiful-Lyrics version.

### ISSUE THREAD

**Issue by SpikeNew7774** [surfbryce/beautiful-lyrics#996]
I tried running the Beautiful Lyrics "Release" version, but it didn't work. I'm really intrested in this project, and I wanted to see how it started. Thanks!

**Comment by LeNerd46** [comment]
I've been trying to figure this out for the past like half hour. I know I've done it before, but I'm not sure why it isn't working now.

If I recall correctly, it doesn't work on the current version of Spotify, so you have to downgrade your Spotify version (this is what I can't get working for some reason). If you can downgrade your Spotify, it should work

**Comment by Mysticc28** [comment]
> I've been trying to figure this out for the past like half hour. I know I've done it before, but I'm not sure why it isn't working now.
> 
> If I recall correctly, it doesn't work on the current version of Spotify, so you have to downgrade your Spotify version (this is what I can't get working for some reason). If you can downgrade your Spotify, it should work



Here you go, this should help

https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557

**Comment by LeNerd46** [comment]
> > I've been trying to figure this out for the past like half hour. I know I've done it before, but I'm not sure why it isn't working now.
> > If I recall correctly, it doesn't work on the current version of Spotify, so you have to downgrade your Spotify version (this is what I can't get working for some reason). If you can downgrade your Spotify, it should work
> 
> Here you go, this should help
> 
> https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557

I tried that, among other things, but it still has the new UI and spicetify doesn't apply for some reason

**Comment by SpikeNew7774** [comment]
Thanks!

**Comment by Mysticc28** [comment]
> > > I've been trying to figure this out for the past like half hour. I know I've done it before, but I'm not sure why it isn't working now.
> > > If I recall correctly, it doesn't work on the current version of Spotify, so you have to downgrade your Spotify version (this is what I can't get working for some reason). If you can downgrade your Spotify, it should work
> > 
> > Here you go, this should help
> > 
> > https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557
> 
> I tried that, among other things, but it still has the new UI and spicetify doesn't apply for some reason


Working fix

-backup everything  
-uninstall spotify  
-Install version 1.2.45.451 from https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557 
-restore everything  
-download and apply history in sidebar extension from marketplace  
-go to experimental settings and set "show global navbar with home button ..." to control  
-restart if needed

lmk if you need any help with it

**Comment by SpikeNew7774** [comment]
Thanks, I'm probably going to try that later.
